config/tls.m4
AC_RUN_IFELSE will fail in cross-compile,
we can use AC_COMPILE_IFELSE replace.
Signed-off-by: duguhaotian <duguhaotian@gmail.com>
=> support tls in cross-compile

src/lxc/seccomp.c
This reverts commit dfddc8aa7ef3362212f8394995088a5f525730dd.
Closes #2376.
=> Revert "seccomp: make do_resolve_add_rule() more strict"

src/lxc/tools/lxc_monitor.c
=> coverity: #1425753

src/lxc/network.c, src/lxc/network.h, src/lxc/start.c
bug detail: [issue 2335](https://github.com/lxc/lxc/issues/2335)
simply run **run_script_argv()** in **lxc_create_network_unpriv_exec()** should work, however in **start.c**, **lxc_spawn()** didn't pass **hook_version** to **lxc_create_network_unpriv()**, which is needed by **run_script_argv()**.
so I add a argument **unsigned int hook_version** to **lxc_create_network_unpriv()** and thus need to modify the header **network.h**.
=> fix bug: unpriv lxc will run lxc.net.[i].script.up now

src/lxc/terminal.c
Not entirely sure why this was unset in the first place, but this fixes the logging output when doing something like: 
```
lxc-execute -l info -o /dev/stderr ubuntu
```
=> terminal: enable local output processing

src/lxc/tools/lxc_create.c
Older versions of lxc-create used to set log_file to "none" when a log priority
but no log file was specified on the command line. Let's restore this behavior.
Closes #2392.
=> tools: restore lxc-create log behavior

src/lxc/attach.c
Hello,
There is a double free issue.
This is caused by init_ctx free of payload when lxc_terminal_prepare_login() is failed.
(gdb) 
960		if (options->attach_flags & LXC_ATTACH_TERMINAL) {
(gdb) 
961			ret = lxc_terminal_prepare_login(payload->terminal_slave_fd);
(gdb) 
962			if (ret < 0) {
(gdb) 
963				SYSERROR("Failed to prepare terminal file descriptor %d", payload->terminal_slave_fd);
(gdb) 
964				goto on_error;
(gdb) p ret
$1 = -1
(gdb) p payload->terminal_slave_fd
$2 = 10
(gdb) n
973		lxc_put_attach_clone_payload(payload);
(gdb) 
*** Error in `/usr/local/bin/lxc-attach': double free or corruption (out): 0x000000000060ff70 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff73957e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ffff739e37a] …
=> attach: fix double free

src/lxc/cmd/lxc_user_nic.c
Hello,
I'm sorry. I didn't check it before pull request.
Uninitialized pointer
Thanks.
=> coverity: #1437017

src/lxc/criu.c
=> coverity: #1425778

templates/lxc-busybox.in
Use `busybox --list`, and exclude the `busybox` applet if necessary.
Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>
=> templates: Fix busybox template

src/lxc/monitor.c
Hello,
_exit() system call is safe in child process.
Thanks.
=> monitor: change exit() => _exit() system call in child process

lxc.spec.in
Hello,
Some comments for BuildRequires field are moved in lxc.spec.in.
Thanks.
=> move some comments in lxc.spec.in

src/lxc/log.h, src/lxc/lsm/apparmor.c, src/lxc/lsm/lsm.c, src/lxc/lsm/selinux.c, src/lxc/monitor.c, src/lxc/state.c, src/lxc/sync.c, src/lxc/terminal.c
Hello,
We add a log macro to use strerror_r() for thread safe.
For that, _GNU_SOURCE define is added to some source files.
Please review it then let us know your opinion.
Thanks.
=> log: add strerror_r macro

src/lxc/attach.c, src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/lxc_init.c, src/lxc/cmd/lxc_monitord.c, src/lxc/commands.c, src/lxc/commands_utils.c, src/lxc/conf.c, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/criu.c, src/lxc/initutils.c, src/lxc/log.c, src/lxc/lsm/lsm.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/namespace.c, src/lxc/network.c, src/lxc/seccomp.c, src/lxc/start.c, src/lxc/storage/btrfs.c, src/lxc/storage/overlay.c, src/lxc/storage/storage_utils.c, src/lxc/sync.c, src/lxc/terminal.c, src/lxc/utils.c
Hello,
LOG macros using strerror are changed to SYS* macros.
Thanks.
=> log: change LOG macros using strerror to SYS* macros

src/lxc/attach.c, src/lxc/terminal.c
now container pty output log, use \r\n as a newline flag.
This is a windows type, so we need to change it. By clear
ONLCR can reach it.
Before do this.
```
0000000
0000000  \n   1   2   :   f   i   l   e   s   :   /   l   x   c   /   h
0000020   a   o   z   i  \r  \n   1   1   :   p   i   d   s   :   /   l
0000040   x   c   /   h   a   o   z   i  \r  \n   1   0   :   m   e   m
0000060   o   r   y   :   /   l   x   c   /   h   a   o   z   i  \r  \n
0000100   9   :   h   u   g   e   t   l   b   :   /   l   x   c   /   h
0000120   a   o   z   i  \r  \n   8   :   p   e   r   f   _   e   v   e
0000140   n   t   :   /   l   x   c   /   h   a   o   z   i  \r  \n   7
0000160   :   c   p   u   s   e   t   :   /   l   x   c   /   h   a   o
0000200   z   i  \r  \n   6   :   d   e   v   i   c   e   s …
```
=> clear ONLCR flag for container pty

src/lxc/log.h
=> log: account for Android's Bionic's strerror_r()

src/lxc/tools/arguments.h, src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_cgroup.c, src/lxc/tools/lxc_freeze.c, src/lxc/tools/lxc_start.c, src/lxc/tools/lxc_stop.c, src/lxc/tools/lxc_unfreeze.c, src/lxc/tools/lxc_wait.c
Hello,
Currently, a quiet option of tools is not working because of using fprintf directly.
So, we change fprintf or print to lxc_error log with some cleanups.
And lxc_sys_error is added to print errno string additionally.
Thanks.
=> tools: fix quiet option is not working

src/tests/concurrent.c
Hello,
fix "Explicit null dereferenced".
This is false positive because the optarg value is not null.
But coverity can not detect this. So, I add a contidtion to avoid this case.
Thanks.
=> coverity: #1425816

src/lxc/cgroups/cgfsng.c, src/lxc/sync.c, src/lxc/tools/lxc_ls.c, src/lxc/utils.c, src/lxc/utils.h
Hello,
The recursive_destroy() is moved to utils.
And rm_r() is removed from lxc_ls.c
Thanks.
=> utils: move recursive_destroy() from cfgsng to utils.

src/lxc/log.c
Hello,
The trailing . are removed in log.c.
Thanks.
=> log: remove the trailing .

src/lxc/conf.c, src/lxc/terminal.c
=> conf: use mknod() to create dummy mount targets

src/lxc/tools/lxc_unshare.c
Hello,
A duplicated function is removed.
=> tools: lxc-unshare: replace write_id_mapping() to the same function in conf.c

src/lxc/tools/lxc_ls.c
Hello,
Fix assignment of a signed value which has type 'int' to a variable of a bigger integer type 'size_t'
Thanks.
=> tools: lxc-ls: fix signed_to_bigger_unsigned issue

src/lxc/confile.c
Passing additional configuration options with "--define" was broken.
Result of git bisect:
d899f11b7bfb14c4b532bc801de89c8fb46307d4 is the first bad commit
=>  confile: fix incorrect strncmp

src/lxc/tools/lxc_unshare.c
Hello,
change legacy codes for managing interface names.
Thanks.
=> tools: lxc-unshare: use lxc list for interface names

src/tests/parse_config_file.c
=> tests: add lxc.monitor.signal.pdeath

config/apparmor/abstractions/start-container
openSUSE Leap 15 is using --libdir=/usr/lib64 when building for
x86_64 so we need to allow this path in the apparmor profiles.
Link: https://bugzilla.opensuse.org/show_bug.cgi?id=1099239
Signed-off-by: Markos Chandras <mchandras@suse.de>
=> apparmor: Allow /usr/lib* paths for mount and pivot_root

src/lxc/conf.c
This means they need to be added for remount and for fresh mounts.
=> conf: the atime flags are locked in userns

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile.h, src/lxc/lxccontainer.c, src/lxc/lxccontainer.h, src/lxc/start.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/Makefile.am, src/tests/mount_injection.c
Hi there!
This is an initial step for moving the mount injection stuff from LXD to LXC. 
In this PR, the new `lxc_container` API method `mount` is introduced, alongside with the supporting config option `shmounts` for `lxc.mount.auto` (because in order to enable mount injection in the running container, a shared mount point is established between on a startup) and the necessary utils.
UPD: also introduce the `umount` API method.
=> Mount injection API 

src/lxc/caps.c, src/lxc/start.c
Hello,
change log macro of error case from lxc_ambient_caps_up/down.
because all errno strings are printed in lxc_amvient_caps_up / down() functions.
Thanks.
=> change log macro of error case from lxc_ambient_caps_up/down

config/apparmor/abstractions/container-base.in, config/apparmor/abstractions/start-container, config/apparmor/profiles/lxc-default-cgns, config/apparmor/profiles/lxc-default-with-nesting, configure.ac, src/lxc/Makefile.am, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/criu.c, src/lxc/lsm/apparmor.c, src/lxc/lsm/lsm.c, src/lxc/lsm/lsm.h, src/lxc/lsm/nop.c, src/lxc/lsm/selinux.c, src/lxc/start.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/Makefile.am, src/tests/lxc-test-apparmor-generated, src/tests/lxc-test-apparmor-mount
This implements apparmor profile generation as done by lxd in lxc and adds support for nesting profiles and apparmor namespaces directly out of lxc.
An advantage this brings is being able to avoid having to maintain the profile in multiple places.
Enabling nesting currently also implicitly adds the /dev/.lxc/{proc,sys} mounts.
Questions on my side are mainly whether to keep the profile snippets in the source file, or put them in files installed in the system. They could that way be in the apparmor abstractions directory, `#include`-able by others, with the original profile there simply built from the individual parts. (Of course, this alone with no other support code would also solve the profile maintenance issue ;-) )
Feedback welcome :-)
=> RFC: Generated Apparmor profiles, namespaces, stacking

src/lxc/nl.c
It's a valid case to call nla_put() with NULL data and 0 len. It's done e.g. in
the nla_put_attr().
There has to be a check for data in nla_put() as passing NULL to the memcpy()
is not allowed. Even if length is 0, both pointers have to be valid.
For a reference see C99 standard (7.21.1/2), it says: "pointer arguments on
such a call shall still have valid values".
Reported-by: Daniel Gimpelevich <daniel@gimpelevich.san-francisco.ca.us>
Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
[christian.brauner@ubuntu.com: adapted commit message]
=> nl: avoid NULL pointer dereference

doc/lxc.container.conf.sgml.in
Unprivileged containers are not compatible with sharing the 
host namespace due to an inability to mount sysfs. Add docs
in lxc.container.conf to document that.
Refs #2463
Signed-off-by: Alexandros Kosiaris <akosiaris@gmail.com>
=> Unprivileged's incompatibility with type=none docs

src/lxc/conf.c
The "max" option to devpts got introduced in kernel 3.4.
Closes #2490.
=> conf: mount devpts without "max" on EINVAL

src/lxc/tools/lxc_destroy.c
=> coverity: #438136

src/lxc/log.c, src/lxc/log.h, src/lxc/tools/arguments.c, src/lxc/tools/lxc_unshare.c
Hello,
I have a proposal for default log priority by used tools.
Now, user does not specify log priority or log file using -l or -o options, any logs are not printed.
So, I added default log priority without logfiles.
(If user specify log priority & log file explicitly, behavior is the same as before.)
If this is merged, I'll apply default log priority as error level to all tools.
Thanks.
=> add default log priority & cleanups

.travis.yml, src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h, src/lxc/start.c
Start to allocate a new network namespace id for each container.
Relates to lxc/lxd#4831.
=> netns: allocate network namespace id

src/lxc/network.c
The kernel expects a __s32 for NETNSA_NSID and a __u32 for NETNSA_FD.
=> network: type fixes lxc_netns_set_nsid()

src/lxc/network.c, src/lxc/nl.c, src/lxc/nl.h
These allow to pass a struct nlmsghdr directly and are used in the higher level
netlink_{send,rcv,transaction}.
=> netlink: add __netlink_{send,recv,transaction}

src/lxc/pam/pam_cgfs.c
=> coverity: #1438392

src/lxc/state.c
sleep() is not thread-safe but nanosleep() is. Since no resources are allocated
in lxc_wait() it is safe to call nanosleep() without cancellation handlers.
=> state: s/sleep()/nanosleep()/

doc/lxc.container.conf.sgml.in
Current we have a few minor grammatical errors in the documentation for LXC container configuration.
Fix minor grammatical errors.
=> doc: Fix minor grammatical errors

src/lxc/cmd/lxc_usernsexec.c
Currently if `lxc-usernsexec` is run on a kernel without user namespaces
enabled the error message is
```
unshare: Invalid argument
read pipe: Success
```
This error message 'Invalid argument' does not point at the root cause
of the error.  We can help the user out by giving a more detailed error
message and also not using perror() if errno==0.
Improve error message by
- Printing unshare flags
- Printing suggested cause of failure (user namespace not enabled)
- Print error message with fprintf() if errno==0 (EOF)
With this applied error message is
```
unshare: CLONE_NEWNS | CLONE_NEWUSER
You may need to enable user namespaces
pipe closed by child
```
I'm not convinced this is the best message.  If this is judged a _real_ issue perhaps we can come up with something better.
thanks,
Tobin. …
=> usernsexec: Make err out vebose for unshare error

CODING_STYLE.md, CONTRIBUTING
The first entry point to a project for new developers is often the `CONTRIBUTING` and `CODING_STYLE.md` files.  We should keep these documents as correct and accessible as possible to ease the pathway for new contributors.
Clean up `CONTRIBUTING` and `CODING_STYLE.md` documentation files by:
- Cleanly referencing and linking to kernel docs coding style guide.
- Minor grammar fix.
- Simplify the docs where possible including removing superfluous documentation.
- Improve section header format.
These changes shouldn't be too contentious, except perhaps these two patches:
524440e920df ("CODING_STLYE: Remove sections implied by 'kernel style'")
7419c83f441b ("CODING_STYLE: Update section header format")
thanks,
Tobin.
=> Clean up contributing and coding stlye docs

src/lxc/cmd/lxc_init.c, src/lxc/cmd/lxc_monitord.c, src/lxc/cmd/lxc_user_nic.c
This is the remainder of the fixes found by checkpatch for `cmd/`.  The warnings left are either contentious or not demanded by our coding style.
- Use parenthesis around complex macro i.e. `(foo + 1)` instead of `foo + 1`.
- Use 'void' instead of empty parameter list i.e. `static int fn(void)` .
- Do not use braces for single statement block.
- Fix all whitespace issues as a single patch since these are easy to review.
- Use 'const' for static string constant.
- Remove unnecessary whitespace in string (separate patch because this only subjectively better).
- Put trailing */ on a separate line (standard comment format).
- Remove accidental duplicate semicolon 
- Do not use comparison to NULL i.e. `if (!foo)` instead of `if (foo == NULL)`.
All patches build cleanly but no further testing …
=> cmd: Fix up checkpatch warnings

src/lxc/cmd/lxc_init.c
Since we switched to execveat() whenever possible in
commit 4b5b3a2a299b ("execute: use execveat() syscall if supported")
it is unlikely that remove_self() has any job to do at all. So dumb down the
error levels.
Closes #2536.
=> lxc_init: s/SYSDEBUG()/SYSERROR()/g in remove_self

src/lxc/storage/storage_utils.c, src/lxc/storage/storage_utils.h, src/lxc/tools/lxc_copy.c, src/lxc/tools/lxc_create.c
Hello,
get_fssize() function is defined in lxc_create and lxc_copy tools.
So, we moved this function to storage_utils.
Thanks.
=> storage_utils: move duplicated function from tools

src/lxc/storage/loop.c
The issue was introduced in PR (https://github.com/lxc/lxc/pull/1705):
Previous code:
```
if (lseek(fd, size, SEEK_SET) < 0) {
SYSERROR("Error seeking to set new loop file size");
close(fd);
return -1;
}
```
New code:
```
int fd, ret;
[...]
ret = lseek(fd, size, SEEK_SET);
if (ret < 0) {
SYSERROR("Failed to seek to set new loop file size for loop "
"file \"%s\"", path);
close(fd);
return -1;
}
```
Based on http://man7.org/linux/man-pages/man2/lseek.2.html:
> Upon successful completion, lseek() returns the resulting offset location as measured in bytes from the beginning of the file.
Because `size` is `uint64_t`, it's very easy to overflow `res` and as a result the code will success randomly (if overflow is >0 it will pass it it's <0 it will fail).
Example from strace:
```
[...]
[pid …
```
=> storage/loop.c: integer overflow

src/lxc/tools/lxc_execute.c
Initialize buf to avoid parsing random data later on.
=> tools: fix lxc-execute command parsing

src/lxc/conf.c
Fixes: 6947153da ("conf: use mknod() to create dummy mount target")
=> conf: fix path/lxcpath mixups in tty setup

src/lxc/cmd/lxc_user_nic.c
Run linter `cppcheck` over `src/lxc/cmd`.
This is i tiny PR to see if `LXC` is into using cppcheck for linting.  Patch one makes a change that is directly related to the discussion in #2542 (in regards to declaring/initializing local variables).  Patch 2 is a stylistic change reducing the scope of a variable (and minuscule amounts of required cognitive load).  Please be harsh to critique these changes, I'll follow on the ruling here with further linting if deemed useful.
thanks,
Tobin. 
=> cmd: Lint with cppcheck

src/lxc/start.c
When creating container that has multiple net ifaces fails
because of wrong net config, lxc doesn't remove previously created
net ifaces.
Solve this issue with changing return path in lxc_spawn().
Signed-off-by: Jungsub Shin jungsub_shin@tmax.co.kr
=> start: Fix net iface remaining issue

src/lxc/Makefile.am
=> Makefile: don't allow undefined symbols

configure.ac, src/lxc/start.c
We line up with the Linux kernel and won't support any compiler under 4.6.
Additionally, we also require at least gnu99 so this is due anyway.
=> autotools: check if compiler is new enough

src/lxc/execute.c
Passing /proc/1/fd/<nr> presupposes that CLONE_NEWPID was specified. This isn't
the case when users use lxc.namespace.keep = pid to inherit pid namespaces.
Pass /proc/self/fd/<nr> instead.
Reported-by: Mrinal Dhillon <mdhillon@juniper.net>
=> execute: pass /proc/self/fd/<nr>

src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/conf.h, src/lxc/confile.c, src/lxc/criu.c, src/lxc/freezer.c, src/lxc/lxc.h, src/lxc/lxccontainer.c, src/lxc/start.c, src/tests/cgpath.c
This adds the new lxc.cgroup.keep config key. The key can be used to instruct
LXC to not escape to never escape to the root cgroup. This makes it easy for
users to adhere to restrictions enforced by cgroup2 and systemd. Specifically,
this makes it possible to run LXC containers as systemd services.
Note that cgroup v1 is considered legacy and will not see additional
controllers being added to it. This means that it is safe to use
lxc.cgroup.keep as config key since there is no "keep" controller. The only way
a conflict can be introduced is if the user is creating a named controller. I
think this case can be safely ignored since it is super rare and also the users
problem.
Cc: Felix Abecassis <fabecassis@nvidia.com>
Cc: …
=>  confile: add lxc.cgroup.keep

src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/log.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/tools/lxc_monitor.c, src/lxc/utils.c, src/tests/lxc-test-utils.c
I think this way it's easier with future changes, unless someone changes an array to a pointer, but then all uses must be checked anyway, and we already have both versions in the code.
=> tree-wide: use sizeof on static arrays

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/lxccontainer.c, src/tests/parse_config_file.c
This introduces a new config key lxc.rootfs.managed which can be used to
indicate whether this LXC instance is managing the container storage. If LXC is
not managing the storage then LXC will not modify the container storage.
For example, an API call to c->destroy(c) will then run any destroy hooks but
will not destroy the actual rootfs (Unless, of course, the hook does so behind
LXC's back.).
CC: Wolfgang Bumiller <w.bumiller@proxmox.com>
CC: Stéphane Graber <stgraber@ubuntu.com>
CC: Serge Hallyn <serge@hallyn.com>
CC: 2xsec <dh48.jeong@samsung.com>
=> [RFC] conf: introduce lxc.rootfs.managed

src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/log.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/tools/lxc_monitor.c, src/lxc/utils.c, src/tests/lxc-test-utils.c
This reverts commit 2fb7cf0b325d2e34cd6faa2758cbaba6b6c3b99f.
The problem wasn't caused by the reverted commit and was fixed in
commit 0c9b1f826d3 ("macro: calculate buffer lengths correctly")
The full explanation can be taken from the following irc excerpt from
the #lxc-dev channel:
```
│19:54:47 brauner | there was a bug in one of the standard macros we used
│19:55:01 brauner | and the changes by INTTYPE_TO_STRLEN() caused the issue to surface
│19:55:03 brauner | which is good
│19:55:16 brauner | i sent a branch and stgraber merged it that fixes it
│19:57:56  Blub\0 | so...
│19:58:31  Blub\0 | still doesn't explain how it was the sizeof() patch
│20:07:14 brauner | Blub\0: so here's the long explanation
│20:07:35 brauner | Blub\0: stgraber bumped pid_max on our jenkins test builders …
```
=> Revert "Revert "tree-wide: use sizeof on static arrays""

configure.ac
Fix #2592 by defining -Wvla -std=gnu11 even if --disable-werror is set
As -std=gnu11 is always set, bump requirement on gcc from 4.6 to 4.7
(see https://gcc.gnu.org/projects/cxx-status.html#cxx11)
=> lxc: fix build with --disable-werror

src/lxc/lxccontainer.c
=> lxccontainer: use correct pid_t type

src/lxc/conf.c, src/lxc/lxccontainer.c, src/lxc/tools/lxc_unshare.c
Hello,
Some resources have too wide or inconsistent non-owner permissions.
So, we remove the permissions of others.
Thanks. 
=> security: fix too wide or inconsistent non-owner permissions

src/lxc/attach.c
POSIX mandates that on ENOEXEC 126 and on ENOENT 127 is supposed to be
reported.
=> attach: report standard shell exit codes

src/lxc/lxccontainer.c
=> lxccontainer: remove cgroup locking

src/lxc/conf.c
The extra bind-mount is not required. To succesfully remount read-only
we just need MS_REMOUNT|MS_RDONLY.
Closes #2602.
Cc: Serge Hallyn <serge@hallyn.com>
=> conf: remove extra MS_BIND with sysfs:mixed

src/lxc/cgroups/cgfsng.c
Helps to easily tell the cgfsng ops functions from helpers.
=> cgfsng: mark ops with __cgfsng_ops__ attribute

src/lxc/conf.c
Hello,
realpath() does not use null as second parameter. It can cause buffer overflow.
So, the second parameter is modified to null to prevent buffer overflow.
Thanks.
=> conf: realpath() uses null as second parameter to prevent buffer overflow

src/lxc/cgroups/cgfsng.c
Closes https://github.com/lxc/lxd/issues/5060.
=> cgfsng: copy parent's cpu settings for monitor too

src/lxc/compiler.h, src/lxc/confile.c, src/lxc/parse.h
This instructs the compiler to better optimize the config parsing code.
=> compiler: add __hot attribute

src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/start.c, src/lxc/start.h
Since we switched to the new cgroup scoping scheme that places the
container payload into `lxc.payload/<container-name>` and
`lxc.monitor/<container-name>` deletion becomes slightly more complicated.
The monitor will be able to `rm_rf(lxc.payload/<container-name>)` but will
not be able to `rm_rf(lxc.monitor/<container-name>)` since it will be
located in that cgroup and it will thus be populated.
My current solution to this is to create a lxc.pivot cgroup that only
exists so that the monitor process on container stop can pivot into it,
call `rm_rf(lxc.monitor/<container-name>)` and can then exit. This group
has not function whatsoever apart from this and can thus be shared by
all monitor processes.
=> cgroups: implement monitor cgroup deletion

src/lxc/storage/btrfs.c
Closes #2655.
Fixes: 9de31d5a1394 ("tree-wide: s/strncpy()/strlcpy()/g")
=> btrfs: fix btrfs containers

templates/lxc-oci.in
OCI image spec dosen't specify an action when there is
no /etc/passwd or /etc/group. So if there is no
/etc/passwd with string user info, set uid to 0. If there
is no /etc/group with string group info, set gid to 0.
Signed-off-by: Jungsub Shin jungsub_shin@tmax.co.kr
=> oci-template: Add logic for no /etc/passwd, group

src/include/netns_ifaddrs.c, src/include/netns_ifaddrs.h
=> netns_ifaddrs: only use struct rtnl_link_stats64

src/lxc/parse.c
When we call lxc_file_for_each_line_mmap() we will always parse the
whole config file. Prefault it in case it is really long to optimize
performance.
=> parse: prefault config file with MAP_POPULATE

src/lxc/cgroups/cgfsng.c, src/lxc/utils.c
Otherwise we will create a race.
=> cgfsng: do not reuse another monitor's cgroup

src/lxc/cgroups/cgfsng.c
Signed-off-by: Wolfgang Bumiller <w.bumiller@errno.eu>
=> cgfsng: use realloc instead of malloc+copy+free

src/lxc/file_utils.c, src/lxc/start.c
Hello,
When nsid setting is failed, error level log is printed. But lxc_spawn() is working.
So, we changed a log level of this operation to sys warning.
Thanks.
=> start: change log level

src/lxc/attach.c
=> attach: fix missing pthread.h include

src/lxc/confile.c, src/lxc/parse.c
Hello,
unused variale is removed.
Thanks.
=> confile: remove unused variable

src/lxc/criu.c
Testing `lxc <container> stop --stateful` crashed LXD:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x7f3198ff0592]
runtime stack:
runtime.throw(0x117fe4a, 0x2a)
/opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
/opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/signal_unix.go:372 +0x28e
goroutine 375 [syscall]:
runtime.cgocall(0xef38e3, 0xc420731630, 0x29)
/opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/cgocall.go:128 +0x64 fp=0xc4207315f0 sp=0xc4207315b8 pc=0x410fc4
gopkg.in/lxc/go-lxc%2ev2._Cfunc_go_lxc_migrate(0x7f316c001220, 0xc400000001, 0xc420302460, 0xc4205d6080, 0x0)
_cgo_gotypes.go:752 +0x4d …
```
=> checkpoint: fix running do_dump()

src/lxc/commands.c, src/lxc/commands_utils.c, src/lxc/commands_utils.h, src/lxc/monitor.c
Hello,
Some redundancy codes are removed with log cleanups.
Code logic is not changed.
Thanks.
=> Some redundancy codes of abstract unix socket are removed with log cleanups.

src/lxc/string_utils.c
Hello,
There is additional overflow issue using must_make_path with realloc(). This issue is also detected by the address sanitizer.
We fixed this issue and must_append_path() also.
==zone-launcher==1030==ERROR: AddressSanitizer: global-buffer-overflow on address 0xb60f3ee0 at pc 0xb60a78d1 bp 0xbe16e5b0 sp 0xbe16e5b4
READ of size 4 at 0xb60f3ee0 thread T0
#0 0xb60a78cf in strlcpy
#1 0xb60a794d in strlcat
#2 0xb6095305 in must_make_path
#3 0xb5fe6079 in __do_cgroup_enter.isra.9
#4 0xb60702c9 in __lxc_start
#5 0xb6070cc9 in lxc_start
#6 0xb6042577 in do_lxcapi_start
#7 0xb604351d in lxcapi_start
#8 0x4d1b31 in main
#9 0xb5cdc867 in __libc_start_main
Thanks.
=> string_utils: fix global buffer overflow issue

src/include/strlcpy.c
=> include: simplify strlcpy()

src/lxc/Makefile.am
=> autotools: fix --disable-commands builds

src/lxc/confile.c
Reported-by: 2xsec dh48.jeong@samsung.com
=> confile: fix append_unexp_config_line()

src/lxc/parse.c
Hello,
uninitialized value is fixed.
Thanks.
=> parse: fix uninitialized value

src/lxc/start.c
=> start: simplify

src/lxc/confile.c, src/lxc/lxccontainer.c, src/lxc/start.c, src/tests/mount_injection.c
Allow users to specify a path in the container they want to use.
This will help LXD.
Needed-by: https://github.com/lxc/lxd/issues/5227
=> conf: expand shmounts lxc.mount.auto option

src/lxc/caps.c, src/lxc/log.c
Hello,
read & write syscalls are replaced to nointr functions.
Thanks.
=> replace read & write syscalls with nointr functions

src/lxc/Makefile.am, src/lxc/cgroups/cgfsng.c, src/lxc/file_utils.c, src/lxc/initutils.c, src/lxc/pam/pam_cgfs.c, src/lxc/string_utils.c, src/lxc/utils.c
Hello,
Some redundancy functions in pam_cgfs & cgfs are removed.
And dependencies of pam_cgfs from cap & log are removed.
Thanks.
=> pam_cgfs: remove dependency & redundancy functions

src/lxc/storage/lvm.c
Adds `-qq` flags to lvcreate commands to avoid answer 'no' to any questions the LVM subsystem asks to avoid hanging the `lxc-create` command.
See http://man7.org/linux/man-pages/man8/lvcreate.8.html
```
-q|--quiet ...
Suppress output and log messages. Overrides --debug and
--verbose.  Repeat once to also suppress any prompts with
answer 'no'.
```
Fixes: https://github.com/lxc/lxc/issues/2346
=> Adds -qq flags to lvcreate commands

src/lxc/utils.c
=> utils: make keyring allocation failure non-fatal

src/lxc/Makefile.am
After commit 2b670df lxc-create and lxc-copy fails with "undefined
symbol: get_fssize".
Closes #2730
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
=> autotools: fix lxc-{create,copy} build

src/lxc/start.c
=> start: don't call cgroup_exit() twice

doc/lxc-copy.sgml.in, src/lxc/lxccontainer.c, src/lxc/lxccontainer.h, src/lxc/tools/arguments.h, src/lxc/tools/lxc_copy.c
Currently, LXC only allows to create new containers using a snapshot if the source container is shutdown.
While it is safer to do so, it is not required to shutdown the source container to get an working clone.
This is because creating a snapshot is much like an unexpected power outage; most Filesystems and databases are built from ground up to handle this case with minimum impact.
I have deployed LXC in a way that i have "live" containers that receive traffic and some sandbox/dev containers that are for testing with live data and environment. Using the --allowrunning option, i can reset and retest the sandboxes multiple times without downtime of the live containers.
i tested this against lxc-2.0 branch and have had no problems so far.
=> Added allowrunning command line option for snapshotting running containers

src/lxc/cmd/lxc_usernsexec.c
* Place NULL bytes at the end of strings so that
lxc_safe_ulong() can parse them correctly
* Only free the newly created id_map on error,
to avoid passing garbage to lxc_map_ids()
Signed-off-by: Cameron Nemo <camerontnorman@gmail.com>
=> lxc-usernsexec: fix default map functionality

src/lxc/string_utils.h
Fixes:
- http://autobuild.buildroot.org/results/0b90e7dca2984652842832a41abad93ac49a9b86
=> stringutils: include stdarg for va_list

configure.ac
Compiler based hardening (including -fstack-protector-strong) are
enabled since version 3.0.3 and
https://github.com/lxc/lxc/commit/2268c27754152aa538db2c9e3753d72d19bcd17a
However, some compilers could missed the needed library (-lssp or
-lssp_nonshared) at linking step so use ax_check_link_flag instead of
ax_check_compile_flag
Fixes:
- http://autobuild.buildroot.org/results/0b90e7dca2984652842832a41abad93ac49a9b86
=> configure.ac: fix build without stack-protector

src/lxc/tools/lxc_cgroup.c
lxc-cgroup fails to provide any output since the latest version ( #2742 ), this should fix it
Signed-off-by: Oguz Bektas <o.bektas@proxmox.com>
=> fix #2742: lxc-cgroup not giving output

config/apparmor/abstractions/container-base, config/apparmor/abstractions/container-base.in
RW bind mounts need to be restricted for some paths in
order to avoid MAC restriction bypasses, but read-only bind
mounts shouldn't have that problem.
Additionally, combinations of 'nosuid', 'nodev' and
'noexec' flags shouldn't be a problem either and are
required with newer systemd versions, so let's allow those
as long as they're combined with 'ro,remount,bind'.
(cherry picked from commit e6ec0a9e71aa68c9fd67c691a62aaae87e356cef)
=> apparmor: allow various remount,bind options

src/lxc/conf.c
=> conf: use SYSERROR on lxc_write_to_file errors

src/lxc/lxccontainer.c
Reverts lxc/lxc#2763 as it is unnecessary to set c to NULL after free in this case.
See; https://github.com/lxc/lxc/pull/2763#issuecomment-450723571
=> Revert "Set c to NULL after freeing it"

doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/conf.h, src/lxc/confile.c, src/lxc/seccomp.c
This adds the lxc.seccomp.allow_nesting api extension. If
lxc.seccomp.allow_nesting is set to 1 then seccomp profiles will be
stacked. This way nested containers can load their own seccomp policy on
top of the policy that the outer container might have applied.
Cc: Simon Fels <simon.fels@canonical.com>
=> confile: add lxc.seccomp.allow_nesting

src/lxc/cgroups/cgfsng.c
=> cgfsng: do not free container_full_path on error

src/lxc/lxccontainer.c
We need to strip the prefix from the container's source path before
trying to update the file.
Closes #2380.
=> lxccontainer: fix container copy

src/lxc/commands.c, src/lxc/terminal.c, src/lxc/terminal.h
SIGWINCH is handled in lxc_terminal_signalfd_cb().
I cannot for the life of me figure out what this is supposed to do.
Afaict, it scans a global list that is totally unnecessary and also
let's say you have 100 ttys and for a single one SIGWINCH is sent. In
that case the whole list is walked and two ioctl()s are performed: one
to get window size one to set window size. For 99 of them the window
size hasn't changed.
If we see issues we can revert!
=> terminal: remove sigwinch command

src/lxc/network.c
unprivileged veth devices (e.g. vethFWABHX) never contain 'Z' character in the randomly generated device name part because for modulo one does not need to substract 1 from strlen().
=> trivial fix: unprivileged veth devices (e.g. vethFWABHX) never contain 'Z' char

src/include/lxcmntent.c
Fixing compile error when compiling for android 
```
mv -f $depbase.Tpo $depbase.Po
../include/lxcmntent.c:145:30: error: implicitly declaring library function 'malloc' with type 'void *(unsigned long)' [-Werror,-Wimplicit-function-declaration]
getmntent_buffer = (char *)malloc(LXC_MAX_BUFFER);
^
../include/lxcmntent.c:145:30: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
1 error generated.
```
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
=> Fixing compile error when compiling for android

src/lxc/start.c
If cgroup namespaces are not supported we should just record it in the
log and move on.
Cc: Ondrej Kubik <ondrej.kubik@canonical.com>
=> start: handle missing CLONE_NEWCGROUP

src/lxc/cgroups/cgroup.c
Add free memory pointed by struct cgroup_ops *ops
=> Fix memory leak in cgroup_exit

src/lxc/conf.c, src/lxc/conf.h
1. cleanup namespace memory
2. fix bug when ro mount not setted, mount propagation will be skipped.
Signed-off-by: t00416110 <tanyifeng1@huawei.com>
=> conf.c: fix memory leak and mount error

src/lxc/utils.c
On android system sh is located at /system/bin/sh
If /bin/sh does not exist, try /system/bin/sh
Signed-off-by: ondra <ondrak@localhost.localdomain>
=> Fixing hooks functionality Android where 'sh' is placed under /system

src/lxc/commands.c
As we call "lxc_add_state_client(fd, handler, (lxc_state_t *)req->data)"
which supposes that the last parameter is a table of MAX_STATE
entries when calling memcpy():
memcpy(newclient->states, states, sizeof(newclient->states))
=> Avoid risk of "too far memory read"

src/lxc/freezer.c
Use strlen() on "state" variable instead of harcoded
value 6.
=> Avoid hardcoded string length

templates/lxc-busybox.in
The busybox template installs default.script in /usr/share/udhcpc/.
But the pathname of "default.script" may vary from one busybox
build to another. As the pathname is displayed in udhcpc's help,
grab it from it.
=> Installation of default.script for udhcpc

templates/lxc-busybox.in
As "which busybox" is stored in BUSYBOX_EXE 
global variable at startup, use it wherever it is
needed.
=> Use BUSYBOX_EXE variable in configure_busybox()

templates/lxc-busybox.in
This file grows indefinitely : upon each DHCP lease renew,
the "nameserver ..dns..." line is added at the end of the file.
Make a "grep" in the file to make sure that the same line
does not already exist.
=> /etc/resolv.conf grows indefinitely

src/include/prlimit.h, src/lxc/compiler.h
=> compiler: remove deprecated and unneeded header

src/lxc/conf.c
Since liblxc is completely in control of the mount entry file we should
only consider a parse successful when EOF is reached.
Closes #2798.
=> conf: check for successful mount entry parse

src/lxc/utils.c
When calling lxc-create, if the template exists but is not executable, we end with the following error messages which make believe that the template file does not exist when it is merely a execute access problem:
lxc-create: ctn00: utils.c: get_template_path: 918 No such file or directory - bad template: /.../lxc-busybox
lxc-create: ctn00: lxccontainer.c: do_lxcapi_create: 1786 Unknown template "/.../lxc-busybox"
lxc-create: ctn00: tools/lxc_create.c: main: 327 Failed to create container ctn00
Actually internally the errno is lost as the following code triggers a useless access to (strace output):
access("/.../lxc-busybox", X_OK) = -1 ENOENT (No such file or directory)
With the above fix, we get a more explicit error message when the template file is missing the "execute" bit:
lxc-create: …
=> More accurate error msg for template file

src/lxc/freezer.c, src/lxc/lxccontainer.c
Fix the coding style in a few files.
Fixes: db1228b35f3e ("Avoid hardcoded string length")
Fixes: 71fc9c046816 ("Avoid risk of "too far memory read"")
Fixes: 2341916a0367 ("Avoid double lxc-freeze/unfreeze")
Fixes: 9eb9ce3e4778 ("Update freezer.c")
=> freezer: non-functional changes

src/lxc/conf.c
The above commit reverted here confuses the mountall unit of privileged
Ubuntu 14.04 containers at startup so that they cannot finish booting.
This effectively reverts the commit fixing #2602.
@tommyknows, was there any actual breakage causing you to open #2602 or was it just about mount cleanliness? Because apparently removing that mount confuses 14.04 containers, and while that's certainly a bug on the container's side reverting this is the simplest solution if there's no harm in it. Otherwise if there was any breakage from the mount entry I'll instead make a patch to make this configurable.
=> Revert "conf: remove extra MS_BIND with sysfs:mixed"

lxc.spec.in
Closes #1825
Signed-off-by: tomponline <tomp@tomp.uk>
=> fix rpm packaging for bash completion directory.

src/include/lxcmntent.c, src/lxc/Makefile.am, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/lxc_user_nic.c, src/lxc/commands.c, src/lxc/commands_utils.c, src/lxc/conf.c, src/lxc/confile.c, src/lxc/lxccontainer.c, src/lxc/memory_utils.h, src/lxc/monitor.c, src/lxc/namespace.c, src/lxc/network.c, src/lxc/pam/pam_cgfs.c, src/lxc/start.c, src/lxc/storage/loop.c, src/lxc/storage/lvm.c, src/lxc/storage/nbd.c, src/lxc/storage/overlay.c, src/lxc/storage/rbd.c, src/lxc/storage/storage.c, src/lxc/string_utils.c, src/lxc/terminal.c, src/lxc/tools/lxc_unshare.c
=> tree-wide: wipe alloca() from the codebase

src/lxc/caps.c
When we are running inside of a user namespace getuid() will return a
non-zero uid. So let's check euid as well to make sure we correctly drop
capabilities
=> caps: check uid and euid

src/lxc/string_utils.h
Correcting license for string_utils.h from GPLv2+ to LGPLv2.1+ to be in line with the rest of the codebase and our licensing guidelines (CONTRIBUTING).
This license header was accidentally copy/paste from the wrong source file, this commit fixes the situation.
Individual copyright holders were tracked down and have confirmed their agreement with correcting the licensing information for this file.
Master issue: #2842
/* Affected People */
Christian Brauner <christian.brauner@ubuntu.com>
Fabrice Fontaine <fontaine.fabrice@gmail.com>
Josh Soref <jsoref@gmail.com>
Acked-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Acked-by: Josh Soref <jsoref@gmail.com>
=> string_utils.h: fix wrong licensing

src/lxc/Makefile.am, src/lxc/rexec.c, src/lxc/rexec.h, src/lxc/tools/lxc_attach.c
We cannot rexecute the liblxc shared library unconditionally as this would
break most of our downstreams. Here are some scenarios:
- anyone performing a dlopen() on the shared library (e.g. users of the LXC
Python bindings)
- LXD as it needs to know the absolute path to its own executable based on
/proc/self/exe etc.
This commit makes the rexecution of liblxc conditional on whether the
LXC_MEMFD_REXEC environment variable is set or not. If it is then liblxc is
unconditionally rexecuted.
The only relevant attack vector exists for lxc-attach which we simply reexecute
unconditionally.
Reported-by: Stéphane Graber <stgraber@ubuntu.com>
=> rexec: make rexecution opt-in for library callers

src/lxc/rexec.c, src/lxc/rexec.h, src/lxc/tools/lxc_attach.c
=> rexec: remove needless /proc/cmdline parsing

src/lxc/conf.c, src/lxc/network.c
Fixes: https://discuss.linuxcontainers.org/t/warning-in-the-container-log/4072/2
=> log: fixes

.travis.yml
This runs our coccinelle checks during testing. If any changes are detected by
git diff after coccinelle has executed we fail the build.
=> tests: run coccinelle checks

src/lxc/attach.c
Previously this set `ctx->ns_fd[*]` to `-EBADF` until commit
fd2a88b190eb ("attach: cleanup macros lxc_proc_close_ns_fd",
but there are some code paths where we call this before
later calling `lxc_proc_put_context_info` which would call
this function again with the file descriptors still
unchanged.
Note: Haven't run into an actual issue, just noticed this while
going through my unread notifications...
=> attach: use move_fd in lxc_proc_close_ns_fd

templates/lxc-download.in
Hi everyone,
I found that `gpg` ignores the `http_proxy` environment variable. As the lxc-download script already adjusts the keyserver when `http_proxy` is set, it also should set the necessary `gpg` option. Currently there is no way to use lxc-download behind a proxy, because of this problem.
I had to put the `gpg` command in a subshell, because if not, `gpg` would not work properly, as it does not treat `${DOWNLOAD_GPG_PROXY}` as a valid argument.
If there is a better solution, let me know about it. This is my first pull request for this project, I hope I got everything right.
Cheers,
Marco
=> gpg: use proxy, if http_proxy is set

src/lxc/conf.c
Signed-off-by: tomponline <tomp@tomp.uk>
=> conf: Fixes uninitialised variable.

src/lxc/conf.c
=> conf: avoid compiler warning

src/lxc/cgroups/cgfsng.c
In the pure-unified cgroup case (`cg_unified_init` instead of `cg_hybrid_init`), `ops->unified` was left uninitialized, making any attempts to set cgroup controllers using `lxc.cgroup2.<controller>` fail on systems with only cgroup2 mounted.
=> Fix lxc.cgroup2.<controller> on cgroup2-only systems

src/lxc/start.c
Callers such as LXD run post-stop hooks to perform cleanup operations on
shutdown. This can involve umount and other things. To avoid surprises with
lingering namespace references we should close all our namespace-preserving
file descriptors. We don't need them at this point anymore anyway.
=> hooks: drop namespace references before post-stop

src/lxc/storage/btrfs.c
Apparently the name received from the tree walk is not guaranteed to have \0
byte at the end. So let's make sure we append one.
Note that this is only an issue if there are any subvolumes in the container's
rootfs.
Closes 2826.
=> btrfs: ensure \0 byte at end

src/lxc/start.c, src/lxc/utils.c
@brauner given what you said in #2902, I believe we can unconditionally pass `monitor_pid` to `lxc_set_death_signal` if we fix the parent check in `lxc_set_death_signal`.
=> Fix PID namespace pdeathsig handling

configure.ac, src/lxc/Makefile.am
This adds --{disable,enable}-asan. It is disabled by default.
=> hardening: enable address sanitizer build

src/lxc/storage/lvm.c, src/lxc/utils.c, src/lxc/utils.h
lvm: Updates lvcreate to wipe signatures if supported, fallbacks to old command if not.
Signed-off-by: tomponline <tomp@tomp.uk>
Related to https://github.com/lxc/lxd/issues/5482#issuecomment-464810627
I found it quite tricky to test an older version of lvcreate, as LXC won't compile on CentOS 5, which has an older version of lvcreate without the `-Wy` flag.
Instead I created a dummy lvcreate command in `/usr/local/sbin/lvcreate` as follows, which outputs the same error as the old version of lvcreate does when passed the `-Wy` flag.
```
ARGS=$@
logger "lvcreate $ARGS"
while [ ! $# -eq 0 ]
do
case "$1" in
-Wy )
echo "lvcreate: invalid option -- W
Error during parsing of command line."
exit 3
;;
esac
shift
done
/usr/sbin/lvcreate $ARGS
```
Here is the syslog output from it, showing the …
=> lvm: Updates lvcreate to wipe signatures if supported

src/lxc/network.c
=> network: fix network device removal

src/lxc/start.c
Completes #2903 for user namespaces and `lxc.monitor.signal.pdeath`
=> More pdeathsig fixes

doc/api/Makefile.am
Signed-off-by: yosukesan <y.otsuki30@gmail.com>
This patch fix api doc generation failure by doxgen.
Absence of argument when doxygen is called was the cause.
If no argument is specified, doxygen searches a Doxyfile in current dir. Hence, in source build worked.
However, in out of source build this did not.
I tested both out of source and in source build both successfully terminated.
* In source build was just simple.
```
bash autogen.sh && ./configure && make
```
* out of source build
Identical to "Step to reproduce" in #2972
Do I need test more ? If so let me know.
For CMake users, out of source build is standard procedure :).
=> fix: #2927 api doc generation fails under out of source build.

src/lxc/attach.c
=> attach: use tighter scope for fd variable

src/lxc/cgroups/cgfsng.c
The child_path variable is initialized very late in the function so jumping to
the on_error label would cause a nullderef. With the cleanup macros we can
simplify this function to simply do direct returns and avoid that whole issue.
Closes #2935.
=> cgroups: fix potential nullderef

hooks/nvidia
Previously, environment variables with a space where splitted.
=> hooks/nvidia: handle spaces in NVIDIA_REQUIRE variables

src/lxc/conf.c
These configuration options use the same syntax and therefore it seems
more intuitive to have the same behavior for both of them, which is
not the case today since mount hooks and autodev mounts are called
between the two.
See: https://github.com/lxc/lxc/issues/2932
=> conf: do lxc.mount.entry mounts right after lxc.mount.fstab

src/include/netns_ifaddrs.c, src/lxc/macro.h
s/NETLINK_DUMP_STRICT_CHK/NETLINK_GET_STRICT_CHK/g
=> netns_getifaddrs: adapt to kernel changes

src/lxc/tools/lxc_start.c
We don't in fact exit(1) if this is not specified, and it wouldn't make
sense to, since most people probably don't specify this.
=> lxc-start: remove bad doc

src/lxc/storage/zfs.c
Another case of calling 'zfs get' which requires reordering arguments to work with latest zfs.
Signed-off-by: Paul Gauret <pgauret@yahoo.com>
=> Fix 'zfs get' command order

src/lxc/network.c
I noticed that the vlan network type doesn't execute network up/down hook scripts.
=> network: Adds hook handling for vlan network type

src/lxc/network.c
=> network: Fixes a little typo in an error message

src/lxc/network.c
Fixes issue introduced by https://github.com/lxc/lxc/pull/2952
=> network: Fixes vlan hook script

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/network.c, src/lxc/network.h, src/tests/parse_config_file.c
Adds support for specifying static routes for veth network devices what will be created on the host.
e.g.
```
lxc.net.0.veth.ipv4.route = 192.0.2.1/32
lxc.net.0.veth.ipv4.route = 192.0.3.0/24
lxc.net.0.veth.ipv6.route = 2001:db8::1/128
lxc.net.0.veth.ipv6.route = 2001:db8:2::/64
```
=> network: Adds veth static routes feature

doc/api-extensions.md
=> docs: Adds missing doc entries for seccomp related API extensions

src/lxc/network.c, src/lxc/network.h
The following functions can be made static for consistency:
lxc_ipv4_dest_add
lxc_ipv6_dest_add
lxc_ip_route_dest_add (renamed)
=> network: Makes some routing functions static

src/lxc/lxcseccomp.h
since apparently there are insane programming languages out there that just
silently remove packed members in structs.
=> seccomp: remove alignment requirements

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h, src/tests/parse_config_file.c
Example usage:
lxc.net[i].type=ipvlan
lxc.net[i].ipvlan.mode=[l3|l3s|l2] (defaults to l3)
lxc.net[i].ipvlan.isolation=[bridge|private|vepa] (defaults to bridge)
lxc.net[i].link=eth0
lxc.net[i].flags=up
=> network: Adds IPVLAN support

src/lxc/seccomp.c
=> seccomp: ensure fields are set to 0

src/lxc/confile_utils.c
This is something that might be needed per the crio/runc bundle spec documentation, i.e.
https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#namespaces
=> namespaces: allow a pathname to a nsfd for namespace to share

src/lxc/af_unix.c, src/lxc/af_unix.h, src/lxc/seccomp.c
There's an inherent race when reading a process's memory. The easiest way is to
have liblxc get an fd and check that the race was one, send it to the caller
(They are free to ignore it if they don't use recvmsg()).
=> seccomp: send process memory fd

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/file_utils.c, src/lxc/file_utils.h, src/lxc/network.c, src/lxc/network.h
Adds the `lxc.net.[i].l2proxy` flag that can be either 0 or 1.
Defaults to 0.
This, when used with `lxc.net.[i].link`, will add IP neighbour proxy entries on the linked device
for any IPv4 and IPv6 addresses on the container's network device.
E.g. where enp3s0 is the linked parent interface.
```
ip -4 route add local ${IF_IP4}/32 dev enp3s0
ip neigh add proxy ${IF_IP4} dev enp3s0
ip -6 route add local ${IF_IP6}/128 dev enp3s0
ip neigh add proxy ${IF_IP6} dev enp3s0
```
Additionally, for IPv4 addresses it will check the following sysctls are enabled and fail with an error if not:
```
sysctl net.ipv4.conf.enp3s0.forwarding=1
```
Additionally, for IPv6 addresses it will check the following sysctls are enabled and fail with an error if not:
```
sysctl net.ipv6.conf.enp3s0.proxy_ndp=1
sysctl …
```
=> network: Adds layer 2 (ARP/NDP) proxy mode

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/network.c, src/lxc/network.h, src/tests/parse_config_file.c
Adds ability to specify "dev" as the gateway value, which will cause a device route to be set as default gateway.
This is primarily intended for use with IPVLAN where due to the nature of it operating at layer 3, we do not need to specify a gateway IP address.
=> network: Adds gateway device route mode

src/lxc/compiler.h, src/lxc/raw_syscalls.c
The returns_twice attribute tells the compiler that a function may return more
than one time. The compiler will ensure that all registers are dead before
calling such a function and will emit a warning about the variables that may be
clobbered after the second return from the function. Examples of such functions
are setjmp and vfork. The longjmp-like counterpart of such function, if any,
might need to be marked with the noreturn attribute.
=> compiler: add __returns_twice attribute

templates/lxc-busybox.in
Added /dev in the mknod commands.
=> Devices created in rootfs instead of rootfs/dev

src/lxc/conf.c, src/lxc/namespace.c, src/lxc/namespace.h, src/lxc/start.c, src/lxc/start.h, src/lxc/storage/nbd.c, src/lxc/tools/lxc_unshare.c
Use CLONE_PIDFD when possible.
Note the clone() syscall ignores unknown flags which is usually a design
mistake. However, for us this bug is a feature since we can just pass the flag
along and see whether the kernel has given us a pidfd.
=> start: use CLONE_PIDFD

templates/lxc-busybox.in
Some error messages were not redirected to stderr.
Moreover, do "exit 0" instead of "exit 1" when "help" option is passed.
=> Redirect error messages to stderr

src/lxc/lxccontainer.c
lxc-ls without root privileges on privileged containers should not display
information. In lxc_container_new(), ongoing_create()'s result is not checked
for all possible returned values. Hence, an unprivileged user can send command
messages to the container's monitor. For example:
$ lxc-ls -P /.../tests -f
NAME     STATE AUTOSTART GROUPS IPV4 IPV6 UNPRIVILEGED
ctr -     0         -      -    -    false
$ sudo lxc-ls -P /.../tests -f
NAME     STATE   AUTOSTART GROUPS IPV4      IPV6 UNPRIVILEGED
ctr RUNNING 0         -      10.0.3.51 -    false
After this change:
$ lxc-ls -P /.../tests -f      <-------- No more display without root privileges
$ sudo lxc-ls -P /.../tests -f
NAME     STATE   AUTOSTART GROUPS IPV4      IPV6 UNPRIVILEGED
ctr RUNNING 0         -      10.0.3.37 -    false
$ …
=> lxccontainer: do not display if missing privileges

templates/lxc-busybox.in
. Add the "--bbpath" option to pass an alternate busybox pathname instead of the one found from ${PATH}.
. Take this opportunity to add some formatting in the usage display
. As a try is done to pick rootfs from the config file and set it to ${path}/rootfs, it is unnecessary to make it mandatory
=> New --bbpath option and unecessary --rootfs checks

src/lxc/criu.c
CRIU has only 4 [levels of verbosity](https://criu.org/Logging) (errors, warnings, info, debug). Thus, using `-v4` is more appropriate.
=> criu: Use -v4 instead of -vvvvvv

configure.ac
GLIBC supports %m to avoid calling strerror(). Using it saves some code space.
==> This check will define HAVE_M_FORMAT to be use wherever possible (e.g. log.h)
=> Config: check for %m availability

src/lxc/criu.c, src/lxc/storage/lvm.c, src/lxc/storage/zfs.c
This fixes a couple of issues in error paths when returning -1 when false was intended. Detected by the help of cppcheck.
=> Fix returning -1 in functions with return type bool

src/lxc/log.h
Use %m under HAVE_M_FORMAT instead of strerror()
=> Use %m instead of strerror() when available

src/lxc/macro.h, src/lxc/network.c
Updates lxc_restore_phys_nics_to_netns() to move phys netdevs back to the monitor's network namespace rather than the previously hardcoded PID 1 net ns.
This is to fix instances where LXC is started inside a net ns different from PID 1 and physical devices are moved back to a different net ns when the container is shutdown than the net ns than where the container was started from.
=> network: move phys netdevs back to monitor's net ns rather than pid 1's

src/lxc/attach.c, src/lxc/attach.h, src/lxc/lxccontainer.c
Let lxc_attach() reuse the already initialized container.
Closes https://github.com/lxc/lxd/issues/5755.
=> attach: do not reload container

src/lxc/lxccontainer.c
Specifically, refloat function arguments and remove useless comments.
=> lxccontainer: cleanup attach functions

src/lxc/cmd/lxc_user_nic.c, src/lxc/utils.h
Hello.
If group has a lot of members getgrgid_r fails with ERANGE if buffer is too small. 
I added retry with a larger buffer and buffer limit.
Please backport this to lxc-2.0.11 release.
Thanks.
Signed-off-by: Alexander Kriventsov <akriventsov@nic.ru>
=> lxc-user-net: Failed to convert string " Failed to get group name" to integer

src/lxc/start.c
=> start: fix handler memory leak at lxc_init failed

src/lxc/lxccontainer.c
There is a previous pull request for this: https://github.com/lxc/lxc/pull/2892
Signed-off-by: Paul Romlow <promlow@users.noreply.github.com>
Changed name of function so its purpose is more clear, and added comment. The function will return only the characters to the right of '/', if one exists.
=> proposed fix for #2892 - fix lxcbasename in lxc/lxccontainer.c

configure.ac, src/lxc/lxcseccomp.h, src/lxc/seccomp.c
When the seccomp notifier PR was merged everything was apparently renamed...
=> seccomp: align with upstream libseccomp

src/lxc/seccomp.c
Align with upstream libseccomp.
=> seccomp: s/SCMP_FLTATR_NEW_LISTENER/SECCOMP_FILTER_FLAG_NEW_LISTENER/g

src/lxc/lxcseccomp.h
So that we can deal with older kernels.
=> seccomp: add ifdefine for SECCOMP_FILTER_FLAG_NEW_LISTENER

src/lxc/conf.c
The hook string names must not be repeated in the source code to facilitate future changes
=> Centralize hook names

src/lxc/seccomp.c
Do not set SECCOMP_FILTER_FLAG_NEW_LISTENER as seccomp attribute.
Prior to libseccomp merging support for SECCOMP_RET_USER_NOTIF there was a
libseccomp specific attribute that needed to be set before
SECCOMP_RET_USER_NOTIF could be used. This has been removed.
=> seccomp: do not set SECCOMP_FILTER_FLAG_NEW_LISTENER

src/lxc/network.c
Return an error code when the name is invalid instead of pretending that things
are fine.
Closes #3044.
=> network: fix lxc_netdev_rename_by_index()

configure.ac, src/lxc/Makefile.am, src/lxc/lxccontainer.c, src/lxc/utils.c, src/lxc/utils.h
The reason for this is because openssl can be statically linked
against, gnutls cannot.
[ commit msg addendum ] I don't know that openssl is what we want.  Maybe we just want to hardcode our own.  But at least openssl is widely avaiable, and available as .a's.  Also, I guess lxc.pc will also need to be updated if we do this.
=> [RFC\ Switch from gnutls to openssl for sha1

lxc.pc.in
None of them seem to support pkg-config themselves, else we could add
them to Requires.private.
=> lxc.pc.in: add libs.private for static linking

src/lxc/parse.c
Signed-off-by: t00416110 <tanyifeng1@huawei.com>
=> parse.c: fix fd leak from memfd_create

src/lxc/cgroups/cgfsng.c
Reported-by: Free Ekanayaka <free.ekanayaka@canonical.com>
=> cgfsng: write cpuset.mems of correct ancestor

src/lxc/cgroups/cgfsng.c
=> cgfsng: fix memory leak in lxc_cpumask_to_cpulist

src/lxc/start.c
In start.c, do not fill path[] table if not necessary
=> Move code/variable in smaller scope

src/lxc/conf.c, src/lxc/network.c, src/lxc/network.h, src/lxc/start.c
Make sure that network creation happens at the same time for containers started
by privileged and unprivileged users. The only reason we didn't do this so far
was to avoid sending network device ifindices around in the privileged case.
Link: https://github.com/lxc/lxc/issues/3066
=> start: unify network creation

src/lxc/network.c, src/lxc/start.c
This restores the lxc.net.x.ipv4.gateway = auto and
lxc.net.x.ipv6.gateway = auto functionality.
When the child is created the parent and child have different views of
struct lxc_handler since - obviously - virtual memory is duplicated. So any
changes to done by the parent that the child should see need to be IPCed to it.
For any non-actual device creation stuff this does not make much sense. This
includes finding gateway addresses. Move it back prior to clone().
Fixes #3078
[christian.brauner@ubuntu.com: non-functional changes and update commit message]
=> start: call lxc_find_gateway_addresses early

configure.ac, doc/lxc.container.conf.sgml.in, src/lxc/af_unix.c, src/lxc/af_unix.h, src/lxc/confile.c, src/lxc/file_utils.c, src/lxc/file_utils.h, src/lxc/lxcseccomp.h, src/lxc/seccomp.c
General description (from the `seccomp: update notify api` commit:)
```
The previous API doesn't reflect the fact that
`seccomp_notif` and `seccomp_notif_resp` are allocatd
dynamically with sizes figured out at runtime.
We now query the sizes via the seccomp(2) syscall and change
`struct seccomp_notify_proxy_msg` to contain the sizes
instead of the data, with the data following afterwards.
Additionally it did not provide a convenient way to identify
the container the message originated from, for which we now
include a cookie configured via `lxc.seccomp.notify.cookie`.
Also verify the `id` in the client's response.
```
Another big change is the switch from `SOCK_STREAM` to `SOCK_SEQPACKET`. I think it makes sense: the seccomp notify kernel api is basically packet based as well.
=> Seccomp notify api update

src/lxc/utils.c
. Use sizeof() instead of hardcoded values
. snprintf(..., size, ""...) is in error if the return code is >= size (not sufficient to set only ">")
=> Suppress hardcoded table sizes

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/log.h, src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h
This PR adds a new "router" mode for veth networking.
The idea behind this is to provide an ipvlan-like networking mode that has the following properties:
- Works on older kernels.
- Uses the host's routing table (and netfilter rules) to route packets (potentially out of different interfaces or between containers), unlike ipvlan.
- Prevents containers from altering their IP.
- Prevents broadcast/multicast traffic to/from containers.
- Provides same MAC externally for all containers.
- No bridge interface to manage.
- Supports layer 3 only mode for setups where BGP (or other routing protocols) are running on the host to distribute container's IPs in the local routing table to the wider network.
- Containers can optionally have IPs published on local LAN at layer 2 using the existing …
=> Adds veth router mode

src/lxc/seccomp.c
Makes it easier to implement syscalls which need to write to
a buffer passed by user space as a pointer.
=> seccomp: open memfd read-write

src/lxc/start.c
Most kernels don't have this functionality yet, and so the warning is
printed a lot. Our people are scared of warnings, so let's make it INFO
instead in this case.
=> pidfds: don't print a scary warning on ENOSYS

src/lxc/cgroups/cgfsng.c, src/lxc/confile.c
=> tree-wide: initialize all auto-cleanup variables

src/lxc/cgroups/cgfsng.c
=> cgroups: initialize cpuset properly

src/lxc/attach.c, src/lxc/attach.h, src/lxc/lxccontainer.c, src/lxc/network.c, src/lxc/network.h
lxccontainer: do_lxcapi_detach_interface to support detaching wlan devices.
=> lxccontainer: do_lxcapi_detach_interface to support detaching wlan devs

src/lxc/lxccontainer.c, src/lxc/utils.c, src/lxc/utils.h
If SSL is enabled, utils will include function `do_sha1_hash()` to
generate a sha1 encrypted buffer. Last function argument of
`EVP_DigestFinal_ex()` requires a `unsigned int` but the current
parameter is an `integer` type.
See error:
utils.c:350:38: error: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign
[-Werror,-Wpointer-sign]
EVP_DigestFinal_ex(mdctx, md_value, md_len);
^~~~~~
/usr/include/openssl/evp.h:549:49: note: passing argument to parameter 's' here
unsigned int *s);
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
=> utils: Fix wrong integer of a function parameter.

src/lxc/attach.c
See the first context line, we want to replace stderr, as stdout is the pipe from which we want to read the result.
=> attach: don't close stdout of getent

src/lxc/cmd/lxc_user_nic.c
Hello.
This patch prevent search username as a substring in another username.
Signed-off-by: Alexander Kriventsov <akriventsov@nic.ru>
=> try to fix search user instead of search substring

src/lxc/utils.c
Some applications use information from `LOOP_GET_STATUS64`. The
file associated with loop device is pointed inside structure field
`lo_file_name`. The current code is setting up a loop device without
this information. A legacy example of code checking this in cryptsetup:
static char *_ioctl_backing_file(const char *loop)
{
struct loop_info64 lo64 = {0};
int loop_fd;
loop_fd = open(loop, O_RDONLY);
if (loop_fd < 0)
return NULL;
if (ioctl(loop_fd, LOOP_GET_STATUS64, &lo64) < 0) {
close(loop_fd);
return NULL;
}
lo64.lo_file_name[LO_NAME_SIZE-2] = '*';
lo64.lo_file_name[LO_NAME_SIZE-1] = 0;
close(loop_fd);
return strdup((char*)lo64.lo_file_name);
}
It will return an empty string because lo_file_name was not set.
v1: missing string casting for `lo_file_name`.
Signed-off-by: Julio Faracco …
=> utils: Copying source filename to avoid missing info [v2].

configure.ac
This PR adds to configure.ac the AC_PREREQ(2.69) to ensure that a recent enough version of Autoconf is being used. It also changes AC_HELP_STRING renamed to AS_HELP_STRING in Autoconf 2.69 and allows users to give to ./configure the option '--enable-feature' or  '--with-package' by setting the action-if-given values. I'd like to send more patches to configure.ac but will open small PR to easy the review process. Please let me know if there is something else that you guys would like to do in configure.ac.
=> Autoconf 2.69 conformance

src/lxc/cmd/lxc-update-config.in
Dear developpers,
When we use lxc-update-config to translate a LXCv2 to LXCv3 configuration file, we have a issue with the parameters lxc.network.X.ipv4.address.
The output of the translate is:
lxc.net.0.ipv4.address.address
Instead of:
lxc.net.0.ipv4.address
This introduce a bug: the container want to use the gateway address as a secondary network address.
Regards,
Signed-off-by: Alban VIDAL <zordhak@debian.org>
=> Fix lxc-update-config in network.address

src/lxc/start.c
=> start: pidfds obviously start - like any fd - at 0

src/lxc/start.c, src/lxc/start.h, src/lxc/utils.c, src/lxc/utils.h
In the usual case the child runs in a separate pid namespace. So far we haven't
been able to reliably set the pdeath signal. When we set the pdeath signal we
need to verify that we haven't lost a race whereby we have been orphaned and
though we have set a pdeath signal it won't help us since, well, the parent is
dead.
We were able to correctly handle this case when we were in the same pidns since
getppid() will return a valid pid. When we are in a separate pidns 0 will be
returned since the parent doesn't exist in our pidns.
A while back, while Jann and I were discussing other things he came up
with a nifty idea: simply pass an fd for the parent's status file and check the
"State:" field. This is the implementation of that idea.
Suggested-by: Jann Horn <jann@thejh.net>
Signed-off-by: …
=> start: handle setting pdeath signal in new pidns

doc/lxc.container.conf.sgml.in, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/tests/parse_config_file.c
Second try's a charm. Sorry. Closed the other PR in favour for this PR. 
This PR wants to solve an issue with a limited size of the `/dev` tmpfs, which already happened a while ago in https://github.com/lxc/lxc/issues/781. Back then the size of the `/dev` tmpfs was increased but with a fixed size. 
Under some rare but real circumstances, the `/dev` tmpfs can run out of space. Here from a real container in production:
```
root@irnsrvc16 ~ # df -h /dev
Filesystem     Type   Size  Used Avail Use% Mounted on
none           tmpfs  492K  492K     0 100% /dev
```
The reason in this case is that this specific container is used as central syslog server (using syslog-ng) for a couple dozen other LXC containers. syslog-ng uses its console logging to /dev/tty10, which just uses up the whole space
``` …
```
=> Add config parameter for /dev tmpfs size

configure.ac
In addition to PR  #3146. This PR updates the remaining obsolete functions according to Autoconf 2.69 manual. 
Signed-off-by: Caio B. Silva <caioboffo@gmail.com>
=> Autoconf 2.69 conformance II 

doc/lxc.container.conf.sgml.in
This trivial patch adds more information about 'lxc.start.order'. Currently there is nothing about how the "order" is treated (whether a lower value means an earlier start or opposite). This patch adds a sentence which explains it.
=> doc: Add more info about 'lxc.start.order'

doc/lxc.container.conf.sgml.in
When calling "man lxc.container.conf", an internal "man" keyword is displayed :
$ man lxc.container.conf
[...]
lxc.mount.entry
Specify a mount point corresponding to a line in the fstab format.  Moreover lxc supports mount  propagation,  such  as
rslave  or  rprivate, and adds three additional mount options.  optional don't fail if mount does not work.  create=dir
or create=file to create dir (or file) when the point will be mounted.  relative source path is taken to be relative to
the mounted container root. For instance,
dev/null proc/kcore none bind,relative 0 0
.fi     <-----------------------------------UNEXPECTED KEYWORD !!!!
The problem seems to come from the missing blanks before "dev/null proc/kcore none bind,relative 0 0"
Moreover, for homogeneity purposes, it is better to use …
=> Bad sgml/man translation

src/lxc/tools/lxc_destroy.c
Partially reverts 65b92ea5fcab559fd21be2685bd2f15ef6d33532 so that trying to destroy a non-existent container gives an error message.
=> lxc/tools/lxc/destroy: Restores error message on container destroy

src/lxc/syscall_wrappers.h
In case the internal memfd_create has to be used, make sure we don't
clash with the already existing memfd_create function from glibc.
This can happen if this glibc function is a stub. In this case, at
./configure time, the test for this function will return false, however
the declaration of that function is still available. This leads to
compilation errors.
Signed-off-by: Patrick Havelange <patrick.havelange@essensium.com>
=> syscall_wrappers: rename internal memfd_create to memfd_create_lxc

src/lxc/lsm/apparmor.c
=> apparmor: Prevent writes to /proc/acpi/**

src/lxc/terminal.c, src/lxc/terminal.h
=> terminal: prevent memory leak for lxc_terminal_state

src/lxc/terminal.c
Callers expect a NULL on error, and with PR #3171 marking
the pointer as `__do_free`, we now return a pointer to freed
memory here otherwise.
=> terminal: return NULL on error in terminal_signal_init

src/tests/Makefile.am, src/tests/lxc-test-exit-code
lxc2 broke this feature for lxc-execute, and lxc3 broke it for
lxc-attach. This adds a test making sure we don't do the same mistake
a third time.
=> tests: add tests making sure the exit code is appropriate.

src/lxc/cmd/lxc_usernsexec.c
Been wanting this for a long time.
Let's say you do
```
lxc-usernsexec mkdir x
lxc-usernsexec touch x/y
```
(Or just do an lxc-create) Now you can neither just rm -rf x, nor lxc-usernsexec rm -rf x.  You can do it in >1 steps, or provide your own mapping, but it sure would be nice to just lxc-usernsexec -s rm -rf x
=> lxc-usernsexec: support easily mapping own uid

src/tests/device_add_remove.c
BugLink: https://bugs.launchpad.net/bugs/1848587
The latter device has been removed apparently.
=> tests: use /dev/null instead of /dev/network_latency

src/lxc/start.c
"above" was used instead of "below"
=> Typo in a comment

src/lxc/network.c
Seems to be a simple mixup.
Found in LXC 3.0.3 shipped with Ubuntu 18.04.
=> fix wrong order of bridge/nic in error message

src/lxc/cgroups/cgroup2_devices.c, src/lxc/conf.h
=> cgroups/devices: use dedicated enums

src/lxc/conf.c
fix memory leak for  lxc_grow_array
=> conf: fix memory leak for set config rootfs options

src/lxc/api_extensions.h, src/lxc/cmd/lxc_user_nic.c, src/lxc/commands_utils.c, src/lxc/commands_utils.h, src/lxc/compiler.h, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/file_utils.c, src/lxc/file_utils.h, src/lxc/macro.h, src/lxc/memory_utils.h, src/lxc/raw_syscalls.c, src/lxc/raw_syscalls.h, src/lxc/rexec.c, src/lxc/ringbuf.c, src/lxc/ringbuf.h, src/lxc/string_utils.c, src/lxc/string_utils.h, src/lxc/syscall_wrappers.h
This branch updates a number of file which were shipping with an incorrect licensing header.
Per our CONTRIBUTING guidelines, all files shipped as part of liblxc must be LGPLv2.1+ or a compatible, more permissive license (as is the case for some of the includes).
Binaries that are shipped outside of liblxc may be licensed under the GPLv2+ license instead if the author so desires.
This branch fixes a number of file that are part of liblxc but were improperly licensed under GPLv2+, in most cases due to bad copy/paste of licensing headers.
This is treated as re-licensing so all affected files were analyzed to get a list of current potential copyright holders and all of them were contacted to confirm the change.
A follow-up branch will replace all those headers with machine-parsable SPDX …
=> tree-wide: Fix inconsistent license headers

src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/cgroups/cgroup2_devices.c, src/lxc/commands.c, src/lxc/commands.h, src/lxc/file_utils.c, src/lxc/file_utils.h
=> cgroup: add command to retrieve cgroup2 fd and rework cgroup2 attach

src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.h, src/lxc/commands.c, src/lxc/log.h, src/lxc/macro.h
The current attach.c codepath which handles moving the attaching process into
the container's cgroups allocates a whole new struct cgroup_ops and goes
through the trouble of reparsing the whole cgroup layout.
That's costly and wasteful. My plan has always been to move this into the
command api by getting fds for attaching back but but it's not worth going
through that hazzle for non-unified hosts. On pure unified hosts however -
being the future - we can just attach through a single fd so there's no need to
allocate and setup struct cgroup_ops.
=> cgroups: improve container cgroup attaching

src/lxc/conf.c
When parsing mount options e.g. from lxc.mount.entry the specified options are mapped to the flags constants. To do so, the strings are compared to the options contained in mount_opt. However, when comparing the strings, the length of the string is not checked. That entails that the option "rootcontext=selinux-context" is mapped to the mount option read-only (ro). This commit fixes
this issue by checking if a '=' is contained in the specified option and additionally comparing the length of the strings.
=> config: Fix parsing of mount options

src/lxc/conf.c, src/lxc/start.c, src/lxc/terminal.c
"busy" field is assigned with the command socket descriptor when the terminal is in use. So, use "-1" to disable it.
=> "busy" field init to -1 instead of 0

src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.h, src/lxc/start.c
When adding the new improved cgroup setup logic I didn't account for the fact
that we need the hierarchy fds up until chown. Add a dedicated cleanup method
to fix this:
```
lxc b1 20191212205052.712 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1481 - Bad file descriptor - Failed to fchownat(-9, , 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc b1 20191212205052.712 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1481 - Bad file descriptor - Failed to fchownat(-9, tasks, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc b1 20191212205052.712 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1481 - Bad file descriptor - Failed to fchownat(-9, cgroup.procs, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc b1 20191212205052.712 WARN     cgfsng - …
```
=> cgroups/cgfsng: do not prematurely close file descriptors

src/lxc/seccomp.c
Signed-off-by: dongxinhua <dongxinhua@huawei.com>
=> seccomp: support s390 seccomp

src/lxc/cmd/lxc-checkconfig.in, src/lxc/cmd/lxc-update-config.in
Signed-off-by: vikaig <vikaig99@gmail.com>
Fixes these errors
```
$ lxc-checkconfig
Failed to execute process '/usr/bin/lxc-checkconfig'. Reason:
exec: Exec format error
The file '/usr/bin/lxc-checkconfig' is marked as an executable but could not be run by the operating system.
$ lxc-update-config
Failed to execute process '/usr/bin/lxc-update-config'. Reason:
exec: Exec format error
The file '/usr/bin/lxc-update-config' is marked as an executable but could not be run by the operating system.
```
=> cmd: fix shebang

src/lxc/lxccontainer.c
create_run_template(): Double "will mount" in a comment
=> Word repetition in comment

templates/lxc-busybox.in
In busybox 1.30, the help of udhcpc for "-s" option changed:
--> busybox v1.27.2: -s,--script PROG	Run PROG at DHCP events (default /usr/share/udhcpc/default.script)
--> busybox v1.30.1: -s PROG		Run PROG at DHCP events (default /etc/udhcpc/default.script)
So, I changed the command line which extracts the script name to make it work for both versions
=> Adaptation to latest busybox

templates/lxc-busybox.in
The udhcpc directory is created with "mkdir -p" at the place dynamically specified by "busybox udhcpc --help".
=> Suppress useless udhcpc directory

src/lxc/cmd/lxc_user_nic.c, src/lxc/network.c, src/lxc/network.h, src/tests/api_reboot.c
This allows us to avoid having to move the network device. It also allows us to
work around a kernel bug that in combination with a recent change in systemd
244 causes uses of systemd-networkd to not get an ip address.
=> network: improve veth device creation

src/lxc/cgroups/cgroup.c
=> cgroup.c: fix memory leak at cgroup init failed

src/lxc/network.c
If MTU setting is provided in network device config then always use it rather than inheriting from the link device.
Affected both bridge and router veth modes.
=> network: Restore fixed MTU functionality

src/lxc/start.c
We need to account for the case where pidfd's are not supported by the kernel
in question.
Closes: #3254
=> start: fix container killing logic

config/selinux/lxc.te, doc/lxc.container.conf.sgml.in, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/lsm/lsm.c, src/lxc/lsm/lsm.h, src/lxc/lsm/selinux.c, src/lxc/utils.c, src/lxc/utils.h
lxc set's up a new session keyring for every container by default. If executed on an SELinux enabled system, by default, the keyring inherits the label of the creating process. If executed with the
currently available SELinux policy, this means that the keyring is labeled with the lxc_t type. Applications inside the container, however, might expect that the keyring is labeled with a certain context (and will fail to access the keyring if it's not explicitly allowed in the global policy). This patch introduces the config option lxc.selinux.keyring_context which enables to specify the label of the newly created keyring. That is, the keyring can be labeled with the label expected by the started application.
=> Add keyring option

src/lxc/lxclock.c
if (!name), we allocate an unnamed semaphore, but if we then fail to
allocate/create the lock, we don't free this semaphore, and we just leak
it.
=> lxclock: fix a small memory leak

src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/lxccontainer.c, src/lxc/start.c, src/lxc/storage/btrfs.c, src/lxc/storage/storage_utils.c
Drop groups before we change to userns root.
Reported-by: Teddy Reed <teddy.reed@gmail.com>
=> tree-wide: improve setgroups() dropping

src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h
=> cgroups: remove unused method and cleanup cgroup_exit()

configure.ac, src/lxc/cgroups/cgfsng.c, src/lxc/initutils.c
Link: https://discuss.linuxcontainers.org/t/lxc-cgroup-pattern-is-not-being-honored
=> cgroups: honor lxc.cgroup.pattern if set explicitly

src/lxc/raw_syscalls.c
Build of lxc 3.2.1 fails with ultrasparc on:
```
raw_syscalls.c: In function ‘lxc_raw_clone’:
raw_syscalls.c:66:3: error: invalid 'asm': invalid operand output code
asm volatile(
^~~
```
Issue has been added with commit b52e8e68a61866da2af86e85905ec850f8a8b7fc which added `%g1` instead of `%%g1`
Fixes:
- http://autobuild.buildroot.org/results/17c2319850f02f24da6fbef9656c07f86fdc5a3a
=> src/lxc/raw_syscalls.c: fix sparc assembly

src/lxc/utils.c
=> utils: only move_fd() when fdopen() has been successful

src/lxc/network.c
There is an intermittent issue, experienced on at least Ubuntu 18.04 (5.3.0-40-generic) and Alpine 3.11 (5.4.12-1-virt) when using the router network interface type that causes the IP proxy neighbour entries on the host side of the veth pair to not be created (or to disappear very shortly after being added).
The `ip neigh add proxy` command returns without an error, however by the time the network up hook has started a short time later, the IP neighbour proxy entries are no longer there (if they ever were).
I've also tested this using netlink rather than the ip command to add and both are equally affected.
Adding a short sleep between setting up the veth pair and adding the proxy entries appears to fix it.
=> network: Adds short sleep between veth setup and neighbour proxy add

src/lxc/commands.c, src/lxc/commands_utils.c, src/lxc/compiler.h
If lxc_add_state_client() is called with the container already being in
the desired state the client fd will never be closed and is leaking.
This due to setting stay_connected in lxc_cmd for
LXC_CMD_ADD_STATE_CLIENT. If the desired state isn't already achieved
the client fd will later be closed by calling lxc_cmd_fd_cleanup() but
in the other case the client configuration isn't added to the handlers
state clients. So the client fd has to be closed explicitely.
This is simply tested by starting container A and calling lxc-wait -n A
-s RUNNING.
=> commands_utils: fix socket leak when adding state client

src/lxc/memory_utils.h
=> memory_utils: remove unneeded inclusion of mntent.h

templates/lxc-busybox.in
shm file system was not mounted because of the "/" in :
lxc.mount.entry = shm /dev/shm tmpfs defaults 0 0
=> Trigger the mounting of shm file system

templates/lxc-busybox.in
Mount fs on /dev/shm and /dev/mqueue to experiment IPC in namespaces
=> Auto-create /dev/shm and /dev/mqueue

src/lxc/Makefile.am, src/lxc/cmd/lxc_user_nic.c, src/lxc/file_utils.c, src/lxc/file_utils.h
as this breaks on sparc.
Closes #3262.
=> lxc_user_nic: don't depend on MAP_FIXED

src/lxc/commands.c, src/lxc/raw_syscalls.c, src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_execute.c, src/lxc/utils.c
=> tools: fix -g and -u parameters for lxc-execute and lxc-attach and fix pidfd detection logic

src/lxc/Makefile.am, src/lxc/cgroups/cgroup2_devices.h, src/lxc/lxccontainer.c, src/lxc/raw_syscalls.c, src/lxc/raw_syscalls.h, src/lxc/seccomp.c, src/lxc/syscall_numbers.h, src/lxc/syscall_wrappers.h, src/lxc/tools/lxc_unshare.c
This allows us:
- to compile on kernels with outdated headers
- compile on older kernels but shipping on newer kernels
=> tree-wide: introduce and use syscall number header

src/lxc/Makefile.am, src/lxc/tools/lxc_unshare.c
=> lxc-unshare: add syscall_wrappers.h to build requirements

src/lxc/Makefile.am
=> Makefile: fix typo

src/lxc/conf.c, src/lxc/network.c, src/lxc/string_utils.h
=> network: fixes

src/lxc/start.c
This allows users to generate custom profiles at startup.
Closes #1848.
=> start: move reading seccomp profile after pre-start hook

src/lxc/conf.c
Here we would always set MS_RDONLY in required_flags if it was set in
mountflags, so the expression:
!(required_flags & ~mountflags)
would always be true, and we would always skip the remount.
Instead, let's treat readonly as special: always do the remount if
MS_RDONLY is present. Unfortunately it doesn't seem to show up in
sb.f_flag, so we can't use the same path as everything else.
This only inadvertently worked before because of a bug fixed in
f75917858023 ("conf: don't accidently double-mount").
=> conf: fix read-only bind mounts

Makefile.am, coccinelle/Makefile.am, configure.ac, doc/Makefile.am, src/tests/Makefile.am
deleted:    CODING_STYLE.md
deleted:    LICENSE.GPL2
deleted:    LICENSE.LGPL2.1
deleted:    README.md
deleted:    coccinelle/exit.cocci
deleted:    coccinelle/run-coccinelle.sh
deleted:    coccinelle/while-true.cocci
deleted:    doc/api-extensions.md
deleted:    src/tests/lxc-test-exit-code
deleted:    src/tests/travis.sh
=> make dist: add missing files

src/lxc/cgroups/cgfsng.c
=> cgroups: use hidden directory for attaching cgroup

src/lxc/cgroups/cgfsng.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/start.c
On olders kernels the restrictions to move processes between cgroups are
different than they are on newer kernels. Specifically, we're running into the
following check:
```c
if (!uid_eq(cred->euid, GLOBAL_ROOT_UID) &&
!uid_eq(cred->euid, tcred->uid) &&
!uid_eq(cred->euid, tcred->suid))
ret = -EACCES;
```
which dictates that in order to move a process into a cgroup one either needs
to be global root (no restrictions apply) or the effective uid of the process
trying to move the process and the {saved}uid of the process that is supposed
to be mvoed need to be identical. The new attaching logic we did didn't
fulfill this criterion for because it's not present on new kernels.
=> cgroups: handle older kernels (e.g. v4.9)

.gitignore, config/init/systemd/Makefile.am, config/init/systemd/lxc-monitord.service.in, configure.ac, lxc.spec.in, src/lxc/cmd/lxc_monitord.c
lxc-monitord instances are spawned on demand and, if this
happens from a service, the daemon is considered part of
it by systemd, as it is running in the same cgroups. This
can be avoided by leaving it running permanently.
=> allow running lxc-monitord as a system daemon

config/init/systemd/lxc.service.in
I wanna say it seems nicer for packaging, but then again debhelpers cannot reload anyway ;-)
Still, I think it makes sense.
=> init: add ExecReload to lxc.service to only reload profiles

src/lxc/cgroups/cgfsng.c
Without this change, a build error is triggered if you compile with
`-Werror=maybe-uninitialized`.
```
cgroups/cgfsng.c: In function 'cgfsng_monitor_enter':
groups/cgfsng.c:1387:9: error: 'transient_len' may be used uninitialized in this function
ret = lxc_writeat(h->cgfd_mon, "cgroup.procs", transient, transient_len);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The issue is that if `handler->transient_pid` is 0, then `transient_len` is
uninitialised but `lxc_writeat(..., transient_len)` still gets called.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> cgroups: fix "uninitialized transient_len" warning

src/lxc/cgroups/cgfsng.c
GCC 7 appears to be clever enough to detect that transient_len is
uninitialised but not that it won't be used despite [1]. Just initialise
it to zero to stop the complaining, and allow LXC to build on openSUSE
Leap.
[1]: 346830421a96 ("cgroups: fix "uninitialized transient_len" warning")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> cgroups: fix build warning on GCC 7

src/lxc/lxccontainer.c
=> lxccontainer: poll takes millisecond not seconds

src/lxc/start.c
This reverts commit 52520e4f793f73e5956c2d9de9c83f074622ce1d.
This can be NULL when there's a pre-start hook which fails.
=> Revert "start: remove unnecessary check for valid cgroup_ops"

doc/lxc.container.conf.sgml.in, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.h, src/lxc/commands.c, src/lxc/commands.h, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/criu.c
This is a new approach to #1302 with a container-side
configuration instead of a global boolean flag.
Contrary to the previous PR using an optional additional
parameter for the get-cgroup command, this introduces two
new additional commands to get the limiting cgroup path and
cgroup2 file descriptor. If the limiting option is not in
use, these behave identical to their full-path counterparts.
If these variables are used the payload will end up in the
concatenation of lxc.cgroup.dir.payload and
lxc.cgroup.dir.namespace (namespace may be empty), and the
monitor will end up in lxc.cgruop.dir.monitor. The
directories are fixed, no retry count logic is applied,
failing to create these directories will simply be a hard
error.
Note that …
=>  introduce lxc.cgroup.dir.{monitor,container,container.inner}

src/lxc/cgroups/cgfsng.c, src/lxc/start.c
Otherwise we cannot use an 'a' entry in devices.deny/allow
as these are not permitted once a subdirectory was created.
Without isolation we initialize the devices cgroup
particularly late, so there are probably cases which cannot
work with isolation.
=> cgroup isolation: handle devices cgroup early

src/lxc/af_unix.c, src/lxc/start.c, src/lxc/syscall_numbers.h
Closes https://github.com/checkpoint-restore/criu/issues/1011.
=> start: ensure all file descriptors are closed during exec

src/lxc/network.c
I want to create a lxc container with IPVLAN in L2 mode.
```
lxc.net.0.type = ipvlan
lxc.net.0.link = ens192
lxc.net.0.ipvlan.mode = l2
lxc.net.0.ipvlan.isolation = bridge
lxc.net.0.flags = up
lxc-start test 20200409065446.102 DEBUG    network - network.c:instantiate_ipvlan:681 - Instantiated ipvlan "ipkeGP4J" with ifindex is 21 and mode 0
lxc-start test 20200409065446.125 DEBUG    network - network.c:lxc_network_move_created_netdev_priv:3132 - Moved network device "ipkeGP4J" with ifindex 21 to network namespace of 9925
lxc-start test 20200409065446.125 TRACE    network - network.c:lxc_network_send_to_child:3583 - Sent network device name "ipkeGP4J" to child
lxc-start test 20200409065446.125 TRACE    network - network.c:lxc_network_recv_from_parent:3610 - Received network device name …
```
=> network: Make it possible to set the mode of IPVLAN to L2

src/lxc/cgroups/cgfsng.c
Link: https://github.com/lxc/lxc/issues/3183#issuecomment-612462322
=> cgroups: ignore legacy limits on pure cgroup2 systems

templates/lxc-oci.in
Move the content of rootfs inside OCI package to rootfs instead of replacing it, as the directory is used as the mountpoint.
Tested with directory and loop backingstore.
Noticed this on Debian, where the error message was `rmdir: failed to remove '/usr/lib/x86_64-linux-gnu/lxc/rootfs': Device or resource busy` when running 
lxc-create -n test -t oci -B loop -- -u docker://centos:latest
=> Fix lxc-oci template with loop backingstore

src/lxc/cgroups/cgroup.c
=> cgroup: fix wrong use of cgfd_con in cgroup_exit

src/lxc/conf.c
Fixes: Coverity 1461760.
Fixes: Coverity 1461762.
Fixes: Coverity 1461763.
=> conf: correctly cleanup memory in get_minimal_idmap()

src/lxc/cgroups/cgfsng.c
Fixes: https://discuss.linuxcontainers.org/t/memory-limits-no-longer-being-applied/7429/7
=> cgroups: fix cgroup limit braino

src/lxc/network.c
=> src/lxc/network: Fixes netlink attribute type 1 has an invalid length message

configure.ac, src/lxc/conf.c, src/lxc/conf.h, src/lxc/macro.h, src/lxc/syscall_numbers.h, src/lxc/syscall_wrappers.h, src/lxc/terminal.c, src/lxc/utils.h
to avoid the overhead of calling to lxc-usernsexec whenever we can.
=> conf: introduce userns_exec_mapped_root()

src/lxc/terminal.c
=> terminal: remove unneeded if condition

src/lxc/commands.c
When a newer lxc library communicates with an older one
(such as running an lxc 4.0 lxc-freeze on a longer running
container which was started while lxc was still at version
3), the LXC_CMD_GET_LIMITING_CGROUP command is not
available, causing the remote to just close the socket.
Catch this and try the previous command instead.
=> improve LXC_CMD_GET_CGROUP compatibility

src/lxc/network.c
Fixes: https://lists.linuxcontainers.org/pipermail/lxc-users/2020-May/015245.html
=> network: use __instantiate_ns_common() in instantiate_ns_phys() too

src/lxc/api_extensions.h
Somehow it's documented but wasn't ever added.
=> api_extensions: add "pidfd"

src/tests/lxc-test-usernsexec
Previously if the user was root, then the test would just skip
running (and exit 0).  The lxc test environment is run as root.
So, instead of never doing anything there, we create a user,
make sure it is in /etc/sub{ug}id and then execute the test as that
user.
If user is already non-root, then just execute the tests as before.
=> lxc-test-usernsexec: If user is root, then create and use non-root user.

doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h, src/tests/parse_config_file.c
Adds support for native bridge vlans.
Adds the following config keys:
- `lxc.net.0.veth.vlan.id` - singular VLAN ID for untagged membership (PVID). It accepts a special value of "none" to indicate that it should not be a member of any untagged VLAN (including the default one for the bridge).
- `lxc.net.0.veth.vlan.tagged.id` - multi-line option for specifying additional tagged VLAN ID memberships.
E.g.
```
lxc.net.0.flags = up
lxc.net.0.type = veth
lxc.net.0.veth.mode = bridge
lxc.net.0.veth.vlan.id = 2
lxc.net.0.veth.vlan.tagged.id = 3
lxc.net.0.veth.vlan.tagged.id = 4
lxc.net.0.link = br0
```
=> NIC: Veth native bridge VLAN support

src/tests/containertests.c
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
In the if condition : if !str is true i.e. str is NULL, it does further operations on str (fprintf) which can cause segmentation fault. Fix this by by changing the if condition to : 
if (str && strcmp(str, CONFIGFNAM))
=> containertests: fix null pointer defereference

src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h
The previous change made things confusing by impliying there may be a
secondary when VLAN/IPVLAN/bridge members can only have a single parent
device.
=> network: Rename primary to master

src/lxc/lxccontainer.c
Stopping a lxc container with without waiting on it was broken in master. This
patch fixes it.
Signed-off-by: Robert Vogelgesang <vogel@folz.de>
=> lxccontainer: fix non-blocking container stop

src/lxc/commands.c
We're ignoring commands that we don't know about. They used to be fatal. Not
anymore.
Closes: #3459.
=> commands: don't flood logs

src/lxc/attach.c
In `start.c:1284`, no_new_privs flag is set after LSM label is set.
Also, in `lxc.container.conf` documentation it is written that:
```
Note that PR_SET_NO_NEW_PRIVS is applied after the container has
changed into its intended AppArmor profile or SElinux context.
```
This commit fixes the behavior of `lxc_attach` by moving
`PR_SET_NO_NEW_PRIVS` set logic after LSM for the process is configured;
Closes #3393
Signed-off-by: Alexander Livenets <a.livenets@gmail.com>
=> attach: set no_new_privs flag after LSM label

templates/lxc-download.in
Use the result of the gpg command, not the result when executing the result of the gpg command.
In my understanding, we want to execute the gpg command and use its return code. We do not want to execute the gpg command, then collect its output, execute that and then return the exit code from that command.
=> templates/lxc-download.in: fix wrong if-condition

templates/lxc-download.in
Using the option --recv-keys I get an error on openSUSE Tumbleweed which has `gpg2-2.2.20-1.2.x86_64`.
Not sure if this needs to be set differently for older systems, that do not have a recent gpg2 and thus might require the old  behaviour.
=> templates/lxc-download.in: use GPG option "--receive-keys"

doc/api-extensions.md, src/lxc/api_extensions.h
=> api-extensions: add seccomp_allow_deny_syntax extension

src/include/openpty.c
=> openpty: fix faulty rename

src/lxc/cmd/lxc-checkconfig.in
Please add the LXC version to the output of lxc-checkconfig.  Convenience is King 👑 
Thanks
=> checkconfig: Show LXC version in output.

src/lxc/network.c
To detect if a newly generated interface name is a duplicate of an existing interface lxc_ifname_alnum_case_sensitive() currently gets a list of all interfaces using netns_getifaddrs(). When the system has a small number of interfaces this works fine, however when there are thousands or tens of thousands of interfaces this quickly becomes less than optimal.
As we only need to check if an interface name exists, and do not need the detailed information about the interfaces provided by netns_getifaddrs(), we can instead use the if_nametoindex() function, which is much more efficient.
Signed-off-by: Sam Boyles <sam.boyles@alliedtelesis.co.nz>
=> Improve efficiency of lxc_ifname_alnum_case_sensitive

config/apparmor/abstractions/start-container.in
The rule added in 863845075d3f77d27c91bd9f47d2f8ddc4867bd5 did not cover all
necessary mount calls for /proc/sys/kernel/random/boot_id
(in src/lxc/conf.c: lxc_setup_boot_id) - the ro remount is missing.
Signed-off-by: Stoiko Ivanov <s.ivanov@proxmox.com>
=> apparmor: Allow ro remount of boot_id

src/lxc/seccomp.c
Linux v5.8 will land my patch where seccomp notifies when a filter goes unused,
i.e. when the last task using a given seccomp filter has exited. This wasn't
possible before and so we accumulated file descriptors in the container's event
loop whenever we attached to the container.
I'm not sure whether the task exiting before we could handle its syscall should
cause us to report and error or not. For now, let's simply close the event loop
and not report an error.
=> seccomp: remove seccomp fd from event loop after task exited

src/lxc/seccomp.c
Fixes: https://launchpadlibrarian.net/490341075/buildlog_snap_ubuntu_bionic_amd64_lxd-latest-edge_BUILDING.txt.gz
=> seccomp: add missing header

src/lxc/syscall_numbers.h, src/lxc/syscall_wrappers.h
lxc fails to build if `__NR_signalfd` is not defined since version 4.0.0 and https://github.com/lxc/lxc/commit/bed09c9cc0bec7bbd2442fcce4a2a0f03994cb09
However, some architectures don't define `__NR_signalfd` but only
`__NR_signalfd4.` This is the case for example for nios2 or csky:
https://github.com/bminor/glibc/blob/f9ac84f92f151e07586c55e14ed628d493a5929d/sysdeps/unix/sysv/linux/nios2/arch-syscall.h
https://github.com/bminor/glibc/blob/f9ac84f92f151e07586c55e14ed628d493a5929d/sysdeps/unix/sysv/linux/csky/arch-syscall.h
Fixes:
- http://autobuild.buildroot.org/results/75096a48d2dbda57459523db3ed0952e63f93535
=> syscall: don't fail if __NR_signalfd is not defined

src/lxc/seccomp.c
=> seccomp: don't close the mainloop, simply remove the handler

doc/api-extensions.md, src/lxc/api_extensions.h, src/lxc/commands.c, src/lxc/commands.h, src/lxc/lxccontainer.c, src/lxc/lxccontainer.h, src/lxc/seccomp.c
which allows to retrieve an active seccomp notifier fd from a running
container.
=> seccomp: add seccomp_notify_fd_active api extension

doc/api-extensions.md, src/lxc/api_extensions.h
=> api-extension: add missing seccomp_proxy_send_notify_fd extension

src/lxc/utils.c
When detecting if rootfs is on ramfs instead of checking "- rootfs
rootfs" which is the " - <file_system> <device>" information only check
the file system type. This is due to a change introduced in kernel where
ramfs file system doesn't set the device to "rootfs" but instead mark it
as "none". By making sure we only check for "rootfs" as the file system
name we also offer backward compatibility with earlier kernels as well.
The kernel commit that introduced this change was
commit f32356261d44d580649a7abce1156d15d49cf20f
Author: David Howells <dhowells@redhat.com>
Date:   Mon Mar 25 16:38:31 2019 +0000
vfs: Convert ramfs, shmem, tmpfs, devtmpfs, rootfs to use the new
mount API
Signed-off-by: Pranay Kr. Srivastava <pranay.srivastava@pantacor.com>
=> Check only rootfs as filesystem type

src/lxc/cgroups/cgfsng.c
Link: https://launchpadlibrarian.net/494473462/buildlog_ubuntu-groovy-armhf.lxc_1%3A4.0.4-0ubuntu2_BUILDING.txt.gz
=> cgroups: fix armhf builds

src/lxc/attach.c, src/lxc/terminal.c, src/lxc/terminal.h
Seems to appear when stderr is a terminal and not stdin or stdout.
Signed-off-by: Scott Parlane <scott.parlane@alliedtelesis.co.nz>
=> avoid a NULL pointer dereference in lxc-attach

src/lxc/commands.c
We can e.g. fail the unfreeze because the freezer cgroup is not available and
then we erronously report that stopping the container failed.
Closes: #3471.
=> commands: don't fail if unfreeze fails

config/init/systemd/lxc-monitord.service.in, config/init/systemd/lxc@.service.in
The Standard output type "syslog" is obsolete, causing a warning since systemd
version 246 [1].
Please consider using "journal" or "journal+console"
[1] https://github.com/systemd/systemd/blob/master/NEWS#L202
Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
=> Remove obsolete setting regarding the Standard Output

src/lxc/seccomp.c
While trying to implement seccomp profile generation for OCI container spec in crio-lxc I noticed the following error:
shortened log output:
```
seccomp - seccomp.c:parse_config_v2:790 - Processing "epoll_ctl_old allow"
seccomp - seccomp.c:parse_config_v2:987 - Added native rule for arch 0 for epoll_ctl_old action 2147418112(allow)
seccomp - seccomp.c:do_resolve_add_rule:558 - Numerical argument out of domain - Failed loading rule for epoll_ctl_old (nr 214 action 2147418112 (allow))
start - start.c:lxc_init:827 - Failed loading seccomp policy
```
The stripped down seccomp profile
```
2
allowlist errno 0
[X86_64]
epoll_ctl_old allow
```
The syscall `epoll_ctl_old` resolves on the native host architecture (here x86_64) but is not available in the compat architectures `X32` and ` i386`. But …
=> seccomp: Check if syscall is supported on compat architecture.

src/lxc/conf.c, src/lxc/conf.h, src/lxc/start.c
When no devpts devices are requested we used to return early but did not send a
response to the parent. This is a problem because the parent will be waiting
for a devpts fd to be sent. Make sure to always send a response.
=> conf: always send response to parent waiting for devptfs_fd

src/lxc/confile.c, src/lxc/confile.h, src/lxc/lxccontainer.c, src/tests/get_item.c
Use exact match instead of longest prefix match to check whether a config item is supported.
The current implementation matches the longest prefix which does not work when checking for sub-options.
E. g. checking whether `lxc.cgroup.dir.container` is supported will match on `lxc.cgroup.dir`,
and return true even if `lxc.cgroup.dir.container` is not implemented. See the added test-case.
Signed-off-by: Ruben Jenster <r.jenster@drachenfels.de>
=> lxccontainer: fix lxc_config_item_is_supported

doc/lxc.container.conf.sgml.in, src/lxc/cgroups/cgfsng.c, src/lxc/conf.h, src/lxc/confile.c
On termination lxc may fail to remove either `lxc.cgroup.dir` or `lxc.cgroup.dir.monitor`,
because the monitor process may still be a member of either of these cgroups.
The pivot cgroup should not be a member (subpath) of any other container cgroup (dir)
because only empty cgroups can be removed.
Although I've used the newly introduced option `lxc.cgroup.dir.monitor` as prefix this option should work fine
with with either `lxc.cgroup.dir`  or `lxc.cgroup.dir.monitor`.
I've discovered this when working on `crio-lxc` - I found the following warning in the log.
```
Oct 07 14:27:20 k8s-cluster2-controller kubelet[3725]: W1007 14:27:20.906211    3725 pod_container_manager_linux.go:200] failed to delete cgroup paths for [kubepods besteffort pod2159cf63-66b6-4fa5-88b1-23489e084727] : unable to …
```
=> cgroups: Introduce lxc.cgroup.dir.monitor.pivot - fixes cgroup removal on termination

src/lxc/attach.c, src/lxc/attach_options.h, src/lxc/tools/lxc_attach.c
Enable lxc-attach to set the SELinux context that the user will end up
in when attaching to a container (This can be used to overwrite the
context set in the config file). If the option is not used, behavior
will be as before
=> lxc-attach: Enable setting the SELinux context

src/lxc/conf.c
I missed a free in my previous seccomp fixes.
=> Add missing free for monitor_pivot_dir.

src/lxc/cgroups/cgfsng.c
These errors do not affect the normal operation. In order to avoid user misunderstanding,  adjust the level  to warning instead of error.
Signed-off-by: lifeng68 <lifeng68@huawei.com>
=> cgfsng: adjust log level to warn instead of error

src/lxc/file_utils.c
We accidently used the "bytes_to_write" variable after we've written all the
bytes at which point it is guaranteed to be 0. Let's use the "bytes_read"
variable instead.
=> file_utils: fix config file parsing

src/lxc/commands_utils.c, src/lxc/state.c
Closes: #3570
Fixes: 7792a5b60f79 ("commands: add additional check to lxc_cmd_sock_get_state()")
=> commands_utils: fix lxc-wait

src/lxc/network.c
We have a case where we have a nested container with LXC_NET_NONE run
inside a container that's *also* got no network namespace (run by
lxc-usernsexec).
The "am I root" check in this function then does not suffice, since the
euid of the task is 0 but it does not have privilege over its network
namespace, and thus cannot do any of the restore operations:
lxc foo 20201201232059.271 TRACE    network - network.c:lxc_restore_phys_nics_to_netns:3299 - Moving physical network devices back to parent network namespace
lxc foo 20201201232059.271 ERROR    network - network.c:lxc_restore_phys_nics_to_netns:3307 - Operation not permitted - Failed to enter network namespace
lxc foo 20201201232059.271 ERROR    start - start.c:__lxc_start:2045 - Failed to move physical network devices back to parent …
=> network: fix LXC_NET_NONE cleanup

src/lxc/start.c
If the container unexpectedly exists we may need to restore physical
interfaces back into the main namespace in a tidy way.
Signed-off-by: Blair Steven <blair.steven@alliedtelesis.co.nz>
=> Restore interfaces to the correct namespace on error

src/lxc/conf.c
=> conf: fix block-device based rootfs mounting

README.md
Changed Version from 2.. to 4.. because the current latest release is 4.0.5
Please note that I can be wrong to I am new here first time reading the README.md
Signed-off-by: sirh3e <marvin.huber@bluewin.ch>
=> Changed Version from 2.*.* to 4.*.*

config/init/common/lxc-net.in
lxc's dnsmasq will try to read system's dnsmasq if `--conf-file` is not
specified. This is likely not desirable, as lxc's dnsmasq should be
self-contained.
On my system the conflicting options are `--bind-interfaces` and
`--bind-dynamic`, since the same host is doing other DNS-y things
unrelated to lxc.
This is an incompatible change, since lxc's dnsmasq will stop honoring
system's `/etc/dnsmasq.conf`, and some systems may be relying on it.
Given that, I believe it should not depend on it by default, since
dnsmasq is lxc's implementation detail. However, if the user desires,
the old behavior could be brought back by setting
`LXC_DHCP_CONFILE=/etc/dnsmasq.conf` in `/etc/default/lxc-net`.
Signed-off-by: Motiejus Jakštys <motiejus@jakstys.lt>
=> make lxc-net's dnsmasq hermetic

configure.ac, src/lxc/commands.c
`configure` checks for libseccomp features even if `--disable-seccomp` is given.  Then `command.c` will use these features to conditionally compile support for seccomp features, without checking if seccomp should be enabled.  `lxcseccomp.h`, OTOH, does the proper checking, and disables seccomp's features.  This results in build failure when `--disable-seccomp` is given, and `configure` finds `libseccomp` headers and library:
```
commands.c: In function 'lxc_cmd_get_seccomp_notify_fd_callback':
commands.c:532:46: error: 'struct lxc_seccomp' has no member named 'notifier'
if (!handler->conf || handler->conf->seccomp.notifier.notify_fd < 0)
^
commands.c:534:62: error: 'struct lxc_seccomp' has no member named 'notifier'
ret = lxc_abstract_unix_send_fds(fd, …
```
=> Fix compilation without seccomp when libseccomp is installed

src/lxc/conf.c, src/tests/Makefile.am, src/tests/lxc-test-procsys
Some container images don't have it, and strange things happen when they don't. Since these directories are required for normal functioning, it's wise to pre-create them while starting the container.
Signed-off-by: Motiejus Jakštys <motiejus@jakstys.lt>
=> mkdir -p /proc /sys on container startup

src/lxc/conf.c
Fixes: 493e00b ("mkdir -p /proc /sys on container startup")
Cc: stable-4.0
=> conf: proc and sys mountpoint creation fixes

src/lxc/cgroups/cgfsng.c
We're already ensuring before that conf isn't NULL.
=> cgroups: remove pointless NULL checks

src/lxc/lsm/apparmor.c, src/lxc/macro.h
It turns out that since Linux 5.1 there are now per-LSM subdirectories
for major LSMs, [which users are recommended to use over the "legacy"
top-level /proc/$pid/attr/... files][1]:
> Process attributes associated with “major” security modules should be
> accessed and maintained using the special files in /proc/.../attr. A
> security module may maintain a module specific subdirectory there,
> named after the module. /proc/.../attr/smack is provided by the Smack
> security module and contains all its special files. The files directly
> in /proc/.../attr remain as legacy interfaces for modules that provide
> subdirectories.
[AppArmor has had such a directory since Linux 5.8][2], and it turns out
that with certain CONFIG_LSM configurations you can end up with AppArmor
files not being …
=> apparmor: prefer /proc/.../attr/apparmor/current over legacy interface

src/lxc/file_utils.c, src/lxc/lsm/apparmor.c
Fixes: Coverity 1473189
Fixes: Coverity 1473190
Fixes: 47f4914 ("apparmor: prefer /proc/.../attr/apparmor/current over legacy interface")
=> lsm: fixes

src/lxc/cgroups/cgroup.c
This is a spiritual revert of 5c7b81439cecfbd885b3c10f9edfefdc1ac7c45b (it
doesn't add back any of the logs, just removes the bad check).
Not having writable hierarchies is not actually a problem:
1. if I remove this check, things work just fine; below is a successful log
of a run where there are no writable hierarchies
2. I believe the test for writability is slightly incorrect.
unified_hierarchy_delegated() and legacy_hierarchy_delegated() both test
the writability of $current_hierarchy/cgroup.procs. On my system, I
have:
~ cat /proc/self/cgroup
12:hugetlb:/
11:pids:/user.slice/user-1000.slice/session-c38.scope
10:memory:/user.slice/user-1000.slice/session-c38.scope
9:freezer:/user/tycho/0
8:cpuset:/
7:net_cls,net_prio:/
6:blkio:/user.slice
5:devices:/user.slice
4:rdma:/ …
=> cgroup: do not fail if there are no writable heirarchies

src/lxc/attach_options.h
This makes it easier to detect support for various features at compile
time.
Enables: lxc/go-lxc#149
Fixes: https://launchpadlibrarian.net/526273274/buildlog_snap_ubuntu_bionic_i386_lxd-4.0-edge_BUILDING.txt.gz
=> attach_options: header improvements

configure.ac, src/lxc/macro.h
=> macro: define __aligned_u64 to handle kernels without such support

src/lxc/rexec.c
Otherwise we'll fail to attach to containers later on.
Fixes: https://discuss.linuxcontainers.org/t/error-failed-to-retrieve-pid-of-executing-child-process
=> rexec: don't close stderr

src/include/strchrnul.c
Fixes: https://jenkins.linuxcontainers.org/view/LXC/job/lxc-build-android/7949/console
=> strchrnul: ignore increased required alignment warning

src/lxc/confile_utils.c
lxc_free_netdev() will already free the list element.
Fixes: https://github.com/google/oss-fuzz/pull/5498
=> confile_utils: don't free netdev twice

src/lxc/conf.c
It was triggered by passing "lxc.selinux.context.keyring=xroot" to the
fuzz target introduced in https://github.com/google/oss-fuzz/pull/5498
```
=================================================================
==22==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 6 byte(s) in 1 object(s) allocated from:
#0 0x538ca4 in __strdup /src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:468:3
#1 0x5c40e8 in set_config_string_item /src/lxc/src/lxc/confile_utils.c:635:14
#2 0x44394e in set_config_selinux_context_keyring /src/lxc/src/lxc/confile.c:1596:9
#3 0x5af955 in parse_line /src/lxc/src/lxc/confile.c:2953:9
#4 0x4475cd in lxc_file_for_each_line_mmap /src/lxc/src/lxc/parse.c:125:9
#5 0x5af24f in lxc_config_read /src/lxc/src/lxc/confile.c:3024:9
#6 0x580b04 in …
```
=> conf: fix a memory leak

.github/workflows/cifuzz.yml
Now that lxc has been integrated into OSS-Fuzz it should be
possible to start using https://google.github.io/oss-fuzz/getting-started/continuous-integration/
(mostly to make sure that the project is buildable there).
It should help to keep the integration in more or less good shape.
=> ci: turn on CIFuzz

src/lxc/confile.c
We never call these helper without an initialized config afaict but
since we're now exposing these two functions to oss-fuzz directly in a
way we never do to users so let's be stricter about it.
Inspired-by: #3733
=> confile: be stricter in config helpers

src/tests/fuzz-lxc-config-read.c, src/tests/oss-fuzz.sh
With this patch applied the fuzz target can be built (with ASan)
and run with
```
./src/tests/oss-fuzz.sh
./out/fuzz-lxc-config-read doc/examples/
```
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32475 can be
reproduced by running
```
$ echo "lxc.console.buffer.size=d" >oss-fuzz-32475
$ ./out/fuzz-lxc-config-read ./oss-fuzz-32475
INFO: Seed: 1044753468
INFO: Loaded 1 modules   (18770 inline 8-bit counters): 18770 [0x883cc0, 0x888612),
INFO: Loaded 1 PC tables (18770 PCs): 18770 [0x888618,0x8d1b38),
./out/fuzz-lxc-config-read: Running 1 inputs 1 time(s) each.
Running: oss-fuzz-32475
=================================================================
==2052097==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffcca063e7f at pc 0x000000659e0d bp 0x7ffcca063e30 sp …
```
=> oss-fuzz: make it possible to build the fuzzer without docker

src/lxc/network.c, src/lxc/network.h
Reviewed-by: Blair Steven <blair.steven@alliedtelesis.co.nz>
Signed-off-by: Sam Boyles <sam.boyles@alliedtelesis.co.nz>
=> network: handle name collisions when returning interfaces to host

src/lxc/confile_utils.c
Reported-by: Evgeny Vereshchagin <evvers@ya.ru>
Link: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32484
=> confile_utils: free list during lxc_remove_nic_by_idx()

src/lxc/confile_utils.c
This was triggered by the following chain of conversions:
```
lxc_safe_uint("020000000020") -> 2147483664 (uint)
sig_num(2147483664 (uint)) -> -2147483632 (int)
64 - -2147483632 cannot be represented in type 'int'
```
Closes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32596
@brauner could you take a look?
=> confile_utils: fix a signed integer overflow

.github/workflows/cifuzz.yml, src/tests/oss-fuzz.sh
* cifuzz: turn on UBsan
* oss-fuzz.sh: take SANITIZER into account
to make it possible to build the fuzzer with UBSan and MSan locally
```
$ SANITIZER=undefined ./src/tests/oss-fuzz.sh
$ printf 'lxc.signal.stop=sigrtmax-020000000020' >oss-fuzz-32596
$ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1 ./out/fuzz-lxc-config-read oss-fuzz-32596
INFO: Seed: 595864277
INFO: Loaded 1 modules   (61553 inline 8-bit counters): 61553 [0x80a1b0, 0x819221),
INFO: Loaded 1 PC tables (61553 PCs): 61553 [0x819228,0x909938),
./out/fuzz-lxc-config-read: Running 1 inputs 1 time(s) each.
Running: oss-fuzz-32596
confile_utils.c:1051:20: runtime error: signed integer overflow: 64 - -2147483632 cannot be represented in type 'int'
#0 0x51799a in rt_sig_num …
```
=> oss-fuzz/cifuzz: a couple of follow-up commits

.github/workflows/cifuzz.yml, src/lxc/string_utils.c
MSan doesn't instrument stpncpy (https://github.com/google/sanitizers/issues/926),
which causes the fuzzer to fail with:
```
$ cat ../minimized-from-740f56329efc60eab59b8194132b712a873e88a3
lxc.console.size=123
$ ./out/fuzz-lxc-config-read ../minimized-from-740f56329efc60eab59b8194132b712a873e88a3
INFO: Seed: 3561494591
INFO: Loaded 1 modules   (18795 inline 8-bit counters): 18795 [0x866b98, 0x86b503),
INFO: Loaded 1 PC tables (18795 PCs): 18795 [0x86b508,0x8b4bb8),
./out/fuzz-lxc-config-read: Running 1 inputs 1 time(s) each.
Running: ../minimized-from-740f56329efc60eab59b8194132b712a873e88a3
==850885==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x6b3e7f in parse_byte_size_string /home/vagrant/lxc/src/lxc/string_utils.c:912:6
#1 0x550991 in set_config_console_size …
```
=> CIFuzz: turn on MSan

configure.ac, src/lxc/compiler.h, src/lxc/conf.c, src/lxc/conf.h, src/lxc/initutils.c
=> compiler: fix thread_local detection

doc/lxc.container.conf.sgml.in
=> doc: Documented that net type field must come before other options on the net device

README.md, configure.ac, src/lxc/Makefile.am
=> autotools: remove --enable-{asan,ubsan} in favor of --enable-sanitizers

src/lxc/confile.c
instead move networking keys into a subtable. This avoids even just the
remote danger of recursion and also speeds up config parsing.
=> confile: don't jump into the global table twice

src/tests/oss-fuzz.sh
It's just a follow-up to 0abcc213e2291d71 (where the "lxc.net" keys
were moved from config_jump_table to config_jump_table_net)
=> oss-fuzz.sh: put the "lxc.net" keys to the seed corpus as well

src/tests/fuzz-lxc-config-read.c
It should help the fuzzer to avoid running into timeouts
like https://oss-fuzz.com/testcase-detail/5132999948632064.
Hopefully, once this is merged OSS-Fuzz will report only
infinite loops as timeouts.
=> oss-fuzz: reject giant configs early

src/lxc/conf.c, src/lxc/log.h
Fixes: #3770
Suggested-by: Ruben Jenster <r.jenster@drachenfels.de>
=> conf: fix setups where /dev is outside of LXC's control

templates/lxc-busybox.in, templates/lxc-download.in, templates/lxc-local.in, templates/lxc-oci.in
if $PATH already contains a path with a space the append of the
default directories in all template scripts fails with an error
like the following:
/usr/share/lxc/templates/lxc-download: 69: export: (x86)/NVIDIA: bad
variable name
=> templates/*.in: fixed PATH handling with spaces

.github/workflows/cifuzz.yml, src/lxc/confile.c, src/tests/fuzz-lxc-define-load.c, src/tests/oss-fuzz.sh
=> oss-fuzz: fuzz lxc_config_define_add and lxc_config_define_load

src/tests/cgpath.c
```
$ sudo ./src/tests/lxc-test-cgpath
Container creation tests...Passed
Container creation with LXCPATH tests...Passed
=================================================================
==57206==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 296 byte(s) in 1 object(s) allocated from:
#0 0x7fef22c27dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
#1 0x557c6e3ce3d9 in cgroup_ops_init cgroups/cgfsng.c:3347
#2 0x557c6e3d6516 in cgroup_init cgroups/cgroup.c:33
#3 0x557c6e3788e2 in test_running_container /home/vagrant/lxc/src/tests/cgpath.c:102
#4 0x557c6e379c69 in test_container /home/vagrant/lxc/src/tests/cgpath.c:197
#5 0x557c6e379e37 in main /home/vagrant/lxc/src/tests/cgpath.c:233
#6 0x7fef2136c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Direct …
```
=> tests: fix a memory leak in cgpath

src/tests/lxcpath.c
```
$ sudo ./src/tests/lxc-test-lxcpath
=================================================================
==95911==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 39 byte(s) in 1 object(s) allocated from:
#0 0x7effafc8d3dd in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
#1 0x7effaf5a2de6 in lxcapi_config_file_name /home/vagrant/lxc/src/lxc/lxccontainer.c:3190
#2 0x562961680c30 in main /home/vagrant/lxc/src/tests/lxcpath.c:49
#3 0x7effae5150b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Direct leak of 21 byte(s) in 1 object(s) allocated from:
#0 0x7effafc8d3dd in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
#1 0x7effaf5a2de6 in lxcapi_config_file_name /home/vagrant/lxc/src/lxc/lxccontainer.c:3190
#2 0x56296168115e in main …
```
=> tests: fix a memory leak in lxcpath

src/tests/lxc-test-checkpoint-restore
criu can't seem to dump systemd-logind used in Ubuntu due to what appears to be
checkpoint-restore/criu#1430.
Let's switch to busybox where all the processes hopefully can be dumped.
Closes https://github.com/lxc/lxc/issues/3792
=> tests: switch to the "busybox" template in lxc-test-checkpoint-restore

src/lxc/lsm/apparmor.c
It's extracted from https://github.com/lxc/lxc/pull/3787
```
==70349==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000009fb at pc 0x000000433b70 bp 0x7ffcde087810 sp 0x7ffcde086fd0
READ of size 12 at 0x6020000009fb thread T0
#0 0x433b6f in strcspn (/usr/bin/lxc-execute+0x433b6f)
#1 0x7f720413a5cb in apparmor_process_label_get /home/runner/work/lxc/lxc/src/lxc/lsm/apparmor.c:449:8
#2 0x7f720413bc2a in apparmor_prepare /home/runner/work/lxc/lxc/src/lxc/lsm/apparmor.c:1104:13
#3 0x7f720409b6e9 in lxc_init /home/runner/work/lxc/lxc/src/lxc/start.c:848:8
#4 0x7f72040a395a in __lxc_start /home/runner/work/lxc/lxc/src/lxc/start.c:2009:8
#5 0x7f7203fc7186 in lxc_execute /home/runner/work/lxc/lxc/src/lxc/execute.c:99:9
#6 0x7f7204000e44 in do_lxcapi_start …
```
=> apparmor: turn bytes into null-terminated strings before calling strcspn

.github/workflows/sanitizers.sh, config/attributes.m4, configure.ac, src/lxc/Makefile.am
=> ci: make use of --enable-sanitizers instead of CFLAGS

configure.ac, src/lxc/attach.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/lsm/apparmor.c, src/lxc/mount_utils.c, src/lxc/mount_utils.h, src/lxc/start.c, src/lxc/storage/dir.c, src/lxc/storage/storage.c, src/lxc/storage/storage.h, src/lxc/syscall_numbers.h, src/lxc/syscall_wrappers.h
```
lxc.rootfs.options = idmap=/path/to/user/ns/to/idmap/to
```
=> Initial support for idmapped mounts

src/lxc/tools/include/getsubopt.c
=> getsubopt: use correct include

src/lxc/seccomp.c
It's a follow-up to 84cf6d259b24e4ad48e
Closes https://github.com/lxc/lxc/issues/3806
=> seccomp: init and destroy notifier.cookie

src/lxc/storage/dir.c
We need to be able to lookup symlinks and allow xdev.
=> dir: fix rootfs mounting

src/lxc/storage/storage.c
=> storage: fix dup_cloexec() call

src/lxc/cgroups/cgfsng.c
When we attach to an old server the server can return ENOSYS instead of
ENOCGROUP2 which causes LXC to abort the attach unnecessary. Fix this!
=> cgroups: fix fallback attach codepath

configure.ac, src/lxc/log.c
Apparently /proc/self/comm can't be used (reliably) on OSS-Fuzz to figure out
whether the code is run inside the fuzz targets, which causes the
fuzz targets to fill the filesystem with log files.
Related: https://github.com/google/oss-fuzz/issues/5509
Should address https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33835
=> oss-fuzz: always turn off logging on OSS-Fuzz

src/lxc/cmd/lxc_monitord.c
The tool is effectively unused with current master so removing the log
should be ok by now. Let's remove the log to avoid issues such as #3747.
Fixes #3747
=> lxc_monitord: remove monitord log

.github/workflows/sanitizers.sh
We don't build any packages there so it seems we don't need
those packages any more. Apart from that, it should make the
script work on Ubuntu Hirsute where dh-systemd was merged into
debhelper and is no longer available.
=> github: remove the dh-* packages

src/lxc/string_utils.c
by getting rid of stpncpy
Tested with gcc (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1)
Closes https://github.com/lxc/lxc/issues/3752
=> string_utils: get around GCC-11 false positives

src/lxc/conf.c
LXC is being very clever and sometimes maps the caller's uid into the
child userns. This means that the caller can technically write fscaps
that are valid in the ancestor userns (which can be a security issue in
some scenarios) so newer kernels require CAP_SETFCAP to do this. Until
newuidmap/newgidmap are updated to account for this simply write the
mapping directly in this case.
Cc: stable-4.0
=> conf: handle kernels with CAP_SETFCAP

doc/lxc.container.conf.sgml.in
=> doc: document new idmap= option for lxc.rootfs.options

src/lxc/conf.c
Hello! This is definitely a drive-by contribution, only tested through to "Works For Me" status, but it fixes a predicament for me. The last couple versions of LXC failed to start my containers, so I pinned to 4.0.6, but was bitten by the bug discussed at https://github.com/lxc/lxc/issues/3828 after upgrading the kernel to 5.12.1, so couldn't start any unprivileged containers that had ZFS roots.
It seems that the recently-rewritten code for rootfs pinning in conf.c (see https://github.com/lxc/lxc/commit/79ff643d24593a1b77bb39233219d55d20efa4bc) is not considering the case of ZFS roots. The old version reads like it would return -2, i.e., "nothing needed to be pinned", for ZFS roots since the paths would fail to canonicalize. In the new version, containers with ZFS roots fail to start with …
=> Skip rootfs pinning for ZFS roots.

.gitignore, src/lxc/confile.c, src/tests/Makefile.am, src/tests/arch_parse.c, src/tests/lxctest.h
Apparenty we dropped this when we cleaned up architecture handling.
Fixes: #3832
=> confile: re-add aarch64 architecture

src/tests/Makefile.am, src/tests/arch_parse.c
Fixes: https://jenkins.linuxcontainers.org/job/lxc-build-tarballs/2762/console
=> tests: fix lxc-test-arch-parse for make dist

src/tests/Makefile.am, src/tests/fuzz-lxc-cgroup-init.c
=> oss-fuzz: add basic cgroup_init()/cgroup_exit() fuzzing

src/lxc/start.c
At the prior location we we're placed between sending and receiving
networking information over the data socket causing the startup to fail.
=> start: move idmapped mount setup later

src/lxc/conf.c
Anbox mounts a squashfs image and uses it as the lxc container root. The squashfs image is mounted read-only, hence the rootfs pinning code in newer versions of lxc breaks anbox.
This fixes the issue.
Reference: bug report of anbox: https://github.com/anbox/anbox/issues/1801
=> Skip rootfs pinning for read-only file system.

src/lxc/conf.c
=> conf: fix mount option parsing

config/init/common/lxc-net.in, lxc.spec.in
Closes #3093
Closes #3602
Add support for nftables firewall rules if `nft` command line
interface is available in the system
I have tested this in a local machine (without ipv6) with nftables and seems to be working perfectly fine. 
Note that I have removed the `CHECKSUM` rule in nft, as the automatic rule translation creates something completely meaningless: `oifname "lxcbr0" meta l4proto udp udp dport 68 counter packets 0 bytes 0 # CHECKSUM fill`, that in addition never sees any packages.
=> Update lxc-net to support nftables

doc/api-extensions.md, src/lxc/api_extensions.h
This indicates that LXC supports idmapping the rootfs and
idmapped lxc.mount.entry entries.
Link: https://github.com/lxc/lxd/issues/8870
=> api_extensions: introduce idmapped_mounts_v2 api extension

src/lxc/string_utils.c
The function lxc_string_split_quoted and lxc_string_split_and_trim use
realloc to reduce the memory. But the result may be NULL, then the
returned memory will be uninitialized
=> string utils: Make sure don't return uninitialized memory.

src/lxc/lxccontainer.h, src/lxc/start.c
The LISTEN_FDS environment variable defines the number of
file descriptors that should be inherited by the container,
in addition to stdio.
The LISTEN_FDS environment variable is defined in the OCI spec
and used to support socket activation.
Refs #3845
Signed-off-by: Ruben Jenster <r.jenster@drachenfels.de>
=> Add support for LISTEN_FDS environment variable.

src/lxc/cgroups/cgroup.h
=> cgroups: verify that hierarchies are non-empty

src/lxc/lxccontainer.c
Fix for #3876.
When an item is added to an array, then the array is realloc()ed (to size+1),
and the item is copied (strdup()) to the array.
Thus, when an item is removed from an array, memory allocated for that item
should be freed, successive items should be left-shifted and the array
realloc()ed again (size-1).
Additional changes:
- If strdup() fails in add_to_array(), then an array should be
realloc()ed again to original size.
- Initialize an array in list_all_containers().
Valgrind summary on the patched version:
```
==476062==
==476062== HEAP SUMMARY:
==476062==     in use at exit: 0 bytes in 0 blocks
==476062==   total heap usage: 13 allocs, 13 frees, 73,880 bytes allocated
==476062==
==476062== All heap blocks were freed -- no leaks are possible
==476062==
==476062== For lists of …
```
=> remove_from_array() causes a crash

config/templates/userns.conf.in, src/lxc/confile.c
With `common.conf` including `common.conf.d/` I find it would make sense to have the "common" `userns.conf` include `userns.conf.d/`.
The only downside is that it some people might already be doing this and possibly end up double-including those files...
=> RFC: conf: userns.conf: include userns.conf.d

src/lxc/file_utils.c
Link: https://discuss.linuxcontainers.org/t/error-failed-to-retrieve-pid-of-executing-child-process
=> file_utils: surface ENOENT when falling back to openat()

src/lxc/cmd/lxc_init.c, src/lxc/initutils.c
Otherwise we might end up with implicit function declaration warnings.
Link: https://jenkins.linuxcontainers.org/job/lxc-build-android/8915/console
=> initutils: include pthread.h

src/lxc/af_unix.c, src/lxc/terminal.c
This is not a fatal error and the fallback codepath is equally safe.
When we use TIOCGPTPEER we're using a stashed fd to the container's
devpts mount's ptmx device and allocating a new fd non-path based
through this ioctl. If this ioctl can't be used we're falling back to
allocating a pts device from the host's devpts mount's ptmx device which
is path-based but is not under control of the container and so that's
safe. The difference is just that the first method gets you a nice
native terminal with all the pleasantries of having tty and friends
working whereas the latter method does not.
Fixes: #3625
=> terminal: log TIOCGPTPEER failure less alarmingly

src/lxc/cgroups/cgroup2_devices.c
bpf_devices_cgroup_supported() tries to load a simple BPF program to test
if BPF works. This is problematic because the function used to load the
program - bpf_program_load_kernel() - emits an error to the log if BPF is
not enabled in the kernel although device controller is not requested in
the configuration.
To detect if BPF is supported we need to check if the BPF syscall is
available. We can do it by passing a NULL pointer instead of the syscall
argument as the kernel returns either ENOSYS, when the sysall is not
implemented or EFAULT, when it is implemented.
=> bpf: simplify detection if BPF is supported

src/lxc/string_utils.h
Link: https://launchpadlibrarian.net/550723147/buildlog_snap_ubuntu_focal_ppc64el_lxd-latest-edge_BUILDING.txt.gz
=> string_utils: cast __s64 to long long signed int

doc/lxc.container.conf.sgml.in
I found this ability when working on https://github.com/lxc/lxd/pull/9103.
But I couldn't find any mention of it in the docs, so am adding it now.
=> doc: Adds mention of ability to specify manual IPv4 broadcast address

configure.ac, src/lxc/Makefile.am, src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/lxc_monitord.c, src/lxc/commands.c, src/lxc/commands.h, src/lxc/conf.c, src/lxc/lxcseccomp.h, src/lxc/macro.h, src/lxc/mainloop.c, src/lxc/mainloop.h, src/lxc/seccomp.c, src/lxc/start.c, src/lxc/syscall_wrappers.h, src/lxc/terminal.c, src/lxc/terminal.h, src/lxc/tools/lxc_top.c, src/tests/Makefile.am
Users can choose to compile liblxc with io_uring support. This will
cause LXC to use io_uring instead of epoll.
We're using both, io_uring's one-shot and multi-shot poll mode depending
on the type of handler.
=> mainloop: io_uring support

src/lxc/mainloop.c
I get the following warning (which then fails the build because of
-Werror):
In file included from mainloop.c:11:
/usr/include/sys/poll.h:1:2: error: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Werror=cpp]
1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
|  ^~~~~~~
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
=> mainloop: s,sys/poll,poll

src/lxc/mainloop.c, src/lxc/memory_utils.h
They are sometimes used to just clean something up automatically at end
of scope but the variables themselves might not be actually used.
=> memory_utils: make cleanup handler as unused

config/bash/lxc.in, doc/ja/lxc-attach.sgml.in, doc/ja/lxc-autostart.sgml.in, doc/ja/lxc-execute.sgml.in, doc/ko/lxc-attach.sgml.in, doc/ko/lxc-autostart.sgml.in, doc/ko/lxc-execute.sgml.in, doc/lxc-attach.sgml.in, doc/lxc-autostart.sgml.in, doc/lxc-execute.sgml.in, src/lxc/Makefile.am
Hey,
Made a lot of changes on the bash completion file to try to enhance the overall experience of using the command line tools. Although not a really high priority issue (since most should use `lxd` or similar), it would feel good if we could get a better completion.
I also realized that most distros have to create symlinks to use the bash completion file. The current out-of-the-box bash(>=4.1)  completion expects the command to have a completion that matches its name, i.e. if you try `lxc-create -B [TAB]`, it searches for `/usr/share/bash-completion/completions/lxc-create`, but this file does not exist. 
I tried my hand on a local solution, but if you feel that this is not time or even an issue, I will drop the commit and move forward with the rest. 
Most distros have these symlinks in …
=> Improve bash completion experience.

src/lxc/seccomp.c
```
[2021-08-18 05:48:26] [build-stdout] mv -f $depbase.Tpo $depbase.Po
[2021-08-18 05:48:26] [build-stderr] seccomp.c: In function ‘seccomp_notify_cleanup_handler’:
[2021-08-18 05:48:26] [build-stderr] seccomp.c:1367:25: error: ‘struct lxc_seccomp’ has no member named ‘notifier’
[2021-08-18 05:48:26] [build-stderr]  1367 |  if (fd == conf->seccomp.notifier.notify_fd)
[2021-08-18 05:48:26] [build-stderr]       |                         ^
[2021-08-18 05:48:26] [build-stderr] In file included from af_unix.h:12,
[2021-08-18 05:48:26] [build-stderr]                  from seccomp.c:14:
[2021-08-18 05:48:26] [build-stderr] seccomp.c:1368:29: error: ‘struct lxc_seccomp’ has no member named ‘notifier’
[2021-08-18 05:48:26] [build-stderr]  1368 |   fd = move_fd(conf->seccomp.notifier.notify_fd); …
```
=> seccomp: fix complication when !HAVE_DECL_SECCOMP_NOTIFY_FD

src/lxc/confile.c
Make lxc fail if seccomp.profile is specified but lxc is compiled without seccomp support. Currently, seccomp.profile is silently ignored if is specified in such a scenario. This could lead to the false impression that the seccomp filter is applied while it actually isn't.
With this patch make the behavior of lxc.seccomp.profile compliant to the other lxc.seccomp,* options and will thus prevent a situation as described above.
Signed-off-by: Maximilian Blenk <Maximilian.Blenk@bmw.de>
=> config: enable seccomp profile only when compiled with libseccomp

config/bash/lxc.in
Hi,
this is a follow-up to #3899. It includes some ideas discussed there, as well as a couple of fixes for stuff my tests did not catch at the time.
However, I would like to have feedback about some changes I did, mostly on design:
1. **Names with spaces**: when you create a container like `lxc-create -t download -n "arch linux"`, you can autocomplete the name as `'arch linux'`, `"arch linux"`or `arch\ linux`. I choose the one with backslash because it felt natural to me. However, you may be able to tell this is a bad idea if there is an edge case that I am unaware of.
2. **cgroup completion**: I am using the entry `lxc.payload.${name}`, where `name` is the container name. Not sure if this is correct. I try first the `user.slice` entry and the payload is my fallback for `cgroups_v2`. I …
=> Improve bash completion - part 2.

src/lxc/lxccontainer.h
=> Don't include internal headers in external library headers

doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/attach.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/initutils.h, src/lxc/start.c, src/lxc/syscall_wrappers.h, src/tests/parse_config_file.c
Core scheduling defines if the container payload is marked as being
schedulable on the same core. Doing so will cause the kernel scheduler
to ensure that tasks that are not in the same group never run
simultaneously on a core. This can serve as an extra security measure to
prevent the container payload from using cross hyper thread attacks.
The only allowed values are 0 and 1. Set this to 1 to create a core
scheduling domain for the container or 0 to not create one. If not set
explicitly no core scheduling domain will be created for the container.
=> lxc: core scheduling support

src/lxc/attach.c, src/lxc/macro.h, src/lxc/start.c
Link: https://launchpadlibrarian.net/561086365/buildlog_ubuntu-focal-ppc64el.lxc_1%3A4.0.10+master~20210930-1812-0ubuntu1~focal_BUILDING.txt.gz
=> tree-wide: cast to core scheduling cookie to llu

src/lxc/start.c
=> start: make failure to apply core scheduling fatal

configure.ac, src/lxc/Makefile.am
When installing LXC with the default options, a single non-symlink liblxc.so* (e.g. liblxc.so.1.7.0) file is created:
```
$ ./autogen.sh && ./configure && make && \
rm -rf "$HOME/lxci" && make DESTDIR="$HOME/lxci" install && \
stat -c%N "$HOME/lxci/usr/local/lib/liblxc.so"*
[...]
'/home/someone/lxci/usr/local/lib/liblxc.so' -> 'liblxc.so.1'
'/home/someone/lxci/usr/local/lib/liblxc.so.1' -> 'liblxc.so.1.7.0'
'/home/someone/lxci/usr/local/lib/liblxc.so.1.7.0'
```
However, when automake>=1.16.5, and the `--enable-pam` option is used, two non-symlink liblxc.so* (e.g. liblxc.so.1.0.0 and liblxc.so.1.7.0) are erroneously created:
```
$ ./autogen.sh && ./configure --enable-pam && make && \
rm -rf "$HOME/lxci" && make DESTDIR="$HOME/lxci" install && \
stat -c%N …
```
=> autotools: Avoid multiple liblxc.so with --enable-pam

src/lxc/initutils.c
This reverts commit d65e5e492f740bbb50e3005f97420c3ddae3d595.
With vfork the child process modifies the parent's memory,
so the calls to `signal`, `fprintf` and regular `exit` may
be dangerous and might cause conflicting states in the
parent.
---
While I haven't actually run into issues, from what the manpage says I think it's better to stick with `fork` for this one.
(Though from the code I think we would mostly see issues in the error cases, if any, not sure about the state of the signal handlers and whether the functions we're calling here actually cause any changes under the hood that would affect the parent process.)
=> Revert "initutils: use vfork() in lxc_container_init()"

src/lxc/cgroups/cgfsng.c
I get:
In file included from cgroups/cgfsng.c:42:
In function 'cpuset1_cpus_initialize',
inlined from 'cpuset1_initialize' at cgroups/cgfsng.c:658:7,
inlined from '__cgroup_tree_create.constprop' at cgroups/cgfsng.c:723:26:
./log.h:376:9: error: '%s' directive argument is null [-Werror=format-overflow=]
376 |         LXC_ERROR(&locinfo, format, ##__VA_ARGS__);                     \
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./log.h:457:17: note: in expansion of macro 'ERROR'
457 |                 ERROR("%s - " format, ptr, ##__VA_ARGS__); \
|                 ^~~~~
./log.h:491:17: note: in expansion of macro 'SYSERROR'
491 |                 SYSERROR(format, ##__VA_ARGS__);              \
|                 ^~~~~~~~
cgroups/cgfsng.c:585:24: note: in expansion of macro …
=> cgroups: fix compiler warning

src/lxc/lxccontainer.c
If we're saving the config file to somewhere that's *not* the container
dir, we don't need to create the container dir. Let's not do this and
thus not require its parent to exist, which can be confusing, especially in
light of the sparse logging through these functions.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
=> api: ->save_config() doesn't need to create container dir

src/lxc/api_extensions.h, src/lxc/commands.c, src/lxc/confile.c, src/lxc/lxcseccomp.h
=> seccomp: only guard seccomp notify behind HAVE_DECL_SECCOMP_NOTIFY_FD

src/lxc/seccomp.c
Reported-by: Wolfgang Bumiller <w.bumiller@proxmox.com>
=> seccomp: close seccomp notifier fd in cleanup handler

src/lxc/cmd/lxc-checkconfig.in
CONFIG_NF_NAT_IPV4 was removed from the kernel 2019-03-03
Signed-off-by: Tim L <elatllat@gmail.com>
=> lxc-checkconfig.in: CONFIG_NF_NAT_IPV4

templates/lxc-download.in
GPG has been a major source of issues over the years with various
attacks on the key network as well as client side issues making it hard
to retrieve our keys.
Back when we introduced the image server, SSL certificates were still
expensive and annoying to setup, so not something we'd have expected
potential mirrors to setup for us. They were also issued for multiple
years, making a compromise of such a certificate quite problematic.
But things have changed since, we now have completely free, very easily
deployable SSL certificates everywhere with the majority of those being
shortlived and with good reporting of issued certificates.
With that, we can now deprecate the GPG validation, disable the fallback
to non-HTTPS download and rely on our indices being accurate because
they've been …
=> lxc-download: Rely on HTTPS only

.github/workflows/sanitizers.sh
=> github: stop installing gnupg now that it's unused

src/lxc/lxccontainer.c
=> lxccontainer: allow xdev when creating the container dir

config/init/systemd/lxc-net.service.in
When lxc is installed inside an lxc container, trying to bring up
lxc-net with the default parameters will conflict with the networking
setup for lxc on the host. This breaks all networking inside the
container where lxc is installed.
Signed-off-by: Antonio Terceiro <terceiro@debian.org>
=> lxc-net: don't start by default inside lxc

src/lxc/conf.c, src/lxc/terminal.c, src/lxc/terminal.h
=> ttys: ensure container_ttys= env variable is set correctly

src/lxc/cgroups/cgfsng.c
Recent kernels have seen various permission checking fixes when moving
processes into cgroups. So we're forced to modify how we attach to
containers.
Link: https://discuss.linuxcontainers.org/t/lxd-4-23-unable-to-start-nested-containers
=> cgroups: modify cgroup2 attach logic

src/lxc/cmd/lxc-checkconfig.in
Kernels can be built with `CONFIG_MODULES=n` which results in `is_probed()` telling the module isn't probed and `lsmod` spamming the following to stderr each time it's called:
```
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
```
Fix this by "stubbing" `is_probed()` when `/proc/modules` doesn't exist as it's always called after a `is_enabled()` anyway.
=> lxc-checkconfig: Only check probed modules if /proc/modules exists

src/lxc/utils.c
Call 'access' to examine whether 'dir' is already existed or not instead
of directly calling 'mkdir' on each dir name separated by slash '/' even though
'dir' is existed.
Signed-off-by: Leesoo Ahn <lsahn@ooseel.net>
=> utils: add fastpath routine on mkdir_p function

config/init/common/lxc-net.in
Failure executing dnsmasq happens if misc dir is not existed as the
following error messages.
localhost.localdomain systemd[1]: Starting LXC network bridge setup...
localhost.localdomain lxc-net[5754]: dnsmasq: cannot open or create lease file /usr/local/var/lib/misc/dnsmasq.lxcbr0.leases: No such file or directory
localhost.localdomain dnsmasq[5754]: cannot open or create lease file /usr/local/var/lib/misc/dnsmasq.lxcbr0.leases: No such file or directory
localhost.localdomain dnsmasq[5754]: FAILED to start up
localhost.localdomain lxc-net[5727]: Failed to setup lxc-net.
localhost.localdomain lxc-net[5727]: Failed to setup lxc-net.
localhost.localdomain systemd[1]: lxc-net.service: Main process exited, code=exited, status=1/FAILURE
localhost.localdomain systemd[1]: lxc-net.service: Failed …
=> lxc-net.in: fix failure executing dnsmasq

src/lxc/utils.c
My kernel is old enough not to have pidfds but I spawn containers regularly and don't want to see this err.
I need it in stable-4.0 actually. but master first.
=> lxc_can_use_pidfd: don't log error if pidfds not supported, trace

CODING_STYLE.md
Hi,
it seems to me that your example in the coding style markdown file is lacking the `fallthrough` statement it is intended to demonstrate.
I created this example based on the way you do it in `src/lxc/commands.c`. I don't know what exactly the markdown-example is supposed to do. I just assumed that you might want to treat ENOENT and ENOTDIR identically, for example.
In your code you use `__fallthrough`, whereas the markdown suggests `__fallthrough__`. Before pulling this, that should be made congruent, probably. I can not decide what version the document intents to instruct the programmer to do. Take my PR just a suggestion.
Cheers
=> CODING_STYLE: add forgotten fallthrough

.github/workflows/build.yml, .github/workflows/coverity.yml, .github/workflows/sanitizers.yml, .github/workflows/static-analysis.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src/lxc/conf.c
We appended container_tty= and then used setenv(container_tty, ...)
resulting int container_tty=container_tty=.
=> conf: fix append_ttyname()

src/lxc/confile.c
For /31 and /32 IPv4 addresses there is no direct broadcast address. Instead, as discussed with @tomponline for issue #4026, it should be set to 0.0.0.0.
=> fix for issue #4026: set broadcast to 0.0.0.0 for /31 and /32

meson.build
we use HAVE_STATVFS in the code but with meson the check got
lost causing mount_entry to fail to remount some things such
as a bind mount of /dev/fuse via
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file 0 0
which would cause the following log messages:
DEBUG    conf - ../src/lxc/conf.c:mount_entry:2416 - Remounting "/dev/fuse" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/fuse" to respect bind or remount options
ERROR    conf - ../src/lxc/conf.c:mount_entry:2459 - Operation not permitted - Failed to mount "/dev/fuse" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/fuse"
note that the `Flags for ... were ...` line is not showing
up there, which depends on HAVE_STATVFS
=> add check for statvfs

src/lxc/storage/overlay.c
This fixes a really subtle off-by-one error constructing overlay mount options if rootfs options are provided and modern overlayfs (i.e. requiring a workdir) is used. We need to allow for the extra "," required to separate the extra options when computing the length!
Without the fix container creation fails with a "Failed to create string" error in the debug log.
=> Fix errors constructing mount string when extra mount options supplied

src/lxc/caps.h
fuzz-lxc-cgroup-init currently fails for me with the input
```
lxc.cap.keep=0
```
with this report:
```
==640655==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x833c77 in parse_cap /src/lxc/san_build/../src/lxc/conf.c:3161:6
#1 0xaa5fd6 in add_cap_entry /src/lxc/san_build/../src/lxc/confile.c:2462:9
#2 0x9eb69c in set_config_cap_keep /src/lxc/san_build/../src/lxc/confile.c:2503:8
#3 0x974a76 in parse_line /src/lxc/san_build/../src/lxc/confile.c:3115:9
#4 0xea8cac in lxc_file_for_each_line_mmap /src/lxc/san_build/../src/lxc/parse.c:123:9
#5 0x9700a1 in lxc_config_read /src/lxc/san_build/../src/lxc/confile.c:3192:9
#6 0x4a3b50 in LLVMFuzzerTestOneInput /src/lxc/san_build/../src/tests/fuzz-lxc-cgroup-init.c:40:8
#7 0x10556e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, …
```
=> Fix uninitialized read in parse_cap when libcap is not used

meson.build, src/tests/meson.build
These are all still in use in the code but have not been
added to meson.build when switching over from autoconf.
=> meson: add remaining still-in-use config checks

src/lxc/log.h
`STRERROR_R_CHAR_P` is always defined to 0 or 1 depending on the value of `have_func_strerror_r_char_p` in `meson.build` so replace `#ifdef` by `#if` to avoid a redefinition build failure if `char *strerror_r` is not defined
=> src/lxc/log.h: fix STRERROR_R_CHAR_P

meson.build
Define `libcap_static` to an empty array to avoid the following build failure with `-Dcapabilities=false`:
```
output/build/lxc-5.0.0/src/lxc/cmd/meson.build:64:4: ERROR: Unknown variable "libcap_static".
```
=> meson.build: fix build with -Dcapabilities=false

meson.build
Move `-fstack-protector-strong` from `possible_cc_flags` to `possible_link_flags` to avoid a build failure on toolchains without ssp
=> meson.build: fix build without stack-protector

meson.build, src/lxc/file_utils.c, src/lxc/macro.h, src/lxc/mount_utils.c, src/lxc/mount_utils.h, src/lxc/process_utils.c, src/lxc/process_utils.h, src/lxc/start.c, src/lxc/start.h, src/lxc/syscall_wrappers.h, src/lxc/utils.c, src/tests/reboot.c
=> tree-wide: only rely on sys/ headers to avoid conflicts with linux/ headers

meson.build, meson_options.txt
Allows either:
- Build inside minimal-and-clean chroot without neither
/etc/sysconfdir nor /etc/default.
- Cross Compile lxc from foreign distro,
let's say host distro uses /etc/sysconfdir and build distro
uses /etc/default and vice versus.
Fix #4178
=> meson.build: allow explicit distrosysconfdir

meson.build
docbook2man can sometimes be docbook2x and other times be docbook-utils.
Rather than compare paths, use version constraints to detect version.
Signed-off-by: Cameron Nemo <cam@nohom.org>
=> meson: fix docbook2x detection

src/lxc/tools/arguments.h
Signed-off-by: Neil.wrz <wangrunze13@huawei.com>
using all the commands from lxc tools with -? option to get the help list gives an error message:
For example:
lxc-info -? gives an error message lxc-info: invalid option -- '?'
fix this by adding one entry for `-?` option 
[my issues here](https://github.com/lxc/lxc/issues/4191)
=> fix error message when use tools with -? option

.github/workflows/cifuzz.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/lxc/conf.c
Fixes: https://github.com/lxc/lxd/issues/10914
=> conf: allow cross-device links

meson.build, src/lxc/cgroups/cgfsng.c
The sd_bus_call_method_asyncv's 10th parameter is of type
va_list and supplying NULL when invoking it causes compilation
error. Just replace it with the async one.
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
=> use sd_bus_call_method_async to replace the asyncv one

src/tests/lxc-test-checkpoint-restore
This test will fail on Jammy 5.15, and because of the "set -e" it will never go through the lxc-stop and lxc-destroy code in the end of this script. Thus the lxc-test-criu container will not be removed.
Compose a cleanup() and use TRAP to solve this problem.
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
=> tests: lxc-test-checkpoint-restore: use trap to do cleanup

src/lxc/tools/lxc_destroy.c
Looks like the --force is a flag to stop a running container before destroying it.
Update the help message accordingly.
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
=> tools: lxc-destroy: update help message for --force

src/lxc/tools/lxc_attach.c
Closes #4203. 
lxc-attach swallows the return codes of processes that are terminated via a signal, and by default exits with a return code of 0 (i.e. indicating success) even if the command it tried to execute was terminated.
This patch fixes it by explicitly checking if the process was terminated via a signal, and returning an appropriate exit code.
Note that we add 128 to the signal value to generate the exit code because by convention the exit code is 128 + signal number. e.g. if a process is killed via signal 9, then the error code is 9 + 128 = 137.
Signed-off-by: Mohammed Ajmal Siddiqui <ajmalsiddiqui21@gmail.com>
=> lxc-attach: Fix lost return codes of spawned processes that are killed

src/lxc/storage/overlay.c
This fixes a really subtle off-by-one error constructing overlay mount options if rootfs options are provided and modern overlayfs (i.e. requiring a workdir) is used. We need to allow for the extra "," required to separate the extra options when computing the length!
Signed-off-by: srd424 <srd424@users.noreply.github.com>
(cherry picked from commit df3301046fc5f31881a2d4736cc5c381342ecc3d)
=> Fix off-by-one error constructing mount options

src/lxc/meson.build
Since switching to meson, liblxc.a is being shipped as liblxc_static.a. Change it back to liblxc.a.
=> src/lxc/meson.build: fix the static library path

config/init/systemd/meson.build, meson.build, meson_options.txt, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/meson.build, src/lxc/conf.c, src/lxc/conf.h, src/lxc/meson.build, src/lxc/mount_utils.c, src/lxc/process_utils.h, src/lxc/syscall_wrappers.h
This is primarily a backport of the key patches in #4214 but it was also necessary to backport:
* 16ebb29dccb35bf74e8a19e8c45d2513f927476f (#4180)
* c1115e1503bf955c97f4cf3b925a6a9f619764c3 (#4179)
* ef1e0607b82e27350c2d677d649c6a0a9693fd40 (#4179)
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> [lxc-5.0.z] build: fix build issues on openSUSE

meson.build
Fixes issue #4223
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
Same PR as https://github.com/lxc/lxc/pull/4224 but posted to `master` branch.
=> meson.build: strip newlines from git output

meson.build
Unfortunately, builds using alpine:edge still break! Apparently, run_command(...).stdout() must be strip()'ed for variable assignments
Addendum to d5600cf76a4d932a03ea75aea6dd6c997a4e2f35 Fixes issue #4223
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
=> meson.build: strip newline for variable assignments

README.md
It's more or less dead. If we care about a service like this we should use something else.
=> README: remove lgtm

config/apparmor/abstractions/start-container.in, src/lxc/conf.c
Finally, we turn the rootfs into a shared mount. Note, that this doesn't reestablish mount propagation with the hosts mount namespace. Instead we'll create a new peer group.
We're doing this because most workloads do rely on the rootfs being a shared mount. For example, systemd daemon like sytemd-udevd run in their own mount namespace. Their mount namespace has been made a dependent mount (MS_SLAVE) with the host rootfs as it's dominating mount. This means new mounts on the host propagate into the respective services.
This is broken if we leave the container's rootfs a dependent mount. In which case both the container's rootfs and the service's rootfs will be dependent mounts with the host's rootfs as their dominating mount. So if you were to mount over the rootfs from the host it would …
=> conf: create separate peer group for container's root

.github/workflows/coverity.yml
1. install meson (ninja is a dependency)
2. run meson setup before ninja build
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
=> github: fix coverity build

.github/workflows/coverity.yml
Should fix
meson.build:494:0: ERROR: C header 'security/pam_modules.h' not found
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
=> github: fix coverity (add libpam-dev)

src/lxc/cmd/lxc-checkconfig.in
This fixes various issues with `lxc-checkconfig` that have been confusing some users lately.
=> Tweak checkconfig output

meson.build
We really need to split up our code into better chunks so we avoid all of this duplicated compilation.
Fixes: https://github.com/lxc/lxc/issues/4249
=> build: force linking against liblxc

src/lxc/meson.build
Don't build `lsm/apparmor.c` if apparmor is explicitly disabled by the user to avoid the following build failure with gcc 4.8:
```
/home/buildroot/autobuild/run/instance-3/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/bits/fcntl2.h: In function '__apparmor_process_label_open.isra.0': /home/buildroot/autobuild/run/instance-3/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/bits/fcntl2.h:50:24: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
__open_missing_mode ();
^
```
Fixes:
- http://autobuild.buildroot.org/results/c9f05ad264543adf429badb99310905427092772
=> src/lxc/meson.build: fix build without apparmor

src/lxc/cmd/lxc_user_nic.c
get_mtu() returns int, but "mtu" variable has unsigned int type. It leads to logical error in error handling, which can end up with strange -EINVAL error in lxc_veth_create(), cause (mtu > 0) condition is met, but negative "mtu" value is too large when set as mtu for network device.
Issue #4232
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
=> lxc_user_nic: fix get_mtu() error handling

config/apparmor/profiles/lxc-default-cgns
=> lxc-default-cgns apparmor profile: allow overlay mounts

meson.build
When building on a sparc64 machine running Debian sid with gcc 12.2.0, linking fails with the following error:
`collect2: fatal error: ld terminated with signal 10 [Bus error]` ([build log](https://buildd.debian.org/status/fetch.php?pkg=lxc&arch=sparc64&ver=1%3A5.0.1-2&stamp=1672947476&raw=0))
It appears to be caused by using the gold linker, although I'm not exactly sure why. None of the other Linux-based Debian architectures exhibit this issue with the gold linker.
I made the proposed change and tested it on one of the GCC Compile Farm sparc64 machines (gcc202), which was then able to successfully compile lxc.
=> Fix build error on sparc64 caused by using the gold linker

src/lxc/conf.c
Alternatively we could have used safe_strlcat, but it's not used anywhere and there's also no safe_strlcpy
Signed-off-by: Ariel Miculas <amiculas@cisco.com>
=> Fix strlcat's return value checks

config/init/common/lxc-net.in
The nftables masquarade rule for IPv6 was using the IPv4 syntax. This resulted in the following error when starting the lxc-net.service with LXC_IPV6_NAT="true" and nftables:
Feb 11 18:54:54 pc lxc-net[4936]: Error: conflicting protocols specified: ip6 vs. ip
Feb 11 18:54:54 pc lxc-net[4936]:                              ^^^^^^^^
Feb 11 18:54:54 pc lxc-net[4917]: Failed to setup lxc-net.
Feb 11 18:54:54 pc systemd[1]: lxc-net.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 18:54:54 pc systemd[1]: lxc-net.service: Failed with result 'exit-code'.
Feb 11 18:54:54 pc systemd[1]: Failed to start LXC network bridge setup.
Signed-off-by: Quentin Lyons <36303164+n0p90@users.noreply.github.com>
=> lxc-net.in: fix nftables syntax for IPv6 NAT

src/lxc/initutils.c
```
Kernel UAPI provides as with the following declaration:
/*
* This structure provides new memory descriptor
* map which mostly modifies /proc/pid/stat[m]
* output for a task. This mostly done in a
* sake of checkpoint/restore functionality. */ struct prctl_mm_map {
__u64	start_code;		/* code section bounds */
__u64	end_code;
__u64	start_data;		/* data section bounds */
__u64	end_data;
__u64	start_brk;		/* heap for brk() syscall */
__u64	brk;
__u64	start_stack;		/* stack starts at */
__u64	arg_start;		/* command line arguments bounds */
__u64	arg_end;
__u64	env_start;		/* environment variables bounds */
__u64	env_end;
__u64	*auxv;			/* auxiliary vector */
__u32	auxv_size;		/* vector size */
__u32	exe_fd;			/* /proc/$pid/exe link file */
};
Let's use appropriate types/format specifiers …
```
=> initutils: use PRIu64 for uint64_t in setproctitle

src/lxc/lsm/apparmor.c
In case empty profile files linger somehow (eg. powerloss or oom killer etc. between creating and writing the file) we tried to use mmap() with a length of 0 which is invalid. Let's treat this as if it did not exist.
=> apparmor: don't try to mmap empty files

config/apparmor/abstractions/start-container.in, templates/lxc-oci.in
This adds support to the oci template for squashfs images. It uses 'atomfs' from [1] to accomplish this.
Squashfs images (media type
application/vnd.stacker.image.layer.squashfs+zstd+verity) have several benefits compared to tar+gz:
* immediately mountable
* read-only filesystem
* verity data present in oci manifest.
I presented this at Fosdem 2023 at [2].
[1] https://github.com/project-machine/atomfs
[2] https://fosdem.org/2023/schedule/event/container_secure_storage/
=> Add support for squashfs images in oci via atomfs

.github/workflows/build.yml, .github/workflows/cifuzz.yml, .github/workflows/coverity.yml, .github/workflows/sanitizers.sh, .github/workflows/sanitizers.yml, lxc.spec.in, meson.build, meson_options.txt, src/lxc/cgroups/cgfsng.c, src/tests/console_log.c, src/tests/oss-fuzz.sh
This is purely so that we can do static linking.  Linking against libsystemd makes that a challenge because while it's perfectly simple to do, distros tend not to provide a libsystemd.a.
Tools that want to (a) link against liblxc and (b) have a statically linked binary to bind into a minimal container are ill served by this.  So link against libdbus-1.
.github/workflows/build.yml: switch to dbus-1.
src/lxc/cgroups/cgfsng.c: replace the unpriv_systemd_create_scope(),
start_scope, and enter_scope() systemd code with dbus-1 code.
=> switch from libsystemd's dbus to dbus-1

src/lxc/file_utils.c, src/lxc/file_utils.h, src/lxc/mainloop.c, src/lxc/seccomp.c, src/lxc/terminal.c
Something is wrong with multishot polling mode in io_uring. Let's workaround that and safe from possible stucks on read.
=> mainloop: fix stuck when io_uring is enabled

src/tests/parse_config_file.c
Link: https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1980218
Check if seccomp is enabled before throwing error.
=> tests: fix parse_config_file seccomp test

src/lxc/mainloop.c
When lxc is built with io-uring-event-loop enabled, there is implicit pointer to int conversion in __io_uring_disarm.
=> explicitly convert *mainloop_handler to __u64

src/lxc/cgroups/cgfsng.c
If I start a container with loglevel WARN, and (on a pretty stock ubuntu) do lxc-info -n $c, I get
lxc-start media 20230706233337.765 WARN     cgfsng - cgroups/cgfsng.c:get_hierarchy:142 - There is no useable cpuacct controller
lxc-start media 20230706233337.765 WARN     cgfsng - cgroups/cgfsng.c:get_hierarchy:142 - There is no useable blkio controller
I don't think that's worth WARNing about, so change it to INFO.
=> get_hierarchy: dont WARN about no usable controller

src/lxc/commands.c, src/lxc/commands.h, src/lxc/commands_utils.c, src/lxc/commands_utils.h, src/lxc/lxccontainer.c, src/lxc/lxccontainer.h, src/lxc/state.c, src/lxc/state.h
lxccontainer set_timeout method allows to set LXC client
timeout for waiting monitor response.
Right now, it's implemented using the SO_RCVTIMEO client
socket option. (But it's the implementation detail that
can be changed in the future.)
See https://github.com/lxc/lxc/issues/4257
=> LXC API extension: set_timeout

src/lxc/utils.c
Closes #4338
We should not give execute permissions to console output.
=> Update console perms to 0600

src/lxc/lxccontainer.h
The recent PR to add set_timeout is adding new fields to the `lxc_container` struct, but as that struct is public API, in fact the main struct in our public API, additions should always be appended to it to avoid breaking ABI.
=> lxccontainer.h: Move new fields to the end

src/lxc/conf.c
root_nsuid_map and root_nsgid_map can point to entries in id_map. When the id_map is cleared, these parameters could point to wrong memory. So set them to NULL when the idmap is cleared.
this fixes #4356
=> reset root_nsuid_map and root_nsgid_map when idmaps is cleared

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/storage/storage.c, src/lxc/storage/storage.h
It appears that `rootfs->bdev_type` wasn't actually being set anywhere, other than if it comes from a config file.
Fixes: #4199
=> lxc_storage_prepare(): Fix ephemeral copies

templates/lxc-download.in
This patch fixes unpacking images when the system provided tar is libarchive (bsd-tar). bsd-tar  doesn't support 'exclude' flags (--anchored) like gnu-tar does. Instead each exclude path is prepended with ^ to simulate behavior of --anchored when bsd tar is detected.
=> Add libarchive tar support for lxc download

src/lxc/network.c
vid 0 is a special value that indicates the absence of a default pvid
this fixes #4350
=> don't try to delete vlan 0 from veth

src/lxc/storage/zfs.c
zfs list blocks forever for longer lists of filesystems (as pclose will wait for termination of zfs list). Therefore just reading the output until end.
=> Read list until process exits

templates/lxc-local.in
I refactored the script to use functions, added more reasonable checks for existence of the metadata tarball, improved variable naming, added a "--no-dev" option to exclude /dev/ from tarballs (to make creating unprivileged containers easier)
=> Updated lxc-local template

templates/lxc-download.in
closes #4380
```
root@motorhead:~# lxc-create -t download -n abContainer2
Downloading the image index
---
DIST             RELEASE     ARCH   VARIANT  BUILD         
---
almalinux        8           amd64  default  20240105_23:08
almalinux        8           arm64  default  20240105_23:08
almalinux        9           amd64  default  20240105_23:08
almalinux        9           arm64  default  20240105_23:08
alpine           3.16        amd64  default  20240105_13:00
alpine           3.16        arm64  default  20240105_13:03
alpine           3.17        amd64  default  20240105_13:00
alpine           3.17        arm64  default  20240105_13:02
alpine           3.18        amd64  default  20240105_13:00
alpine           3.18        arm64  default  20240105_13:02
alpine           3.19 …
```
=> Align columns in lxc-download.in template

templates/lxc-download.in
I have been studying the anatomy of an LXC image server. I haven't been able to find a written description of an LXC image server so I have been reverse engineering by reading the LXC download template. It was helpful to see the URLs of the files that the LXC download template was downloading.
=> Add Verbose Output in Download Template

src/lxc/cgroups/cgfsng.c, src/lxc/conf.c, src/lxc/network.c, src/lxc/start.c
While playing with [isolated user namespaces](https://github.com/mihalicyn/isolated-userns) and LXC I've noticed that we have a few different ways to determine if a container uses user namespace or not depending on the context. While in some cases it's reasonable, in most other cases it makes no sense. In this simple PR I converted most places to use an old `container_uses_namespace()` helper. Some less-trivial cases left untouched, because converting them require adding some extra fields on the structures or passing more arguments down the stack which makes no sense right now (as isolated user namespaces stuff is not upstreamed in the Linux kernel anyways).
No functional changes intended.
=> tree-wide: use container_uses_namespace() in more places

templates/lxc-download.in, templates/lxc-local.in
Update `tar` invocation to preserve all xattrs when unpacking the rootfs, notably retaining `security.capability` xattrs (e.g. for `ping`, `newuidmap`)
Note: `bsdtar` already preserves xattrs with `-p`
Related / analogous:
- https://github.com/lxc/incus/commit/38778dfb6fbda86ddf2ec273968364e7d9d55bd7
- https://github.com/lxc/distrobuilder/pull/340/commits/ed7c50e2988d6dc2db1d01d25dce491765825350
=> lxc-download, lxc-local: preserve xattrs on unpack

src/lxc/confile.c
LXC supports x32 containers, but currently creation of those containers is broken:
```
lxc-create: x32-test: ../src/lxc/confile.c: set_config_personality: 1432 Invalid argument - Unsupported personality "x32"
lxc-create: x32-test: ../src/lxc/parse.c: lxc_file_for_each_line_mmap: 129 Failed to parse config file "/var/lib/lxc/x32-test/config" at line "lxc.arch = x32"
lxc-create: x32-test: ../src/lxc/tools/lxc_create.c: main: 317 Failed to create container x32-test
```
The underlying support is still there, it's just an issue when parsing the container's config.
With this change, I can successfully create and use x32 containers on a Debian sid amd64 host booted with `syscall.x32=y`, running lxc 5.0.3.
=> Add x32 to the list of recognized architectures

src/tests/lxc-test-usernic.in
The Ubuntu lxc package has a patch fixing lxc-test-usernic, which is not yet upstream.
I'm splitting that into two patches here as I suspect at least the second patch will probably need a rework.
=> test-usernic fixes

src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-unpriv
We have removed the same piece of code in
ec85e5ca495 ("lxc-test-usernic: drop cgroup handling") let's do the same for two other tests.
This fixes autopkgtests.
=> tests: remove old and broken cgroup handling code from tests

config/apparmor/meson.build, config/apparmor/usr.bin.lxc-copy, config/init/systemd/lxc-apparmor-load
lxc-copy can start container as lxc-start does in some cases, so we need to have the same profile for it.
=> config: apparmor: add AppArmor profile for lxc-copy

src/tests/lxc-test-usernic.in
This is required to fix autopkgtest failures.
=> tests: lxc-test-usernic: use iproute tool instead of brctl

templates/lxc-oci.in
This commit addresses an issue in the OCI template where `lxc-create` fails if OCI-cache directory for blob caching is not on the same mount as the destination OCI directory. `lxc-create` bails when skopeo tries to create a hard-link across the two and fails.
For example, if `/var/lib/lxc` is a bind mountpoint of a random directory then skopeo fails to hard-link across `/var/cache/lxc` and `/var/lib/lxc`
This commit introduces a check where if both directories are on not the same mount points, it disables blob caching in skopeo and continues.
=> oci: resolve cross-filesystem blob caching failure

src/lxc/tools/lxc_unshare.c
If the input parameter length is greater than PATH_MAX, a buffer overflow will occur.
=> lxc-unshare: fix an buffer overflow issue in lxc_unshare

src/lxc/tools/lxc_unshare.c
pass the optarg straight to getpwnam_r, instead of first scanning the name out of it.
=> unshare: simplify lookup_name

README.md
Use the correct designation for the armv7l arch, as also reflected in src/lxc/confile.c.
Smaller nit that was the result of series of misconfigurations due to the mistake of using armvl7 in our configurations instead of armv7l.
=> README: Correct 'armvl7' to 'armv7l'

src/lxc/lxccontainer.c
When lxc is doing cgroup_freeze,：
```c
int cgroup_freeze(const char *name, const char *lxcpath, int timeout)
{
__do_close int unified_fd = -EBADF;
int ret;
if (is_empty_string(name) || is_empty_string(lxcpath))
return ret_errno(EINVAL);
unified_fd = lxc_cmd_get_limit_cgroup2_fd(name, lxcpath);
if (unified_fd < 0)
return ret_errno(ENOCGROUP2);
lxc_cmd_notify_state_listeners(name, lxcpath, FREEZING);
ret = __cgroup_freeze(unified_fd, timeout);
lxc_cmd_notify_state_listeners(name, lxcpath, !ret ? FROZEN : RUNNING);
return ret;
}
```
if the lxc process is killed after setting the container status to FREEZING, the container status will be abnormal, unfreezing operation will not be possible, and normal life cycle management will not be possible. Therefore, containers in the FREEZING state also …
=> containers in the FREEZING state also need to be unfreeze

src/lxc/syscall_numbers.h
Drop `#define -1` to avoid the following m68k build failure with gcc 12:
```
In file included from ../src/lxc/syscall_wrappers.h:19,
from ../src/lxc/mount_utils.h:15,
from ../src/lxc/conf.h:24,
from ../src/lxc/log.h:19,
from ../src/lxc/storage/btrfs.c:20:
../src/lxc/syscall_numbers.h:423:25: error: macro names must be identifiers
423 |                 #define -1
|                         ^
```
Fixes:
- http://autobuild.buildroot.org/results/f40a517eba86838b11b4b1d6a8a05b8233a3394d
=> src/lxc/syscall_numbers.h: drop define -1

src/lxc/tools/lxc_autostart.c, src/lxc/tools/lxc_copy.c, src/lxc/tools/lxc_info.c, src/lxc/tools/lxc_ls.c, src/lxc/tools/lxc_monitor.c, src/lxc/tools/lxc_snapshot.c, src/lxc/tools/lxc_top.c
For some reason, we don't have default log_priority set for many tools which leads to the situation when tools can fail silently even if error occurs.
Fixes: #4405
=> lxc/tools: set default log_priority to ERROR

src/lxc/lxccontainer.c
=> lxc-ls: list names with whitespaces in `--active`.

meson.build, meson_options.txt
Trying to get the nix lxc package up to 5.x and these options are helpful to avoid writing to places outside the nix sandbox. The default behavior should be unchanged.
=> build: add more options for customizing install

.github/workflows/build.yml, src/lxc/cmd/meson.build, src/lxc/tools/meson.build
It was reported recently that on NixOS LXC fails to build with the following errors:
```
[135/139] Linking target src/lxc/cmd/lxc-monitord
FAILED: src/lxc/cmd/lxc-monitord
gcc  -o src/lxc/cmd/lxc-monitord src/lxc/cmd/lxc-monitord.p/lxc_monitord.c.o src/lxc/cmd/lxc-monitord.p/.._.._include_netns_ifaddrs.c.o -flto -Wl,--no-undefined -pie -Wl,--no-as-needed -Wl,--gc-sections -Wl,-z,relro -Wl,-z,now -fstack-protector -fstack-protector-strong -Wl,-fuse-ld=gold -Wl,--warn-common '-Wl,-rpath,$ORIGIN/../../..' -Wl,-rpath-link,/home/adam/git/lxc/build/ -Wl,--start-group src/lxc/liblxc.a liblxc.so.1.8.0 /nix/store/jnlxl2ry9y03vq4skhm26igfd84xwa93-dbus-1.14.10-lib/lib/libdbus-1.so -pthread /nix/store/iglb2fmla149fbprj6fb18swfls033q4-libseccomp-2.5.4-lib/lib/libseccomp.so …
```
=> meson: fix build on NixOS

templates/lxc-download.in
Running `bash lxc-download.in --help` and `bash lxc-download.in --list` currently results in a non-zero exit code, indicating an error occurred (e.g. wget is not installed to download the image index). This PR changes the exit code for `--help` and `--list` to 0 so that a successful run with these flags can be distinguished from runs where a failure occurred.
=> Exit 0 when there's no error

meson.build
this fix issue #4480 
When I use clang to build on openEuler-24.03-LTS(aarch64),I got the error:
```c
[  112s] [2/1785] Compiling C object src/lxc/liblxc.a.p/error.c.o
[  112s] FAILED: src/lxc/liblxc.a.p/error.c.o 
[  112s] clang -Isrc/lxc/liblxc.a.p -Isrc/lxc -I../src/lxc -I. -I.. -Isrc -I../src -Isrc/include -I../src/include -I../src/lxc/json -I../src/lxc/cgroups -I../src/lxc/storage -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -g -include config.h -O2 -g -grecord-gcc-switches -pipe -fstack-protector-strong -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/generic-hardened-clang.cfg -fasynchronous-unwind-tables -fstack-clash-protection -fsigned-char -fPIC -pthread -fvisibility=default -MD …
```
=> fix possible clang compile error on AARCH

templates/lxc-oci.in
PuzzleFS images (media type 'application/vnd.puzzlefs.image.rootfs.v1') can be mounted in a similar way to squashfs images, we just have to detect the type and reuse the existing code for providing a mount helper. PuzzleFS is a next-generation container filesystem [1] with several benefits, such as  reduced duplication, reproducible image builds, direct mounting support and memory safety guarantees.
Since PuzzleFS currently doesn't provide an image config, also add support for empty image configs, they are supported by the OCI spec [2].
[1] https://github.com/project-machine/puzzlefs
[2] https://github.com/opencontainers/image-spec/blob/main/manifest.md#image-manifest
=> Add suppport for PuzzleFS images in the oci template

src/lxc/lxccontainer.c
It's ok that we don't free the malloc()d space since we're immediately exec()ing.
Originally-by: Kurt Godwin <kgodwin@itron.com>
Reported-by: Kurt Godwin <kgodwin@itron.com>
=> create_run_template: don't use txtuid and txtguid out of scope

src/lxc/conf.c
rootfs->storage not set by lxc_storage_prepare when using a shared rootfs.
Fixes: https://github.com/lxc/lxc/issues/4476
Tested on Fedora 41 Beta with 6.0.2 via patched rpm rebuild.
=> Avoid null pointer dereference when using shared rootfs

config/init/common/lxc-net.in
This is meant to be a completely random ULA subnet.
=> lxc-net: Replace random IPv6 subnet

src/lxc/lxccontainer.c
When an unprivileged container is running with an inheritted network namespace, then the ip addresses of the container are not shown with 'lxc-ls -f'.
This MR solves  #4496
=> network config of unprivileged containers is not shown

src/lxc/cgroups/cgroup_utils.c
IMHO, the value to return here is `ret` as it is the value got from recursion. Because this is not a call to a I/O-function, the value of `errno` is unrelated to this call, u.e. undefined.
=> fix return code of recursive all of cgroup_tree_prune

src/lxc/confile.c
Full description was in issue: [#4474](https://github.com/lxc/lxc/issues/4474)
Main problem was explained in 'consequence2', if we have a config with undefined (missing) line about vlan.id, after we just load_config then save_config, config file will change it contents and it will have unwanted vlan.id=0 line that cause new set of problems and blocks container from starting.
This change (one condition-line added in code) solves this problem well. Someone already prepared bool value that will mark int(0) value as valid or undefined, and this new line just uses that bool var (**vlan_id_set**), as it was probably intended to be used.
This was patched locally in my own test version 5 months ago and tested/used since then, so I am pretty sure that is valid.
=> confile-vlanid: undefined is not a zero value

src/lxc/attach.c
This reverts commit f02158439677d0c1d4b2ed2ed1ba9bc43923a05d (from https://github.com/lxc/lxc/pull/4509)
Let's revert this change as it introduces 2 regressions:
1. it's not correct to do exit(2) from a signal handler in this case, as we skip a proper cleaning procedures like restoring PTY configuration state (see lxc_terminal_delete()) which leads to a problem with a PTY after lxc-attach exits.
[ hint: just try to use lxc-attach on a main branch with this change and you will see it. After lxc-attach exits you won't be able to type anything in your current terminal session as it's messed up. ]
2. this introduces race-condition in the code which leads to a regression on LXD/(and I believe Incus too) which can be seen as random "Failed to retrieve PID of executing child process" errors on …
=> lxc/attach: Revert "- LXC attach should exit on SIGCHLD"

src/lxc/confile.c
=> config-bcast: fix incorrect broadcast address calculation

config/init/common/lxc-net.in
Some hosts might not have IPv6 support, or IPv6 addresses are not required in LXC containers. Adding the `LXC_IPV6_ENABLE` option doesn't change default behaviour, but allows users to disable DHCP for IPv6 addresses in dnsmasq using `LXC_IPV6_ENABLE="false"` e.g. in `/etc/default/lxc-net`.
=> Added LXC_IPV6_ENABLE option for lxc-net to enable or disable IPv6

config/sysconfig/lxc.in
I tested running `lxc-net` and this setting was not overridden. Changing this setting did affect if `lxcbr0` was created. If this setting is supposed to be ignored in `lxc-net`, I can create a bug report for it.
=> sysconfig/lxc: remove false comment

src/lxc/start.c
We need to do `prctl(PR_SET_DUMPABLE)` later, after last `lxc_switch_uid_gid()` call. Because otherwise, our earlier call won't be effective as `commit_creds()` in the kernel [1] will `set_dumpable(task->mm, suid_dumpable)` if UID/GID or capabilities were affected by `lxc_switch_uid_gid()` call.
This only affects LXC API `->start(struct lxc_container *c, int useinit, char *const argv[])` call when `useinit == 1` because in this case we don't perform additinal exec() and task's dumpable bit remains set to 2 (default value taken from `/proc/sys/fs/suid_dumpable`).
If `useinit == 0`, then we do `exec()` (see `start_ops->start` callback) and then dumblable flag will be reset in `begin_new_exec()` to `SUID_DUMP_USER=1` [2]. Then everything will be fine.
Reproducer (problem with lxc-attach).
1. …
=> lxc/start: do prctl(PR_SET_DUMPABLE) after last uid/gid switch

src/lxc/start.c
Without it, we're running into issues with complex hooks like nvidia.
=> start: Re-introduce first SET_DUMPABLE call

meson_options.txt
Avoids this deprecation notice from `meson` 1.3.2:
```
:: NOTICE: Future-deprecated features used:
::  * 1.1.0: {'"boolean option" keyword argument "value" of type str'}
```
Other options already use this syntax so backward compat should remain unchanged.
=> meson_options.txt: don't use str when defining bool default values

src/lxc/conf.c, src/lxc/start.c
Commit eae44ce19931 ("conf: fix append_ttyname()") changed the format of `conf->ttys.tty_names`, where the `container_ttys=` prefix was removed.
This seems to have been taken into account in `lxc_create_ttys()` in `src/lxc/conf.c`, however that's not enough. `do_start()` in `src/lxc/start.c` clears the environment, and then does `putenv(...)` directly on the value of `tty_names`. As it no longer has the `container_ttys=` prefix, this call doesn't have the intended effect.
This behaviour is also confirmed via `ltrace` when doing `lxc-start`:
[pid 53587] liblxc.so.1->setenv("container_ttys", "pts/1 pts/2 pts/3 pts/4", 1) = 0
[pid 53587] liblxc.so.1->clearenv(0, 1, 0, 0)                                   = 0
[pid 53587] liblxc.so.1->putenv("container=lxc")                                = 0 …
=> lxc/conf,start: fix setting container_ttys environment variable

src/lxc/attach.c, src/lxc/lsm/apparmor.c, src/tests/aa.c
attach and start were assuming the container's apparmor profile too early, causing the profile to require elevated capabilities, including CAP_SYS_ADMIN to finish the container setup (e.g. load seccomp profiles).  This change re-adds the `onexec` usage to apparmor LSM module and moves the label assumption to later in the attach code.
relevant issue is https://github.com/lxc/lxc/issues/4525
=> delay assumption of apparmor labels

meson.build
After some research, it seems that Ubuntu 14.10's libcap-dev package corrected the mistake and shiped the `.pc` file.
Both Ubuntu releases are very old now so remove the workaround.
=> meson.build: remove quirk for Ubuntu 14.04 libcap-dev

src/tests/oss-fuzz.sh
See also
https://github.com/google/oss-fuzz/pull/13286/commits/093b2480ce44c38c2418c20df2212f56b9e7fbd2
Thanks to Evgeny Vereshchagin
Fixes: #4551
=> src/tests/oss-fuzz: pin meson to 1.7.2 to workaround build failures

config/bash/_lxc.in, src/lxc/confile.c, src/tests/arch_parse.c
Debian refers to the loong architecture as "loong64".
=> Add loong64 to list of recognized architectures

src/lxc/lxccontainer.c, src/lxc/utils.c, src/lxc/utils.h
In enter_net_ns() we try to enter network namespace at first, before entering a user namespace to support inherited netns case properly. It is expected to get EPERM for unprivileged container with non-shared network namespace at first try. Let's take this into account and stop misleading users with these error messages.
Link: https://discuss.linuxcontainers.org/t/lxc-ls-fancy-command-shows-operation-not-permitted/24080
Fixes: 3011e79f92ef ("lxccontainer: fix enter_net_ns helper to work when netns is inherited")
Fixes: #4560
=> lxc/lxccontainer: stop printing misleading errors in enter_net_ns()

doc/api-extensions.md, doc/lxc.container.conf.sgml.in, src/lxc/api_extensions.h, src/lxc/attach.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/start.c
Introduce `lxc.environment.runtime` to set environment variables only
for the container init process and `lxc.environment.hooks` to set
environment variables only for hooks. Leave the original
`lxc.environment` unchanged. It still applies to everything.
This is needed in Proxmox Virtual Environment for containers created from OCI images that specify custom environment variables.
See: https://lore.proxmox.com/pve-devel/20250908150224.155373-6-f.schauer@proxmox.com/
=> conf: split `lxc.environment` into `runtime` and `hooks`

src/lxc/log.c, src/lxc/terminal.c, src/lxc/tools/lxc_attach.c
I read through the contributing guidelines and it didn't seem like there was much required except the sign-off line.
I did look at some of the tests but it seems like this kind of change probably doesn't warrant a new test?
I'm not a C developer so this was a manual code-only change.  It makes sense to me but I didn't run locally.
Let me know if you need changes.
Thanks.
Fixes: https://github.com/lxc/lxc/issues/4588
=> Standardize log file create mode to 0640
