lxc/lxc

- configure.ac
> autotools: fix check for -Wimplicit-fallthrough

- src/lxc/caps.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cmd/lxc_init.c
- src/lxc/compiler.h
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/log.c
- src/lxc/lsm/apparmor.c
- src/lxc/lxclock.c
- src/lxc/macro.h
- src/lxc/storage/overlay.c
- src/lxc/tools/arguments.c
> macro: add STRLITERALLEN() and STRARRAYLEN() 

- src/lxc/compiler.h
> compiler: __attribute__((noreturn)) on bionic

- configure.ac
- src/include/ifaddrs.c
- src/lxc/log.h
- src/lxc/lxccontainer.c
- src/lxc/network.c
- src/lxc/rtnl.c
> compiler: compiler based hardening

- src/lxc/commands.c
> stop: Only freeze if freezer is available

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
> cgfsng: set errno to ENOENT on get_hierarchy()

- .gitignore
- config/apparmor/Makefile.am
- config/apparmor/abstractions/start-container.in
- configure.ac
Signed-off-by: Cameron Nemo <camerontnorman@gmail.com>
> apparmor: account for specified rootfs path (closes #2617)

- src/lxc/compiler.h
> compiler: fix __noreturn on bionic

- doc/ja/lxc-attach.sgml.in
- doc/ja/lxc-execute.sgml.in
Update for commit ddd51fd and 0840104
> doc: Add -u and -g args to Japanese lxc-attach(1) and lxc-execute(1)

- src/include/netns_ifaddrs.c
- src/include/netns_ifaddrs.h
> netns_ifaddrs: fix missing include

- templates/lxc-oci.in
oci template changes character user info to uid, gid
according to OCI image spec.
Signed-off-by: Jungsub Shin jungsub_shin@tmax.co.kr
> template: oci template supports for char user info

- config/ax_check_link_flag.m4
- configure.ac
> autotools: support -z relro and -z now

- configure.ac
- src/include/netns_ifaddrs.c
- src/include/netns_ifaddrs.h
- src/lxc/macro.h
> netns_ifaddrs: handle IFLA_STATS{64} correctly

- src/include/netns_ifaddrs.c
- src/lxc/cgroups/cgfsng.c
> cgroups: remove unnecessary line

- src/lxc/start.c
- src/lxc/utils.c
- src/lxc/utils.h
> utils: fix lxc_set_death_signal()

- src/lxc/cgroups/cgfsng.c
- src/lxc/utils.c
> cgfsng: close tiny race window

- src/lxc/tools/lxc_start.c
- src/lxc/tools/lxc_unshare.c
Hello,
Unused argument and unnecessary initialization are removed.
Thanks.
> remove unused argument

- src/lxc/cmd/lxc_init.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/log.h
- src/lxc/lsm/apparmor.c
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/network.c
- src/lxc/pam/pam_cgfs.c
- src/lxc/start.c
- src/lxc/storage/btrfs.c
- src/lxc/storage/loop.c
- src/lxc/storage/lvm.c
- src/lxc/storage/overlay.c
- src/lxc/storage/rbd.c
- src/lxc/storage/storage.c
- src/lxc/storage/storage_utils.c
- src/lxc/storage/zfs.c
- src/lxc/terminal.h
- src/lxc/tools/lxc_cgroup.c
- src/lxc/tools/lxc_copy.c
- src/lxc/tools/lxc_destroy.c
- src/lxc/tools/lxc_execute.c
- src/lxc/tools/lxc_unshare.c
- src/lxc/utils.c
> tree-wide: s/MAXPATHLEN/PATH_MAX/g

- src/lxc/parse.c
- src/tests/get_item.c
- src/tests/parse_config_file.c
> parse: do not mask failed parse

- src/include/netns_ifaddrs.c
- src/lxc/macro.h
> netns_ifaddrs: support NETLINK_DUMP_STRICT_CHK

- lxc.spec.in
- src/lxc/confile.c
- src/lxc/parse.c
Hello,
rpm build issue is fixed.(https://github.com/lxc/lxc/issues/2541)
Thanks.
> fix rpm packaging error for static library

- src/lxc/conf.c
> conf: log prlimit setup

- src/lxc/cgroups/cgfsng.c
> cgfsng: ensure initialized cpuset controller

- src/lxc/conf.c
Fixes: https://discuss.linuxcontainers.org/t/are-lxc-mount-entry-available-when-lxc-hook-start-is-validated/2906/3
> conf: verify_start_hooks() after lxc.mount.entry

- src/lxc/cmd/lxc-checkconfig.in
https://github.com/lxc/lxd/issues/5151
> checkconfig: Handle missing kernel version

- src/lxc/Makefile.am
- src/lxc/cmd/lxc_init.c
- src/lxc/execute.c
> lxc-init: log to /dev/console

- src/lxc/raw_syscalls.c
> raw_syscalls: ensure function always returns value

- src/lxc/conf.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/macro.h
- src/lxc/parse.c
> parse: protect against config updates during parse

- configure.ac
> autotools: compiler based hardening

- src/include/netns_ifaddrs.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cmd/lxc_init.c
- src/lxc/cmd/lxc_monitord.c
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/criu.c
- src/lxc/lxccontainer.c
- src/lxc/start.c
- src/lxc/state.c
- src/lxc/tools/lxc_copy.c
- src/lxc/tools/lxc_info.c
- src/lxc/tools/lxc_stop.c
- src/lxc/tools/lxc_top.c
> tree-wide: bugfixes

- src/lxc/parse.c
- src/lxc/storage/storage_utils.c
> storage_utils: add error handling

- src/lxc/start.c
Hello,
A function is added to inherit file descriptors of dlog to print dlog.
Thanks.
> dlog: inherit dlog fds

- src/lxc/confile.c
> confile: remove debug printf()s

- src/lxc/log.c
> log: fix too wide or inconsistent non-owner permissions

- src/include/lxcmntent.c
- src/lxc/string_utils.c
Hello,
Some wrong coding styles are fixed.
Thanks.
> lxcmntent: coding rules

- src/include/lxcmntent.c
> include: correctly include macro.h

- src/lxc/namespace.c
Signed-off-by: Jungsub Shin supsup5642@tmax.co.kr
> Fix spacing error in namespace.c

- src/lxc/start.c
> dlog: move match_dlog_fds()

- src/lxc/conf.c
> conf: s/ty/tty/g

- doc/ko/lxc-copy.sgml.in
> doc: Add -a, --allowrunning arg to Korean lxc-copy(1)

- src/lxc/Makefile.am
> fix install error when using --disable-commands option

- src/lxc/api_extensions.h
- src/lxc/lxccontainer.c
> lxccontainer: fix mount api (mount_injection_file)

- src/lxc/lxccontainer.c
Signed-off-by: S.Çağlar Onur <caglar@10ur.org>
> Set c to NULL after freeing it

- src/lxc/lxccontainer.c
> storage: do not destroy pre-existing rootfs

- src/lxc/cgroups/cgfsng.c
Cc: Ondrej Kubik <ondrej.kubik@canonical.com>
> cgroups: try to handle layouts with no cgroups

- src/lxc/cmd/lxc_user_nic.c
Signed-off-by: Hajo Noerenberg <hajo-github@noerenberg.de>
> network: prefix veth interface name with uid info

- src/lxc/start.c
> start: __lxc_start return -1 when start fails

- src/lxc/utils.c
on android loop devices are located under /dev/block/loop*
Signed-off-by: ondra <ondrak@localhost.localdomain>
> Handle alternative loop device location on Android

- src/lxc/seccomp.c
This reverts commit f1bcfc796e0a4a04b36284f6261afff59123b1aa.
The reverted branch breaks starting all seccomp confined containers. Not
even a containers with our standard seccomp profile starts correctly.
This is strong evidence that these changes have never been tested even
with a standard workload. That is unacceptable!
We are still happy to merge that feature but going forward we want tests
that verify that standard workloads and new features work correctly.
seccomp is a crucial part of our security story and I will not let the
be compromised by missing tests!
> Revert "seccomp: add rules for specified architecture only"

- src/lxc/tools/lxc_create.c
Copied from the [manpage](https://github.com/lxc/lxc/blob/9e42c1e3f102be48be9014e1ecbacc2a57446e20/doc/lxc-create.sgml.in#L175).
> Add template-options to help output

- doc/ja/lxc.container.conf.sgml.in
> doc: Add lxc.seccomp.allow_nesting to Japanese lxc.container.conf(5)

- configure.ac
- src/lxc/attach.c
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/conf.c
- src/lxc/criu.c
- src/lxc/log.c
- src/lxc/log.h
- src/lxc/lxccontainer.c
- src/lxc/network.c
- src/lxc/pam/pam_cgfs.c
- src/lxc/storage/lvm.c
- src/lxc/storage/overlay.c
- src/lxc/storage/storage.c
- src/lxc/storage/zfs.c
- src/lxc/string_utils.c
- src/lxc/tools/lxc_info.c
- src/lxc/tools/lxc_ls.c
- src/lxc/tools/lxc_unshare.c
- src/tests/Makefile.am
- src/tests/share_ns.c
- src/tests/state_server.c
> compiler: hardening

- README.md
> README: add LGTM

- src/lxc/cgroups/cgfsng.c
- src/lxc/memory_utils.h
> cgroups: partially switch to cleanup macros

- coccinelle/exit.cocci
- coccinelle/run-coccinelle.sh
- coccinelle/while-true.cocci
- src/lxc/attach.c
- src/lxc/cmd/lxc_init.c
- src/lxc/lxccontainer.c
- src/lxc/network.c
- src/lxc/pam/pam_cgfs.c
- src/lxc/storage/btrfs.c
- src/lxc/storage/nbd.c
- src/lxc/string_utils.c
- src/lxc/tools/arguments.c
- src/lxc/tools/lxc_autostart.c
- src/lxc/utils.c
- src/tests/aa.c
- src/tests/cgpath.c
- src/tests/list.c
- src/tests/locktests.c
- src/tests/may_control.c
- src/tests/snapshot.c
- src/tests/startone.c
> coccinelle support

- src/lxc/cgroups/cgfsng.c
- src/lxc/macro.h
> cgroup: bugfixes

- src/lxc/parse.c
> parse: handle \r

- src/include/fexecve.c
- src/include/fexecve.h
- src/lxc/Makefile.am
- src/lxc/rexec.c
> include: add fexecve() for Android's Bionic

- src/lxc/api_extensions.h
- src/lxc/compiler.h
- src/lxc/file_utils.h
- src/lxc/macro.h
- src/lxc/memory_utils.h
- src/lxc/rexec.c
- src/lxc/ringbuf.h
- src/lxc/syscall_wrappers.h
These are files only I touched. Aleksa gave his Ack on the other files.
> fix licensing headers

- .travis.yml
Compare command output to already existing container-rules file
Signed-off-by: Hervé Beraud <hberaud@redhat.com>
> apparmore: Improve testing on apparmor python script

- src/lxc/rexec.c
- src/lxc/rexec.h
- src/lxc/tools/lxc_attach.c
> rexec: cmdline and environ parsing improvements

- src/lxc/lxccontainer.c
> mount: Allow over-mounting

- src/lxc/Makefile.am
- src/lxc/af_unix.c
- src/lxc/attach.c
- src/lxc/cgroups/cgroup_utils.c
- src/lxc/cmd/lxc_init.c
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/cmd/lxc_usernsexec.c
- src/lxc/commands.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/macro.h
- src/lxc/memory_utils.h
- src/lxc/rexec.c
- src/lxc/start.c
> cleanup macros and rexec fixes

- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/memory_utils.h
- src/lxc/rexec.c
> rexec: handle legacy kernels

- src/lxc/cgroups/cgfsng.c
- src/lxc/commands.c
- src/lxc/file_utils.c
- src/lxc/macro.h
- src/lxc/rexec.c
Suggested-by: Wolfgang Bumiller <w.bumiller@proxmox.com>
> tree-wide: s/steal_{fd,ptr}/move_{fd,ptr}/g

- src/lxc/rexec.c
> rexec: try sendfile() fallback to fd_to_fd()

- src/tests/Makefile.am
- src/tests/cve-2019-5736.c
> cve-2019-5736: add test

- configure.ac
- src/lxc/Makefile.am
- src/lxc/conf.c
> autotools: handle getgrgid_r on bionic

- src/lxc/lxccontainer.c
> Fix existing mount target check

- .travis.yml
> travis: run coccinelle

- src/lxc/tools/lxc_attach.c
> lxc-attach: switch to attach_run_wait

- src/lxc/attach.c
- src/lxc/commands_utils.c
- src/lxc/conf.c
> tree-wide: cleanup macros

- src/include/fexecve.c
Fixing build error when building for android target
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
> Fix android compilation

- src/lxc/conf.c
- src/lxc/confile.c
> minor fixes

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/lxccontainer.c
- src/lxc/monitor.c
- src/lxc/network.c
- src/lxc/start.c
- src/lxc/storage/loop.c
- src/lxc/storage/lvm.c
- src/lxc/storage/nbd.c
- src/lxc/storage/storage.c
Builds on PR from @brauner https://github.com/lxc/lxc/pull/2886
I'm still working through these (the build still fails), but thought I would open in draft form early.
> gcc -Wall flag compat

- src/lxc/conf.c
- src/lxc/initutils.c
- src/lxc/utils.c
- src/lxc/utils.h
> tree-wide: kill fgets()

- src/lxc/commands_utils.c
- src/lxc/commands_utils.h
- src/lxc/file_utils.c
- src/lxc/string_utils.c
Acked-by: Donghwa Jeong <dh48.jeong@samsung.com>
> tree-wide: fix wrong licensing

- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/confile_utils.h
- src/tests/lxc-test-utils.c
> minor tweaks

- src/lxc/lxccontainer.c
This function can fail, because it uses the command API. If it does fail,
we get weird errors about not being able to open strange proc paths:
xc authyldapservice-c8020e20-e203-e852-90ef-4d378e8d1444 20190323163231.386 ERROR    lxc_utils - utils.c:switch_to_ns:1184 - No such file or directory - failed to open /proc/-104/ns/net
So let's check for errors before then.
> lxccontainer: check do_lxcapi_init_pid() for failure

- .travis.yml
- src/lxc/attach.c
Signed-off-by: tomponline <tomp@tomp.uk>
As per https://github.com/lxc/lxc/pull/2894#issuecomment-469746460
> Travis: Adds -Wall and -Werror cflags flags to automatic build.

- doc/lxc-user-nic.sgml.in
- src/lxc/cmd/lxc_user_nic.c
> lxc-user-nic: update

- doc/ja/lxc-user-nic.sgml.in
> doc: update Japanese lxc-user-nic manpage

- src/lxc/storage/btrfs.c
We can simply fix this issue by switching to our cleanup macros instead of
manually freeing the memory.
Closes #2912.
> storage: prevent unitialized variable warning

- src/lxc/raw_syscalls.c
Account for different trap number on 32bit SPARC.
Link: https://bugs.gentoo.org/656368
> raw_syscalls: lxc_raw_clone() account for different trap number on 32bit SPARC

- configure.ac
> configure: s/LDLAGS/LDFLAGS/

- configure.ac
- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/criu.c
- src/lxc/freezer.c
- src/lxc/initutils.c
- src/lxc/lxc.h
- src/lxc/lxccontainer.c
- src/lxc/start.c
- src/tests/cgpath.c
BugLink: https://bugs.launchpad.net/bugs/1825155
This will allow us to better support cgroup2 layouts on stable-3.0.
> cgfsng: backport new cgroup handling logic

- configure.ac
- doc/lxc.container.conf.sgml.in
- src/lxc/af_unix.c
- src/lxc/af_unix.h
- src/lxc/api_extensions.h
- src/lxc/attach.c
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/lxccontainer.c
- src/lxc/lxccontainer.h
- src/lxc/lxcseccomp.h
- src/lxc/macro.h
- src/lxc/seccomp.c
- src/lxc/start.c
> seccomp: SECCOMP_RET_USER_NOTIF support

- .gitignore
> tests: Updates .gitignore to ignore test build artefacts

- src/lxc/confile_utils.c
> network: Fixes bug in macvlan mode selection

- src/lxc/af_unix.c
- src/lxc/attach.c
- src/lxc/lxcseccomp.h
- src/lxc/seccomp.c
- src/lxc/start.c
> seccomp: notifier fixes

- src/lxc/lxccontainer.h
- src/lxc/lxcseccomp.h
I'm not sure that I want to be married (to this layout) just yet.
> seccomp: don't commit to an api just yet

- src/lxc/network.c
network: Adds ipvlan static routes for l2proxy mode.
> network: Static routes for IPVLAN with L2PROXY

- src/lxc/af_unix.c
- src/lxc/network.c
- src/lxc/nl.c
> tree-wide: make socket SOCK_CLOEXEC

- src/lxc/raw_syscalls.c
- src/lxc/raw_syscalls.h
- src/lxc/start.c
- src/lxc/start.h
Well, I added this syscall so we better use it. :)
> raw_syscalls: add initial support for pidfd_send_signal()

- src/lxc/seccomp.c
> seccomp: document path calculation

- src/lxc/network.c
> network: Adds custom mtu support for ipvlan interfaces

- src/lxc/network.c
This is consistent with veth and ipvlan types.
Also makes the debug message for success occur after up script has run.
Also makes device clean up on error more thorough and consistent.
> network: Makes vlan network interfaces set mtu before upscript called

- src/lxc/network.c
Handles more errors and gives better error messages.
> network: Re-works veth gateway logic

- src/lxc/macro.h
- src/lxc/utils.c
> utils: improve switch_to_ns()

- src/lxc/attach.c
- src/lxc/conf.c
- src/lxc/raw_syscalls.c
- src/lxc/raw_syscalls.h
- src/lxc/start.c
- src/lxc/utils.c
- src/tests/lxc_raw_clone.c
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=eac7078a0fff1e72cf2b641721e3f55ec7e5e21e
> clone: add infrastructure for CLONE_PIDFD

- doc/api-extensions.md
- src/lxc/api_extensions.h
- src/lxc/network.c
- src/lxc/network.h
> network: Adds mtu support for phys and macvlan types

- CODING_STYLE.md
> coding style: update

- configure.ac
> configure: handle checks when cross-compiling

- src/lxc/network.c
> network: Fixes bug that stopped down hook from running for phys netdevs

- configure.ac
> configure: remove additional comma

- src/lxc/cmd/lxc_user_nic.c
Hi,
I think this will solve issue #2765.
Please, take a look.
Thanks
> fix issue 2765

- doc/lxc.container.conf.sgml.in
- src/lxc/namespace.c
Here's some things I was thinking about on a plane while working on something else :)
> Pass zero to clone

- src/lxc/namespace.c
> lxc_clone: add a comment about stack size

- src/lxc/cgroups/cgfsng.c
Handle offline cpus in v1 hierarchy.
In addition to isolated cpus we also need to account for offline cpus when our
ancestor cgroup is the root cgroup and we have not been initialized yet.
Closes #2953.
> cgroups: handle offline cpus in v1 hierarchy

- templates/lxc-busybox.in
/tmp created with "rwxrwxrwt" mode
> Make /tmp accessible to any user

- src/lxc/cgroups/cgfsng.c
> cgroups: prevent segfault

- src/lxc/Makefile.am
- src/lxc/conf.c
- src/lxc/uuid.c
- src/lxc/uuid.h
Closes #3027.
BugLink: https://bugs.launchpad.net/bugs/1831258
Cc: Dimitri John Ledkov <xnox@ubuntu.com>
Cc: Scott Moser <smoser@ubuntu.com>
> start: generate new boot id on container start

- doc/ja/lxc.container.conf.sgml.in
Update for commit 8de90384363fe01f5258d36724dd3eae55918b5b
> doc: add a note about shared ns + LSMs to Japanese doc

- src/lxc/start.c
In privileged mode, the container startup looses a file descriptor for "handler->nsfd[LX_NS_NET]". At line 1782, we preserve the namespaces file descriptor (in privileged mode, the network namespace is also preserved) :
for (i = 0; i < LXC_NS_MAX; i++)
if (handler->ns_on_clone_flags & ns_info[i].clone_flag)
INFO("Cloned %s", ns_info[i].flag_name);
if (!lxc_try_preserve_namespaces(handler, handler->ns_on_clone_flags, handler->pid)) {
ERROR("Failed to preserve cloned namespaces for lxc.hook.stop");
goto out_delete_net;
}
Then at line 1830, we preserve one more time the network namespace :
ret = lxc_try_preserve_ns(handler->pid, "net");
if (ret < 0) {
if (ret != -EOPNOTSUPP) {
SYSERROR("Failed to preserve net namespace");
goto out_delete_net;
}
The latter overwrites the file descriptor …
> Fixed file descriptor leak for network namespace

- src/lxc/lxccontainer.c
> fix memory leak in do_storage_create

- src/lxc/lxccontainer.c
- src/lxc/lxccontainer.h
> lxccontainer: rework seccomp notify api function

- src/lxc/network.c
Reported-by: Thomas Parrott <thomas.parrott@canonical.com>
> network: remove faulty restriction

- src/lxc/cgroups/cgfsng.c
> cgroups: hande cpuset initialization race

- src/lxc/network.c
- src/lxc/network.h
- src/lxc/start.c
> network: fixes after unifying network creation

- src/lxc/network.c
> network: simplify lxc_network_move_created_netdev_priv()

- src/lxc/lxccontainer.c
Closes: #3082
Reported-by: Stéphane Graber <stgraber@ubuntu.com>
> lxccontainer: properly cleanup on mount injection failure

- src/lxc/raw_syscalls.c
> pidf_send_signal: fix return value

- src/lxc/seccomp.c
> seccomp: coding style

- src/lxc/cgroups/cgroup.c
> cgroup: check for non-empty conf

- doc/ja/lxc.container.conf.sgml.in
> doc: Add lxc.comp.notify.cookie to Japanese lxc.container.conf(5)

- src/lxc/network.c
> network: restore ability to move nl80211 devices

- src/lxc/tools/lxc_create.c
Fix: #3123
Signed-off-by: qianfan Zhao <qianfanguijin@163.com>
> lxc-create: check absoule path for param '--dir'

- src/lxc/lxccontainer.c
- src/lxc/macro.h
To make the file/directory names, use the defines from macro.h
> Use file/directory names from macro.h

- src/lxc/cgroups/cgfsng.c
> cgroups: unify cgfsng_{un}freeze()

- .gitignore
- configure.ac
- doc/Makefile.am
- doc/pam_cgfs.sgml.in
#3035
Signed-off-by: Venkata Harshavardhan Reddy Allu <venkataharshavardhan_ven@srmuniv.edu.in>
> doc: add man page for pam_cgfs

- .gitignore
- configure.ac
- doc/ja/Makefile.am
- doc/ja/lxc.container.conf.sgml.in
- doc/ja/pam_cgfs.sgml.in
* Add pam_cfgs(8)
* Add the description of lxc.net.[i].veth.mode to Japanese lxc.container.conf(5)
* support --{enable,disable}-{commands,tools} in doc/ja
> Update Japanese man pages

- doc/ja/lxc.container.conf.sgml.in
> Update lxc.containers.conf(5) in Japanese

- src/lxc/terminal.c
- src/lxc/terminal.h
> terminal: bugfixes

- src/lxc/cgroups/cgfsng.c
> cgfsng: return attach fail if container stopped

- configure.ac
- src/lxc/Makefile.am
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/start.c
> cgroups: add cgroup2 device controller support

- configure.ac
- src/lxc/api_extensions.h
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/memory_utils.h
> cgroup2: add bpf device controller live update

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/freezer.c
- src/lxc/mainloop.c
- src/lxc/mainloop.h
> cgroups/freezer: rework cgroup2 freezer feature usage

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup_utils.c
- src/lxc/cgroups/cgroup_utils.h
- src/lxc/freezer.c
- src/lxc/log.h
- src/lxc/state.h
> freezer: cleanup

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/start.c
- src/lxc/start.h
> cgroup2: rework controller delegation

- src/lxc/af_unix.c
- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/commands.c
- src/lxc/compiler.h
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/log.h
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/network.c
- src/lxc/start.c
> cgroups, logging: fixes and improvements

- src/lxc/cgroups/cgfsng.c
> cgroups/devices: enable devpath semantics for cgroup2 device controller

- src/lxc/file_utils.c
> file_utils: use O_NOCTTY | O_NOFOLLOW

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/initutils.c
- src/lxc/lsm/apparmor.c
- src/lxc/start.c
- src/lxc/string_utils.c
- src/lxc/string_utils.h
- src/lxc/utils.h
- src/tests/cgpath.c
> cgroups: flatten hierarchy

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/file_utils.c
- src/lxc/utils.c
- src/lxc/utils.h
> cgroups/cgfsng: rework legacy cpuset handling

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
- src/lxc/file_utils.c
- src/lxc/memory_utils.h
> cgroupfs: improve cgroup removal

- src/lxc/api_extensions.h
> api_extensions: advertise cgroup2 support

- src/lxc/mainloop.c
Signed-off-by: dongxinhua <dongxinhua@huawei.com>
> fd: only add valid fd to mainloop

- .travis.yml
- configure.ac
- src/lxc/Makefile.am
- src/tests/travis.sh
> travis: enable -fsanitize=undefined

- src/lxc/start.c
- src/lxc/start.h
> start: remove procfs pidfd support

- src/lxc/mainloop.c
- src/lxc/start.c
- src/tests/api_reboot.c
> handle kernel version <--> header incompatibility

- src/tests/api_reboot.c
> test: increase timeout for api reboot tests

- configure.ac
https://github.com/lxc/lxc/pull/3223#issuecomment-578183093
Signed-off-by: Kirill Petrov <yakutskkirill@mail.ru>
> cgroups: fix default cgroup pattern

- src/lxc/network.c
Removes need for ip command when managing IP neighbour proxies.
> network: Uses netlink for IP neighbour proxy management

- src/lxc/cgroups/cgfsng.c
- src/lxc/commands.c
- src/lxc/commands_utils.c
- src/lxc/conf.c
- src/lxc/memory_utils.h
- src/lxc/pam/pam_cgfs.c
- src/lxc/utils.h
- src/tests/share_ns.c
> tree-wide: cleanup

- src/lxc/commands.c
> commands: make sure to always close the client fd

- src/lxc/commands.c
> commands: simplify lxc_cmd_fd_cleanup()

- doc/api-extensions.md
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/commands_utils.c
- src/lxc/lxccontainer.c
- src/lxc/lxccontainer.h
- src/lxc/raw_syscalls.h
- src/lxc/start.c
- src/lxc/utils.c
- src/lxc/utils.h
> pidfds: switch infrastructure to rely on pidfds whenever possible

- .travis.yml
> travis: enable all architectures

- src/lxc/af_unix.c
- src/lxc/attach.c
- src/lxc/caps.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/commands.c
- src/lxc/commands_utils.c
- src/lxc/conf.c
- src/lxc/file_utils.c
- src/lxc/freezer.c
- src/lxc/lxccontainer.c
- src/lxc/memory_utils.h
- src/lxc/rexec.c
- src/lxc/seccomp.c
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/utils.c
- src/lxc/uuid.c
> memory_utils: improvements

- src/lxc/conf.c
- src/lxc/criu.c
- src/lxc/execute.c
- src/lxc/lxc.h
- src/lxc/lxccontainer.c
- src/lxc/start.c
- src/lxc/start.h
> smaller cleanups and simplifications

- src/lxc/conf.c
> conf: flatten logic in mount_entry()

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/log.h
- src/lxc/macro.h
> tree-wide: logging fixes and hardening

- src/lxc/network.c
- src/lxc/nl.c
- src/lxc/nl.h
- src/lxc/rtnl.c
- src/lxc/rtnl.h
> network: fix ovs removal

- src/lxc/network.c
> network: use cleanup macros

- src/lxc/cmd/lxc_user_nic.c
- src/lxc/log.h
- src/lxc/nl.c
> network: fixes

- src/lxc/log.h
> log: add missing \

- src/lxc/log.c
- src/lxc/log.h
> log: fixes

- src/lxc/cgroups/cgfsng.c
- src/lxc/mainloop.c
- src/lxc/mainloop.h
- src/lxc/ringbuf.c
- src/lxc/ringbuf.h
> mainloop, ringbuf: cleanup

- src/lxc/log.h
> log: fix cmd logging

- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/list.h
- src/lxc/lxccontainer.c
- src/lxc/storage/btrfs.c
- src/lxc/storage/btrfs.h
- src/lxc/storage/dir.c
- src/lxc/storage/dir.h
- src/lxc/storage/loop.c
- src/lxc/storage/loop.h
- src/lxc/storage/lvm.c
- src/lxc/storage/lvm.h
- src/lxc/storage/nbd.c
- src/lxc/storage/nbd.h
- src/lxc/storage/overlay.c
- src/lxc/storage/overlay.h
- src/lxc/storage/rbd.c
- src/lxc/storage/rbd.h
- src/lxc/storage/storage.c
- src/lxc/storage/storage.h
- src/lxc/storage/storage_utils.h
- src/lxc/storage/zfs.c
- src/lxc/storage/zfs.h
- src/lxc/tools/lxc_copy.c
> overlay: rewrite

- src/lxc/cmd/lxc-update-config.in
- src/lxc/storage/lvm.c
- templates/lxc-local.in
> lxc-update-config: handle lxc.rootfs.backend correctly

- src/lxc/utils.c
> utils: allow removal of immutable files

- src/include/strlcat.c
- src/include/strlcat.h
- src/lxc/cmd/lxc_init.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/criu.c
- src/lxc/storage/btrfs.c
- src/lxc/storage/dir.c
- src/lxc/storage/overlay.c
- src/lxc/storage/storage_utils.c
- src/lxc/storage/zfs.c
- src/lxc/string_utils.h
> tree-wide: fixes

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/conf.c
- src/lxc/conf.h
> cgroups: fix attaching to the unified cgroup

- src/lxc/cgroups/cgfsng.c
- src/lxc/commands.c
- src/lxc/conf.c
> conf: rework and fix leak in userns_exec_1()

- src/lxc/cgroups/cgfsng.c
- src/lxc/conf.c
- src/lxc/conf.h
> attach: fixes

- src/lxc/cgroups/cgfsng.c
- src/lxc/conf.c
> conf: simplify userns_exec_minimal()

- src/lxc/cgroups/cgfsng.c
> cgroups: please compilers

- src/lxc/commands.c
validate that a cgroup controller name is a valid
zero-terminated string before passing it to
`cgroup_ops->get_cgroup()`.
> verify cgroup controller name

- src/lxc/lsm/apparmor.c
and update to changes based on lxd
> apparmor: generate ro,bind,remount rule list

- config/init/systemd/lxc-monitord.service.in
- config/init/systemd/lxc-net.service.in
> systemd: Add Documentation key

- src/lxc/attach.c
- src/lxc/start.c
- src/lxc/utils.c
- src/lxc/utils.h
Signed-off-by: gaohuatao <gaohuatao@huawei.com>
> fix non-root user cannot write /dev/stdout

- doc/api-extensions.md
- src/lxc/api_extensions.h
> api-extensions: add and document cgroup_advanced_isolation

- doc/ja/lxc.container.conf.sgml.in
> doc: Add lxc.cgroup.dir.{monitor,container,container.inner} to Japanese man

- src/lxc/cgroups/cgfsng.c
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/seccomp.c
> lxc_user_nic: fixes

- src/lxc/network.c
> src/lxc/network: ipvlan comment and code style tweak

- src/lxc/cmd/lxc-update-config.in
> lxc-update-config: Fix bad handling of lxc.logfile

- src/tests/lxc-test-no-new-privs
> tests/no-new-privs: Don't mess with /etc/lxc

- src/lxc/cgroups/cgfsng.c
> cgroups: adhere to boolean return

- .travis.yml
> travis: add back coverity

- src/lxc/log.h
> log: set GNU_SOURCE as it might help coverity along

- .travis.yml
- configure.ac
- src/lxc/log.h
> travis: coverity gets confused about the %m printf extension in glibc

- config/apparmor/abstractions/start-container.in
> apparmor: Allow boot_id

- config/templates/common.conf.in
- config/templates/userns.conf.in
- src/lxc/cgroups/cgfsng.c
Fixes: #3183
Cc: Thomas Moschny <thomas.moschny@gmx.de>
> cgroup: fixes

- configure.ac
- src/lxc/af_unix.h
- src/lxc/compiler.h
- src/lxc/conf.h
- src/lxc/confile.h
- src/lxc/confile_utils.h
- src/lxc/file_utils.h
> compiler: more hardening

- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/confile_utils.h
- src/lxc/tools/lxc_ls.c
> network: fix key ordering independence

- src/lxc/criu.c
- src/lxc/log.c
- src/lxc/log.h
- src/lxc/lxccontainer.c
- src/lxc/start.c
- src/lxc/start.h
> reboot fixes

- src/lxc/conf.c
otherwise weird things might happen.
> console: only create detached mount when a console is requested

- src/lxc/network.c
I introduced a regression: when users didn't specify a specific name via
lxc.net.<idx>.name then the device would retain the random name it received
when we created it. Before we would use the "eth%d" syntax to get the kernel to
assign a fixed name. Restore that behavior.
Closes: #3407.
Fixes: 8bf64b77ac8a ("network: rework network device creation")
> network: restore old behavior

- src/include/fexecve.c
> bionic: s/lxc_raw_execveat()/execveat()/g

- src/lxc/cmd/lxc_usernsexec.c
> lxc-usernsexec: improvements

- .gitignore
> .gitignore: Ignores COPYING file created by make

- doc/lxc.container.conf.sgml.in
- src/lxc/api_extensions.h
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/macro.h
- src/lxc/network.c
- src/lxc/network.h
- src/tests/parse_config_file.c
Includes https://github.com/lxc/lxc/pull/3435
Adds openvswitch VLAN support.
> NIC: Veth OVS bridge VLAN support

- src/lxc/nl.c
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Fix memory leak: Free nlmsg before returning
> nl: fix memory leak

- CODING_STYLE.md
- doc/ja/lxc.container.conf.sgml.in
- doc/lxc.container.conf.sgml.in
- src/include/openpty.c
- src/include/openpty.h
- src/tests/console.c
> tree-wide: variable naming update

- config/init/common/lxc-net.in
> lxc-net: Set broadcast

- doc/api-extensions.md
- doc/lxc.container.conf.sgml.in
- src/lxc/api_extensions.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/namespace.c
- src/lxc/namespace.h
- src/lxc/start.c
- src/lxc/string_utils.c
- src/lxc/string_utils.h
> time namespace support

- doc/ja/lxc.container.conf.sgml.in
- doc/lxc.container.conf.sgml.in
* descriptions of vlan bridge options
* lxc.time.offset.{boot,monotonic}
> Update Japanese lxc.container.conf(5)

- src/lxc/confile.c
- src/lxc/start.c
- src/lxc/utils.c
- src/lxc/utils.h
> confile: handle overflow in lxc.time.offset.{boot,monotonic}

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/process_utils.c
- src/lxc/process_utils.h
- src/lxc/start.c
- src/lxc/start.h
> lxc: support CLONE_INTO_CGROUP

- src/lxc/start.c
- src/lxc/start.h
> clone_into_cgroup: fixes

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
> cgroups: fix bpf device program generation

- src/lxc/cgroups/cgroup2_devices.c
Link: https://launchpadlibrarian.net/487274879/buildlog_ubuntu-eoan-amd64.lxc_1:4.0.3+master~20200705-1541-0ubuntu1~eoan_BUILDING.txt.gz
> cgroups: handle empty bpf log buffer

- doc/ja/lxc.container.conf.sgml.in
- doc/ko/lxc.container.conf.sgml.in
- doc/lxc.container.conf.sgml.in
- src/include/openpty.c
- src/include/openpty.h
- src/lxc/attach.c
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/conf.c
- src/lxc/criu.c
- src/lxc/lxccontainer.c
- src/lxc/lxccontainer.h
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/terminal.h
- src/tests/console.c
> tree-wide: update terminal terminology once more

- configure.ac
- src/include/openpty.c
- src/include/openpty.h
- src/lxc/Makefile.am
- src/lxc/conf.c
- src/lxc/terminal.c
> openpty: improve implementation and handling of platforms without it

- COPYING
Closes: #3484.
Suggested-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> autotools: include COPYING file

- src/lxc/Makefile.am
- src/lxc/af_unix.h
- src/lxc/attach.h
- src/lxc/caps.h
- src/lxc/cmd/lxc_user_nic.c
- src/lxc/commands.h
- src/lxc/commands_utils.h
- src/lxc/compiler.h
- src/lxc/conf.h
- src/lxc/error.c
- src/lxc/file_utils.c
- src/lxc/initutils.c
- src/lxc/network.c
- src/lxc/nl.c
- src/lxc/nl.h
- src/lxc/rtnl.c
- src/lxc/rtnl.h
- src/lxc/string_utils.h
- src/tests/Makefile.am
> hide unnecessary symbols I

- src/lxc/Makefile.am
- src/lxc/tools/lxc_ls.c
> lxc-ls: bugfixes

- configure.ac
- src/lxc/Makefile.am
- src/lxc/attach.c
- src/lxc/conf.c
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/syscall_numbers.h
- src/lxc/syscall_wrappers.h
> new mount api support: basics

- configure.ac
- src/lxc/Makefile.am
- src/lxc/attach.c
- src/lxc/conf.c
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/syscall_numbers.h
- src/lxc/syscall_wrappers.h
> autotools: fix Makefile

- src/lxc/lsm/selinux.c
Link: https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1888705
> selinux: remove security_context_t usage as it's deprecated

- src/lxc/conf.c
> conf: ensure that the idmap pointer itself is freed

- doc/api-extensions.md
- src/lxc/api_extensions.h
- src/lxc/attach.c
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/lxccontainer.c
- src/lxc/lxccontainer.h
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/terminal.h
This was a year long journey which seems to finally have come to an end.
Closes: #1620.
> terminal: safely allocate pts devices from inside the container

- src/lxc/conf.c
- src/lxc/macro.h
> macro: define TIOCGPTPEER if missing

- configure.ac
- src/lxc/cgroups/cgfsng.c
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/syscall_numbers.h
- src/lxc/syscall_wrappers.h
- src/lxc/utils.c
- src/lxc/utils.h
> openat2() and safe mounting

- src/lxc/attach.c
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/terminal.h
> conf: terminal and /dev hardening

- src/lxc/attach.c
- src/lxc/attach.h
- src/lxc/conf.c
- src/lxc/lsm/apparmor.c
- src/lxc/lsm/lsm.c
- src/lxc/lsm/lsm.h
- src/lxc/lsm/nop.c
- src/lxc/lsm/selinux.c
- src/lxc/start.c
- src/lxc/start.h
- src/lxc/utils.c
- src/lxc/utils.h
- src/tests/attach.c
> lsm: rewrite

- src/lxc/attach.c
- src/lxc/attach.h
- src/lxc/conf.c
- src/lxc/lsm/apparmor.c
- src/lxc/lsm/lsm.c
- src/lxc/lsm/lsm.h
- src/lxc/lsm/nop.c
- src/lxc/lsm/selinux.c
- src/lxc/start.c
- src/lxc/start.h
- src/tests/attach.c
> lsm: remove the need for atomic operations

- doc/pam_cgfs.sgml.in
Signed-off-by: Arjun Ramachandrula <arjun.ramachandrula@gmail.com>
> Updated documentation to reflect lack of support for pure cgroupv2

- src/lxc/conf.c
Signed-off-by: wujing <Jing.Woo@outlook.com>
> remove useless parameters

- src/lxc/seccomp.c
> seccomp: bugfixes

- src/lxc/seccomp.c
Link: https://launchpadlibrarian.net/502200189/buildlog_snap_ubuntu_bionic_ppc64el_lxd-latest-edge_BUILDING.txt.gz
> seccomp: fix compilation on powerpc

- src/lxc/conf.c
- src/lxc/start.c
- src/lxc/sync.c
- src/lxc/sync.h
> startup fixes

- src/lxc/conf.c
> conf: account for early return when sending devpts fd

- doc/ja/pam_cgfs.sgml.in
Update for commit b87ed83bbc7db3f826b4f54df1bb458c2c539be7
> Update Japanese pam_cgfs(8) to reflect lack of support for pure cgroupv2

- src/lxc/seccomp.c
Hello lxc team, 
I've added a few more fixes for the seccomp code. 
Please have a look at the logging output below.
I've added logging output for the current master without the changes (`before`) 
and for the current master including the changes  (`after`).
I've also changed the loglevel from WARN to INFO if a syscall is undefined because this will flood the log 
in production with a lot of ephemeral containers (`crio-lxc`). E.g If kubernetes/cri-o  add a default seccomp profile
for kernel 5.n+1 but you're running kernel 5.n, there will likely be new syscalls that are undefined and flood logging.
before
```
lxc 20201027075832.580 INFO     seccomp - seccomp.c:parse_config_v2:795 - Processing "foobar allow"
lxc 20201027075832.580 WARN     seccomp - seccomp.c:do_resolve_add_rule:523 - Failed …
```
> seccomp: fix pseudo syscalls, improve logging and avoid duplicate processing

- src/lxc/attach.c
- src/lxc/attach_options.h
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/utils.c
> coverity fixes

- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/seccomp.c
Suggested-by: Jann Horn <jann@thejh.net>
> seccomp: fixes

- src/lxc/attach.c
- src/lxc/utils.c
> attach: silence stdio permission adjust warnings

- src/lxc/conf.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/parse.c
> conf: improve mountinfo and config parsing

- doc/ja/lxc.container.conf.sgml.in
> doc: Add lxc.cgroup.dir.monitor.pivot to Japanese man page

- src/include/netns_ifaddrs.h
- src/lxc/confile.c
- src/lxc/lxccontainer.c
- src/lxc/utils.c
> tree-wide: fixes and cleanups

- templates/lxc-download.in
Signed-off-by: Andrew Deng <adeng1433@gmail.com>
Fixes #1507
> new standard resolver option in ldc-download.in shell script

- src/lxc/confile.c
> confile: don't accidently alter lxc.cgroup.dir

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/lsm/apparmor.c
- src/lxc/tools/lxc_attach.c
- src/lxc/utils.c
> conf: fix containers retaining CAP_NET_ADMIN

- configure.ac
- src/lxc/Makefile.am
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/initutils.h
> build: allow to build all binaries statically via --enable-static-binaries

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/criu.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/string_utils.h
> cgroups: fixes and cgroup2 improvements

- configure.ac
- src/lxc/attach.c
- src/lxc/attach.h
- src/lxc/attach_options.h
- src/lxc/confile.c
- src/lxc/confile.h
- src/lxc/lsm/lsm.c
- src/lxc/lsm/lsm.h
- src/lxc/macro.h
- src/lxc/namespace.c
- src/lxc/namespace.h
- src/lxc/start.c
- src/lxc/sync.c
- src/lxc/sync.h
- src/tests/attach.c
> attach: improve attach codepaths

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/log.c
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/seccomp.c
> cgroups: fixes and improvements

- src/lxc/attach.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/utils.c
- src/lxc/utils.h
> attach: rework id handling

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup_utils.c
- src/lxc/cgroups/cgroup_utils.h
- src/lxc/file_utils.c
- src/lxc/memory_utils.h
- src/lxc/syscall_wrappers.h
> attach & cgroup hardening

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
- src/lxc/commands_utils.c
- src/lxc/commands_utils.h
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/freezer.c
- src/lxc/lxc.h
- src/lxc/lxccontainer.c
- src/lxc/lxcseccomp.h
- src/lxc/macro.h
- src/lxc/seccomp.c
- src/tests/Makefile.am
- src/tests/cgpath.c
- src/tests/device_add_remove.c
> cgroup2: only rely on command socket when getting cgroup values

- src/lxc/attach.c
This is a feature we've enabled in kernel v5.8 and v5.9.
> attach: attach to namespaces via pidfds

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/string_utils.h
- src/lxc/syscall_wrappers.h
- src/lxc/utils.c
- src/lxc/utils.h
> cgroups: fix cgroup mounting

- src/lxc/attach.c
- src/lxc/utils.c
> Tiny fixes in attach and utils

- src/lxc/attach.c
- src/lxc/attach_options.h
- src/lxc/cgroups/cgfsng.c
- src/lxc/cmd/lxc_usernsexec.c
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/lxccontainer.c
- src/lxc/start.c
- src/lxc/storage/btrfs.c
- src/lxc/storage/rsync.c
- src/lxc/storage/storage_utils.c
- src/lxc/utils.c
- src/lxc/utils.h
- src/tests/Makefile.am
- src/tests/get_item.c
> conf: implement lxc.init.groups

- src/lxc/attach.c
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
> mount_utils: initialize fd

- configure.ac
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/start.c
- src/lxc/start.h
- src/lxc/storage/dir.c
- src/tests/lxc-test-unpriv
> conf: expand fd-only setup codepaths

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/conf.c
- src/lxc/criu.c
- src/lxc/macro.h
- src/lxc/memory_utils.h
> criu: fixes

- src/lxc/cgroups/cgfsng.c
> cgroups: fixes

- src/lxc/cgroups/cgfsng.c
- src/lxc/conf.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/macro.h
- src/lxc/memory_utils.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/string_utils.h
> Improved mount api support checking & console setup hardening

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup_utils.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/criu.c
- src/lxc/file_utils.c
- src/lxc/freezer.c
- src/lxc/initutils.c
- src/lxc/log.c
- src/lxc/lsm/apparmor.c
- src/lxc/lsm/selinux.c
- src/lxc/lxccontainer.c
- src/lxc/namespace.c
- src/lxc/network.c
- src/lxc/seccomp.c
- src/lxc/start.c
- src/lxc/state.c
- src/lxc/string_utils.c
- src/lxc/terminal.c
- src/lxc/utils.c
> tree-wide: convert to strequal() and strnequal()

- src/lxc/macro.h
- src/lxc/namespace.h
- src/lxc/network.c
- src/lxc/start.c
- src/lxc/start.h
> hooks: rework exposing namespace information

- src/lxc/start.c
> start: small fixes

- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/log.h
- src/lxc/string_utils.h
> cgroups: tighten cgroup config items

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup_utils.c
- src/lxc/cgroups/cgroup_utils.h
- src/lxc/file_utils.c
- src/lxc/file_utils.h
> cgroups: fd-only cgroup tree pruning

- src/lxc/cgroups/cgfsng.c
- src/lxc/start.c
> cgroups: rework unified cgroup controller delegation

- src/lxc/cgroups/cgfsng.c
> cgroups: third batch of cgroup fixes

- src/lxc/cgroups/cgfsng.c
- src/lxc/conf.c
> cgroups: fourth batch of cgroup fixes

- src/lxc/conf.c
- src/lxc/start.c
> console: fixes

- configure.ac
- src/include/bpf.h
- src/include/bpf_common.h
- src/lxc/Makefile.am
- src/lxc/api_extensions.h
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.c
- src/lxc/cgroups/cgroup.h
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/commands.c
- src/lxc/compiler.h
- src/lxc/conf.h
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/memory_utils.h
- src/lxc/utils.c
> cgroups: fixes & bpf rework

- doc/lxc.container.conf.sgml.in
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/conf.h
> bpf: device cgroup improvements

- src/lxc/attach.c
- src/lxc/commands.c
- src/lxc/sync.h
- src/lxc/terminal.c
> attach: improve attaching of new clients to old servers

- src/lxc/af_unix.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/commands.c
> Fix issues reported by Coverity

- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/commands.h
> build fix & cgroup braino

- src/lxc/Makefile.am
- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/criu.c
- src/lxc/error_utils.h
- src/lxc/file_utils.c
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/memory_utils.h
- src/lxc/terminal.c
> commands: rework and add LXC_CMD_GET_CGROUP_FD and LXC_CMD_GET_LIMIT_CGROUP_FD

- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/compiler.h
> commands: array hardening

- src/lxc/af_unix.c
- src/lxc/af_unix.h
- src/lxc/commands.c
- src/lxc/commands.h
- src/lxc/log.h
- src/lxc/macro.h
- src/lxc/start.c
- src/tests/lxc-test-lxc-attach
- src/tests/lxc-test-unpriv
> commands: improvements and fixes

- src/lxc/af_unix.c
- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/log.h
> tree-wide: some more logging fixes

- src/lxc/confile_utils.c
- src/lxc/network.c
- src/lxc/network.h
Fixes: #3696
Reported-by: Sam Boyles <sam.boyles@alliedtelesis.co.nz>
Reported-by: Blair Steven <blair.steven@alliedtelesis.co.nz>
> network: fix networks with switched names

- src/lxc/af_unix.c
- src/lxc/start.c
> small fixes

- src/lxc/start.c
Reported-by: Ondrej Kubik <ondrej.kubik@canonical.com>
Cc: stable-4.0
> start: handle CLONE_PIDFD on arm64

- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/start.c
> conf: automount fixes

- src/lxc/cgroups/cgfsng.c
Someone might have created a name=<controller> controller after the
container has started and so the container doesn't make use of this
controller.
Link: https://github.com/lxc/lxd/issues/8577
> cgroups: ignore unused controllers

- .github/workflows/coverity.yml
> github: Fix invalid syntax for coverity

- configure.ac
- src/lxc/Makefile.am
> configure: fix strchrnul conditiona compilation

- src/include/strchrnul.c
> strchrnul: fix copy-paste braino

- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/list.h
> oss-fuzz: fixes

- src/lxc/confile.c
- src/lxc/log.c
- src/tests/parse_config_file.c
Fixes: #3730
Fixes: https://github.com/google/oss-fuzz/issues/5509
> log: dont create log file for fuzz builds

- README.md
- src/tests/fuzz-lxc-config-read.c
- src/tests/oss-fuzz.sh
* fuzz: generate all the config keys and add them to the seed corpus
* README: add OSS-Fuzz/CIFuzz badges
* fuzz: create tmpfiles in /tmp
> oss-fuzz: a few follow-up commits

- src/lxc/confile_utils.c
- src/lxc/criu.c
- src/lxc/storage/overlay.c
- src/lxc/string_utils.c
- src/lxc/string_utils.h
- src/tests/lxc-test-utils.c
Link: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32689
> string_utils: switch to path_simplify()

- src/lxc/cmd/lxc_user_nic.c
- src/lxc/confile.c
- src/lxc/confile.h
- src/lxc/string_utils.c
- src/lxc/string_utils.h
- src/lxc/tools/lxc_copy.c
> fixes: Makefile, lxc-user-nic, simplify get_network_config_ops()

- src/lxc/confile.c
Link: https://github.com/lxc/lxc/pull/3763/files#r606089660
> confile: fix lxc.namespace.share.[identifier]

- src/lxc/confile.c
> lsm: fixes

- src/lxc/confile.c
- src/lxc/log.h
- src/lxc/macro.h
> confile & log: fixes

- .github/workflows/build.yml
- .github/workflows/cifuzz.yml
- .github/workflows/coverity.yml
- .github/workflows/static-analysis.yml
> github: Try to fix action naming

- src/lxc/conf.c
> conf: idmaptool fixes

- src/tests/attach.c
> tests: fix a memory leak in attach

- src/lxc/lxccontainer.c
> lxccontainer: fix container creation error paths

- src/tests/share_ns.c
Closes https://github.com/lxc/lxc/issues/3791
> tests: stop cutting off right square brackets in share_ns

- src/tests/lxc-test-apparmor-mount
- src/tests/lxc-test-unpriv
- src/tests/lxc-test-usernic.in
- src/tests/lxc-test-usernsexec
to make it easier to run them under ASan/UBSan.
> tests: pass on ASAN/UBSAN options to several tests

- configure.ac
- src/lxc/commands.c
- src/lxc/error_utils.h
- src/lxc/process_utils.c
> lxc_clone & configure fix

- .github/workflows/sanitizers.sh
- src/tests/console_log.c
This reverts commit 44818e893e68e6e76652323ff4f12c9214d2ffa7.
> Revert "ci: get around https://github.com/lxc/lxc/issues/3796"

- src/include/strchrnul.c
- src/lxc/Makefile.am
- src/lxc/conf.c
- src/lxc/tools/include/getsubopt.c
- src/tests/Makefile.am
> include fixes for Bionic

- src/lxc/conf.c
> mntopt fixes

- configure.ac
> configure: fix function detection

- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/criu.c
- src/lxc/lxccontainer.c
- src/lxc/mount_utils.c
- src/lxc/start.c
- src/lxc/storage/dir.c
- src/lxc/storage/rsync.c
- src/lxc/storage/storage.c
> rootfs rework

- src/lxc/storage/dir.c
> storage/dir: cleanup mount code

- doc/api-extensions.md
- src/lxc/api_extensions.h
> api-extensions: add entry for idmapped_mounts

- .github/workflows/sanitizers.sh
> github: Run apt-get update in sanitizer test

- src/lxc/conf.c
Small fix to log messages to make them match the updated code (from 1dd71c90e807).
> conf: fix console chmod error log messages

- src/lxc/attach.c
- src/lxc/attach_options.h
- src/lxc/commands.c
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/confile.h
- src/lxc/macro.h
- src/lxc/syscall_numbers.h
- src/lxc/syscall_wrappers.h
- src/lxc/tools/lxc_attach.c
> lxc.arch fixes

- src/lxc/conf.c
> conf: fix containers without rootfs

- README.md
> README: Update IRC

- lxc.pc.in
Fixes: #3853
Suggested-by: Tycho Andersen <tycho@tycho.pizza>
> lxc: add lpthread to lxc.pc

- src/lxc/tools/lxc_autostart.c
Don't include skipped containers in the failed count.
Fixes: #3857
> tools/lxc_autostart: fix failed count

- config/templates/common.conf.in
- doc/examples/lxc-complex.conf.in
- doc/ja/lxc-user-nic.sgml.in
- doc/ja/lxc.container.conf.sgml.in
- doc/ko/lxc-user-nic.sgml.in
- doc/ko/lxc.container.conf.sgml.in
- doc/ko/lxc.sgml.in
- doc/lxc-user-nic.sgml.in
- doc/lxc.container.conf.sgml.in
- src/lxc/attach.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/conf.c
- src/lxc/ringbuf.c
- src/lxc/seccomp.c
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/tools/lxc_ls.c
- src/tests/api_reboot.c
- src/tests/lxc-test-unpriv
> remove problematic terminology

- templates/lxc-download.in
> lxc-download: Switch GPG server

- .gitignore
- src/lxc/conf.c
- src/tests/Makefile.am
- src/tests/sys_mixed.c
> Improve read-only /sys with read-write /sys/devices/virtual/net

- src/lxc/tools/lxc_unshare.c
> lxc-unshare: fixes

- doc/common_options.sgml.in
> doc/common_options: add trace and alert loglevels

- src/lxc/start.c
- src/lxc/sync.c
Fixes: #3875
Suggested-by: Hank.shi <shk242673@163.com>
> grammar fixes

- src/lxc/terminal.c
Fixes: f382bcc6d820 ("terminal: log TIOCGPTPEER failure less alarmingly")
> terminal: fix error handling

- src/lxc/cgroups/cgfsng.c
The commits apply cleanly to stable-4.0 and master.
Will gladly open another pull-request for stable-4.0 if needed.
> Fix legacy cgroup devices

- src/lxc/conf.c
If a device file is opened and there isn't the underlying device,
the open call fails with ENXIO, but the path can be opened with
O_PATH, which is enough for mounting over the device file.
Generalize this idea and use O_PATH for all cases when the file
is there. One still must check for both ENXIO and EEXIST as it's
unspecified what error is reported if multiple error conditions
occur at the same time.
> lxc_setup_ttys: Handle existing ttyN file without underlying device

- src/lxc/conf.c
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/string_utils.h
- src/lxc/terminal.c
> conf: devpts rework

- src/lxc/conf.c
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/terminal.c
> devpts: move setup before pivot root

- src/lxc/conf.c
- src/lxc/terminal.c
- src/lxc/terminal.h
> conf: move remaining setup before pivot root

- src/lxc/conf.c
- src/lxc/file_utils.c
- src/lxc/file_utils.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/start.c
- src/lxc/terminal.c
- src/lxc/terminal.h
> conf: rework console setup

- src/lxc/conf.c
- src/lxc/syscall_wrappers.h
- src/lxc/terminal.c
- src/lxc/terminal.h
> terminal: handle kernel without TIOCGPTPEER

- src/lxc/conf.c
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
> mount_utils: introduce mount_at()

- .gitignore
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/storage/dir.c
- src/tests/Makefile.am
- src/tests/rootfs_options.c
> conf: rootfs mount option fixes

- src/lxc/confile.c
- src/lxc/network.c
> network: fix container with empty network namespaces

- src/lxc/lsm/apparmor.c
> lsm/apparmor: small fixes

- doc/api-extensions.md
> doc/api-extensions: Grammar fix

- src/lxc/mainloop.c
> mainloop: io_uring cleanup handling fixes

- src/lxc/mainloop.c
- src/lxc/mainloop.h
> mainloop: further io_uring fixes

- src/lxc/cgroups/cgfsng.c
> cgroups: cpumask fixes

- src/lxc/cgroups/cgfsng.c
> cgroups: simplify offline and isolated cpumask handling

- src/lxc/af_unix.c
- src/lxc/confile.c
> confile: return negative errno everywhere

- src/lxc/attach.c
- src/lxc/attach_options.h
- src/lxc/confile.c
- src/lxc/confile.h
- src/lxc/tools/lxc_attach.c
Signed-off-by: Maximilian Blenk <Maximilian.Blenk@bmw.de>
> tools: lxc-attach fixes

- src/lxc/Makefile.am
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.c
- src/lxc/commands.c
- src/lxc/commands_utils.c
- src/lxc/compiler.h
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/confile_utils.h
- src/lxc/criu.c
- src/lxc/hlist.h
- src/lxc/macro.h
- src/lxc/mainloop.c
- src/lxc/mainloop.h
- src/lxc/network.c
- src/lxc/network.h
- src/lxc/start.c
> tree-wide: introduce new list type and port network handling to it

- src/lxc/tools/lxc_attach.c
I think this one is still required ;-)
Orignal PR: https://github.com/lxc/lxc/pull/3946
> attach: Fix -c option v2 :-D

- src/lxc/Makefile.am
- src/lxc/cmd/lxc_usernsexec.c
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/confile.c
- src/lxc/criu.c
- src/lxc/hlist.h
- src/lxc/lsm/apparmor.c
- src/lxc/lxccontainer.c
> conf: port more types to new list type

- configure.ac
> configure: add sanitizer flags to LDFLAGS as well

- src/include/fexecve.h
- src/include/getgrgid_r.h
- src/include/getline.h
- src/include/lxcmntent.h
- src/include/netns_ifaddrs.h
- src/include/openpty.h
- src/include/prlimit.h
- src/include/strchrnul.h
- src/include/strlcat.h
- src/include/strlcpy.h
- src/lxc/Makefile.am
- src/lxc/cgroups/cgfsng.c
- src/lxc/string_utils.h
- src/lxc/tools/lxc_destroy.c
- src/tests/Makefile.am
> tree-wide: build fixes

- configure.ac
- src/lxc/log.h
> log: fix cross-compilation with %m modifier

- src/tests/parse_config_file.c
Link: https://bugs.launchpad.net/bugs/1943441
> tests: fix config file tests

- src/lxc/tools/lxc_copy.c
> tools: use correct include for Android

- hooks/unmount-namespace.c
- meson.build
- src/include/meson.build
- src/include/strlcat.c
- src/lxc/af_unix.c
- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup2_devices.h
- src/lxc/conf.c
- src/lxc/confile.c
- src/lxc/confile_utils.c
- src/lxc/criu.c
- src/lxc/log.c
- src/lxc/lxccontainer.c
- src/lxc/macro.h
- src/lxc/process_utils.h
- src/lxc/start.c
- src/lxc/string_utils.c
- src/lxc/string_utils.h
- src/lxc/syscall_wrappers.h
- src/lxc/tools/include/meson.build
- src/lxc/tools/meson.build
- src/lxc/utils.c
- src/lxc/utils.h
> build: improve meson build

- .github/workflows/build.yml
> github: Drop 16.04 tests

- meson.build
- src/lxc/compiler.h
> build: compiler attribute improvements

- src/lxc/start.c
- src/lxc/syscall_wrappers.h
> lxc: core scheduling tweaks

- meson.build
- src/lxc/mainloop.c
> build: fixes

- .gitignore
- meson.build
- src/lxc/conf.c
- src/tests/Makefile.am
- src/tests/capabilities.c
- src/tests/lxctest.h
- src/tests/proc_pid.c
- src/tests/sysctls.c
> conf: lxc.proc.* and lxc.sysctl.* fixes and tests

- src/lxc/macro.h
- src/lxc/mainloop.c
> macro: ensure necessary io_uring flags are defined

- src/lxc/af_unix.c
> (trivial) Fix error message, failure was connect not bind

- README.md
Signed-off-by: Devin Norgarb dnorgarb@gmail.com
> Update README.md: Fix broken link (403 Forbidden)

- src/lxc/cgroups/cgfsng.c
- src/lxc/cgroups/cgroup.h
- src/lxc/commands.c
> cgroups: improvements

- doc/lxc.container.conf.sgml.in
- src/lxc/cmd/lxc-checkconfig.in
> lxc-checkconfig: Fix bashism

- doc/ja/lxc.container.conf.sgml.in
Update for commit 2965130c45124a01f017144512c39fc39fa8717c
> doc: Fix reverse allowlist/denylist in Japanese man page

- meson.build
- meson_options.txt
- src/lxc/pam/meson.build
- src/lxc/pam/pam_cgfs.c
> build: add pam_cgfs to meson

- .github/workflows/cifuzz.yml
- meson.build
- meson_options.txt
- src/lxc/meson.build
- src/tests/meson.build
- src/tests/oss-fuzz.sh
> tests: fix oss-fuzz port to meson

- meson.build
> meson: Fix bad strerror_r check

- src/lxc/conf.c
- src/lxc/start.c
> conf: startup fixes

- src/lxc/start.c
> start: fix namespace sharing

- src/lxc/cmd/lxc_usernsexec.c
> lxc-usernsexec: allow to select which {g,u}id to switch to

- meson.build
- src/lxc/conf.c
- src/lxc/conf.h
- src/lxc/mount_utils.c
- src/lxc/mount_utils.h
- src/lxc/process_utils.h
- src/lxc/syscall_wrappers.h
> build: fixes for glibc 2.36

- src/tests/reboot.c
Add the prototype for `__clone2(...)` that is used on ia64, and adjust the code to use it via macro tests.
Verified that the code compiles properly on Debian's ia64 porterbox (yttrium), but was unable to actually run as `lxc-test-reboot` requires root privileges.
> tests: lxc-test-reboot: Fix build on ia64

- meson.build
Fixes issue #4223
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
> meson.build: strip newlines from git output

- src/lxc/cgroups/cgfsng.c
> cgroups: fix cgroup removal 

- src/lxc/cmd/lxc_user_nic.c
lxc-user-nic in lxc through 5.0.1 is installed setuid root, and may allow local users to infer whether any file exists, even within a protected directory tree, because "Failed to open" often indicates that a file does not exist, whereas "does not refer to a network namespace path" often indicates that a file exists. NOTE: this is different from CVE-2018-6556 because the CVE-2018-6556 fix design was based on the premise that "we will report back to the user that the open() failed but the user has no way of knowing why it failed"; however, in many realistic cases, there are no plausible reasons for failing except that the file does not exist.
PoC:
> % ls /l
> ls: cannot open directory '/l': Permission denied
> % /usr/lib/x86_64-linux-gnu/lxc/lxc-user-nic delete lol lol /l/h/tt h h
> …
> Patching an incoming CVE (CVE-2022-47952)

- src/lxc/conf.h
Signed-off-by: Ariel Miculas <amiculas@cisco.com>
> Fix typo: bev_type -> bdev_type

- src/lxc/initutils.c
Prior to the changes introduced in #4299 (on my suggestion), LXC's `setproctitle()` handled possible NULL returns from `strchr()` calls it made on contents of `/proc/self/stat`. With these changes, it does not handle a possible NULL return from the newly added `strrchr()`. This PR fixes that. CC: @tych0 
I've only tested this out-of-tree using the below program. Please also test in-tree.
```c
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>
#include <unistd.h>
#include <sys/prctl.h>
#include <sys/syscall.h>
#include "lxc/src/include/strlcpy.c"
#define __do_fclose /* nothing */
#define fopen_cloexec fopen
#define lxc_read_nointr read
#define LXC_LINELEN 4096
#define prctl_arg(x) ((unsigned long)x)
/* setproctitle() body inserted here */
int main(void)
{ …
```
> setproctitle(): Handle potential NULL return from strrchr()

- src/lxc/lxccontainer.c
If a user of the container.start api call provided NULL for the argv argument, then lxc would load either 'lxc.execute.cmd' or 'lxc.init.cmd' configuration items as the command.
Given a config like:
lxc.execute.cmd = /usr/bin/touch "file one" "file 2"
lxc would just split the string on spaces and end up executing array:
['touch', 'file"', 'one"', '"file', '2"']
This differs from the experience with the `lxc-start` command which would use lxc_string_split_quoted and execute:
['touch', 'file one', 'file 2']
Note that as described in lxc_string_split_quoted, commands that include nested quotes and possibly other characters are still a problem.  In those cases, the caller of 'start' can provide an argv array.
> Fix start api call to split quoted strings in execute or init command.

- src/lxc/cmd/lxc-checkconfig.in
Other minor/cosmetic tweaks while at it.
> Make `lxc-checkconfig` shellcheck clean

- src/lxc/network.c
When creating a bridged veth tunnel, disable assignment of IPv6
link-local addresses on the host's end by writing 1 to
/proc/sys/net/ipv6/conf/NAME/disable_ipv6, if it exists.
Closes #1414 
Signed-off-by: Cole Miller <m@cole-miller.net>
> Disable IPv6 link-local addresses for bridged veth

- src/lxc/start.c
Signed-off-by: dongxinhua <dongxinhua@huawei.com>
> config: try to create workdir if not exist

- src/lxc/rexec.c
Commit "rexec: free argv array on failure" used __do_free_string_list as a destructor for argv, which is an array of pointers to a single buffer and not an array of pointers to independent buffers, which leads to an attempt to free invalid pointer whenever argv has more than one element.
Structure argv as one memory block and use __do_free as the destructor.
> rexec: Avoid invalid free in rexec failure path

- src/lxc/lxccontainer.c
> lxccontainer: fixes

- src/lxc/lxccontainer.c
> Rework "lxccontainer: fixes" PR

- src/lxc/confile.c
- src/lxc/utils.c
- src/lxc/utils.h
- src/tests/parse_config_file.c
Replacement PR for https://github.com/lxc/lxc/pull/4374
> confile_utils: fix incorrect multiply_overflow test #2

- src/lxc/network.c
> Don't fail veth creation if ipv6 is disabled

- src/lxc/tools/meson.build
See also:
https://github.com/lxc/lxc/pull/4428
Fixes: #4427
> meson: fix build with -Dtools-multicall=true on NixOS

- meson.build
Hi team, This PR is to fix issue #4492 . It simply corrects a typo.
> meson: fix minor typo

- src/lxc/attach.c
problem described in the issue 169, https://github.com/lxc/lxc/issues/4507
lxc-attach hangs if there are active sbprocesses.
this changes should fix it.
> - LXC attach should exit on SIGCHLD

- src/lxc/cgroups/cgfsng.c
Fixes: https://github.com/lxc/lxc/issues/4508
> dbus: replace hardcoded dbus address with environment variable

- src/lxc/lsm/selinux.c
> selinux: fix typo (AppArmor)

- src/tests/lxc-test-apparmor-generated
- src/tests/lxc-test-apparmor-mount
- src/tests/lxc-test-unpriv
Requires https://github.com/lxc/lxc-ci/pull/888
> re-enable some tests

- src/lxc/lxccontainer.c
This pull request updates create_mount_target() to check the type of the existing mount target before removing it. Previously, the function would unconditionally call remove(dest), which could result in unintended deletions.
Relevant thread: https://github.com/canonical/lxd/pull/16280#discussion_r2301692498.
> lxccontainer: check if target exists before remove in create_mount_target()
