config/apparmor/abstractions/start-container

The permission to make a mount "slave" is spelt "make-slave", not "slave", see
https://launchpad.net/bugs/1401619. Also, we need to make all mounts slave, not
just the root dir.
https://launchpad.net/bugs/1350947

apparmor: Fix slave bind mounts

---

src/lxc/conf.c

Container fail to start with configs (as shown below) where the same
vlan id is used for several type=vlan container interfaces.
Then, during the instantiation of the vlan interfaces, an error occurs
because the lxc code tries to assign the same temporary name to both
of them before it is bound into the container.
> lxc.network.type      = vlan
> lxc.network.flags     = up
> lxc.network.link      = eth1
> lxc.network.vlan.id   = 3842
> lxc.network.name      = iso0
>
> lxc.network.type      = vlan
> lxc.network.flags     = up
> lxc.network.link      = eth2
> lxc.network.vlan.id   = 3842
> lxc.network.name      = iso1
Signed-off-by: Axel Neumann <neumann@cgws.de>

Fix instantiation of multiple vlan interfaces with same id

---

templates/lxc-busybox.in

1. tty5 is not needed
2. the devices should be optional in case they didn't exist in the
host / parent-container
3. switch from 'touch $rootfs/dev/$dev' to using create=file in the
mount entry.

fix busybox unpriv

---

templates/lxc-centos.in

lxc-create -n centos5 -t centos -- --release 5 --arch i686
then
Command line error: no such option: --releasever
Signed-off-by: tukiyo3 <tukiyo3@gmail.com>

no such option: --releasever on CentOS5's yum

---

src/lxc/attach.c

I ran into this issue while using lxc_attach in a native node.js addon: For some reason, the intermediate process created by lxc_attach could not be reaped by the parent process (waitpid reported no child processes). This causes the IPC communication between the attached process and the initial thread to fail, since the initial thread jumps to the cleanup block. (Error reported was "error using IPC to receive notification from initial process (0)")
As far as I can tell, the problem is that the call to exit() in the intermediate process causes cleanup handlers set by node.js or V8 (Google's javascript engine upon which node.js is based) to be run, which mess with the child process so it can't be reaped any more. 
This change prevents any on_exit() and atexit() functions registered by the …

attach: use _exit() instead of exit() in the intermediate child process

---

src/lxc/lxc_top.c

Currently, if container name is fqdn (which frequently exceeds 18 characters), this breaks the output of lxc-top and misaligns the columns. This patch fixes this by limiting container name to 18 characters, which is what lxc-top currently assumes as maximum for container name.

lxc-top: limit container name to 18 characters

---

src/python-lxc/lxc.c
src/python-lxc/lxc/__init__.py

The main purpose of this commit is to add a backing store type (bdevtype) to a python create function (like lxc-create -B)
Signed-off-by: Bieliaievskyi Sergey magelan09@gmail.com

 Lxccreate: add a backing store type (bdevtype) to a python create function

---

config/templates/gentoo.common.conf.in

/dev/shm needs to be mounted as tmpfs. It's needed by python
and possibly other packages.
Signed-off-by: Markos Chandras <hwoarang@gentoo.org>

templates: gentoo.common: Add /dev/shm tmpfs mount entry

---

templates/lxc-centos.in

The current lxc-centos template dosen't support this use case:
alexandrel@epsilon:~/work$ lxc-create -n c7.test01 -t centos -- -R 7
Host CPE ID from /etc/os-release: 
Checking cache download in /var/cache/lxc/centos/x86_64/7/rootfs ... 
Downloading centos minimal ...
Usage: yum [options] COMMAND
List of Commands:
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
downgrade      downgrade a package
erase          Remove a package or packages from your system
groupinfo      Display details about a package group
groupinstall   Install the packages in a group on your system
grouplist      List available package groups
groupremove    Remove the packages in a group from your system
help           Display a helpful …

Added a more reliable test for yum --releasever in the centos template

---

src/lxc/lxc_autostart.c

Original pull request closed, because it was mistakenly made by using master branch instead of bugfix/*-named one.
https://github.com/lxc/lxc/pull/461
-------[ Original text ]--------------------------------------
As configuration parameter is called lxc.start.ORDER, one expects that container with order setting "1" will start before container with order setting set to "2", but this is not the case. Containers start in reverse order. If that is the desired behaviour, then I believe "order" should be called "priority" or something similar.
Anyway, I looked into src/lxc/lxc_autostart.c, and found this:
In main() there is this code:
qsort(&containers[0], count, sizeof(struct lxc_container *), cmporder);
In cmporder() the last comparison looks like this:
return (c1_order - c2_order) * -1; …

autostart: Fix bug with containers being started in reverse order

---

src/lxc/conf.c
src/lxc/lxc_user_nic.c

This PR is a follow up to https://www.mail-archive.com/lxc-users@lists.linuxcontainers.org/msg02624.html
Short summary, I suggest the following enhancement steps for unprivileged containers to allow veth networking with proxyarp/non-bridge setup:
1. Allow empty lxc.network.link with lxc.network.type = veth for unprivileged container, so that user can create a veth interface not attached to any bridge
2. Allow custom veth name on the host side
3. Allow static IP address definition on container config file
This PR only implements (1)
Tested on top of current master on ubuntu 14.04.2 host and container. I use this setup
```
$ cat /etc/lxc/lxc-usernet
user veth lxcbr0 2
user veth none 2
$ grep link ~/.local/share/lxc/u1/config
#lxc.network.link = lxcbr0
```
with lxc.network.link …

Allow veth that is not attached to a bridge on unprivileged container

---

config/init/systemd/lxc-apparmor-load
config/init/upstart/lxc.conf

AppArmor ships /lib/apparmor/profile-load. /lib/init/apparmor-profile-load is
merely a wrapper which calls the former, so just call it directly to avoid the
dependency on the wrapper.
LP: #1432683

Call /lib/apparmor/profile-load directly instead of the wrapper

---

src/lxc/cgfs.c
src/lxc/cgmanager.c
src/lxc/conf.c
src/lxc/conf.h

Add a function to sort the cgroup settings before applying.
Currently, the function will put memory.memsw.limit_in_bytes after
memory.limit_in_bytes setting so the container will start
regardless of the order specified in the input. Fix #453
Signed-off-by: Kien Truong <duckientruong@gmail.com>

Sort the cgroup memory settings before applying.

---

src/lxc/lxc-checkconfig.in

(1) Add test for kernel version greater 3.
(2) Use && and || instead of -a and -o as suggested in
http://www.unix.com/man-page/posix/1p/test/.
lxc-checkconfig will currently report "missing" on "Cgroup memory controller"
for kernel versions greater 3. This happens because the script, before checking
for the corresponding memory variable in the kernel config, currently will test
whether we have a major kernel version greater- or equal to 3 and a minor kernel
version greater- or equal to 6. This adds an additional test whether we have a
major kernel version greater than 3.
Signed-off-by: Christian Brauner <christianvanbrauner@gmail.com>

Make lxc-checkconfig work with kernel versions > 3

---

src/lua-lxc/core.c

If Lua 5.3 is compiled with LUA_COMPAT_5_2 defined, the
luaL_checkunsigned compatibility macro is already defined
in lauxlib.h.
Signed-off-by: Thomas Moschny <thomas.moschny@gmx.de>

Fix Lua 5.3 compatibility code.

---

config/bash/lxc.in

When running in posix mode (for example, because it was invoked as `sh`, or with the --posix option), bash rejects the function names previously used because they contain hyphens, which are not legal POSIX names, and exits immediately.
This is a particularly serious problem on a system in which the following three conditions hold:
1. The `sh` executable is provided by bash, e. g. via a symlink
2. Gnome Display Manager is used to launch X sessions
3. Bash completion is loaded in the (system or user) profile file instead of in the bashrc file
In that case, GDM's Xsession script (run with `sh`, i. e., bash in posix mode) sources the profile files, thus causing the shell to load the bash completion files. Upon encountering the non-POSIX-compliant function names, bash would then exit, …

Use POSIX-compliant function names in bash completion

---

src/lxc/bdev.c

Fix for Launchpad Bug #1441307. 
(I am not sure how to build this changed branch into a Debian/Ubuntu package, so I have not been able to test it. Guidance on that would be nice!)
Signed-off-by: Erik B. Andersen <erik.b.andersen@gmail.com>

Change lxc-clone to use 'rsync -aH' instead of just 'rsync -a'

---

src/lxc/monitor.c

Initialize ret to 0 so compiler no longer complains about
monitor.c: In function 'lxc_monitor_open':
monitor.c:212:5: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]
https://github.com/openwrt/packages/issues/1356
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

fix build on mpc85xx

---

config/templates/gentoo.moresecure.conf.in

The dev/mqueue and dev/shm directories do not exist when using lxc.autodev, thus they have to be created upon mount.
Signed-off-by: Dennis Schridde <devurandom@gmx.net>

Fix creation of dev/mqueue and dev/shm on Gentoo

---

doc/ja/lxc-autostart.sgml.in
doc/ja/lxc-config.sgml.in
doc/ja/lxc-destroy.sgml.in
doc/ja/lxc-snapshot.sgml.in
doc/ja/lxc-user-nic.sgml.in
doc/ja/lxc-usernet.sgml.in
doc/ja/lxc-usernsexec.sgml.in
doc/ja/lxc.conf.sgml.in
doc/ja/lxc.system.conf.sgml.in

Some sections titles (eg. "Author") are not translated.
I change that words to Japanese word.

Translate untranslated section titles in Japanese man pages

---

config/templates/gentoo.moresecure.conf.in

sys_admin and sys_resources are needed for systemd, setpcap is required for journald.
Also include the explanatory blurb that can be found in the other distro's configs.
See-Also: https://bugs.gentoo.org/show_bug.cgi?id=551792
Signed-Off-By: Dennis Schridde <devurandom@gmx.net>

Adopt capability (lxc.cap.drop) documentation from other distros in Gentoo config, drop setpcap and sys_nice

---

doc/lxc-usernet.sgml.in
src/lxc/lxc_user_nic.c

#513 
lxc-user-nic will now check which groups the calling user are a member of and will match them to any lines in lxc-usernet that starts with '@'. Since the user can potentially be a member of several groups specified, all of them are checked. Quotas are checked first based on user name, secondly based on user group, in the order they are specified in lxc-usernet.
It is not yet ready to be merged, the docs and usage instructions will at least need to be updated, but I would appreciate feedback first.
@stgraber

Added support for groups in lxc-usernet

---

templates/lxc-debian.in

debootstrap failed when $GREP_OPTIONS color is set to "always", so we need to unset it in the template
Signed-off-by:  feng xiahou <xiahoufeng@yahoo.com>

 debootstrap failed when $GREP_OPTIONS color is set

---

src/tests/lxc-test-checkpoint-restore

I haven't managed to get past the lxc-checkpoint without failing, but the lxc-wait should be on $name.

Wait on correct container name

---

src/lxc/confile.c

I found that there is no SIGPWR in configuration.
I added miscellaneous signals such as SIGPWR, SIGURG for lxc.haltsignal, lxc rebootsignal, lxc.stopsignal.

config: miscellaneous signals for lxc.*signal

---

config/init/common/lxc-containers.in

This lock file actually needed in autostart moment.
Аt other times it does not provide to create a container from ansible lxc_containers module.

fix container creation from ansible lxc_containers module

---

hooks/ubuntu-cloud-prep
templates/lxc-ubuntu-cloud.in

vendor-data is supported in Ubuntu cloud images in trusty and later.
This allows the user to pass it in on create or clone.
Signed-off-by: Scott Moser <smoser@ubuntu.com>

lxc-ubuntu-cloud: support passing vendor-data

---

src/lxc/seccomp.c

1) Two checks on amd64 for whether compat_ctx has already
been generated were redundant, as compat_ctx is generally
generated before entering the parsing loop.
2) With introduction of reject_force_umount the check for
whether the syscall has the same id on both native and
compat archs results in false behavior as this an internal
keyword and thus produces a -1 on
seccomp_syscall_resolve_name_arch().
The result was that it was added to the native architecture
twice and never to the 32 bit architecture, causing it to
not work on 32 bit containers on a 64 bit host.
3) I do not see a reason to care about whether the syscalls
have the same number on the two architectures. On the one
hand this check was there to avoid adding it to two archs
(and effectively leaving one arch unprotected), while …

seccomp: simplify and fix rule parsing

---

doc/ja/lxc-ls.sgml.in
doc/ko/lxc-ls.sgml.in
doc/lxc-ls.sgml.in

lxc-ls takes -P lxcpath and --version as arguments but it did not specify these
options on the manpages.

Add -P lxcpath and --version to lxc-ls manpage

---

src/lxc/execute.c

lxc-init has been renamed init.lxc so adapt error message
Signed-off-by: Nicolas Cornu <ncornu@aldebaran.com>

Fix error message when cannot find an lxc-init

---

templates/lxc-opensuse.in

zypper info's output is not usable for several reasons:
* it is localized -- there is no "Version: " in my output
* it shows results both from the repo and local system
So use plain rpm to determine whether build is installed and if proper
version is in place.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>

templates: lxc-opensuse, use rpm to determine build version

---

src/lxc/lxc-start-ephemeral.in

Binding a directory at a different location in a ephemeral container is
currently not possible. Using a regular container it however is possible.

Bind mount at different location

---

src/lxc/bdev.c

Adding the -X parameter to rsync copies the extended attributes. This allows things like ping to continue to be used by a non-privilged user in Debian at least.

Caps are getting lost when cloning an LXC.

---

src/lxc/log.c

please see
https://github.com/lxc/lxc/issues/198

Only use LOGPATH if lxcpath is unset or default

---

src/lxc/arguments.h
src/lxc/lxc_attach.c
src/lxc/lxc_checkpoint.c
src/lxc/lxc_clone.c
src/lxc/lxc_console.c
src/lxc/lxc_create.c
src/lxc/lxc_destroy.c
src/lxc/lxc_device.c
src/lxc/lxc_execute.c
src/lxc/lxc_freeze.c
src/lxc/lxc_info.c
src/lxc/lxc_init.c
src/lxc/lxc_monitor.c
src/lxc/lxc_snapshot.c
src/lxc/lxc_start.c
src/lxc/lxc_stop.c
src/lxc/lxc_unfreeze.c
src/lxc/lxc_wait.c
src/lxc/lxccontainer.c

lxc-snapshot:
- lxc_snapshot.c lacked necessary members in the associated lxc_arguments struct
in arguments.h. This commit extends the lxc_arguments struct to include
several parameters used by lxc-snapshot which allows a rewrite that is more
consistent with the rest of the lxc-* executables.
- All tests have been moved beyond the call to lxc_log_init() to allow for the
messages to be printed or saved.
- Some small changes to the my_args struct. (The enum task is set to
SNAP (for snapshot) per default and variables illustrating the usage of the
command line flags are written in all caps.)
- arguments.h has been extended to accommodate a rewrite of lxc-clone
lxc-clone:
- This commit adapts lxc-clone to be similiar in usage and feel to the other
lxc-* executables. It builds on the previous …

Refactor lxc-snapshot, lxc-clone, make LXC_CLONE_KEEPNAME work and add option to destroy container with all snapshots to lxc-destroy

---

src/lxc/lxccontainer.c
src/lxc/start.c

Latest glibc release actually honours calling setenv with a NULL
pointer by causing SIGSEGV but checking pointers before submitting
to any system function is a good idea anyway.
Signed-off-by: Robert Schiele <rschiele@gmail.com>

check for NULL pointers before calling setenv()

---

templates/lxc-debian.in

Signed-off-by: David Noyes <david.j.noyes@gmail.com>
A fix for the lxc-debian template when creating 32-bit containers: Test if dpkg supports the multiarch foreign-architecture flag.
Issue raised in lxc/lxc/#616

Test dpkg for multiarch support in lxc-debian template

---

doc/lxc.container.conf.sgml.in
src/lxc/arguments.h
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/lxc_execute.c
src/lxc/start.c
src/tests/get_item.c

In #417 some people noted that `lxc-execute` didn't work as expected when not running as root. The primary thing I noticed was that, no matter what, the process that was spawned was executed as container UID 0. This is a direct artifact of lxc assuming that, whatever container is launched, is started using "init" with UID 0. For lxc-start that makes a ton of sense, as we are trying to simulate a full distribution and init always runs as root. But, for lxc-execute, we aren't really trying to launch a full system. We are only trying to launch a process in some sort of default containment. So, it doesn't make much sense for something like `lxc-execute whoami` to return `root` unless that user is actually running as root.
I'v modified the "always become root" logic to check to see whether we …

Add support for specified UID/GID for lxc-execute in a private user namespace 

---

src/lxc/start.c

On very busy systems, some virtual network devices won't be destroyed after a
container halts.  This patch uses the lxc_delete_network() method to ensure
that network devices attached to the container are destroyed when the
container halts.
Without the patch, some virtual network devices are left over on the system
and must be removed with `ip link del <device>`.  This caused containers
with lxc.network.veth.pair to not be able to start.  For containers using
randomly generated virtual network device names, the old devices will hang
around on the bridge with their original MAC address.
Signed-off-by: Major Hayden <major@mhtx.net>

Tear down network devices during container halt

---

src/lxc/lxc-start-ephemeral.in

On Ubuntu 15.04, lxc-start-ephemeral's call to pwd.getpwnam always
fails.  While I haven't been able to prove it or track down an exact
cause, I strongly suspect that glibc does not guarantee that you can
call NSS functions after a context switch without re-execing.  (Running
"id root" in a subprocess from the same point works fine.)
It's safer to use getent to extract the relevant line from the passwd
file and parse it directly.
Signed-off-by: Colin Watson <cjwatson@ubuntu.com>

lxc-start-ephemeral: Parse passwd directly

---

templates/lxc-archlinux.in

The systemd-sysctl service includes condition that `/proc/sys/` has to be read-write.
In lxc only `/proc/sys/net/` is read-write which causes the condition to fail and service not to run.
This patch changes the check to `/proc/sys/net/` and makes the service apply only rules that are in `net` tree.

arch template: Fix systemd-sysctl service

---

templates/lxc-debian.in

When running the debian template on a non-debian host, it's usual not to
have debian-archive-keyring.gpg. When that happens, we skip the
signature checking of the release, which is dangerous because it's made over
HTTP.
This commit adds automatic fetching of Debian release keys.
Strongly related to #409

Fetch Debian archive GPG keyrings when they're not available

---

config/apparmor/lxc-generate-aa-rules.py
src/lxc/lxc-ls.in
src/lxc/lxc-start-ephemeral.in
src/python-lxc/examples/api_test.py
src/python-lxc/examples/pyconsole-vte.py
src/python-lxc/examples/pyconsole.py
src/python-lxc/setup.py.in

Previously, lxc-ls would fail on systems without a python3 in /usr/bin:
`-bash: /usr/local/bin/lxc-ls: /usr/bin/python3: bad interpreter: No such file or directory`
Use `env` instead in order to find an appropriate interpreter in $PATH.
Signed-off-by: Fox Wilson <2016fwilson@tjhsst.edu>

lxc-ls: use /usr/bin/env to find an appropriate python3 to run

---

src/lxc/lxccontainer.c

Otherwise it gets shortened with the temporary len but never
restored - which will only break API users which do a clone
then continue to use the original container, meaning this is
a hard one to detect.

lxcapi_clone: restore the unexpanded config len

---

src/lxc/start.c

Commit b6b2b194a8 preserves the container's namespaces for
possible later use in stop hook.  But some kernels don't have
/proc/pid/ns/ns for all the namespaces we may be interested in.
So warn but continue if this is the case.
Implement stgraber's suggested semantics.
- User requests some namespaces be preserved:
- If /proc/self/ns is missing => fail (saying kernel misses setns)
- If /proc/self/ns/<namespace> entry is missing => fail (saying kernel misses setns for <namespace>)
- User doesn't request some namespaces be preserved:
- If /proc/self/ns is missing => log an INFO message (kernel misses setns) and continue
- If /proc/self/ns/<namespace> entry is missing => log an INFO message (kernel misses setns for <namespace>) and continue

Better handle preserve_ns behavior

---

doc/ja/lxc-copy.sgml.in

Signed-off-by: Hiroaki Nakamura <hnakamur@gmail.com>
This PR improves the lxc-copy Japanese manpage created in 842948e4162d89ffce0e8cd292702598d736489a.
This change is agreed by @tenforward at
https://twitter.com/ten_forward/status/672806121011154946

Improve the lxc-copy Japanese manpage

---

src/lxc/lxc_top.c

limit CPU columns to 8 characters is too small，i think 12 is a better value
Signed-off-by: feng xiahou <xiahoufeng@yahoo.com>

lxc-top: limit CPU to 8 characters

---

src/lxc/lxc_top.c

limit BLKIO columns to 10 characters is too small，i think 14 is a better value
Signed-off-by: feng xiahou xiahoufeng@yahoo.com

lxc-top: limit BLKIO to 14 characters

---

doc/lxc-create.sgml.in
src/lxc/arguments.h
src/lxc/bdev.c
src/lxc/initutils.c
src/lxc/initutils.h
src/lxc/lxc_create.c
src/lxc/lxccontainer.h

I propose to add the management of Rados Block Device (http://docs.ceph.com/docs/master/rbd/rbd/)
Currently managing snapshots is not implemented. And the rbd devices are not remap in /dev/* when physical host restart.
Do you have any suggestions?

Add Ceph RBD backingstore.

---

src/lxc/lxc-checkconfig.in

zgrep is a script provided by the 'gzip' package, which may not be
installed on embedded systems etc which use busybox instead of the
standard full-featured utilities.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

lxc-checkconfig: remove zgrep dependency

---

src/lxc/start.c

Physical nic is not instantiated in lxc_create_network. 
There will be a error message when shutting down the container, as the "saved" nic was not created.
Signed-off-by: Li Qiu <li.qiu@nomovok.com>

Return immediately in save_phys_nics if not run as root

---

src/lxc/lxc_top.c

I think this is a common feature for top-like programs.
Signed-off-by: feng xiahou xiahoufeng@yahoo.com

lxc-top: print new line after flush terminal

---

src/python-lxc/lxc.c

As `lxc_attach()` calls `fork()` `PyOS_AfterFork` should be called in the new process if the Python interpreter will continue to be used.
This fixes the issue we had with multithreaded Python program that attaches to a container with `lxc.attach_run_command` and hangs infinitely.
`Container_attach_and_possibly_wait()` calls `self->container->attach()`:
https://github.com/lxc/lxc/blob/master/src/python-lxc/lxc.c#L637
The latter is implemented via `lxc_attach()` that calls `fork()`:
https://github.com/lxc/lxc/blob/master/src/lxc/attach.c#L814
`PyOS_AfterFork` should be called in the new process if the Python interpreter will continue to be used:
https://docs.python.org/3/c-api/sys.html?highlight=fork#c.PyOS_AfterFork
In the multithreaded Python program the thread that does not own the GIL …

python-lxc: Call PyOS_AfterFork after attaching to a container

---

src/include/ifaddrs.c

We encounter this issue when using lxc in android with bionic. This is the fix.
jenkins: ok to test
Signed-off-by: Tw <tw19881113@gmail.com>

fix buffer overflow in ifaddrs.c

---

doc/lxc.container.conf.sgml.in
src/lxc/attach.c
src/lxc/cgmanager.c
src/lxc/namespace.h
src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h

This set incorporates a few cgroup related changes.
1. Be more lenient in starting a container when not all cgroup
controllers are writeable.  If a controller is not writeable,
don't fail unless it is (a) a 'crucial' cgroup (freezer, or
name=systemd) or (b) is listed in lxc.cgroup.use.
2. Support cgroup namespaces

2016 01 04/cgroup.use

---

src/lxc/start.c

When preserving fds for the stop hook, make sure to also save
any fds we've inherited.

preserve inherited fds for stop hook

---

config/bash/lxc.in

`bash-completion` version 2.1 and later no longer include the `have` command, and consequently the `lxc` competion file fails on such systems. The command is now called `_have`.

bash completion: the 'have' command was deprecated in favor of '_have'

---

src/lxc/Makefile.am
src/lxc/arguments.h
src/lxc/lxc_ls.c

This is a reimplementation of `lxc-ls` in C. It supports all features previously supported by `lxc-ls` except `--nesting` (for now). I need to put more thought into the nesting part in since we fork when calling  `lxc_attach()`. A recursive implementation seems to be the most intuitive one. Thoughts on that appreciated.
All flags and parameters have the same name as before except when the user specifies a regex to filter container names by. In the Python implementation the regex was passed without a parameter flag. The new C-implementation has the parameter flag `-r/--regex` for this.

Reimplement lxc-ls in C

---

templates/lxc-opensuse.in

Adding release Leap 42.1. Repo locations were moved one level deeper with it, explaining why $DISTRO is made to "leap/42.1". I couldn't think of a cleaner way to do it.

Add openSUSE Leap release in opensuse template

---

templates/lxc-fedora.in

We no longer use mirrors.kernel.org. Commit f71e8f4 switched to archives.fedoraproject.org
Fixes #705

Fix Comment inside Fedora Template

---

.gitignore

Just noticed it after build was done.

.gitignore: add missing templates/sparclinux to ignore list

---

.gitignore

Seems like a nice simplification.
Please evaluate and merge PR #770 first.
b.

Refactor templates section of .gitignore - no need to specify individual templates anymore

---

src/tests/lxc-test-usernic.in

the new lxcpath and lxcname are not optional

lxc-test-usernic: update to reflect new lxc-test-usernic arguments

---

templates/lxc-centos.in
templates/lxc-fedora.in

If the backingstore is not 'dir', then lxc shouldn't ask the user
to change the password by performing a 'chroot'. Rather, the user
should start, attach, use the passwd command, and then stop the
container.
Fixes #731

Fix message after {fedora|centos}container creation

---

templates/lxc-centos.in

I found this when I created a CentOS5.5 container in Ubuntu. The container requested dhcp address with incorrect hostname because `HOSTNAME` was empty in `/etc/sysconfig/network` .

Use ${utsname} instead of ${UTSNAME} because latter variable is not defined

---

src/lxc/lxccontainer.c

* Suppose that you create a git repository under lxc.lxcpath (it
can be useful to keep track of the configurations of your containers)
Then, when you run lxc-ls you will get the following output:
.git      container1      container2    ....
This is because there is a 'config' file inside the '.git' directory.
It is where git stores the configuration of the repository.
And the test lxc-ls does to check if a directory contains a container
is just to check if the 'directory/config' file exists.
* Given that the odds of someone naming a container '.git' is almost zero,
ignore any directory/container with such name.

Ignore any container named '.git'

---

config/apparmor/abstractions/container-base.in
src/lxc/attach.c

We have to do it before we join the container's mntns so we have
the host's procdir.

cgroup ns: move the check for whether cgns is supported

---

src/lxc/cgfs.c

Small fixes which allow lxc-cgfs to boot privileged and unprivileged systemd containers.
With these, we can start seriously using lxc and lxd without cgmanager.

2016 01 31/cgfs

---

config/apparmor/abstractions/container-base.in

Some systems need to be able to bind-mount /run to /var/run
and /run/lock to /var/run/lock. (Tested with opensuse 13.1
containers migrated from openvz.)

apparmor: allow binding /run/{,lock/} -> /var/run/{,lock/}

---

src/lxc/bdev/lxcoverlay.c
src/lxc/conf.c

Since we allow containers to be created without a rootfs most checks in conf.c
are not sane anymore. Instead of just checking if rootfs->path != NULL we need
to check whether rootfs != NULL.
Minor fixes:
- Have mount_autodev() always return -1 on failure: mount_autodev() returns 0
on success and -1 on failure. But when the return value of safe_mount() was
checked in mount_autodev() we returned false (instead of -1) which caused
mount_autodev() to return 0 (success) instead of the correct -1 (failure).
closes #782

Fix NULL-ptr derefs for container without rootfs

---

src/lxc/bdev/lxcoverlay.c
src/lxc/conf.c

In mount_entry_on_generic() we dereferenced a NULL pointer whenever a container
without a rootfs was created. (Since mount_entry_on_systemfs() passes them with
NULL.) We have mount_entry_on_generic() check whether rootfs != NULL.
We also check whether rootfs != NULL in the functions ovl_mkdir() and
mount_entry_create_aufs_dirs() and bail immediately. Rationale: For overlay and
aufs lxc.mount.entry entries users give us absolute paths to e.g. workdir and
upperdir which we create for them. We currently use rootfs->path and the
lxcpath for the container to check that users give us a sane path to create
those directories under and refuse if they do not. If we want to allow overlay
mounts for containers without a rootfs they can easily be reworked.
Signed-off-by: Christian Brauner …

Fix mount_entry_on_generic()

---

src/lxc/bdev/lxcaufs.c
src/lxc/bdev/lxcaufs.h
src/lxc/conf.c

- The function mount_entry_create_aufs_dirs() moves from conf.c to
lxcaufs.{c,h} where it belongs.
- In accordance with the "aufs_" prefix naming scheme for functions associated
with lxcaufs.{c,h} mount_entry_create_aufs_dirs() becomes aufs_mkdir().

move and rename mount_entry_create_aufs_dirs()

---

src/lxc/lxc-checkconfig.in

Since we need fuse to run lxcfs, which is required by systemd, let's warn
about that as well.

lxc-checkconfig: warn about fuse as well

---

src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c

Comment rootfs.path and rootfs.mount so people can better figure
out which to use.
Remove the unused pivotdir argument from setup_rootfs_pivot_root().
Remove the unused pivot member of the lxc_rootfs struct.  And just
return 0 (success) when someone passes a lxc.pivotdir entry.  One
day we'll turn that into an error, but not yet...

Comment the lxc_rootfs structure

---

src/lxc/bdev/lxcaufs.c
src/lxc/bdev/lxcaufs.h
src/lxc/bdev/lxcoverlay.c
src/lxc/conf.c

Allow lxc.mount.entry entries for containers without a rootfs.

allow overlay lxc.mount.entry with no rootfs

---

src/lxc/lxc_destroy.c
src/lxc/start.c

- Ephemeral containers are destroyed on shutdown so we do not destroy them.
- Destroy ephemeral containers with clones: first destroy all the clones, then
destroy the container.
- Ephemeral containers with snapshots cannot be easily handled but we can
probably trust that no one will try to make snapshots of an ephemeral
container.

lxc-destroy: deal with ephemeral containers

---

config/apparmor/abstractions/container-base.in

This is needed to silence apparmor on current Xenial (4.4 kernel) running either trusty or xenial containers.

Couple of apparmor tweaks

---

src/lxc/attach.c
src/lxc/bdev/bdev.c
src/lxc/bdev/lxclvm.c
src/lxc/bdev/lxcnbd.c
src/lxc/bdev/lxcrbd.c
src/lxc/bdev/lxczfs.c
src/lxc/network.c

NULL pointers passed to execl*() functions must be cast to (char *)NULL since
they are variadic functions.

cast NULL pointers passed to execl*()

---

src/lxc/cgfs.c
src/lxc/cgmanager.c

If we're trying to allow a device which was denied to our parent
container, just continue.
Cgmanager does not help us to distinguish between eperm and other
errors, so just always continue.
We may want to consider actually computing the range of devices
to which the container monitor has access, but OTOH that introduces
a whole new set of complexity to compute access sets.
Closes #827

cgroups: do not fail if setting devices cgroup fails due to EPERM

---

doc/ja/lxc.sgml.in
doc/ko/lxc.sgml.in
doc/lxc.sgml.in

Fix typo in lxc manpage

---

templates/lxc-sshd.in

Systems with systemd have /sbin/init as a symlink pointing to real init.
Sshd template tries to bind-mount special init implementation.
The problem is that one cannot bind-mount to a location that is a symlink.
Fix this by deferencing /sbin/init symling and using that as bind-mount location.
Signed-off-by: Nikolay Martynov <mar.kolya@gmail.com>

Fix sshd template on systems with systemd

---

src/lxc/cgmanager.c
src/lxc/console.c
src/lxc/console.h
src/lxc/lxc_attach.c
src/lxc/start.c

~~Work in progress.~~ Have lxc-attach use a pty. As has been discussed the default approach is to create a pty in the container. If that fails we try to create a pty on the host. ~~What needs to be decided among other things is how to handle the case where we have no tty as fd 0.~~

make lxc-attach use a pty

---

src/lxc/lxc_attach.c

bionic libc doesn't know _Exit(). Replace it with _exit().

fix android build

---

doc/lxc-attach.sgml.in

closes #838
- explain rationale behind allocation of pty
- briefly explain how a pty is allocated
- add a short note that describes the changed behavior for lxc-attach when the
user is not placed in a writeable cgroup at login

update lxc-attach manpage

---

doc/lxc.container.conf.sgml.in
src/lxc/cgfs.c

In that case containers will be able to mount cgroup filesystems
for themselves as they do on a host.
This fixes inability to start systemd based containers on cgns-enabled
kernels with cgmanager not running.
I've tested debianjessie, busybox, ubuntu trusty and xenial, all of
which booted ok.  However if there are some setups which require
premounted cgroupfs (i.e. they don't mount if they detect being in
a container), this may cause trouble.

cgfs: do not automount if cgroup namespaces are supported

---

doc/ja/lxc-clone.sgml.in
doc/ja/lxc-start-ephemeral.sgml.in
doc/ja/lxc.container.conf.sgml.in

* Update lxc-clone(1) and lxc-start-ephemeral(1) as those have been deprecated.
* Update lxc.container.conf(5) about cgroup namespace.

Update Japanese man

---

doc/lxc-attach.sgml.in
src/lxc/lxc_attach.c

Previously we implemented two ways to get a pty for lxc-attach:
1. get a pty in the container
2. get a pty on the host
Where 1. was the default and 2. was only tried after 1. failed.
For safety and simplicity reasons, we remove 1. and just keep 2. around.

lxc-attach: rework pty allocation

---

src/lxc/start.c

If we don't do this, we'll leak the parent's session id to the container,
which maybe doesn't matter, but it still seems better to set it anyway.
Also, it breaks CRIU for containers that don't call setsid themselves.

start: setsid in init task as well

---

src/lxc/lxc_ls.c

Otherwise line wrapping might occur too late.

lxc-ls: count spaces

---

config/templates/Makefile.am
config/templates/alpine.common.conf.in
config/templates/alpine.userns.conf.in
configure.ac
templates/lxc-alpine.in

I’ve rewritten the Alpine template from scratch. The new template script is more readable and robust, uses cache and external LXC config file as other templates.
I hope that it can be added to lxc-ci now (https://github.com/lxc/lxc-ci/issues/4).

Rewrite template script for Alpine Linux

---

src/lxc/cgfs.c
src/lxc/cgmanager.c
src/lxc/cgroup.c
src/lxc/cgroup.h

Cgmanager was taught awhile ago that only some cgroup controllers are
crucial.  Teach cgfs the same thing.
This patch needs improvement, but will fix failure of lxc without cgmanager
for unprivileged users for now.  In particular, needed improvements include:
1. the check for crucial subsystems needs to include lxc.use
2. we should keep a list of the actually used subsystems so we don't keep
trying to chmod and enter after create has found we couldn't use a particular
subsystem
This fixes unprivileged lxc use.  It does not appear to suffice to fix
nested unprivilegd lxd usage.

fix cgfs failure for unpriv users

---

src/lxc/cgfs.c

Dirty fix for the current noisiness when lxc_cgroupfs_create() could not create
cgroups.

cgfs: don't chown/chmod/rm non-existing paths

---

src/lxc/lxc_attach.c
src/lxc/lxc_copy.c

(fixes https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1551935)
lxc-copy -n ORIG -N COPY -e
accidently printed
"Created ORIG as clone of COPY"
instead of
"Created COPY as clone of ORIG".
Fix the ordering.

lxc-copy: correct order of copy and original & lxc-attach: setup ts->stdoutfd

---

doc/lxc-attach.sgml.in
doc/lxc-copy.sgml.in
src/lxc/lxc_copy.c

Explain that the pipe symbol needs to be escaped for -e and -s.

Add features/small improvements to man pages (lxc-attach, lxc-copy)

---

src/lxc/cgfs.c
src/lxc/cgmanager.c
src/lxc/cgroup.c
src/lxc/cgroup.h
src/tests/lxc-test-unpriv

cgfs was failing to clean up its cgroups when unprivileged, and then segfaulting on an error path on subsequent lxc-start.  Fix the lxc-start segfault so it properly falls back to %n-1 if %n exists, and switch to a container namespace to clean up cgroups on exit so that lxc has the permission to remove it.
Also add a test to catch regression in unprivileged restart in the future.

2016 03 02/cgfs.rmperms

---

src/lxc/lxc_attach.c
src/tests/Makefile.am
src/tests/lxc-test-lxc-attach

So that we can do things like:
lxc-attach -n a -- sh -c 'echo ERR >&2' > /dev/null
There seems to be no easy way to discern when we need to write to stderr
instead of stdout when we receive an event on the master fd of an allocated
pty. So we're using a "trick"/"hack". We write to STDOUT_FILENO if it refers to
a pty. If STDOUT_FILENO does not refer to a pty we check whether STDERR_FILENO
refers to a pty and if so write to it.

lxc-attach: fix redirection - stderr

---

src/lxc/Makefile.am
src/lxc/cgfs.c
src/lxc/cgfsng.c
src/lxc/cgmanager.c
src/lxc/cgroup.c
src/lxc/cgroup.h
src/lxc/criu.c
src/lxc/criu.h
src/lxc/utils.c
src/lxc/utils.h

This makes simplifying assumptions:  all usable cgroups must be
mounted under /sys/fs/cgroup/controller or /sys/fs/cgroup/contr1,contr2.
Currently this will only work with cgroup namespaces, because
lxc.mount.auto = cgroup is not implemented.  So cgfsng_ops_init()
returns NULL if cgroup namespaces are not enabled.

cgfsng: next generation filesystem-backed cgroup implementation

---

src/lxc/cgfsng.c

cgfsng: enter/escape error msgs: differentiate and add errno

---

src/tests/lxc-test-apparmor-mount
src/tests/lxc-test-unpriv
src/tests/lxc-test-usernic.in

Lxc only sets it on /lxc, not on /.
It's conceivable that we should really re-set this to the original
value, to prevent making later tests not fail when they should.  I
didn't do that.

tests: set clone_children if need be

---

src/lxc/cgfsng.c

A few crucial fixes for cgfsng.  'batch' really referred to batching the realloc sizes, but that's only a part of this batch of fixes now.

2016 03 08/batch

---

src/lxc/criu.c

The problem here is that dev_t on most platforms is `long unsigned`, but on
android (and ppc?) it's `long long unsigned`. Let's just upcast to `long
long unsigned` and use that format string to keep the compilers happy.
Safety first!

build: fix build on android (and ppc)

---

config/apparmor/abstractions/container-base
config/apparmor/abstractions/container-base.in
config/templates/common.conf.in

Prevent privileged containers from messing with the host's pci devices
directly.  Refuse access under /proc/bus, and drop cap_sys_rawio.  Some
containers may need to re-enable cap_sys_rawio (i.e. if they run an
X server).
It may be desirable to break some of this stuff into files which can be
separately included (or not included), but this patch isn't the right
place for that.

Prevent access to pci devices

---

src/lxc/utils.c

The open_without_symlink routine has been specifically created to prevent
mounts with synlinks as source or destination. Keep SYSERROR'ing in that
particular scenario, but leave error handling to calling functions for the
other ones - e.g. optional bind mount when the source dir doesn't exist
throws a nasty error.
Signed-off-by: Bogdan Purcareata <bogdan.purcareata@nxp.com>

open_without_symlink: Don't SYSERROR on something else than ELOOP

---

lxc.spec.in

Fix the hardcoded path to the lxc-net config file in the lxc.spec.in
Signed-off-by: Johannes Kastl <git@ojkastl.de>

lxc.spec.in: fixed hardcoded path to lxc-net config file

---

src/lxc/start.c
src/lxc/sync.c
src/lxc/sync.h
src/lxc/utils.c
src/lxc/utils.h

I have a container whose /dev is populated by its init, so I don't need autodev hook.
Recent versions of LXC (starting from 1.1, I think) try to open /dev/null from container's rootfs when starting daemonized. And the container fails to start, because there's no /dev/null yet.
I changed the code to open /dev/null before fs root switch, so now container's init will be connected to host's /dev/null. I think it shouldn't break anything or cause a security problem.
Also, the error message was a bit confusing ("unexpected sequence number"). I tried to improve it here too.
This PR fixes #910.

Fix daemonized containers without autodev and/or /dev mount

---

config/apparmor/Makefile.am
config/init/upstart/Makefile.am

Currently, LXC successfully builds out-of-tree (at least it looks so), but `make install` fails, because it tries to install some non-generated files without full path. Prepending "$(srcdir)/" fixes it, and also doesn't break in-source build.

Fix installation of out-of-tree (VPATH) builds

---

templates/lxc-oracle.in
templates/lxc-sparclinux.in

In OL6, it is missing /etc/sysconfig/clock
Tested-by: Deepak Patel <deepak.patel@oracle.com>
Signed-off-by: Thomas Tanaka <thomas.tanaka@oracle.com>

Timezone inside the container is not the same as the host

---

templates/lxc-debian.in

http.debian.net is an alias anyways and httpredir.debian.org is the official name of the service

use httpredir.debian.org as the default Debian mirror

---

templates/lxc-debian.in

This inverts the logic done in c2a85d0 to default to "main only" and allow enabling contrib and non-free on user request.
Closes: #625

only enable Debian's main repository by default

---

templates/lxc-ubuntu.in

debootstrap sometimes selects the wrong mirror due to [1]
[1] https://bugs.debian.org/819300

always provide a default mirror for debootstraping Ubuntu

---

src/lxc/lxccontainer.c
src/lxc/utils.c
src/lxc/utils.h

In order to do this we make use of the MAP_FIXED flag of mmap(). MAP_FIXED
should be safe to use when it replaces an already existing mapping. To this
end, we establish an anonymous mapping that is one byte larger than the
underlying file. The pages handed to us are zero filled.  Now we establish a
fixed-address mapping starting at the address we received from our anonymous
mapping and replace all bytes excluding the additional \0-byte with the file.
This allows us to use normal string-handling function.  The idea implemented
here is similar to how shared libraries are mapped.

add funs to mmap() files to \0-terminated strings

---

src/lxc/utils.c
src/lxc/utils.h

Additionally, fix the comment for lxc_strmmap() and cleanup #includes in
utils.{c,h}.

use smarter error handling for lxc_strmmap()

---

templates/lxc-debian.in

Squeeze is EOL now, Stretch is the upcoming stable
Signed-off-by: Evgeni Golov <evgeni@golov.de>

update Debian release names

---

src/lxc/criu.c

strncat only returns its first argument and not the end of the written string.
Thus "buf-pos" is always 0 and consquently no range check is performed.
Also the terminating null character was not being accounted for.
Signed-off-by: Niklas Eiling <niklas.eiling@rwth-aachen.de>

fix possible buffer overflow

---

src/lxc/start.c

It's unlikely to happen, but still better check for overflow before writing, not after.

Fix buffer overflow in do_start()

---

src/lxc/criu.c
src/lxc/criu.h
src/lxc/lxccontainer.c
src/lxc/lxccontainer.h

this enables lxc to perform "disk-less migrations" where memory pages are sent directly to the destination machine instead of being written to the sources filesystem first.
For this, the migrate_opts struct has been added the strings "pageserver_address" and "pageserver_port" so that criu can be told where to look for a pageserver.
Signed-off-by: Niklas Eiling <niklas.eiling@rwth-aachen.de>

c/r: support for the criu pageserver

---

src/lxc/bdev/bdev.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c

It'll make future code reading easier.

use more accurate bdev_type name for rootfs.bdev

---

src/lxc/confile.c

clear is just set(x, ""), but before this patch that didn't work bc
"" is nota valid bdev type.

rootfs.bdev_type: implement get and clear

---

src/lxc/bdev/lxcbtrfs.c

A change in kernel 4.2 caused btrfs_recursive_destroy to
fail to delete unprivileged containers.  This patch restores
the pre-kernel-4.2 behaviour.  Ref: Issue #935 .
Signed-off-by: Oleg Freedhom <overlayfs@gmail.com>

fix btrfs_recursive_destroy

---

doc/ja/lxc-attach.sgml.in
doc/ja/lxc-copy.sgml.in
doc/ja/lxc-info.sgml.in
doc/ko/lxc-attach.sgml.in
doc/ko/lxc-copy.sgml.in
doc/ko/lxc-info.sgml.in
doc/lxc-attach.sgml.in
doc/lxc-copy.sgml.in
doc/lxc-info.sgml.in

fix spelling mistakes spotted by Debian's lintian

---

src/lxc/bdev/bdev.c

use correct "overlayfs" instead of "ovl"

---

src/lxc/lxccontainer.c

Since specifying lxc.rootfs.backend can lead to performance improvements we
always set it during container creation.
This also fixes a bug. do_bdev_create() tried to be smart and retrieve the lower
directory when bdev->type == overlayfs or aufs thereby cutting the path.
However, this operation is done in ovl_mount() and aufs_mount() and both
functions need the full src path for this. The bug didn't show before because
when creating a overlayfs container with e.g.:
lxc-create -n c -t busybox -B overlayfs
still left bdev->type set to dir and so the code for retrieving the lower dir in
do_bdev_create() was skipped. But by setting lxc.rootfs.backend on container
creation we force bdev->type to be set to e.g. overlayfs and the code gets
executed thereby exposing the bug.
Signed-off-by: …

set lxc.rootfs.backend on container creation

---

src/lxc/console.c
src/lxc/console.h
src/lxc/lxc_attach.c

lxc_console_create() calls lxc_console_peer_default() which in turn calls
lxc_console_sigwinch_init() which sets up the lxc_tty_state struct for the
current pty. Prior to this commit lxc_console_sigwinch_init() would consider
failures to install a SIGWINCH handler fatal and and return NULL. This commit
makes failures to install a SIGWINCH handler non-fatal. In such cases the
lxc_tty_state struct will still be set up but the sigfd member, which contains
the fd which receives SIGWINCH events, will be set to -1. (This also entails
that the sigset_t oldmaks field is meaningless.) Callers of
lxc_console_sigwinch_init() and lxc_console_sigwinch_fini() should thus make
sure that sigfd >= 0 or sigfd != -1 before trying to register a SIGWINCH handler
in e.g. an lxc_mainloop or resetting the …

lxc-attach: attach even without sigwinch handler

---

src/lxc/console.c
src/lxc/console.h
src/lxc/lxc_attach.c
src/lxc/start.c

lxc-attach allocated a pty in a manner that relied on ts->stdinfd and
ts->stdoutfd to be set. We had to resort to a trick to get it working when
output is redirected. The new implementation gets rid of the black magic and
also simplifies the code.
This commit also implements pty logging for lxc-attach. Users will now be able
to log commands and corresponding output to a file given that lxc-attach
allocates a pty.

simplify pty allocation and implement pty logging

---

src/lxc/console.c
src/lxc/lxc_attach.c

Using EPOLLHUP to determine when to exit the loop is unreliable. Let's exit
clean when read() returns -1 && errno != EINTR or 0.

use lxc_read_nointr() and lxc_write_nointr()

---

src/tests/lxc-test-lxc-attach

The current tests for lxc-attach pty allocation and I/O redirection rely on the
standard file descriptors of the test script to refer to a pty. If they do not
the tests are effectively useless with respect to pty allocation. We need a test
environment with the standard file descriptors refering to a pty as well. One
solution is to run this test under the script command.
This commit also adds a test whether pty logging works. This test is only
executed when all standard file descriptors refer to a pty.

adapt lxc-attach tests

---

src/lxc/arguments.c
src/lxc/bdev/bdev.c
src/lxc/bdev/lxcoverlay.c
src/lxc/conf.c
src/lxc/confile.c
src/lxc/network.c
src/lxc/nl.c
src/lxc/parse.c
src/lxc/utils.c

This cleans up some sign-compare warnings as well as avoids any
possibilities of unintended signed offsets for indices during
iteration.
Signed-off-by: Matt Ullman <staticfox@staticfox.net>

Use size_t as an iteration point over int

---

src/lxc/lxc_destroy.c

lxc-destroy: avoid double print

---

src/lxc/cgfsng.c
src/lxc/cgroup.c

Note that is_crucial_subsystem still lists name=systemd.  That is
used in cgfs and cgmanager.  Cgmanager is typically setup to create
name=systemd, so it is ok.  cgfs uses is_crucial_subsystem() only
to decide whether failure to create or chown a directory should be
terminal.  That's ok, because (a) if name=systemd is not mounted then
we won't hit that, and (b) if name=systemd is mounted, then we'd
really still like to set it up for containers.

cgfsng: don't require that systemd subsystem be mounted

---

src/lxc/lxc_attach.c
src/tests/lxc-test-lxc-attach

pty logging only works correctly when stdout and stderr refer to a pty. If they
do not, we do not dup2() them and lxc_console_cb_con() will never write to the
corresponding log file descriptor.
When redirection on stdout and stderr is used we can safely assume that the user
is already logging to a file or /dev/null and creating an additional pty log
doesn't seem to make sense.

lxc-attach: error on -L/--pty-log + redirection

---

templates/lxc-debian.in

closes #302
as discussed with @terceiro, this should go away. make it so :)

do not set the root password in the debian template

---

src/python-lxc/lxc/__init__.py

```
>>> c = lxc.Container('ct')
>>> c.create('debian', args=('-r', 'jessie'))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3/dist-packages/lxc/__init__.py", line 229, in
create
template_args['args'] = tuple(tmp_args)
UnboundLocalError: local variable 'tmp_args' referenced before
assignment
```
Signed-off-by: Aron Podrigal <aronp@guaranteedplus.com>

Fixed python-lxc reference to var before assignment

---

config/init/systemd/lxc.service.in

the target is obsolete since systemd v38 which everybody should have.
original patch by Daniel Baumann

drop obsolete syslog.target from lxc.service.in

---

src/lxc/console.c

Without this some ncurses-based programs behave incorrectly
Signed-off-by: Andrey Jr. Melnikov <temnota.am@gmail.com>

Switch console pty to raw mode. 

---

config/init/sysvinit/lxc-containers.in
config/init/sysvinit/lxc-net.in

- /etc(/rc.d)?/init.d/functions does not exist on all distributions
- LSB does not define a message function without an explicit status
- Debian-derived systems add a log_daemon_msg for that
lets define an own log_daemon_msg as echo and try to load LSB init
functions afterwards, which might overload it with a nicer version
that way the init scripts should work on any system, without hard
dependencies on neither LSB nor /etc/init.d/functions

don't make sysv init scripts dependant on distribution specifics

---

src/lxc/lxc-checkconfig.in

This makes me feel more convenient when reading a long  `lxc-checkconfig` output using `less` or redirecting the `lxc-checkconfig` output to file for sending to others.
I don't know if you guys think this is necessary...

Check if the stdout is a terminal in lxc-checkconfig

---

src/lxc/confile.c

I wanted to have network.type exposed in lxc-python. I'm not sure if we want this key to be part of the network config, if not here I would modify lxc-python to allow such access `Container('ct').network[0].type`.
Signed-off-by: Aron Podrigal <aronp@guaranteedplus.com>

Added `type` to keys in lxc_list_nicconfigs

---

src/python-lxc/lxc.c

When container init failed for whatever reason, previously it resulted
in a `SystemError: NULL result without error in PyObject_Call`
This will now result in a RuntimeError
```
>>> import lxc
>>> 
>>> c = lxc.Container('aron')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3/dist-packages/lxc/__init__.py", line 157, in __init__
_lxc.Container.__init__(self, name)
RuntimeError: Container_init:lxc.c:454: error during init for container 'aron'.
>>> 
```
Signed-off-by: Aron Podrigal <aronp@guaranteedplus.com>

Fixed - set PyErr when Container.__init__ fails

---

templates/lxc-oracle.in
templates/lxc-sparclinux.in

Signed-off-by: Thomas Tanaka <thomas.tanaka@oracle.com>

Improve on the case where default networking config is incomplete

---

templates/lxc-alpine.in

Required for proper applying dnsmasq config entries.
Signed-off-by: Andrey Kostin <andrey@kostin.email>

Force DHCP client to send hostname

---

src/lxc/sync.c

I think (?) this may be related to our hanging monitor bug. Let's do this
anyway, as it's probably a good idea.

sync: fail on unexpected message sizes

---

config/templates/gentoo.moresecure.conf.in
config/templates/slackware.common.conf.in

gentoo.moresecure.conf tries to drop the capability CAP_SYS_RESOURCES.
However, that capability doesn't exist, so the container doesn't start.
Change it to CAP_SYS_RESOURCE, according to capabilities(7).
Also correct the same typo in a comment in slackware.common.conf.
Signed-off-by: Karl-Johan Karlsson <creideiki@ferretporn.se>

Change sys_resources to sys_resource.

---

src/lxc/start.c
src/lxc/sync.c
src/lxc/sync.h

so that there is a root uid mapping for the /proc/net files.
This is a fix for lxd issue #1978.

Unshare netns after setting the userns mappings

---

src/lxc/confile.c

If the value starts and ends with matching quote characters, those
characters are stripped automatically.   Quote characters are the
single quote (') or double quote (").  The quote removal is done after
the whitespace trimming.
This is needed particularly in order that lxc.environment values may
have trailing spaces.  However, the quote removal is done for all values
in the parse_line function, as it has non-const access to the value.
Signed-off-by: Stewart Brodie <stewart@metahusky.net>

Allow configuration file values to be quoted

---

src/lxc/log.c
src/lxc/log.h

When writing out the CRIU exec command, we're bumping up against the buffer
size limit. Let's increase it so we can avoid:
lxc 20160509213229.921 WARN     lxc_log - log.c:log_append_logfile:111 - truncated next event from 523 to 512 bytes

log: remove duplicate definitons and bump buffer size

---

templates/lxc-ubuntu.in

In many environments the preference is to configure containers with
apt mirrors that are SSL-secured.
When building containers using the download template this can't be
done unless an insecure mirror is first used to install the
apt-transport-https package, then the sources reconfigured to
use the https URL.
When building containers without using the download template this
can't be done unless the container creator specifically includes
this package in the package list at build time.
It seems more intuitive to me to have the package installed by
default. This patch includes the required package for the minbase
variant only as this is the default.

Add apt-transport-https to minbase variant packages_template

---

src/lxc/lxc_user_nic.c

`struct in6_addr` is both defined in the C library header `<netinet/in.h>` and the Linux kernel header `<linux/in6.h>`.
lxc_user_nic.c includes both `<netinet/in.h>` and `<linux/if_bridge.h>`. The later one includes `<linux/in6.h>.`
This breaks build with the musl libc:
`error: redefinition of ‘struct in6_addr’`
As lxc_user_nic.c does not use any references from `<linux/if_bridge.h>` it is safe to remove this header.

Fix redefinition of struct in6_addr

---

.travis.yml

It looks like VPATH (split source and build directories) builds
are frequently broken. So let's test them on travis-ci.
Personally I use VPATH build in my deployment scripts.

travis: test VPATH builds

---

src/python-lxc/setup.py

Distribution name starting with an underscore is considered invalid by
many tools. For example, you can't list such name in
install_requires in your setup.py.
error: Invalid distribution name or version syntax: -lxc-0.1

python-lxc: change distribution name _lxc -> lxc

---

.travis.yml
lxc.spec.in
src/python-lxc/setup.py

setuptools is recommended by Python Packaging Guide
https://python-packaging-user-guide.readthedocs.io/en/latest/current/
It contains some useful extensions like 'develop' command. Also it
is required for building wheels AFAIK.
The only downside is an extra build-time dependency. setuptools are
packaged in both Debian and Ubuntu (python3-setuptools), as well as
other major distros, so it shouldn't be an issue, I think.

python-lxc: use setuptools instead of distutils

---

src/python-lxc/Makefile.am

Looks like it's a bug in Debian or Ubuntu Python/setuptools patches.
When `--install-layout=deb` is passed to `setup.py`, setuptools don't generate stub helpers for loading extensions from .egg files. The same command without `--install-layout` works as expected.
However, it could simply be an unsupported configuration, because distro packages should be built with `--single-version-externally-managed`, which prevents .egg builds.
So, I assume setuptools builds will be used for distro packages. Then the fix is very simple: always pass `--root=` to `setup.py`, even when `DESTDIR` isn't set. As `--root` implies `--single-version-externally-managed`.

python-lxc: fix breakage caused by the switch to setuptools

---

config/init/systemd/lxc@.service.in

lxc-start started to default to daemonize the container when starting
this conflicts with type=simple of the systemd unit
call lxc-start with -F and thus force execution in foreground
that way we can feed the log to journald properly and keep type=simple
Debian-Bug: https://bugs.debian.org/826100
Signed-off-by: Evgeni Golov <evgeni@golov.de>

start containers in foreground when using the lxc@.service

---

templates/lxc-ubuntu.in

In many environments the preference is to configure containers with
apt mirrors that are SSL-secured.
When building containers using the download template this can't be
done unless an insecure mirror is first used to install the
apt-transport-https package, then the sources reconfigured to
use the https URL.
When building containers without using the download template this
can't be done unless the container creator specifically includes
this package in the package list at build time. It seems more
intuitive to me to have the package installed by default.
Commit 396f75abb3d319adc7d871b94b08bc6bb9c49585 added the package
to the minbase variant, but this variant is not used by the download
template build process. The build process instead specifies no
variant, so this patch moves the package …

Move apt-transport-https to global packages_template

---

src/python-lxc/Makefile.am

When LXC is configured with --enable-rpath, I expect Python bindings
to be able to find the library in a non-standard location, just like
LXC command-line tools.

python-lxc: follow global rpath setting for autotools builds

---

templates/lxc-oracle.in

There is container-getty.service with OL7.2 systemd, it
is also used for managing the getty service, use that
instead and not manually create it.
Signed-off-by: Thomas Tanaka <thomas.tanaka@oracle.com>

Unable to login via console in OL7.2

---

templates/lxc-debian.in

If you specify an interpreter path with "-I" or "--interpreter-path",
the architecture of the debian container can differ from the one of
the host.
Before creating the container, binfmt must be configured on the host:
the script checks the name of the interpreter in /proc/sys/fs/binfmt_misc/
to know where to install it in the container.
To create a MIPS container on an x86_64 host:
$ cat /proc/sys/fs/binfmt_misc/qemu-mips
enabled
interpreter //qemu-mips
flags: OC
offset 0
magic 7f454c4601020100000000000000000000020008
mask ffffffffffffff00fffffffffffffffffffeffff
$ sudo lxc-create -n virtmips-stretch -t debian -- \
--arch=mips \
--interpreter-path=./mips-linux-user/qemu-mips \
--mirror=http://ftp.debian.org/debian \
--release=stretch
Signed-off-by: Laurent Vivier <laurent@vivier.eu>

lxc-debian: allow to specify a binfmt interpreter

---

templates/lxc-debian.in

init 1.34 is not "Essential" anymore, in order to make it not required
on minimal chroots, docker containers, etc. Because of that we now need
to manually include it on systems that are expected to boot.

lxc-debian: make sure init is installed

---

config/init/upstart/lxc-instance.conf

Remove unnecessary shell wrap around job start.
Force foreground execution to allow job monitoring and control.
Signed-off-by Andrey Repin <anrdaemon@yandex.ru>

Force lxc-instance to behave like a good Upstart client

---

src/lxc/criu.c

A while ago cgroup modes were introduced to CRIU, which slightly changed
the behavior w.r.t. cgroups under the hood. What we're really after is
criu's --full mode, i.e. even if a particular cgroup directory exists
(in particular /lxc/$container[-$number] will, since we create it), we
should restore perms on that cgroup.
Things worked just fine for actual properties (except "special" properties
as criu refers to them, which I've just sent a patch for) because liblxc
creates no subdirectories, just the TLD.

c/r: use criu's "full" mode for cgroups

---

src/include/lxcmntent.h

Newer versions of Android (5.0+, aka API Level 21+) include mntent.h,
which declares setmntent and endmntent. This hits an edge
case with the preprocessor checks in lxcmntent.h because HAVE_SETMNTENT
and HAVE_ENDMNTENT are both defined (in Bionic's mntent.h), but conf.c
always includes lxcmntent.h on Bionic! As a result, we get compiler
warnings of implicit function declarations for setmntent endmntent.
This patch always includes setmntent/endmntent/hasmntopt function
declarations on Bionic, which gets rid of these warnings.
Signed-off-by: Preetam D'Souza <preetamjdsouza@gmail.com>

Include all lxcmntent.h function declarations on Bionic

---

templates/lxc-debian.in

The regression was introduced by commit
3c39b0b7a2b445e08d2e2aecb05566075f4f3423 which makes it possible to
create working stretch containeres by forcinig `init` to be in the
included package list.
However, `init` didn't exit before jessie, so now for wheezy we
explicitly include `sysvinit`; sysvinit on wheezy has `Essential yes`,
so it would already be included anyway.

lxc-debian: fix regression when creating wheezy containers

---

src/lxc/cgfsng.c

First, we're doing this so long a there is any cgroup config item -
even if no devices ones.  Then if devices is not available we fail.
This was leading to Rob E's mysterious startup failures.
Secondly, we're not even using this info.  The user was removed
awhile back.

cgfsng: don't pre-calculate path

---

src/lxc/criu.c

- If version != NULL criu_version_ok() stores the detected criu version in
version. Allocates memory for version which must be freed by caller.
- If version == NULL criu_version_ok() will return true when the version
matches, false in all other cases.

store criu version

---

src/lxc/conf.c

Add flag in mount_entry to skip NODEV in case of a persistent dev entry
Since 1.0.7 persistent /dev mount entries that lives in a parent filesystems with nodev flag will inherit the flag even adding "dev" to mount options and cause access denied errors for /dev/urandom and /dev/null, with this change the mount option will be respected when a persistent dev is used.
Signed-off-by: Rodrigo Vaz <rodrigo@heroku.com>

Add flag in mount_entry to skip NODEV in case of a persistent dev entry

---

src/lxc/lxccontainer.c

The commit "c/r: add support for CRIU's --action-script" breaks
lxc-checkpoint on the command-line. It produces errors like:
sh: $'\260\366\b\001': command not found
and then it fails. src/lxc/criu.c expects migrate_opts->action_script to
be either NULL, then it is ignored, or to actually contain the name of
an action scripts.
As the struct migrate_opts has not static storage is has to be explicitly
initialized or the value of the structure's members is indeterminate.

c/r: initialize migrate_opts properly

---

src/lxc/start.c
src/lxc/start.h

add missing cgroup namespace to ns_info struct

---

src/lxc/criu.c
src/lxc/lxccontainer.h

Shortly after CRIU 2.3 has been released a patch has been added to skip
in-flight TCP connections. In-flight connections are not completely
established connections (SYN, SYN-ACK). Skipping in-flight TCP
connections means that the client has to re-initiate the connection
establishment.
This patch stores the CRIU version detected during version check, so
that during dump/checkpoint options can be dynamically enabled depending
on the available CRIU version.

c/r: drop in-flight connections during CRIU dump

---

src/lxc/criu.c

This is a minimal commit which makes the function 'do_restore()' static
as it is not used anywhere else in the code. This also removes a
trailing space my editor complained about.

c/r: make local function static

---

src/lxc/lxccontainer.c
src/lxc/utils.c
src/lxc/utils.h

This is required by systemd to cleanly shutdown. Other init systems should not
have SIGRTMIN+3 in the blocked signals set.

[RFC]: lxccontainer: detect if we should send SIGRTMIN+3

---

src/lxc/criu.c

Fixes build failures on arm:
criu.c: In function ‘exec_criu’:
criu.c:310:4: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Werror=format=]
ret = sprintf(ghost_limit, "%lu", opts->user->ghost_limit);
^
In file included from criu.c:42:0:
log.h:285:9: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Werror=format=]
struct lxc_log_locinfo locinfo = LXC_LOG_LOCINFO_INIT;  \
^
criu.c:312:5: note: in expansion of macro ‘ERROR’
ERROR("failed to print ghost limit %lu", opts->user->ghost_limit);
^

c/r: use PRIu64 format specifier

---

config/templates/alpine.common.conf.in

When running under grsecurity kernel or userns, it can't be mounted from inside.

lxc-alpine: mount tmpfs under /run

---

src/lxc/cgfsng.c

Both functions advertise that they return true when strncmp() == 0 and false
when strncmp() != 0 but so far they returned the exact opposite.

cgfsng: fix is_lxcfs() and is_cgroupfs()

---

lxc.pc.in

This allows installing to different locations and using
the lxc.pc to build using the generated includedir and
libdir.
Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

Add a prefix to the lxc.pc

---

src/lxc/bdev/bdev.h

Fixes android build error:
bdev/bdev.c: In function 'detect_fs':
bdev/bdev.c:686:2: error: implicit declaration of function 'getline' [-Werror=implicit-function-declaration]
while (getline(&line, &linelen, f) != -1) {
^

bdev: include own getline function in bdev.h

---

src/lxc/attach.c

The process created by lxc-attach has incorrect cgroup ns. It fails lxc-checkpoint as reported in [criu issue](https://github.com/xemul/criu/issues/174).
A real example for this issue, which is used to update ip address:
1. start lxc instance with debian image
2. lxc-attach -n <lxc name> -- service networking restart
3. lxc-checkpoint -n <lxc name> -D <dump dir>
lxc-checkpoint will fail because dhclient process has incorrect cgroup ns. It needs to use setns instead of unshare to set cgroup ns. "setns" already supports cgroup ns in kernel of ubuntu 16.04.

setns instead of unshare in lxc-attach

---

src/lxc/conf.c

This fixes a double free corruption on container-requested
reboots when lxc_spawn() fails before receiving the ttys, as
lxc_fini() (part of __lxc_start()'s cleanup) calls
lxc_delete_tty().

conf: set pty_info to NULL after free

---

src/lxc/tools/lxc_attach.c

Attaching to a container with a configuration file in a non standard path used to work. We used it for template building. With the pty allocation changes this stopped because that part of the code uses the configuration struct, and has a new check which then errors with `container XY is not defined`. This patch copies over the `-f` switch from `lxc-start`. Alternatively it might be possible to restore support for the old config-less variant, but it seems to make more sense to just provide the same config path as was used with `lxc-start`.

lxc-attach: add -f option & cleanup

---

templates/lxc-alpine.in

We are adding support for both armv7 and aarch64 architectures to Alpine Linux. We do not have official repositories yet but they will come with next Alpine release.

templates: add support for new arch on Alpine Linux

---

src/lxc/bdev/lxcloop.c
src/lxc/cgroups/cgfs.c
src/lxc/cgroups/cgfsng.c
src/lxc/conf.c
src/lxc/confile.c
src/lxc/lxccontainer.c
src/lxc/start.c
src/lxc/utils.c

To clarify the motivation behind this PR: `glibc 2.24` has deprecated `readdir_r()` (https://lwn.net/Articles/696469/) and some users already report that they can't compile the `LXC` sources because of that. So we should replace `readdir_r()` with `readdir()`. The problem however is that POSIX currently doesn't require that `readdir()` be thread-safe but it seems all of the relevant `libc`s actually provide a version of `readdir()` that is thread-safe. At least when multiple threads read from different `DIR` streams.
closes #1117.

tree-wide: replace readdir_r() with readdir()

---

src/lxc/log.c

Log output currently looks like this:
lxc-copy: debbdev/lxcdir.c: dir_clonepaths: 45 directories cannot be snapshotted.  Try aufs or overlayfs.
we rather want it to be:
lxc-copy: deb: bdev/lxcdir.c: dir_clonepaths: 45 directories cannot be snapshotted.  Try aufs or overlayfs.

log: fix log_append_stderr()

---

src/lxc/bdev/lxcbtrfs.c
src/lxc/bdev/lxcbtrfs.h
src/lxc/lxccontainer.c

When a container c is on a btrfs filesystem but is directory backed, copying the container will default to snapshot. This is because of should_default_to_snapshot() returning true in this case because c is on a
btrfs filesystem. We should make sure that should_default_to_snapshot() only returns true, when c itself is a btrfs subvolume.
closes  #1124.

bdev: be smarter about btrfs subvolume detection

---

src/lxc/tools/lxc_copy.c

So far we accidently used close() on the original file descriptor. (After
fdopen() the original fd is considered private and should not be used anymore.
The close operations should be performed on the new file handle. We did the
correct thing on error but not on success.) Using close() on the original fd
caused "Text file busy" errors and prevented the cloned tmpfs container from
starting.

tools: use fclose() after fdopen() + add newline

---

src/lxc/Makefile.am
src/tests/Makefile.am
src/tests/lxc-test-utils.c
src/tests/lxctest.h

This adds two simple test macros (We can add more later.). The main macro calls `abort()` to generate a core-dump. I'm happy to discuss other approaches.

[RFC] add minimal unit testing for liblxc functions

---

src/lxc/bdev/lxcoverlay.c

- Assume that the module name is "overlay" per default and not "overlayfs".
- Assume that the overlay version we are using requires a workdir.
- When we mount an overlay filesystem and we fail with ENODEV retry once with
the module name we haven't already used.

bdev: use correct overlay module name

---

doc/common_options.sgml.in
src/lxc/arguments.c
src/lxc/arguments.h
src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_cgroup.c
src/lxc/tools/lxc_checkpoint.c
src/lxc/tools/lxc_console.c
src/lxc/tools/lxc_copy.c
src/lxc/tools/lxc_destroy.c
src/lxc/tools/lxc_device.c
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_freeze.c
src/lxc/tools/lxc_info.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_snapshot.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_top.c
src/lxc/tools/lxc_unfreeze.c
src/lxc/tools/lxc_usernsexec.c
src/lxc/tools/lxc_wait.c

I put the `c->configfile` change into a separate commit - I'm unsure whether it would be a better idea to add a call for that or even let `c->load_config()` handle this, but that could be a potentially breaking change for some library users, so for now I went with just setting it directly.

Rcfile as common arg

---

src/lxc/confile.c
src/lxc/seccomp.c
src/lxc/utils.h
templates/lxc-debian.in

This PR adds MIPS support to the various parts of LXC.
While I'm pretty confident about the 1st and 3rd commits, the 2nd commit which implements seccomp handling required some bigger changes to get it to work with MIPS's 3 ABIs. I'm very open to alternate ways of implementing this.

Add MIPS support

---

src/lxc/seccomp.c

Tested on physical `s390x` host with
`lxc.seccomp = /usr/local/var/lib/lxc/test/seccomp_test`
set in the containers config. `seccomp_test` contained
```
2
blacklist
mknod errno 0
.fi
```

seccomp: add support for s390x

---

templates/lxc-slackware.in

mksh can't redirect fd 200, use 9
this PR is to catch up mksh changes from 17abf27

use fd 9 instead of 200

---

templates/lxc-fedora.in

/usr/share/lxc/templates/lxc-fedora: line 1078: openssl: command not found

templates: fedora requires openssl binary

---

src/lxc/criu.c

All we really needed a unique temp file for was passing the pid. Since CRIU
opened this with O_EXCL | O_CREAT, this was "safe" (users could still
overwrite it afterwards, but the monitor would immediately die since the
only valid number in there was the init process).
In any case, we can just read /proc/self/tid/children, which lists the
child process.
Closes #1150

c/r: use /proc/self/tid/children instead of pidfile

---

doc/api/Doxyfile

otherwise the generated docs have the full build path in them
and nonbody cares that the files were built in
/build/lxc-_BVY2u/lxc-2.0.4/src/lxc/

set FULL_PATH_NAMES=NO in doc/api/Doxyfile

---

templates/lxc-debian.in
templates/lxc-oracle.in

Given commit 330ae3d350e060e5702a0e5ef5d0faeeeea8df6e:
lxccontainer: detect if we should send SIGRTMIN+3
This is required by systemd to cleanly shutdown. Other init systems should not
have SIGRTMIN+3 in the blocked signals set.
we should stop symlinking halt.target to sigpwr.target for systemd.

templates: rm halt.target -> sigpwr.target symlink

---

templates/lxc-debian.in

An incorrect quoting introduced in bf39edb caused a /{lib,etc} folder to
appear in Debian templates
The very next line :
mkdir -p "${rootfs}/etc/systemd/system/getty.target.wants
makes creating ${rootfs}/etc/systemd/system/ unnecessary in the first
place

templates: remove creation of bogus directory in Debian templates

---

src/lxc/console.c

lxc_console is used with lxc_console.c

console: use correct log name

---

configure.ac

-Werror may break builds on some scenarios with trivialities
(especially during developments).

configure: add --disable-werror

---

src/lxc/bdev/lxczfs.c

- We expect destroy to fail in zfs_clone() so try to silence it so users are
not irritated when they create zfs snapshots.
- Add -r recursive to zfs_destroy(). This code is only hit when a) the
container has no snapshots or b) the user calls destroy with snapshots. So
this should be safe. Without -r snapshots will remain.

lxczfs: small fixes

---

src/lxc/lxccontainer.c

2cb80427bc468f7647309c3eca66cfc9afa85b61 introduced a malloc without a
matching free.

c/r: free valid_opts if necessary

---

src/lxc/bdev/lxcrsync.c

Without this switch, `lxc-snapshot` will inappropriately inflate sparse files that are stored in containers.
I guess this is pretty straight forward, tell me if you need a detailed example.

make rsync deal with sparse files efficiently

---

configure.ac
doc/lxc.container.conf.sgml.in
src/lxc/attach.c
src/lxc/attach_options.h
src/lxc/conf.h
src/lxc/confile.c
src/lxc/start.c
src/tests/Makefile.am
src/tests/lxc-test-no-new-privs

start: set PR_SET_NO_NEW_PRIVS when requested
- Set no_new_privs after setting the lsm label. If we do set it before we aren't
allowed to change the label anymore.
attach: use PR_SET_NO_NEW_PRIVS
- When we detect that the container, we want to attach to, has been stared with
PR_SET_NO_NEW_PRIVS we attach with PR_SET_NO_NEW_PRIVS as well. (We might
relax this restriction later but let's be strict for now.)
- When LXC_ATTACH_NO_NEW_PRIVS is set in the flags passed to
lxc_attach()/attach_child_main() then we set PR_SET_NO_NEW_PRIVS irrespective
of whether the container was started with PR_SET_NO_NEW_PRIVS or not.

implement PR_SET_NO_NEW_PRIVS in liblxc

---

templates/lxc-debian.in

Template catches arch from uname -m, but for ppc64el system, arch reports ppc64le
which doesn't match image repo.
Signed-off-by: Thierry Fauck <tfauck@free.fr>

lxc-create -t debian fails on ppc64el arch

---

src/lxc/conf.c

This solves a problem for root started containers. Previously they reset any value set on `netdev->link`.

2016 09 21/retrieve mtu from bridge

---

src/lxc/tools/lxc_attach.c

Discovered while trying to invoke lxc through salt stack. If ```lxc_console_peer_default``` fails to allocate the peer (```src/lxc/console.c +432```) then``` ts``` is unset and will segfault on close. 
Signed-off-by: Oliver Matthews <oliver@codersoffortune.net>

Fix null derefence if attach is called without access to any tty

---

templates/lxc-altlinux.in

Use 'apt-conf' virtual package for ALTLinux default packages set
Signed-off-by: Denis Pynkin <denis_pynkin@epam.com>

Fix for ALTLinux container creation in all branches

---

src/lxc/utils.c

Make sure we always free any memory that was allocated by the call to
lxc_normalize_path().

utils: lxc_deslashify() free memory

---

templates/lxc-centos.in
templates/lxc-download.in

Fix spelling of CentOS in the templates
Signed-off-by: Roman Mueller <roman.mueller@gmail.com>

Fix spelling of CentOS in the templates

---

src/lxc/tools/lxc-checkconfig.in

Only check for DEVPTS_MULTIPLE_INSTANCES on kernels < 4.7.
Closes #1215.

tools: lxc-checkconfig conditionalize devpts check

---

src/python-lxc/examples/api_test.py
src/python-lxc/examples/pyconsole-vte.py
src/python-lxc/examples/pyconsole.py

this allows running them also under Python2, which otherwise
would choke on Stéphane's name and error out with
SyntaxError: Non-ASCII character '\xc3' in file …

mark the python examples as having utf-8 encoding

---

src/lxc/log.c

The returned value from snprintf() should be checked carefully.
This bug can be leveraged to execute arbitrary code through carefully
constructing the payload, e.g,
lxc-freeze -n `python -c "print 'AAAAAAAA' + 'B'*959"` -P PADPAD -o /tmp/log
This command running on Ubuntu 14.04 (x86-64) can cause a segment fault.
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>

log: sanity check the returned value from snprintf()

---

src/lxc/arguments.h
src/lxc/lxc.h

lxc_strerror() was dropped long time ago, in 2009 to be exact.
Related commit:
https://github.com/lxc/lxc/commit/7cee8789514fb42d6a48d50b904e24284f5526e3
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Drop leftover references to lxc_strerror().

---

src/tests/lxc-test-apparmor-mount
src/tests/lxc-test-autostart
src/tests/lxc-test-unpriv
src/tests/lxc-test-usernic.in
templates/lxc-ubuntu-cloud.in

Make release selection more flexible with the algorithm in templates/lxc-ubuntu-cloud.in
Update the KNOWN_RELEAES list, add yakkety and remove vivid.
This closes issue #1231 

tests: fix image download for s390x

---

src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_copy.c

Closes https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1591513.
Closes #1076.

tools: make overlay a valid backend for lxc-copy

---

src/lxc/tools/lxc_start.c

Closes https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1302053.

tools: better error reporting for lxc-start

---

config/templates/alpine.common.conf.in

@brauner I’m not entirely sure about this, could you please answer me two questions?
1. Am I right that `setfcap` is not a security risk, i.e. it cannot be abused to escape from container to the host system?
2. Is it true that `setcap` cannot work in unprivileged containers (i.e. containers that uses user namespace) anyway, only in privileged ones?

lxc-alpine: do not drop setfcap

---

src/lxc/seccomp.c

There are no personalities for s390x, so don't list itself as one.

s390x: Fix seccomp handling of personalities

---

src/lxc/tools/lxc_copy.c

Correct the backingstorage typo in lxc_copy.
This fixes https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1591510

tools: correct the argument typo in lxc_copy

---

src/lxc/criu.c

FWIW, the --external flag is new as of 2.6, so I don't think any of this should be SRU'd into xenial until CRIU 2.6 is.

Use external

---

lxc.spec.in

* use python3_sitearch for including the python code (closes #502)
* include all built files, but only once, otherwise rpmbuild fails because files are either installed twice or not at all

RPM build fixes

---

doc/ja/lxc-ls.sgml.in
doc/ko/lxc-ls.sgml.in
doc/lxc-ls.sgml.in
src/lxc/tools/lxc_ls.c

* improve help text for --fancy and --fancy-format
* improve wording for --fancy-format on the help page for lxc-ls

lxc-ls help fixes

---

src/lxc/tools/lxc_stop.c

When the container is already running our manpage promises to exit with 2.
Let's make it so.
Closes #1263.

tools: use correct exit code for lxc-stop

---

src/lxc/conf.c
src/lxc/conf.h
src/lxc/start.c

On shutdown we move physical network interfaces back to the
host namespace and rename them afterwards as well as in the
later lxc_network_delete() step. However, if the device had
a name which already exists in the host namespace then the
moving fails and so do the subsequent rename attempts. When
the namespace ceases to exist the devices finally end up
in the host namespace named 'dev<ID>' by the kernel.
In order to avoid this, we do the moving and renaming in a
single step (lxc_netdev_move_by_*()'s move & rename happen
in a single netlink transaction).

conf: merge network namespace move & rename on shutdown

---

templates/lxc-voidlinux.in

All the other templates use `#!/bin/bash`

cleanup: /usr/bin/bash vs /bin/bash consistency

---

src/lxc/lxccontainer.c

This would already fail, but with a not-as-good error message. Let's make
the error better.

c/r: check state before doing a checkpoint/restore

---

src/lxc/cgroups/cgfs.c

- cgfs: add `print_cgfs_init_debuginfo()`: When `LXC_DEBUG_CGFS=1` is set, debug information will be printed.
- cgfs: skip empty entries under `/proc/self/cgroup`: If cgroup v2 is enabled either alone or together with legacy hierarchies `/proc/self/cgroup` can contain entries of the form:
```
0::/
```
These entries need to be skipped.
- cgfs: explicitly check for `NULL`
Somehow this implementation of a cgroupfs backend decided to use the hierarchy numbers it detects in `/proc/cgroups` and `/proc/self/cgroups` as indices for the hierarchy struct. Controller numbering usually starts at `1` but may start at `0` if:
a) the controller is not mounted on a cgroups v1 hierarchy;
b) the controller is bound to the cgroups v2 single unified hierarchy; or
c) the controller is disabled
To avoid having …

cgfs: various fixes

---

templates/lxc-centos.in

this patch create /var/run link to point to /run.
This will fix various issue present when /var/run is persistent.

create symlink for /var/run

---

src/lxc/cgroups/cgfsng.c

cgroups: skip v2 hierarchy entry

---

.gitignore

add lxc.egg-info to gitignore

---

config/init/sysvinit/lxc-net.in

there is no reason to not do this :)

also stop lxc-net in runlevels 0 and 6

---

src/lxc/conf.c

This is a GNU extension and some libcs might be missing it.
As observed in #1296.

conf: do not use %m format specifier

---

templates/lxc-debian.in

This package doesn't exist in stretch anymore, and it's unclear why we
were depending on a library to begin with (as opposed to having it
brought by whatever needs it).

debian: Don't depend on libui-dialog-perl

---

src/lxc/criu.c
src/lxc/tools/lxc_checkpoint.c

CRIU supports dirty memory tracking to take incremental checkpoints.
Incremental checkpoints are one way of reducing downtime during
migration. The first checkpoint dumps all the memory pages and the
second (and third, and fourth, ...) only dumps pages which have changed.
Most of the necessary code has already been implemented. This just adds
the existing functionality to lxc-checkpoint:
-p, --pre-dump            Only pre-dump the memory of the container.
Container keeps on running and following
checkpoints will only dump the changes.
--predump-dir=DIR         path to images from previous dump (relative to -D)
The following is an example from a container running CentOS 7 with psql
and tomcat:
Container keeps on running
229M	/tmp/cp
Sync initial checkpoint to destination
Sync file-system …

lxc-checkpoint: enable dirty memory tracking in criu

---

src/lxc/cgroups/cgfsng.c

Fixes https://launchpadlibrarian.net/293453637/buildlog_ubuntu-xenial-armhf.lxc_2.0.5+master~20161114-2016-0ubuntu1~xenial_BUILDING.txt.gz and related build failures.

cgroups: use %zu format specifier to print size_t

---

src/lxc/criu.c

With the criu release 2.8 criu deprecated the --veth-pair command-line
option in favor of --external:
f2037e6 veth: Make --external support --veth-pair
git tag --contains f2037e6d3445fc400
v2.8
With this commit lxc-checkpoint will automatically switch between
the new and old command-line option dependent on the detected
criu version.
For criu version older than 2.8 something like this will be used:
--veth-pair eth0=vethYOK6RW@lxcbr0
and starting with criu version 2.8 it will look like this:
--external veth[eth0]:vethCRPEYL@lxcbr0

lxc-checkpoint: automatically detect if --external or --veth-pair

---

src/lxc/cgroups/cgfsng.c

When we set LXC_DEBUG_CGFSNG=1 we print out info about detected cgroup
hierarchies. When there's no named cgroup mounted we need to make sure that we
don't try to index an unallocated pointer.

cgroups: prevent segfault in cgfsng

---

src/lxc/cgroups/cgfsng.c

- add more logging
- only write to cpuset.cpus if we really have to
- simplify cleanup on error and success

cgroup: improve isolcpus handling

---

src/lxc/arguments.h
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/lxc_monitord.c
src/lxc/start.c
src/lxc/tools/lxc_autostart.c
src/lxc/tools/lxc_console.c
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_top.c
src/lxc/utils.c
src/lxc/utils.h
src/tests/lxc-test-utils.c

Has been sitting in my tree for a while now.
Replace by two custom functions:
```
lxc_safe_uint()
```
and
```
lxc_safe_int()
```
Should make things safer by switching a few types and adhering more to what we advertise for various keys in `man lxc.container.conf`.

remove atoi

---

src/tests/lxc-test-utils.c

They do not behave correctly on some architectures, so let's remove them for
now and come up with better ones later.
Fixes https://jenkins.linuxcontainers.org/view/All/job/lxc-build-android/1006/console.

tests: remove overflow tests

---

config/init/common/lxc-net.in
lxc.spec.in

Requires Linux >= 2.6.26. Prior to that, you could not set a fixed mac address on a bridge.
This is just a random MAC address, the maintainers of LXC should request a MAC Address Block Small assignment from the IEEE here: https://regauth.standards.ieee.org/standards-ra-web/app
Resolves #604

Configure a static MAC address on the LXC bridge

---

src/lxc/log.c

This fixes a race in liblxc logging which can lead to deadlocks. The reproducer
for this issue before this is to simply compile with --enable-tests and then
run:
lxc-test-concurrent -j 20 -m create,start,stop,destroy -D
which should deadlock.

log: use thread-safe localtime_r()

---

configure.ac
src/lxc/log.c

localtime_r() can lead to deadlocks because it calls __tzset() and
__tzconvert() internally. The deadlock stems from an interaction between these
functions and the functions in monitor.c and commands.{c,h}. The latter
functions will write to the log independent of the container thread that is
currently running. Since the monitor fork()ed it seems to duplicate the mutex
states of the time functions mentioned above causing the deadlock.
As a short termm fix, I suggest to simply disable receiving the time when
monitor.c or command.{c,h} functions are called. This should be ok, since the
[lxc monitor] will only emit a few messages and thread-safety is currently more
important than beautiful logs. The rest of the log stays the same as it was
before.
Here is an example output from logs where I …

log: fix race

---

configure.ac
src/lxc/tools/lxc_cgroup.c
src/lxc/tools/lxc_unshare.c
src/lxc/utils.c
src/tests/lxc-test-utils.c

They are pointless and marked optional since C11.

tree-wide: remove any variable length arrays

---

configure.ac
src/lxc/conf.c
src/lxc/conf.h
src/lxc/criu.c

Before we used tmpfile() to write out mount entries for the container. This
requires a writeable /tmp file system which can be a problem for Android where
this filesystem is not necessarily present. This commit switches from tmpfile()
to using the memfd_create() syscall. It allows us to create an anonymous tmpfs
file (And is somewhat similar to mmap().) which is automatically deleted as
soon as any references to it are dropped.
Closes #1296.

conf, criu: add make_anonymous_mount_file()

---

configure.ac

Because we include a header that uses a vla (/me scoffs at header).

configure: remove -Werror=vla

---

src/lxc/monitor.c

Execing lxc-monitord is quite a crucial step so let's be very obsessive about
logging possible errors to guide us in debugging.

monitor: add more logging

---

src/lxc/conf.c

The thread-unsafe functions strsignal() is called in run_buffer() which in turn
is called in run_buffer_argv() which is responsible for running __all__ lxc
hooks. This is pretty dangerous for multi-threaded users like LXD.

conf: remove thread-unsafe strsignal + improve log

---

src/lxc/lxccontainer.c

lxccontainer: log failure to send sig to init pid

---

src/lxc/log.c
src/lxc/log.h
src/lxc/utils.h

Our log functions need to make extra sure that they are thread-safe. We had
some problems with that before. This especially involves time-conversion
functions. I don't want to find any localtime() or gmtime() functions or
relatives in here. Not even localtime_r() or gmtime_r() or relatives. They all
fiddle with global variables and locking in various libcs. They cause deadlocks
when liblxc is used multi-threaded and no matter how smart you think you are,
you __will__ cause trouble using them.
(As a short example how this can cause trouble: LXD uses forkstart to fork off
a new process that runs the container. At the same time the go runtime LXD
relies on does its own multi-threading thing which we can't control. The
fork()ing + threading then seems to mess with the locking states in these …

log: drop all timezone conversion functions 

---

src/lxc/attach.c
src/lxc/bdev/bdev.c
src/lxc/bdev/bdev.h
src/lxc/cgroups/cgfsng.c
src/lxc/commands.h
src/lxc/conf.c
src/lxc/genl.c
src/lxc/log.c
src/lxc/monitor.c
src/lxc/nl.h
src/lxc/tools/lxc_checkpoint.c
src/lxc/tools/lxc_init.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_start.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_usernsexec.c
src/lxc/utils.c
src/lxc/utils.h
src/tests/concurrent.c
src/tests/lxc-test-utils.c

Some random macro-cleanups that came to my attention during the deadlock fixes over the last few days.

tree-wide: random macro cleanups

---

src/lxc/log.c

- single digit months, days, hours, minutes, and seconds should always be
preceded by a 0.

log: make sure that date is correctly formatted

---

src/lxc/tools/lxc_start.c

Same change as in 6118210e0a which was missing in lxc-start
and back then is_defined() wasn't being called.

tools: lxc-start: set configfile after load_config

---

src/lxc/conf.c

conf: clearly report to either use drop or keep

---

templates/lxc-debian.in

Commit bf39edb39ecaea25801d716aebef798885277992 broke the handling of the getty service file with an '@' character in filename. So the startup condition was not fixed.
Because the parameter was quoted with the causal commit, the escaping has to be removed.
Signed-off-by: Andreas Eberlein foodeas@aeberlein.de

templates: fix getty service startup

---

src/lxc/attach.c
src/lxc/conf.c

Save errno across some calls to close() since it can be
interrupted.
Signed-off-by: Wolfgang Bumiller <wry.git@bumiller.com>

conf, attach: save errno across call to close

---

templates/lxc-debian.in

* Fix typo in calling dpkg with --print-foreign-architectures option
* handle ppc hostarch -> powerpc Debian arch

Debian: powerpc and architecture fixes

---

templates/lxc-opensuse.in

This updates lxc-opensuse template to include Leap 42.2 and changes the default release to 42.2. Some checks related to `[ $DISTRO == "leap/42.1 ]"` to `[[ $DISTRO == "leap/4"* ]]`  were changed so it can accomodate future releases a little bit better.
I'm not exactly sure if the following should be in separate pull requests:
* 3ddfde2 uncomments `lxc.aa_profile = unconfined` by default to resolve startup failures on openSUSE based containers
- Sorry, I don't know any other way to fix this without compromising security.
* e080c49 removes libgcc_s1 from preinstalled packages as this was causing container creation to fail
- Related: opensuse/obs-build#188.

templates: update openSUSE release to 42.2

---

src/lxc/confile.c

Enable lxc network config support the following type and link:
lxc.network.type = phys
lxc.network.link = eth*
Thus, when lxc find any network interfaces name prefixed
with "eth" such as "eth0", "eth1" and so on, it will
try to move them the container's namespace; If it didn't
find any matching, it would do nothing for this configure
line.
Signed-off-by: fli <fupan.li@windriver.com>

confile: support the network link string pattern matching

---

configure.ac

Previously HAVE_LIBGNUTLS was never set in config.h even if gnutls was
detected as AC_CHECK_LIB default action-if-found was overriden by
enable_gnutls=yes
This patch adds an --enable-gnutls option and will call AC_CHECK_LIB
with the default action to write HAVE_LIBGNUTLS in config.h
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

Add --enable-gnutls option

---

src/tests/lxc-test-unpriv

This mainly affects Trusty. The 3.13 kernel has a broken overlay module which
does not handle symlinks correctly. This is a problem for containers that use
an overlay based rootfs since `safe_mount()` uses `/proc/<pid>/fd/<fd-number>` in
its calls to `mount()`.

tests: skip unpriv tests on broken overlay module

---

src/lxc/conf.c

We need to remove the newline otherwise lxc_safe_uint() will fail as it detects
an invalid (non-numeric) char in the string.

conf: fix suggest_default_idmap()

---

src/python-lxc/examples/api_test.py

The api_test.py script uses Trusty release by default, which does not
have s390x image. Switch to Xenial to solve this.
This fixes #1377

python3-lxc: fix api_test.py on s390x

---

src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_copy.c
src/lxc/tools/lxc_create.c
src/lxc/tools/lxc_snapshot.c
src/lxc/tools/lxc_start.c

On some Android systems the lxc folders where containers are stored might be
read-only and so checking for O_RDWR, will effectively make the tools useless
on these systems, so let's dumb the check down to O_RDONLY.

tools: only check for O_RDONLY

---

src/lxc/caps.c
src/lxc/caps.h
src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h

lxc_execute() and lxc-execute where broken when a user tried to switch to a
non-root uid/gid. This prevented necessary setup operations like mounting the
rootfs which require root in the user namespace. This commit separates
switching to root in the user namespace from switching to the requested uid/gid
by lxc_execute().
This should be safe: Once we switched to root in the user namespace via
setuid() and then switch to a non-root uid/gid in the user namespace for
lxc_execute() via setuid() we cannot regain root privileges again. So we can
only make us safer (Unless I forget about some very intricate user namespace
nonsense; which is not as unlikely as I try to make it sound.).
Closes https://github.com/lxc/lxc/issues/1176.

start: fix execute and improve setgroups() calls

---

src/lxc/tools/lxc_start.c

We do not check here whether the container is defined, because we support
volatile containers. Which means the container does not need to be created for
it to be started. You can just pass a configuration file as argument and start
the container right away.

tools/lxc-start: remove c->is_defined(c) check

---

config/init/sysvinit/lxc-containers.in

otherwise init might try to start the containers before cgroupfs was mounted.
Debian-Bug: https://bugs.debian.org/850212

add cgroupfs-mount to Should-Start/Stop sysvinit LSB headers

---

configure.ac
src/lxc/bdev/lxclvm.c
src/lxc/conf.c
src/lxc/lxccontainer.c

Before the change build failed on Gentoo as:
bdev/lxclvm.c: In function 'lvm_detect':
bdev/lxclvm.c:140:4: error: implicit declaration of function 'major' [-Werror=implicit-function-declaration]
major(statbuf.st_rdev), minor(statbuf.st_rdev));
^~~~~
bdev/lxclvm.c:140:28: error: implicit declaration of function 'minor' [-Werror=implicit-function-declaration]
major(statbuf.st_rdev), minor(statbuf.st_rdev));
^~~~~
glibc plans to remove <sys/sysmacros.h> from glibc's <sys/types.h>:
https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html
Gentoo already applied glibc patch to experimental glibc-2.24
to start preparingfor the change.
Autoconf has AC_HEADER_MAJOR to find out which header defines
reqiured macros:
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Hea …

Use AC_HEADER_MAJOR to detect major()/minor()/makedev()

---

src/lxc/tools/lxc-start-ephemeral.in

On Ubuntu 12.04 LTS with Python 3.2, `lxc-start-ephemeral` breaks as
follows:
Traceback (most recent call last):
File "/usr/bin/lxc-start-ephemeral", line 371, in attach_as_user
File "/usr/lib/python3.2/subprocess.py", line 515, in check_output
File "/usr/lib/python3.2/subprocess.py", line 732, in __init__
LookupError: unknown encoding: ANSI_X3.4-1968
This is because `universal_newlines=True` causes `subprocess` to use
`io.TextIOWrapper`, and in versions of Python earlier than 3.3 that
fetched the preferred encoding using `locale.getpreferredencoding()`
rather than `locale.getpreferredencoding(False)`, thereby changing the
locale and causing codecs to be reloaded.  However, `attach_as_user`
runs inside the container and thus can't rely on having access to the
same Python standard library …

Make lxc-start-ephemeral Python 3.2-compatible

---

templates/lxc-opensuse.in

The template scripts assumes that DISTRO should contain leap/4* when dealing with Opensuse Leap releases, but the default value did not contain the leap/ prefix

lxc-opensuse: fix default value for release code

---

src/lxc/confile.c

confile: clear lxc.network.<n>.ipv{4,6} when empty

---

config/init/common/lxc-net.in

I found that even though the service lxc-net failed to start because I made some wrong configuration
settings the command exists zero.
So systemd reports the status of the service as good even though it failed:
● lxc-net.service - LXC network bridge setup
Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled)
Active: active (exited) since Wed 2017-02-08 08:17:32 EST; 21min ago
Process: 529 ExecStart=/usr/lib/x86_64-linux-gnu/lxc/lxc-net start (code=exited, status=0/SUCCESS)
Main PID: 529 (code=exited, status=0/SUCCESS)
CGroup: /system.slice/lxc-net.service
Feb 08 08:17:30 dvm2 systemd[1]: Starting LXC network bridge setup...
Feb 08 08:17:32 dvm2 lxc-net[529]: dnsmasq: failed to create listening socket for 10.2.2.1: Address already in use
Feb 08 08:17:32 dvm2 lxc-net[529]: Failed to …

Make lxc-net return non-zero on failure

---

configure.ac
src/lxc/caps.c
src/lxc/caps.h
src/lxc/conf.c
src/lxc/start.c

Currently it is impossible to build lxc with --disable-capabilities if
the user has libcap-dev installed on his system as:
- calls to cap_xxx functions are not protected by HAVE_LIBCAP defines.
The whole file is only protected by HAVE_SYS_CAPABILITY_H.
- AC_CHECK_LIB default action-if-found is overriden by [true] so
HAVE_LIBCAP is never written to config.h
This patch replaces all HAVE_SYS_CAPABILITY_H checks by HAVE_LIBCAP
checks (fix #1361)

Add HAVE_LIBCAP

---

src/lxc/seccomp.c

While lxc has x32 support, it currently works only "natively" when the host runs amd64 kernel x32 userspace.  This patch fixes the more common case of regular amd64 on the host.
Tested only atop of current Debian package (2.0.7).

fix seccomp blocking x32 guests on amd64 (userspace) hosts

---

templates/lxc-sabayon.in

The script is full of bashisms making it break when run with a simple
POSIX shell.

sabayon: Use /bin/bash

---

templates/lxc-fedora.in

The latest adjustments and refactoring to HTTPS by default in the `lxc-fedora` template introduced some regressions for the case the template is run on a non-Fedora host where an intermediate bootstrap setup is required. This case was now properly tested and fixed.
This PR should likely also fix lxc/lxc-ci#13.

Various fixes for Fedora bootstrapping on non-Fedora hosts

---

src/lxc/criu.c

The rest of the mounts can be restored normally.

c/r: only supply --ext-mount-map for bind mounts

---

hooks/clonehostname

Previously this hook did not work when cloning containers using an overlayfs snapshot as the LXC_ROOTFS_PATH didn't point to the actual filesystem that the container would see. LXC_ROOTFS_MOUNT should be used instead and in fact lxc.container.conf man page says that you usually would want to use the _MOUNT variant.

Fix issue with the clonehostname hook not working for overlayfs snapshot clones

---

src/lxc/log.c

The conversion algorithm used uses a clever trick by letting a year start at 1
March. So we need to add 1 for January and February.

log: fix lxc_unix_epoch_to_utc()

---

src/lxc/cgroups/cgfsng.c

cgfsng: make trim() safer

---

src/lxc/seccomp.c

Newer libseccomp has a flag called SCMP_FLTATR_ATL_TSKIP which
allows syscall '-1' (nop) to be executed.  Without that flag,
debuggers cannot skip system calls inside containers.  For reference,
see the seccomp(2) manpage, which says:
The tracer can skip the system call by changing the system call  number  to  -1.
and see the seccomp issue #80

seccomp: set SCMP_FLTATR_ATL_TSKIP if available

---

src/lxc/cgroups/cgfs.c

This allows us to run LXC containers from within docker

Added 'mkdir -p' functionality in create_or_remove_cgroup

---

templates/lxc-download.in

In some environments, outgoing port 11371 (HKP:// port) is blocked.
Manually specifying the key server on every `lxc-create` operation should not be necessary in these cases.
This change allows the variable holding the URL to the key server to be set in the environment, for example through `.bashrc` or `.profile`

Allow setting the key server as an environment variable

---

templates/lxc-altlinux.in
templates/lxc-gentoo.in
templates/lxc-openmandriva.in
templates/lxc-pld.in

don't set a default password for altlinux, gentoo, openmandriva and pld

---

src/lxc/lxccontainer.c

tree-wide: include <sys/sysmacros.h> directly

---

src/lxc/conf.c

Fixing the typo making `suggest_default_idmap` open `subuidfile` instead of `subgidfile` to read subgid information.

Fix opening wrong file in suggest_default_idmap

---

src/lxc/conf.c

In case of a container that is rebooting, freeing veth.pair.name here results in losing given veth.pair name
(Only if given lxc_netdev is reused).
Signed-off-by: Torsten Fohrer <tfohrer@googlemail.com>
issue #1477

Keep veth.pair.name on network shutdown

---

src/lxc/Makefile.am
src/lxc/tools/lxc_execute.c

tools: exit with return code of lxc_execute()

---

config/init/common/lxc-containers.in

Don't wait for bridge if disabled via USE_LXC_BRIDGE
Signed-off-by: Torsten Fohrer <tfohrer@googlemail.com>

Avoid waiting for bridge interface on bootup

---

src/lxc/tools/lxc_info.c

Some "/sys" entries exceeds buffer size.
This results to some statistics loss ('BlkIO' in particular):
wc -c /sys/fs/cgroup/blkio/lxc/alt/blkio.throttle.io_service_bytes
318 /sys/fs/cgroup/blkio/lxc/alt/blkio.throttle.io_service_bytes
Signed-off-by: Denis Pynkin <dans@altlinux.org>

Increased buffer length in print_stats()

---

templates/lxc-altlinux.in
templates/lxc-busybox.in
templates/lxc-debian.in
templates/lxc-gentoo.in
templates/lxc-openmandriva.in
templates/lxc-opensuse.in
templates/lxc-oracle.in
templates/lxc-plamo.in
templates/lxc-slackware.in
templates/lxc-sparclinux.in

ohai,
this is a backport of #973, #1358 and #1474 for `stable-2.0` as discussed in #1418.
with that merged I think we can close #1158 for good

[stable-2.0] default password cleanup

---

src/lxc/console.c
src/lxc/console.h
src/lxc/lxc_attach.c
src/lxc/start.c

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10124
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-10124

stable-1.0: backport fixes for CVE-2016-10124

---

templates/lxc-alpine.in

By making Alpine template more POSIX shell friendly, bug #1498 is solved
Signed-off-by: Vincent Catros <vincent.catros@laposte.net>

make Alpine template more POSIX shell friendly #1498

---

README

Since LXC is at version 2 now, this should probably be removed.

remove obsolete note about api stability

---

configure.ac
doc/lxc.container.conf.sgml.in
src/lxc/attach.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/start.c
src/tests/get_item.c

Currently containers inherit the resource limits of the process starting them, but it can be useful to configure them explicitly.
If for instance a container can be started via a system service or manually via `lxc-start` or some wrapper, these 2 ways of starting the container can end up giving it different limits. Both have the option to change the limits before starting, but if they do not have `CAP_SYS_RESOURCE` or are unprivileged they won't be able to raise them back up if they lowered them and would have to resort to forking first.
Limits which aren't explicitly specified will be inherited as before, so the default behavior stays the same.
As usual the last specified value for a limit takes precedence, specifying an empty value deletes it (iow. declares it as to be inherited as …

Resource Limits

---

src/lxc/start.c

(The code was moved here from the child side of the startup
without adapting the error case.)

start: fix error handling when limits fail to apply

---

src/lxc/tools/lxc_ls.c

In the following code 
```
if ( args->ls_active || (args->ls_active && args->ls_frozen))
```
`(args->ls_active && args->ls_frozen)` always false if `args->ls_active` is false.
so we can delete the second  judgment condition and only keep the first one.

ls: simplify the judgment condition when list active containers

---

src/lxc/caps.c
src/lxc/caps.h
src/lxc/conf.c
src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h

idmap improvements

---

configure.ac
src/lxc/caps.c
src/lxc/caps.h
src/lxc/conf.c

cf. the discussion on https://github.com/lxc/lxc/pull/1513

autotools: check for cap_get_file

---

src/lxc/bdev/lxcloop.c
src/lxc/conf.c
src/lxc/utils.c
src/lxc/utils.h

Use the loop device helpers I wrote for LXD in LXC as well. They should be more
efficient.

utils: use loop device helpers from LXD

---

.github/ISSUE_TEMPLATE.md
src/lxc/cgroups/cgfsng.c

In a lot of cases we need a list of the writeable cgroup controllers detected
by the cgfsng driver.

cgroups: improve cgfsng debugging

---

src/lxc/conf.c
src/lxc/utils.c
src/lxc/utils.h

Create /proc directory if it doesn't exist.
Closes #1475.

utils: tweak lxc_mount_proc_if_needed()

---

templates/lxc-sshd.in

A few things have changed and this patch makes container generated for sshd work in Ubuntu
Signed-off-by: Nikolay Martynov <mar.kolya@gmail.com>

Change sshd template to work with Ubuntu 17.04

---

src/lxc/lxccontainer.c
src/lxc/lxccontainer.h
src/tests/get_item.c

This adds lxc_config_item_is_supported() as API extension. It allows to check
whether a given config item (e.g. lxc.autodev) is supported by this LXC
instance. The function is useful in the following scenarios:
1. Users have compiled liblxc from source and have removed a config items from
the corresponding struct in confile.c. (For example, embedded users might
decide to gut a bunch of options that they cannot use.)
2. Callers that want to check for a specific configuration item independent of
the version numbers exposed in our version.h header.

[RFC] api extension: lxc_config_item_is_supported()

---

src/lxc/conf.c
src/lxc/start.c

I really fail to see the point of this and git {blame, log -S} don't really
enlighten me on the reason for this as well. But I might be dense. The way I
see it the only thing this line achieves is causing trouble when the container
is started as root because the umount2() call will umount e.g.
/usr/lib/x86_64-linux-gnu/lxc in case it is a mountpoint on the host. Note,
this is because lxc_spawn() is still called in the hosts namespaces.
Closes https://github.com/lxc/lxd/#3255.

start: remove umount2() 

---

src/lxc/start.c

So far, we somehow always called lxc_map_ids(), even when no id map was
configured. Let's not do this.
Closes #1555.

start: don't call lxc_map_ids() without id map

---

src/lxc/console.c
src/lxc/tools/lxc_attach.c

lxc-attach: allow for situations without /dev/tty

---

src/lxc/monitor.h

we want to export `monitor.h`, `#include "conf.h"` will cause error
and it is unneccessory so just delete it.

monitor: delete unneccessory include file

---

src/lxc/cgroups/cgfsng.c

This should save some debugging time.  Most often the user didn't *want* a non-standard setup, and it limits the use of unprivileged containers.

cgfsng: log when we defer to cgfsng

---

src/lxc/tools/lxc_top.c

This is patch fix output of memory+swap in batch mode, that
was forgotten in 6b6e702ac83a2bc92959c0dcae5149762826ef30
Signed-off-by: Alexandr Nevenchanniy <a.nevenchannyy@gmail.com

[lxc-top] Fix memory+swap output in batch mode

---

src/lxc/console.c

The 'ts->stdoutfd' did not fill with parameters 'stdoutfd', it used the default value "0".
I think we should fix that mistake.

Fix the bug of 'ts->stdoutfd' did not fill with parameters 'stdoutfd'

---

src/lxc/console.c

I think it is not necessary that  the 'stdin'  must be a tty device.  For example, we can pass a FIFO fd as the ‘stdin’ parameter, then we can do more flexible work on the container console.

DO NOT add the handles of adjust winsize when the 'stdin' is not a tty

---

src/lxc/conf.c

When we didn't create a net dev we should make sure that we don't delete it.  We
can simply check whether we have index for it. If not, we didn't create it.
Closes #1600.

network: don't delete net devs we didn't create

---

config/init/systemd/lxc@.service.in

Ever since 8eb62c2, systemd has not been able to cleanly stop lxc
containers (via lxc@) because it's still using SIGPWR for systemd-based
containers.
We should now use the nice logic in 330ae3d to stop the containers
instead.

Use lxc-stop to stop systemd service

---

src/lxc/conf.c

Because of unprivileged container cannot set MTU by configuration,
Adding a warning can be better.
Closing https://github.com/lxc/lxc/issues/1602
Signed-off-by: Shane Chen <ss1ha3tw@gmail.com>

adding warning for mtu ignoring

---

src/lxc/commands.c
src/lxc/confile.c
src/lxc/confile.h
src/lxc/lxccontainer.c
src/tests/Makefile.am
src/tests/parse_config_file.c

So this has grown into a major rework of the configuration system. My reasons for this are plenty most of all:
- there were/are a bunch of configuration items that had a set but no get method
- there were a bunch of configuration items that could not be cleared via the api
- adding new configuration items was error prone since the set method was enforced by the callback system but neither the get nor clear methods were
This changes to a new callback-based configuration system that is enforced via the lxc_config_t struct. If someone wants to implement a new configuration item things should now be more straightforward. To add a new configuration items one needs to:
- create a new member in the lxc_config_t struct and implement
1. a set method
2. a get method
3. a clear method
simple as …

confile: fix parsing

---

src/lxc/conf.c

Afaict, userns_exec_1() is only used to operate based on privileges for the
user's own {g,u}id on the host and for the container root's unmapped {g,u}id.
This means we require only to establish a mapping from:
- the container root {g,u}id as seen from the host -> user's host {g,u}id
- the container root -> some sub{g,u}id
The former we add, if the user did not specifiy a mapping. The latter we
retrieve from the ontainer's configured {g,u}id mappings.
Closes #1598.

conf: use minimal {g,u}id map

---

src/lxc/confile.c
src/tests/Makefile.am
src/tests/config_jump_table.c

This adds a test that checks LXC's configuration jump table whether all methods
for a given configuration item are implemented. If it is not, we'll error out.
This should provide additional safety since a) the API can now be sure that
dereferencing the pointer for a given method in the config struct is safe and
b) when users implement new configuration keys and forget to implement a
required method we'll see it right away.

tests: enforce all methods for config items being implemented

---

doc/lxc.container.conf.sgml.in
src/lxc/af_unix.c
src/lxc/af_unix.h
src/lxc/attach.c
src/lxc/bdev/bdev.c
src/lxc/bdev/bdev.h
src/lxc/bdev/lxcloop.c
src/lxc/bdev/lxclvm.c
src/lxc/bdev/lxcrbd.c
src/lxc/commands.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/start.c
src/lxc/tools/lxc_attach.c
src/lxc/utils.h

- Enable lxc_abstract_unix_{send,recv}_fd() to send and receive multiple fds at
once.
- lxc_abstract_unix_{send,recv}_fd() -> lxc_abstract_unix_{send,recv}_fds()
- Send tty fds from child to parent all at once.

abstract lxc_abstract_unix_{send,recv}_fd, bugfixes, and improvements

---

src/lxc/seccomp.c

when the log level is `TRACE`, this patch export the seccomp
filter to log file.
the ouput of `seccomp_export_pfc()` is human readable and this feature
is useful for user to make sure their `seccomp configuration file` is
right.
Output for he default ubuntu container's seccomp filter is the
following:
```
lxc-start ubuntu 20170520024159.412 INFO     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:238 - changed apparmor profile to lxc-container-default-cgns
if ($arch == 3221225534)
if ($syscall == 313)
action ERRNO(1);
if ($syscall == 304)
action ERRNO(1);
if ($syscall == 246)
action ERRNO(1);
if ($syscall == 176)
action ERRNO(1);
if ($syscall == 175)
action ERRNO(1);
if ($syscall == 166)
if ($a1.hi32 & 0x00000000 == 0)
if ($a1.lo32 & 0x00000001 == 1)
action ERRNO(13);
action …
```

seccomp: export the seccomp filter after load it into kernel successful

---

templates/lxc-alpine.in

Starting at version 3.6, Alpine Linux has support for ppc64le
architecture. Adding the new keys also.
Signed-off-by: Breno Leitao <breno.leitao@gmail.com>

lxc-alpine: Add support for ppc64le

---

src/lxc/commands.c
src/lxc/commands.h
src/lxc/conf.c
src/lxc/criu.c
src/lxc/execute.c
src/lxc/lxc.h
src/lxc/lxccontainer.c
src/lxc/start.c
src/lxc/start.h
src/lxc/state.c
src/lxc/state.h
src/lxc/tools/lxc_execute.c
src/tests/lxc-test-apparmor-mount
src/tests/lxc-test-unpriv

A LXC container's lifecycle is regulated by the states STARTING, RUNNING, STOPPING, STOPPED, ABORTING. These states are tracked in the LXC handler and can be checked via approriate functions in the command socket callback system. (The freezer stages are not part of a container's lifecycle since they are not recorded in the LXC handler. This might change in the future but given that the freezer controller will be removed from future cgroup implementations it is unlikely.) So far, LXC was using an external helper to track the states of a container (lxc-monitord). This solution was error prone. For example, the external state server would hang in various scenarios that seemed to be caused by either very subtle internal races or irritation of the external state server by signals.
LXC will …

start: kill lxc-monitord

---

src/lxc/conf.c
src/lxc/confile.c
src/lxc/log.c
src/lxc/log.h
src/lxc/lxc_monitord.c
src/lxc/lxccontainer.h
src/lxc/seccomp.c
src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_autostart.c
src/lxc/tools/lxc_cgroup.c
src/lxc/tools/lxc_checkpoint.c
src/lxc/tools/lxc_console.c
src/lxc/tools/lxc_copy.c
src/lxc/tools/lxc_create.c
src/lxc/tools/lxc_destroy.c
src/lxc/tools/lxc_device.c
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_freeze.c
src/lxc/tools/lxc_info.c
src/lxc/tools/lxc_init.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_monitor.c
src/lxc/tools/lxc_snapshot.c
src/lxc/tools/lxc_start.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_unfreeze.c
src/lxc/tools/lxc_wait.c

When we merged the new logging function for the api we exposed the log level
argument in the struct as "priority" which we actually requested to be changed
to "level" which somehow didn't happen and we missed it. Given the fact there
has been no new liblxc release let's fix it right now before it hits users.
Also, take the chance to change the terminology in the log from "priority" to
"level" globally. This is to prevent confusion with syslog's "priority"
argument which we also support.

tree-wide: priority -> level

---

src/lxc/utils.c

see issue #1625 
"sigblk" is a bitmask, so we use bit shift operators to detect whether the "signal" is blocked.
Signed-off-by: Yifeng Tan <tanyifeng1@huawei.com>

utils: fix the way to detect blocking signal

---

src/lxc/Makefile.am
src/lxc/conf.c
src/lxc/confile.c
src/lxc/confile_network_legacy.c
src/lxc/confile_network_legacy.h
src/lxc/confile_utils.c
src/lxc/confile_utils.h
src/lxc/lxccontainer.c
src/tests/get_item.c
src/tests/parse_config_file.c

Serge and I discussed the new network parser we've merge a couple of days ago.
He pointed out that a bunch of use-cases we're currently supporting in the old
network parser would be broken by the new parser. As we've pointed out many
times before, we're strongly commited to backwards compatibility and not
breaking existing use-cases. That's why we decided to take a new approach.
Instead of trying to mangle the old parser and new parser to come up with
something that allows a smooth transition we will simply deprecate the old
configuration keys with LXC 3.0. In the meantime we will support the full-blown
old legacy parser and the new network parser. Specifically, this means that
we're deprecating:
lxc.network.*
in favor of
lxc.net.*
With LXC 2.1. defining networks using lxc.network.* keys …

network: new network parser part II

---

lxc.pc.in

Fix: https://github.com/lxc/lxc/issues/1636
This reverts commit 758243d8af0406e63cc5446c65d415298fa3cef2.

Revert "Add a prefix to the lxc.pc"

---

templates/lxc-centos.in

CentOS only has i386 and x86_64 listed in mirrorlist.centos.org,
use http://mirror.centos.org/altarch/ for all other arches instead
See: https://bugs.centos.org/view.php?id=11250

use altarch mirror for CentOS on arches other than i386 and x86_64

---

src/lxc/bdev/lxcbtrfs.c
src/lxc/cgroups/cgfs.c
src/lxc/cgroups/cgmanager.c
src/lxc/conf.c
src/lxc/utils.c

Our logging function will always spew out the function name.

remove the `__func__` macro

---

src/lxc/lxc_monitord.c

lxc-monitor has an option to tell lxc-monitord to quit.
```
~/lxc (master) # lxc-monitor --help
lxc-monitor monitors the state of the NAME container
Options :
-n, --name=NAME   NAME of the container
NAME may be a regular expression
-Q, --quit        tell lxc-monitord to quit
```
But it does not work. This patch fix that.

lxc-monitord: exit when got a quit command

---

src/lxc/start.c

This pr https://github.com/lxc/lxc/pull/1618 kill lxc-monitord, for backwards compatibility,
we also send state to legacy lxc-monitord state server in function `lxc_set_state`.
we should also send state if there is no state clients registered, otherwise `lxc-monitor` client will
not get state change event if container changed state to `STARTING` or `RUNNING`.

start: send state to legacy lxc-monitord state server even if no state clients registered

---

templates/lxc-altlinux.in

Added [-a|--apt-conf] parameter for selection of exact package
providing 'apt-conf'. By default 'apt-conf-sisyphus' is used for
Sisyphus and 'apt-conf-branch' for the rest of branches.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>

Added '--apt-conf' argument for ALTLinux template.

---

src/lxc/cgroups/cgfs.c
src/lxc/confile.c
src/lxc/confile_legacy.c
src/lxc/lxclock.c
src/lxc/tools/lxc_info.c
src/lxc/tools/lxc_top.c

use cppcheck tools `cppcheck --enable=warning  .` on lxc source directory.
This patch fix the following warnings
```
[src/lxc/cgroups/cgfs.c:794]: (warning) %ld in format string (no. 3) requires 'long' but the argument type is 'unsigned long'.
[src/lxc/confile.c:4441]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[src/lxc/confile.c:4502]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[src/lxc/confile_legacy.c:921]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[src/lxc/confile_legacy.c:938]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[src/lxc/lxclock.c:63]: (warning) %zd in format string (no. 1) …
```

fix some cppcheck warnings

---

src/lxc/lxclock.c
src/lxc/lxclock.h

This pr mainly updates comments based on the current code and also fix a small bug(the errno is the wrong value when open lock file failed).

lxclock: bugfix and update some comment

---

config/apparmor/abstractions/start-container

This patch allows users to start containers in AppArmor namespaces.
Users can define their own profiles for their containers, but
lxc-start must be allowed to change to a namespace.
A container configuration file can wrap a container in an AppArmor
profile using lxc.aa_profile.
A process in an AppArmor namespace is restricted to view
or manage only the profiles belonging to this namespace, as if no
other profiles existed. A namespace can be created as follow:
sudo mkdir /sys/kernel/security/apparmor/policy/namespaces/$NAMESPACE
AppArmor can stack profiles so that the contained process is bound
by the intersection of all profiles of the stack. This is achieved
using the '//&' operator as follow:
lxc.aa_profile = $PROFILE//&:$NAMESPACE://unconfined
In this case, even the guest process …

Allow containers to start in AppArmor namespaces

---

src/lxc/af_unix.c

commit bdb3f44147bc1a55a97131b4b39d42844ae4fb9e says that we may undo
the change in august 2014.
I think that it is time to do that.

lxc_abstract_unix_connect: remove the workaround-code

---

src/lxc/af_unix.c

It is not necessary to unlink the abstract socket pathname when
we have finished using the socket. The abstract name is automatically
removed when the socket is closed.

af_unix: remove unlink operation

---

src/lxc/start.c
src/lxc/utils.c

In the case the container has a console with a valid slave pty file descriptor
we duplicate std{in,out,err} to the slave file descriptor so console logging
works correctly. When the container does not have a valid slave pty file
descriptor for its console and is started daemonized we should dup to
/dev/null.
Closes #1646.

start: dup std{in,out,err} to pty slave

---

src/lxc/cgroups/cgfsng.c

Only output debug info `cgroup 'xxxx' set to 'yyyy'` when we set
cgroup data.

cgfsng: only output debug info when we set cgroup data

---

src/lxc/bdev/lxcdir.c
src/lxc/conf.c
src/lxc/conf.h
src/tests/Makefile.am
src/tests/lxc-test-rootfs

If we want to mount a readonly rootfs. LXC calls mount() only once in the function `dir_mount `, to do the bind mount with the ro mount flag. But because of the behavior of the Linux kernel regarding bind mounts it ignores the MS_RDONLY flag and the bind mount stays writable. ["kernel bug #24912" ](https://bugzilla.kernel.org/show_bug.cgi?id=24912)
Changing mount options requires a second mount() with the MS_REMOUNT flag. LXC should therefore handle this case be doing the rootfs mount in two steps:
1. bind mounting the rootfs
2. re-mount with MS_REMOUNT | MS_BIND | MS_RDONLY
This patch will resolve issue #1702 and #570.

Fix issue #1702, do remount with the MS_REMOUNT flag when mounts with MS_RDONLY

---

src/lxc/bdev/lxclvm.c
src/lxc/cgroups/cgfsng.c

lvm: check whether lxc.bdev.lvm.vg is empty

---

templates/lxc-altlinux.in
templates/lxc-centos.in
templates/lxc-debian.in
templates/lxc-fedora-legacy.in
templates/lxc-fedora.in
templates/lxc-openmandriva.in
templates/lxc-opensuse.in
templates/lxc-ubuntu.in

(updated by Serge to also handle hte new lxc-fedora{-legacy{.in
templates)
Signed-off-by: Harald Dunkel <harri@afaics.de>
Acked-by: Serge Hallyn <serge@hallyn.com>

Use "rsync -SHaAX" to copy the cached rootfs into place

---

src/lxc/cgroups/cgfsng.c

Some devices like LVM or cryptsetup entries have no stable major/minor, changing between host reboots.
In this case, hardcoded numbers are not usable in config file and there is currently no way to use hook with lxc-device to do the link at guest startup :
* `pre-start`/`autodev` hook runs in host context but has the guest in stopped state and so lxc-device not usable
* `start` hook is in running state but runs in guest context and so lxc-device not available
This patch converts fullpath in lxc.devices.allow to current major/minor numbers to address those changing numbers.
Signed-off-by: aeris <aeris@imirhil.fr>

Allow full path in lxc.devices.allow

---

src/lxc/confile.c
src/lxc/lxccontainer.c
src/tests/parse_config_file.c

When we are passed a network key like "lxc.net.[i].ipv4.address" we need to
make sure that we pass the deindexed key "lxc.net.ipv4.address" to the
{get,clr,set} methods otherwise we'll end up in an endless loop.

network parser fixes

---

src/lxc/conf.c
src/tests/console.c

This will only work with kernels >= 3.4

devpts: use max=<count> option on mount

---

src/lxc/cgroups/cgfsng.c
src/lxc/lxccontainer.c

cgfsng: do not use uninitialized variable

---

src/lxc/bdev.c

We shouldn't ignore this anyway.

bdev: enable building with gcc7

---

templates/lxc-busybox.in

lxc.rebootsignal -> lxc.signal.reboot

templates: remove legacy key from busybox

---

templates/lxc-debian.in

The httpredir.debian.org service has been discontinued in favour of
deb.debian.org and httpredir.debian.org now redirects to deb.debian.org.
https://lists.debian.org/debian-mirrors/2017/02/msg00000.html
https://wiki.debian.org/DebianGeoMirror#httpredir.debian.org_.2F_http.debian.net
Cf. https://bugs.debian.org/872719

Use deb.debian.org as the default Debian mirror

---

src/lxc/tools/lxc-update-config.in

Older instances of liblxc allowed to specify networks like this:
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxdbr0
lxc.network.name= eth0
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxdbr0
lxc.network.name = eth1
Each occurrence of "lxc.network.type" indicated the definition of a new
network. This syntax is not allowed in newer liblxc instances. Instead, network
must carry an index. So in new liblxc these two networks would be translated to:
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxdbr0
lxc.net.0.name= eth0
lxc.net.1.type = veth
lxc.net.1.flags = up
lxc.net.1.link = lxdbr0
lxc.net.1.name = eth1
The update script did not handle this case correctly. It should now.
Signed-off-by: Christian Brauner …

lxc-update-config: handle legacy networks

---

src/lxc/cgroups/cgfsng.c
src/lxc/confile.c

This reverts commit 92c590a.
Problem:
Commit 92c590a introduced the following
behavior:
> cgfsng: try to delete parent cgroups
>
> Say we have
>
>     lxc.uts.name = c1
>     lxc.cgroup.dir = lxd/a/b/c
>
> the path for the container's cgroup would be
>
>     lxd/a/b/c/c1
>
> When the container is shutdown we should not just try to delete "c1" we
> should also try to delete "c", "b", "a", and "lxd". This is to ensure
> that we don't leave empty cgroups around thereby increasing the chance
> that we run into trouble with cgroup limits. The algorithm for this isn't
> too costly since we can simply stop walking upwards at the first rmdir()
> failure.
The algorithm employs recursive_destroy() which opens each directory
specified in lxc.cgroup.dir and tries to delete each directory within that …

Revert "cgfsng: try to delete parent cgroups"

---

src/lxc/confile_utils.c
src/lxc/lxc_user_nic.c
src/lxc/network.c
src/lxc/network.h
src/lxc/start.c

When lxc-user-nic is called with the "delete" subcommand we need to make sure
that we are actually privileged over the network namespace for which we are
supposed to delete devices on the host. To this end we require that path to the
affected network namespace is passed. We then setns() to the network namespace
and drop privilege to the caller's real user id. Then we try to delete the
loopback interface which is not possible. If we are privileged over the network
namespace this operation will fail with ENOTSUP. If we are not privileged over
the network namespace we will get EPERM.
This is the first part of the commit. As of now nothing guarantees that the
caller does not just give us a random path to a network namespace it is
privileged over.
Signed-off-by: Christian Brauner …

lxc-user-nic: test privilege over netns on delete

---

src/lxc/criu.c

We cannot use strcmp(). Otherwise we incorrectly report e.g. that criu 2.12.1
is less than 2.8.
Signed-off-by: Federico Briata <federico-pietro.briata@cnhind.com>

criu: add cmp_version()

---

src/lxc/confile_legacy.c
src/lxc/confile_utils.c

The entire netdev is zeroed via memset() already. Unions and
all.

cleanup: remove unnecessary zeroing

---

src/lxc/network.c

Fixes a warning when shutting down a container with a veth interface with no link property defined.

network: add missing checks for empty links

---

src/lxc/tools/lxc-update-config.in

- replace lxc.network.[i].ipv4 with lxc.net.[i].ipv4.address
- remove lxc.rootfs.backend lines
Closes #1790.

tools: fix lxc-upate-config

---

doc/lxc-monitor.sgml.in

To match names beginning with the letters `f` or `b` one can use `[fb].*` or `(f|b).*`, but not `[f|b].*`, which would match strings beginning with `f`, `|`, or `b`.

[TRIVIAL] fix regex-typo in documentation example

---

src/lxc/start.c

The hooks (e.g. lxc.hook.mount) should have the environment variables the user
gave us available.

start: move env setup before container setup

---

templates/lxc-plamo.in

Since some remounts/umounts is executed in the plamo shutdown script,
the filesystem on where a container exists might be mount as
read-only. This patch delete some mounts and umounts from the shutdown
script. It also delete hwclock setting process.
And delete an unncecessary output.

plamo: Delete unnecessary process during container shutdown

---

templates/lxc-alpine.in

Because the `fetch` wget wrapper outputs files to stdout we may end up in a
situation where wget fails but the files are still created. This can happen
e.g. when the host date is out of sync leading to a failed certificate
check, resulting in the creation of empty key files.
Once the empty files have been created the template will try to use them which
causes the certificate check to fail.
By using `-s` instead of `-f` the template will re-fetch the files unless they
exist AND have a size greater than zero.

Change alpine template file check to also check file size (`-f` => `-s`)

---

doc/ja/lxc-monitor.sgml.in
doc/ko/lxc-monitor.sgml.in

Update for commit e3dd06ef41b63d0ee362fea74a3f2d798dbfe929

doc: fix regex-typo in Japanese and Korean lxc-monitor(1)

---

src/lxc/storage/zfs.c

zfs: return error directly when zfs creation fails

---

src/lxc/cgroups/cgfsng.c

We can't rely in general on the presence of an initialized conf on cgroup init
time. One good example are our criu codepaths.

cgfsng: check whether we have a conf

---

src/lxc/start.c

Otherwise we can never share namespaces.
Acked-by: Christian Brauner <christian.brauner@ubuntu.com>

start: don't close inherited namespace fds

---

src/lxc/start.c
src/lxc/tools/lxc_start.c

use-case for share pid namespace:
If we share the PID namespace, then we can start a container to debug another running container with debug tools (gdb).

Add support share pid namespace

---

src/lxc/network.c
src/lxc/network.h
src/lxc/start.c

We need to clear any ifindeces we recorded so liblxc won't have cached stale
data which would cause it to fail on reboot we're we don't re-read the on-disk
config file.

 network: clear ifindeces

---

config/apparmor/abstractions/container-base
config/apparmor/abstractions/container-base.in
src/tests/aa.c

mem and kmem are really in /dev, so this does us no good.

drop useless apparmor denies

---

configure.ac
doc/lxc.container.conf.sgml.in
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/tools/lxc_execute.c
templates/Makefile.am
templates/lxc-oci.in

This adds preliminary (but working) support for creating application
containers from OCI formats.  Examples:
sudo lxc-create -t oci -n a1 -- -u oci:../oci:alpine -t alpine
create a container from a local OCI layout in ../oci.
sudo lxc-create -t oci -n u1 -- -u docker://ubuntu -t ubuntu
create a container pulling from the docker hub.
I'm pretty sure we'll wan to fine-tune the way "urls' are
specified.  The separate specifying of a 'tag' is unfortunate.
Maybe we can be smart enough to know to pull the name for
dockerhub and the tag for oci:.  But for now it simplified things
to the point of making it easy enough to implement and use.
Comments appreciated.
TODO:
- implement lxc.execute.cmd configuration key
- pull more of the OCI runtime information like memory/cpu limits
Signed-off-by: …

Add OCI container creation template

---

src/lxc/confile.c
src/lxc/tools/lxc-update-config.in

confile: ignore lxc.kmsg and lxc.pivotdir 

---

src/lxc/tools/lxc_execute.c
src/lxc/utils.c
src/lxc/utils.h
templates/lxc-oci.in

lxc_string_split_quoted() splits a string on spaces, but keeps
groups in single or double qoutes together.  In other words,
generally what we'd want for argv behavior.
Switch lxc-execute to use this for lxc.execute.cmd.
Switch lxc-oci template to put the lxc.execute.cmd inside single
quotes, because parse_line() will eat those.  If we don't do that,
then if we have lxc.execute.cmd = /bin/echo "hello, world", then the
last double quote will disappear.

implement lxc_string_split_quoted

---

templates/lxc-debian.in

```
if [ -f "${rootfs}/lib/systemd/system/getty@.service" ]; then
sed -e 's/^ConditionPathExists=/# ConditionPathExists=/' \
-e 's/After=dev-%i.device/After=/' \
< "${rootfs}/lib/systemd/system/getty@.service" \
> "${rootfs}/etc/systemd/system/getty@.service"
fi
```
we have only /dev/tty in a container - so this little cutie will spam the log all 10s with the following:
```
Jul 28 22:33:00 mariadb systemd[1]: getty@tty4.service: Service has no hold-off time, scheduling restart.
Jul 28 22:33:00 mariadb systemd[1]: getty@tty3.service: Service has no hold-off time, scheduling restart.
Jul 28 22:33:00 mariadb systemd[1]: getty@tty1.service: Service has no hold-off time, scheduling restart.
Jul 28 22:33:00 mariadb systemd[1]: getty@tty2.service: Service has no hold-off time, scheduling …
```

Don't force getty@ configuration

---

src/lxc/confile.c
src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_autostart.c
src/lxc/tools/lxc_cgroup.c
src/lxc/tools/lxc_checkpoint.c
src/lxc/tools/lxc_clone.c
src/lxc/tools/lxc_config.c
src/lxc/tools/lxc_console.c
src/lxc/tools/lxc_copy.c
src/lxc/tools/lxc_create.c
src/lxc/tools/lxc_destroy.c
src/lxc/tools/lxc_device.c
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_freeze.c
src/lxc/tools/lxc_info.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_monitor.c
src/lxc/tools/lxc_snapshot.c
src/lxc/tools/lxc_start.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_unfreeze.c
src/lxc/tools/lxc_wait.c

With the release LXC 2.1 we started warning users who use LXC through the API
and users who use LXC through the tools equally about updating their config.
This quickly got confusing and annoying to API users who e.g. generate configs
on the fly (e.g. LXD). So instead of unconditionally warning users we make this
opt-in. If LXC detects that the env variable LXC_UPDATE_CONFIG_FORMAT is set
then it will warn the user if any legacy configuration keys are present. If it
is not set however, it will not warn the user. This is ok, since the log will
still log WARN()s for all legacy configuration keys.
The tools will all set LXC_UPDATE_CONFIG_FORMAT since it is very much required
that users update to the new configuration format pre-LXC 3.0.
Signed-off-by: Christian Brauner …

confile: make update warning opt-in

---

.gitignore
src/lxc/commands.c
src/lxc/commands.h
src/lxc/lxc.h
src/lxc/lxccontainer.c
src/lxc/lxccontainer.h
src/tests/Makefile.am
src/tests/livepatch.c

This adds set_running_config_item() which is the analogue of
get_running_config_item(). In essence it allows a caller to livepatch the
container's in-memory configuration. This POC is severly limited. Here are the
most obvious ones:
- Only the container's in-memory config can be updated but no further actions
(e.g. on-disk actions) are made.
- Only keys in the "lxc.net." namespace can be changed. This POC also allows
updating an existing network. For example it allows to change the network
type of an existing network. This is obviously nonsense and in a non-POC
implementation this should be blocked.
Use Case:
Callers can hotplug a new network for the container. For example, LXD can
create a pair of veth devices in the host and in the container and add it to
the container's in-memory …

POC: container live patching

---

src/lxc/arguments.c

liblxc should inform users that they are using a devel version. This will have
liblxc print
MAJOR.MINOR.PATCH-devel
if LXC_DEVEL is true and
MAJOR.MINOR.PATCH
otherwise.

arguments: print "-devel" when LXC_DEVEL is true

---

templates/lxc-archlinux.in

This template would always add "en-US.UTF-8" to the end of the container's locale.gen, which in turn confused locale-gen.

Change locale "en-US.UTF-8" to "en_US.UTF-8"

---

src/lxc/confile.c
src/lxc/confile_legacy.c
src/lxc/confile_utils.c
src/lxc/confile_utils.h
src/lxc/log.c

There's two new build failures on x32, both due to assumption that some type is identical to ｢long｣.

fix build failures on x32

---

templates/lxc-sabayon.in

Problem happens for image with systemd >=233.
Minor fix for mirrors list.
Signed-off-by: Geaaru <geaaru@gmail.com>

Fix start of Sabayon unprivileged containers

---

src/lxc/Makefile.am
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/confile_utils.c
src/lxc/confile_utils.h
src/lxc/console.c
src/lxc/namespace.c
src/lxc/ringbuf.c
src/lxc/ringbuf.h
src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h
src/tests/lxc-test-utils.c

liblxc will use a ringbuffer implementation that employs mmap()ed memory.
Specifically, the ringbuffer will create an anonymous memory mapping twice the
requested size for the ringbuffer. Afterwards, an in-memory file the requested
size for the ringbuffer will be created. This in-memory file will then be
memory mapped twice into the previously established anonymous memory mapping
thereby effectively splitting the anoymous memory mapping in two halves of
equal size.  This will allow the ringbuffer to get rid of any complex boundary
and wrap-around calculation logic. Since the underlying physical memory is the
same in both halves of the memory mapping only a single memcpy() call for both
reads and writes from and to the ringbuffer is needed.
Design Notes:
- Since we're using MAP_FIXED …

ringbuffer: implement efficient and performant ringbuffer

---

templates/lxc-debian.in

Being able to create `testing` containers, regardless of what's the name
of the next stable, is useful in several contexts, included but not
limited to testing purposes. i.e. one won't need to explicitly switch to
`bullseye` once `buster` is released to be able to continue tracking
`testing`. While we are at it, let's also enable `unstable`, which is
exactly the same as `sid`, but there is no reason for not being able to.
Signed-off-by: Antonio Terceiro <terceiro@debian.org>

lxc-debian: allow creating `testing` and `unstable`

---

src/lxc/tools/lxc_execute.c

At some point, `lxc-execute` lost its call to `lxc_config_define_load` - this means it accepted configuration parameters on the command-line via `-s` but didn't actually do anything with them. This puts the call back more-or-less where it was before.
Fixes https://github.com/lxc/lxc/issues/1878

Call lxc_config_define_load from lxc_execute again

---

src/lxc/cgroups/cgfs.c
src/lxc/cgroups/cgfsng.c
src/lxc/cgroups/cgroup.c
src/lxc/conf.c
src/lxc/conf.h

In case cgroup namespaces are supported but we do not have CAP_SYS_ADMIN we
need to mount cgroups for the container. This patch enables both privileged and
unprivileged containers without CAP_SYS_ADMIN.
Closes #1737.

cgroups: enable container without CAP_SYS_ADMIN

---

src/lxc/tools/lxc_attach.c

For example the following sequence is expected to work:
```
lxc-start -n containerName -f /path/to/conf \
-s 'lxc.id_map = u 0 100000 65536' \
-s 'lxc.id_map = g 0 100000 65536' \
-s 'lxc.rootfs = /path/to/rootfs' \
-s 'lxc.init_cmd = /path/to/initcmd'
lxc-attach -n containerName
```
Closes #984.

tools: allow lxc-attach to undefined containers

---

src/lxc/tools/lxc_attach.c

For example the following sequence is expected to work:
lxc-start -n containerName -f /path/to/conf \
-s 'lxc.id_map = u 0 100000 65536' \
-s 'lxc.id_map = g 0 100000 65536' \
-s 'lxc.rootfs = /path/to/rootfs' \
-s 'lxc.init_cmd = /path/to/initcmd'
lxc-attach -n containerName
Closes #984.

stable-2.1: tools: allow lxc-attach to undefined containers

---

configure.ac
src/lxc/Makefile.am
src/lxc/conf.c

Some toolchains which are not bionic like uclibc does not support
prlimit or prlimit64. In this case, return an error.

Fix compilation on toolchain without prlimit

---

src/lxc/start.c

The configure checks for these use AC_CHECK_DECLS, which define the symbol
to 0 if not available - So adjust the code to match.  From the autoconf
manual:
https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Generic-Declarations.html)
For each of the symbols (comma-separated list), define HAVE_DECL_symbol (in
all capitals) to ‘1’ if symbol is declared, otherwise to ‘0’.
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>

lxc/start.c: Fix legacy PR_{G,S}ET_NO_NEW_PRIVS handling

---

src/lxc/attach.c
src/lxc/attach.h

We need to have lxc_attach() distinguish between a caller specifying specific
namespaces to attach to and a caller not requesting specific namespaces. The
latter is taken by lxc_attach() to mean that all namespaces will be attached.
This also needs to include all inherited namespaces.
Closes #1890.

attach: handle namespace inheritance

---

config/templates/archlinux.common.conf.in
src/lxc/cgroups/cgfsng.c
src/lxc/cgroups/cgroup_utils.c
src/lxc/cgroups/cgroup_utils.h
src/lxc/log.c

cgroups/cgfsng: fixes, features, and improved cgroup2 handling

---

.gitignore
src/lxc/commands.c
src/lxc/commands.h
src/lxc/conf.c
src/lxc/conf.h
src/lxc/console.c
src/lxc/console.h
src/lxc/lxccontainer.c
src/lxc/lxccontainer.h
src/lxc/start.c
src/tests/Makefile.am
src/tests/console_log.c

API: add console ringbuffer extension

---

src/tests/lxc-test-unpriv

This patch fixes the missing workdir issue for the overlayfs mount command in
the lxc-test-unpriv test.
Bug link: https://bugs.launchpad.net/bugs/1730915
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>

lxc-test-unpriv: fix the overlayfs mount error

---

src/lxc/tools/lxc_attach.c

@brauner Here's the first refactor in the tools directory for you to review
Signed-off-by: Austin Reichert <austinskyreichert@utexas.edu>

First tools/ refactor for review

---

src/lxc/console.c

Now it will be displayed nicely formatted:
```
a1 login: chb@conventiont|~
> lxc console a1
Connected to tty 0
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself
Ubuntu 17.10 a1 console
a1 login:
```

console: fix console info message

---

src/lxc/console.c

When users pass -1 there's there won't be an escape sequence to exit the
console so no need to print a misleading info message about how to detach.

console: report detach message on demand

---

src/lxc/cgroups/cgfsng.c

In order to enable proper unprivileged cgroup delegation on newer kernels we not
just need to delegate the "cgroup.procs" file but also "cgroup.threads". But
don't report an error in case it doesn't exist. Also delegate
"cgroup.subtree_control" to enable delegation of controllers to descendant
cgroups.

cgroups/cgfsng: adapt to new cgroup2 delegation

---

src/lxc/lxccontainer.c
src/lxc/tools/lxc_execute.c

This enables daemonized execute containers with our minimal init running as
pid one and the requested program running as second pid.

lxccontainer: enable daemonized execute

---

src/lxc/console.c

console: use correct escape sequence check

---

src/lxc/console.c
src/lxc/console.h
src/lxc/tools/lxc_attach.c

This allows cleanly exiting a console session without control sequences.
Relates to lxc/lxd#4001 .

console: exit mainloop on SIGTERM

---

src/lxc/confile_utils.c

Steps to reproduce the problem：
1. Modify the config of container `test1 `as follow
```
$ cat /var/lib/lcrd/lcr/test1/config
......
lxc.namespace.pid = /var/lib/lcrd/lcr/test
.....
```
2. Start the container `test1`, it will be failed to inherit pid namespace  of `test`

Fix lxc_inherit_namespace function error

---

src/lxc/commands.c
src/lxc/commands.h
src/lxc/commands_utils.c
src/lxc/commands_utils.h
src/lxc/lxccontainer.c
src/lxc/start.c

Remove dead state clients from state client list. Consider the following
scenario:
01 start container
02 issue shutdown request
03 state_client_fd is added to lxc_handler
03 container doesn't respond to shutdown request
04 user aborts shutdown request
05 lxc_cmd_fd_cleanup() removes state_client_fd from lxc_mainloop
06 invalid state_client_fd is still recorded in the lxc_handler
07 user issues lxc_cmd_stop() request via SIGKILL
08 container reaches STOPPED state and sends message to state_client_fd
09 state_client_fd number has been reused by lxc_cmd_stop_callback()
10 invalid data gets dumped to lxc_cmd_stop()
Reproducer:
Set an invalid shutdown signal to which the init system does not respond with a
shutdown via lxc.signal.halt e.g. "lxc.signal.halt = SIGUSR1". Then do:
```
1. start …
```

commands: fix state socket implementation

---

src/lxc/tools/lxc_init.c

Additionally, the console seems to be [execute only (0111)](https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L1536) not sure if it's intended or not.

lxc_init: set the control terminal in the child session

---

src/lxc/confile_utils.c

In the case of "lxc.net.0.type", the pointers passed to strncpy were
only 2 elements apart, resulting in undefined behavior.

confile_utils: fix overlapping strncpy

---

src/tests/lxc-test-unpriv

Check the test user (lxcunpriv) before calling deluser command,
otherwise it will print unnecessary error message:
/usr/sbin/deluser: The user 'lxcunpriv' does not exist.
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>

lxc-test-unpriv: check user existence before removing it

---

src/lxc/conf.c
src/lxc/utils.h

conf: move CAP_SYS_* definitions to utils.h

---

src/lxc/conf.c
src/lxc/tools/lxc_unshare.c
src/lxc/utils.h

Create new lxc_helper.h header to hold the implementation of
sethostname, instead of duplicating code in conf.c and lxc_unshare.c

lxc_helper.h: Avoid duplicated sethostname

---

.gitignore
configure.ac
hooks/Makefile.am
hooks/dhclient-script
hooks/dhclient-start.in
hooks/dhclient-stop.in

Add new hooks leveraging dhclient from the host to automatically
configure the container interfaces. This is especially useful for
application containers which rely on an IPAM driver for network
configuration (e.g. Docker).
---
This is a proposal rather than a final patch. In particular, there are some issues I would like to discuss:
- The `dhclient-script` is a fork of the official ISC one because I don't think we need all the resolvconf features for containers. The only differences are:
```
```
- `dhclient` daemonizes itself, hence we will have one `dhclient` process in the init pid namespace per application container
- LSMs aren't ok with that because most distribution have a profile for `dhclient`, it's probably just a matter of …

hooks: add dhclient hooks

---

src/lxc/confile.c
src/lxc/confile_legacy.c
src/lxc/confile_utils.c
src/lxc/log.c
src/tests/lxc-test-utils.c
src/tests/parse_config_file.c

- One memory leak
- One stack overflow
- Multiple out-of-bounds accesses

Fix errors in configuration file parsing

---

templates/lxc-slackware.in

I followed the [changelog of Slackware-current](http://www.slackware.com/changelog/),
and found that Slackware-current split hostname utility from util-linux package in Nov 17 2017.
So I add the new package to the template.
Signed-off-by: Chia-Chun Hsu <a12321aabb@gmail.com>

Add new dependency to Slackware template

---

src/lxc/tools/lxc-checkconfig.in

The double quotes make the script shell try to call `printf \\033[1;31m` instead of calling `printf` with `\\033[1;31m` as parameter.

Fix lxc-checkconfig output

---

config/bash/lxc.in

- Backing Store types are hard-coded (Not sure how to get programmatically)
- Closes #1236
Signed-off-by: Abbas Ally <abbasally5@yahoo.com>

Add bash completion to list backing store types for lxc-create -B

---

src/lxc/execute.c

The lxc_log args have noghing to do with lxc.rootfs.path, and
we need room for a NULL at end of arguments.
How this bug was hidden for so long I don't know - I can only
trigger it on certain systems under certain conditions, but it's
definately wrong as is.

lxc_execute: properly figure out number of needed arguments

---

doc/lxc.container.conf.sgml.in
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/start.c

Add the `lxc.init.cwd`  config to set the current working directory. The value MUST be an absolute path in the container.

confile:add lxc.init.cwd

---

src/lxc/start.c

We want the loglevel that the user specified when starting the container
because it overrides the default one set in the config.
Closes #2003.
Reported-by: Felix Abecassis <fabecassis@nvidia.com>

start: set loglevel correctly

---

src/lxc/Makefile.am
src/lxc/lxc_init.c

@brauner 
Moved `lxc_init.c` up to `src/lxc`, added a custom argument parser to `lxc_init.c`, and updated `Makefile.am` to remove dependencies from `tools/arguments.{c,h}`.
If there's anything wrong with the argument parser, please let me know and I'll make the appropriate changes. Thanks!

Move lxc_init up to lxc/src and add argument parser

---

src/lxc/commands.c
src/lxc/commands_utils.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/execute.c
src/lxc/lxccontainer.c
src/lxc/lxccontainer.h
src/lxc/start.c
src/lxc/start.h
src/lxc/state.c
src/lxc/tools/lxc_stop.c
src/tests/Makefile.am
src/tests/api_reboot.c
src/tests/livepatch.c
src/tests/shortlived.c
src/tests/state_server.c

lxccontainer: add reboot2() API extension
This adds reboot2() as a new API extension. This function properly wait until a
reboot succeeded. It takes a timeout argument. When set to > 0 reboot2() will
block until the timeout is reached, if timeout is set to zero reboot2() will
not block, if set to -1 reboot2() will block indefinitly.
The struct state_client gets rename to lxc_state_client since it's more in line
with other declarations. It also gets moved from the lxc_handler to the
lxc_conf struct so that the state clients waiting for reboots don't get
deallocated on reboot since the handler is deallocated on reboot.

commands: improve and simplify locking + lxccontainer: add reboot2() API extension

---

src/lxc/cgroups/cgmanager.c
src/lxc/lxclock.c

The same message exists in lxclock.c and cgmanager.c, so print the
filename along with the message.
Before this patch:
lxc-destroy -n u1
pthread_mutex_unlock returned:1 Operation not permitted
After this patch:
xc-destroy -n u1
lxclock.c: pthread_mutex_unlock returned:1 Operation not permitted

lxc: Distinguish pthread_mutex_unlock error messages

---

src/lxc/conf.c
src/lxc/confile_legacy.c

This fixes a bug introduced by:
commit 94f0035bf636ba853451d59c129e26d94850c04d
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Thu Dec 7 15:07:26 2017 +0100
coverity: #1425924
remove logically dead condition
Coverity's bug analysis is correct but my fix wasn't.
This commit fixes a bunch of other bugs I just spotted as well.
This unblocks #2009.

legacy confile: fix legacy network parser

---

doc/lxc.container.conf.sgml.in
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/tests/get_item.c
src/tests/parse_config_file.c

Add `lxc.sysctl` config.
It can be useful to configure  kernel parameters for the container.
Usage:
For e.g.
```
lxc.sysctl.net.ipv4.ip_forward = 1
lxc.sysctl.net.core.somaxconn = 256
```

Confile: Add lxc.sysctl config

---

src/lxc/start.c
src/lxc/start.h
src/tests/Makefile.am
src/tests/share_ns.c

When I first solved this problem I went for a fork() + setns() + clone() model.
This works fine but has unnecessary overhead for a couple of reasons:
- doing a full fork() including copying file descriptor table and virtual
memory
- using pipes to retrieve the pid of the second child (the actual container
process)
This can all be avoided by being a little smart in how we employ the clone()
syscall:
- using CLONE_VM will let us get rid of using pipes since we can simply write
to the handler because we share the memory with our parent
- using CLONE_VFORK will also let us get rid of using pipes since the execution
of the parent is suspended until the child returns
- using CLONE_VM will not cause virtual memory to be copied
- using CLONE_FILES will not cause the file descriptor table to be …

start: intelligently use clone() on ns sharing

---

src/lxc/start.c

Starting with commit
commit c5b93afba1d79c6861a6f45db2943b6f3cfbdab4
Author: Li Feng <lifeng68@huawei.com>
Date:   Mon Jul 10 17:19:52 2017 +0800
start: dup std{in,out,err} to pty slave
In the case the container has a console with a valid slave pty file descriptor
we duplicate std{in,out,err} to the slave file descriptor so console logging
works correctly. When the container does not have a valid slave pty file
descriptor for its console and is started daemonized we should dup to
/dev/null.
Closes #1646.
we made std{err,in,out} a duplicate of the slave file descriptor of the console
if it existed. This meant we also duplicated all of them when we executed
application containers in …

start: do not unconditionally dup std{in,out,err}

---

src/lxc/conf.c

I'm not sure about the implications of this, this should be fine but @brauner might know better :)

conf: avoid spawning unnecessary subshells

---

src/lxc/tools/lxc_execute.c

Moving away from internal symbols we can't do hacks like we currently do in
lxc-start and call internal functions like lxc_conf_init(). This is unsafe
anyway. Instead, we should simply error out if the user didn't give us a
configuration file to use. lxc-start refuses to start in that case already.
Relates to discussion in lxc/go-lxc#96 (comment) .
Closes #2023.
Reported-by: Felix Abecassis <fabecassis@nvidia.com>

tools: block using lxc-execute without config file

---

src/lxc/lxccontainer.c

Detaching network namespaces as an unprivileged user is currently not possible
and attaching to the user namespace will mean we are not allowed to move the
network device into an ancestor network namespace.

lxccontainer: only attach netns on netdev detach

---

src/lxc/criu.c
src/lxc/start.c
src/lxc/start.h
src/tests/shortlived.c

Prior to this patch we raced with a very short-lived init process. Essentially,
the init process could exit before we had time to record the cgroup namespace
causing the container to abort and report ABORTING to the caller when it
actually started just fine. Let's not do this.
(This uses syscall(SYS_getpid) in the the child to retrieve the pid just in case
we're on an older glibc version and we end up in the namespace sharing branch
of the actual lxc_clone() call.)
Additionally this fixes the shortlived tests. They were faulty so far and
should have actually failed because of the cgroup namespace recording race but
the ret variable used to return from the function was not correctly
initialized. This fixes it.
Furthermore, the shortlived tests used the c->error_num variable to determine …

start: fix cgroup namespace preservation

---

doc/lxc.container.conf.sgml.in
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/lxccontainer.c
src/lxc/namespace.c
src/lxc/namespace.h
src/lxc/network.c
src/lxc/start.c
src/tests/parse_config_file.c

confile: add lxc.hook.version

---

src/lxc/criu.c
src/lxc/criu.h
src/lxc/lxccontainer.c
src/lxc/lxccontainer.h
src/tests/Makefile.am
src/tests/criu_check_feature.c

For migration optimization features like pre-copy or post-copy migration the support cannot be determined by simply looking at the CRIU version. Features like that depend on the architecture/kernel/criu combination and CRIU offers a feature checking interface to query if it is supported.
This adds a LXC interface to query CRIU for those feature via the migrate() API call. For the recent pre-copy migration support in LXD this can be used to automatically detect if pre-copy migration should be used.
In addition to the existing migrate() API commands this adds a new command: MIGRATE_FEATURE_CHECK'.
The migrate_opts{} structure is extended by the member features_to_check which is a bitmask defining which CRIU features should be queried.
Currently only the querying of the features …

criu: add feature check capability

---

src/lxc/storage/dir.c

if user has lxc.rootfs.path = /some/path/foo, but can't access
some piece of that path, then we'll get an unhelpful "failed to
mount" without any indication of the problem.
At least show that there is a permission problem.

dir_detect: warn on eperm

---

src/lxc/lxc_init.c
src/lxc/tools/arguments.c
src/lxc/tools/arguments.h
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_start.c

This is basically just hoisting the functionality out of lxc-start, so lxc-execute can use it too.

add --share-$NS= support to lxc-execute

---

src/lxc/start.c

When we report STOPPED to a caller and then close the command socket it is
technically possible - and I've seen this happen on the test builders - that a
container start() right after a wait() will receive ECONNREFUSED because it
called open() before we close(). So for all new state clients simply close the
command socket. This will inform all state clients that the container is
STOPPED and also prevents a race between a open()/close() on the command socket
causing a new process to get ECONNREFUSED because we haven't yet closed the
command socket.

commands: fix race when open()/close() cmd socket

---

src/lxc/namespace.c
src/lxc/namespace.h
src/lxc/utils.c
src/tests/Makefile.am
src/tests/lxc_raw_clone.c

run_command() is called in contexts where threads explicitly hold a lock while
fork()ing. Currently, this just affects the legacy cgmanager cgroup driver.
Here's what's happening when we use fork():
1. cgm_chown() calls cgm_dbus_connect()
2. cgm_dbus_connect() calls cgm_lock():
Now the thread holds an explicit lock on the mutex
3. cgm_chown() calls chown_cgroup()
4. chown_cgroup() calls userns_exec_1()
5. userns_exec_1() forks with an explicit lock on the mutex being held
6. pthread_atfork() handlers get run including the prepare() handler:
#ifdef HAVE_PTHREAD_ATFORK __attribute__((constructor))
static void process_lock_setup_atfork(void)
{
pthread_atfork(cgm_lock, cgm_unlock, cgm_unlock);
}
#endif
thus trying to acquire the mutex that is being explicitly held in the
parent. If we were …

utils: use lxc_raw_clone() in run_command()

---

src/lxc/error.h
src/lxc/start.c

When we inherit namespaces we need to reap the attaching process.

start: reap intermediate process

---

src/lxc/conf.c
src/tests/parse_config_file.c

Signed-off-by: Yifeng Tan <tanyifeng1@huawei.com>

conf.c: small fix for args of mount_entry

---

src/lxc/monitor.c

if lxc_abstract_unix_connect fail and return -1,  this code never goto retry.

[monitor] wrong statement of break

---

src/lxc/cgroups/cgfsng.c

At this point, macros such DEBUG or ERROR does not take effect because
this code is called from cgroup_ops_init(cgroup.c), which runs with
__attribute__((constructor)), before any log level is set form any tool
like lxc-start, so these messages are lost.
For now on, use the same LXC_DEBUG_CGFSNG environment variable to
control these messages.

cgfsng: Add new macro to print errors

---

src/lxc/af_unix.c
src/lxc/attach.c
src/tests/attach.c

attach: simplify significantly

---

src/lxc/storage/btrfs.c

We already fixed privileged btrfs snapshot creation in:
commit 1c7222c084769a1d9406ca7dab943d8a5f016a56
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Tue Nov 28 13:51:03 2017 +0100
btrfs: fix btrfs_snapshot()
Closes #1956.
but missed unprivileged btrfs snapshot creation. Fix it too.
Follow-up to #1956.
Closes #2051.
Reported-by: Oleg Freedhom overlayfs@gmail.com

btrfs: fix unprivileged snapshot creation

---

src/lxc/Makefile.am
src/lxc/af_unix.c
src/lxc/attach.c
src/lxc/cgroups/cgfs.c
src/lxc/cgroups/cgmanager.c
src/lxc/console.c
src/lxc/lsm/apparmor.c
src/lxc/lxc_init.c
src/lxc/lxc_monitord.c
src/lxc/lxc_user_nic.c
src/lxc/lxccontainer.c
src/lxc/namespace.c
src/lxc/namespace.h
src/lxc/network.c
src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h
src/tests/lxc_raw_clone.c

start: tweaks + bugfixes

---

src/lxc/start.c

Since we are now dumpable we can open /proc/<child-pid>/ns/cgroup so let's
avoid the overhead of sending around fds.

start: simplify cgroup namespace preservation

---

src/lxc/start.c

On set{g,u}id() the kernel does:
/* dumpability changes */
if (!uid_eq(old->euid, new->euid) ||
!gid_eq(old->egid, new->egid) ||
!uid_eq(old->fsuid, new->fsuid) ||
!gid_eq(old->fsgid, new->fsgid) ||
!cred_cap_issubset(old, new)) {
if (task->mm)
set_dumpable(task->mm, suid_dumpable);
task->pdeath_signal = 0;
smp_wmb();
}
which means we need to re-enable the deat signal after the set{g,u}id().

start: fix death signal

---

src/lxc/tools/lxc_config.c

As the other tools already handle, show usage message when -h or --help
are used.

lxc_config: Add -h and --help flags handler

---

src/lxc/console.c
src/lxc/console.h
src/lxc/mainloop.c
src/lxc/mainloop.h
src/lxc/start.c
src/lxc/start.h

The handler for the signal fd will detect when the init process of a container
has exited and cause the mainloop to close. However, this can happen before the
console handlers - or any other events for that matter - are handled. So in the
case of init exiting we still need to allow for all other pending events to be
handled before exiting. This allows us to capture output from short-lived init
processes.
Closes #1694.

mainloop: capture output of short-lived init procs

---

src/lxc/cgroups/cgfsng.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/confile.c
src/lxc/start.c

Support configurations without root mapping

---

configure.ac

The existing check doesn't work, because when you statically
link a program against libc, any functions not called are not
included.  So cap_init() which we check for is not there in
the built binary.
So instead just check whether a "gcc -lcap -static" works.
If libcap.a is not available it will fail, if it is it will
succeed.

configure.ac: fix the check for static libcap

---

src/lxc/cgroups/cgfsng.c
src/lxc/conf.c
src/lxc/conf.h
src/lxc/start.c

When fully unprivileged users run a container that only maps their own {g,u}id
and they do not have access to setuid new{g,u}idmap binaries we will write the
idmapping directly. This however requires us to write "deny" to
/proc/[pid]/setgroups otherwise any write to /proc/[pid]/gid_map will be
denied.
On a sidenote, this patch enables fully unprivileged containers. If you now set
lxc.net.[i].type = empty no privilege whatsoever is required to run a container.
Enhances #2033.
Cc: Felix Abecassis <fabecassis@nvidia.com>
Cc: Jonathan Calmels <jcalmels@nvidia.com>

conf: write "deny" to /proc/[pid]/setgroups

---

configure.ac
src/lxc/lxc_init.c
src/lxc/tools/arguments.c

As this is actively looked for by go-lxc and LXD.

lxc_get_version() should show the "-devel" suffix

---

src/lxc/lxccontainer.c

If 'lxc_cmd_get_name' failed and return with NULL, this will cause a segment fault when calling ‘add_to_array’.

Add return check for 'lxc_cmd_get_name'

---

src/lxc/tools/lxc_usernsexec.c

* exit(1) when there is an option parsing error
* exit(0) when the user explicitly asks for help
* exit(1) when the user specifies an invalid option

fix up lxc-usernsexec's exit status

---

src/lxc/confile.c
src/lxc/confile_utils.c

otherwise, we just get a return value of false from setting config failure,
with no indication as to what actually failed in the log.

add some idmap parsing error messages

---

src/lxc/confile.c

get_config_console_logsize want console.buffer_size not c->autodev

[console] return wrong console logsize

---

config/templates/alpine.common.conf.in
templates/lxc-alpine.in

It would be convenient to be able to toggle sys_ptrace on a per container basis. Removing the option from the common configuration file would have an effect on deployed containers, though.
Any better ideas to achieve this? Most of the templates do not drop this capability, so there is no good precedent.

lxc-alpine: allow retaining sys_ptrace per container

---

src/lxc/commands.c
src/lxc/commands.h
src/lxc/freezer.c
src/lxc/start.c
src/lxc/start.h
src/lxc/state.c

Closes #2027.
Closes lxc/go-lxc#98.

lxccontainer: restore blocking wait()

---

src/lxc/error.c
src/lxc/lxc_init.c
src/lxc/lxccontainer.c
src/lxc/start.c
src/lxc/start.h
src/lxc/tools/lxc_execute.c

Unfortunately, liblxc didn't do a very good job of keeping track of the exit codes of the tasks it spawned. Here's a series that addresses that. See patch notes for explanations on individual patches, hopefully they present clear arguments, and this will be mostly uncontroversial :)

Propagate exit code for app containers

---

src/lxc/lxc_init.c

It's sort of an implementation detail that this exists at all, and we
should probably not pollute the container's mount tables or FS with this.

unlink lxc-init

---

doc/lxc.container.conf.sgml.in

lxc.log.file instead of just lxc.log

manpage: correct lxc.log.file conf option

---

src/lxc/storage/storage.c

r->ops->destroy() returns an int, -1 on error.
When assigned to a bool, this becomes true and hides errors.
ret will always be true - on error, it's -1 - a true bool - or it is zero and thus set to true.
Signed-off-by: Michael McCracken <mikmccra@cisco.com>

storage: treat return value from ops->destroy as int

---

doc/ja/lxc-attach.sgml.in
doc/ja/lxc.container.conf.sgml.in

* Update for commit ba2be1a (attach: move pty allocation into api)
* Update for commit 5757588 (manpage: correct lxc.log.file conf option)

doc: Update Japanese lxc-attach(1) and lxc.container.conf(5)

---

src/lxc/conf.c
src/lxc/console.c
src/lxc/start.c

Steps to reproduce the problem：
1. Create a container with -t none
`lxc-create -n test1 -t none `
2. Modify the config of container test1 as follow
```
$ cat /var/lib/lcrd/lcr/test1/config
lxc.init_cmd = echo test
lxc.console.logfile = /home/out.log
```
3.Start the container test1,and check the output file `/home/out.log`, It is empty.
We should set the config` lxc.autodev = 0`, if we want to create console when the rootfs is NULL. Because so that we could see the allocated /dev/pts/x device and use it to bind mount the /dev/console.

Create console when the rootfs is NULL

---

src/lxc/network.c
src/lxc/network.h

The last user of ip_forward_set, lxc_ip_forward_on and
lxc_ip_forward_off was in 2009:
commit 92d385229be040cf034ac6efd9405b7bdfe06a3e
Author: Daniel Lezcano <dlezcano@fr.ibm.com>
Date:   Thu Oct 22 15:33:40 2009 +0200
remove test directory
These functions are not called anymore.

network.c: Remove ip_forward_set and callers

---

src/lxc/cgroups/cgfsng.c

lxc_cgroup_set_data: h = get_hierarchy(controller);
if h is NULL, now errno is old, it donot set new one.
And then,
cgfsng_setup_limits:
if (lxc_cgroup_set_data(cg->subsystem, cg->value, d)) {
if (do_devices && (errno == EACCES ||
errno == EPERM)) {
WARN("Error setting %s to %s for %s",
cg->subsystem, cg->value,
d->name);
continue;
}
SYSERROR("Error setting %s to %s for
%s",
cg->subsystem, cg->value,
d->name);
goto out;
}
SYSERROR will show old errno, make me confused.
Signed-off-by: duguhaotian <duguhaotian@gmail.com>

[cgfsng] show wrong errno

---

templates/lxc-debian.in

The package has pretty much always been iproute2 with iproute being an
alias for it, the alias is now gone so we need to use iproute2.

debian: Use iproute2 instead of iproute

---

src/lxc/seccomp.c

seccomp.c: Use return instead of attribution and return

---

src/lxc/tools/arguments.c

This lets users use the tools with "lxc-* -n <container-name>" or
"lxc-* <container-name>".

tools: make "-n" optional

---

src/lxc/lsm/lsm.c
src/lxc/lsm/lsm.h
src/lxc/lsm/selinux.c

Since we stopped linking against AppArmor we can now remove the conditional
compilation.

lsm: do not #ifdefine

---

templates/lxc-debian.in

debian: We must use iproute on wheezy

---

hooks/nvidia

With LXC, you can override the value of an environment variable to
null, but you can't unset an existing variable.
The NVIDIA hook was previously activated when NVIDIA_VISIBLE_DEVICES
was set to null. As a result, it was not possible to disable the hook
by overriding the environment variable in the configuration.
The hook can now be disabled by setting NVIDIA_VISIBLE_DEVICES to
null or to the new special value "void".

hooks: change the semantic of NVIDIA_VISIBLE_DEVICES=""

---

src/lxc/lxc_init.c

d76e3e1 inadvertently switched the alarm timeout from sigterm to sigkill.
We really want sigkill here, so let's bring it back.

lxc-init: use SIGKILL after alarm timeout

---

src/lxc/lxccontainer.c
src/lxc/network.c
src/lxc/start.c
src/lxc/storage/aufs.c
src/lxc/storage/btrfs.c
src/lxc/storage/overlay.c
src/lxc/storage/storage.c
src/lxc/utils.h

Currently if you try to run a privileged container nested inside an unprivileged one, nested lxc detects you are not host root and so tries to use lxc-user-nic to create nics.  root typically doesn't have any entries in /etc/lxc/lxc-usernet, so that fails.
This patchset fixes that.  However I think it leaves what Tycho was trying to fix broken - but I don't recall what the precise problem there was.  When we next run into it, we should fix it with a targeted use of am_host_unpriv().

2018 02 08/priv

---

src/lxc/conf.c

In both of these cases if there is actually an error, we won't close the
pipe and the api call will hang. Instead, let's be sure to close the pipe
before waiting, so that it doesn't hang.

fix userns helper error handling

---

src/lxc/start.c

The variable 'descr' is mistakenly covered with 'descr_console'.
Steps to reproduce the problem：
1. Create and start an container test1
2. use lxc-console to attach the container, it hang

Fix lxc-console hang

---

src/lxc/cgroups/cgfsng.c

cgroups: use correct mask for chmod()

---

src/lxc/cmd/lxc-update-config.in

cmd/lxc-update-config: check for empty arguments

---

configure.ac
src/lxc/Makefile.am
src/lxc/pam/pam_cgfs.c

This moves pam_cgfs from the LXCFS repo into the LXC repo. This will allow us
to share a bunch of code between the cgroup backends and the pam module. The
next step obviously is to share code.
Closes #1307.

pam: create writable cgroups for unpriv users

---

templates/lxc-download.in

* prepend `$LXC_PATH` to `$DOWNLOAD_TEMP` on systems with `/tmp` mounted
securely as a small `tmpfs` / `noexec`
* `gpg_setup()` creates `$DOWNLOAD_TEMP` so remove superflous `mkdir`
* fixes https://github.com/lxc/lxc/issues/516

fix download template for /tmp as tmpfs or noexec

---

src/lxc/commands.c
src/lxc/commands_utils.c
src/lxc/start.c

I was thinking about the locking here yesterday and it dawned on me that we
actually don't need this at all:
- possible contention between traversing list to send states to state clients
and adding new state clients to the list:
It is the command handler that adds new state clients to the state client
list. The command handler and the code that actually sends out the container
states run in the same process so there's not contention and thus no locking
needed.
- adding state clients to the list from multiple threads:
The command handler itself is single-threaded so only one thread's request can
be served at the same time so no locking is needed.
- sending out the state to state clients via the command handler itself:
The state client also adds and removes state clients from the state …

commands: remove mutex from state client list

---

src/lxc/tools/lxc_snapshot.c

https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1751780

lxc-snapshot: fix segfault

---

src/lxc/cmd/lxc_init.c
src/lxc/initutils.c

We have an extensive set of container config options to do this
for us, and doing this unconditionally breaks several use cases.
For instance, if we want to bind mount a /dev/shm using the
container configuration, then lxc-execute, then lxc-init will
rudely unmount the /dev/shm and remount it as a private tmpfs.

lxc_init: don't mount filesystems

---

src/lxc/attach.c
src/lxc/mainloop.h
src/lxc/terminal.c
src/lxc/terminal.h

terminal: improvements and cleanup

---

doc/ja/lxc.container.conf.sgml.in

Update for commit 861813e and 23e0d9a for lxc.container.conf(5)

doc: Add lxc.console.size and remove lxc.console.buffer.logfile in Japanese man page

---

src/lxc/tools/tool_utils.c

Since we do not include config.h, personality is not set. This is fix
it. See issue #2208.

tools: Include config.h in tool_utils.c

---

src/lxc/cmd/lxc_usernsexec.c

lxc-usernsexec uses some functions (e.g. lxc_map_ids()), which are part of
the lxc library and thus use the WARN etc. macros to emit log messages.
However, it doesn't initialize the log in any way, so these messages go
into the ether.
lxc-usernsexec currently has no log parameters, so let's just log these to
stderr. Someone can do something fancier later if they want.

usernsexec: init log fd

---

src/lxc/cgroups/cgfsng.c

If we're host unpriv but root in our userns, we can't really escape
cgroups. Let's switch the cgroup escape test to reflect this.

cgroups: don't escape if we're not real root

---

src/lxc/cgroups/cgfsng.c

This reverts commit 8d961e28f1d759669b477a659cbb694aaa2af915.
Unfortunately I don't believe the check is correct in the general case.
(not in the actual commit msg) - in particular, root-started containers in an unprivileged container will end up starting under the cgroup which systemd assigned (for instance) or, worse, which the user calling 'sudo lxc-start mailcontainer -d' logged in as.

Revert "cgroups: don't escape if we're not real root"

---

src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_start.c
src/lxc/tools/tool_utils.c
src/lxc/tools/tool_utils.h

The command `lxc-execute --define lxc.environment='foo=bar' -n ubuntu --` was failing silently, with exit return code 1.
git bisect:
```
791e7a73a9bca8dbde19afb49f172a901ce0dd43 is the first bad commit
commit 791e7a73a9bca8dbde19afb49f172a901ce0dd43
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Fri Jan 12 15:31:03 2018 +0100
tools: move lxc-execute to API symbols only
Closes #2073.
```

tools: fix usage of boolean function set_config_item

---

src/lxc/conf.c

when compiling lxc with clang-5.0 parse_cap()'s main loop will produce a
warning about a tautological comparision (#2215).
By moving the result of computation into a variable (end) this is no
longer a constant expression. clang-5.0 does not do dataflow analysis at
this point, so it is, to quote someone from #llvm, "morally equivalent"
to casting `(int)i`.
in addition, we also clean up the #if HAVE_LIBCAP to no longer need
its #else branch!
Signed-off-by: Igor Galić <igor.galic@automatic-server.com>

conf: fix clang warning when building w/o libcap

---

src/lxc/conf.c

Regression introduced by 8353b4c90ed18e570521134f2c60bef56a082b55

conf: do not run the "mount" hooks twice

---

src/lxc/execute.c
src/lxc/lxc.h
src/lxc/lxccontainer.c
src/lxc/start.c
src/lxc/start.h

The problem here is that __lxc_start frees the handler, so any use
afterwards is invalid. Since we don't have access to the actual struct
lxc_container object in __lxc_start, let's pass a pointer to error_num in
so it can be returned.
Unfortunately, I'm a little too paranoid to change the return type of
lxc_start, since it returns failure if some of the cleanup fails, which
may be useful in some cases. So let's keep this out of band.
Closes #2218
Closes #2219
Reported-by: Felix Abecassis <fabecassis@nvidia.com>

fix handler use-after-free

---

src/lxc/log.c

This has annoyed me for a long time, 3.0 seems like the time to fix it :).
I think the way that the log prefix was intended to be used was perhaps a
dynamic prefix per file, but we don't do that today; we include the
filename later in the log message. Instead, we use it as the tool name,
which for liblxc is always "lxc", but could also be things like
"lxc-cgroup" or whatever. There is absolutely no reason to pad this, since
it is always the same for every log file (in fact, we could probably get
rid of the prefix all together, but that seems slightly more drastic).
Instead, let's just drop this padding. Hopefully this will save thousands
of hours of slight annoyance and right scrolling in various pastebins.

remove leading whitespace from log files

---

config/init/common/lxc-net.in

Naming functions like tools but do something different is not that intuitive https://manpages.debian.org/testing/ifupdown/ifup.8.en.html
That is why I changed it to `_ifup` and `_ifdown` to make that clear that it does something different.
Also there is no need to pass along environment parameters as function parameter. 
Signed-off-by: Felix hi@l33t.name

Rename ifup/down and remove usless parameter passing

---

src/lxc/lxccontainer.c

lxccontainer: truncate config file

---

src/lxc/conf.c

This function was way more syscall heavy than it needed to be.

conf: simplify autodev

---

src/lxc/start.c

Otherwise lxc.hook.mount hooks that try to inspect /proc/<pid>/*
will fail.
Cc: Jonathan Calmels <jcalmels@nvidia.com>

start: always make us dumpable

---

doc/lxc.container.conf.sgml.in
src/lxc/confile.c

When a bare environment variable is specified then retrieve the value from the
current environment. For example, setting
lxc.environment = PATH
will cause LXC to inherit the value of PATH from the current environment.
Suggested-by: Jonathan Calmels <jcalmels@nvidia.com>

confile: expand lxc.environment

---

src/lxc/start.c

The problem here is that these two clauses were ordered backwards: we first
check if the signal came from not the init pid, and if it did, then we give
a notice and return. The comment notes that this is intended to protect
against SIGCHLD, but we don't in fact know if the signal is a SIGCHLD yet,
because that's tested in the next hunk.
The symptom is that if I e.g. send SIGTERM from the outside world to the
container init, it ignores it and gives this notice. If we re-order these
clauses, it forwards non SIGCHLD signals, and ignores SIGCHLD signals from
things that aren't the real container process.

fix signal sending in lxc.init

---

src/lxc/conf.c
src/lxc/ringbuf.c

lxc_make_tmpfile() uses mkstemp() internally, and thus expects the
template to contain 'XXXXXX' and be writable.
The existing code in make_anonymous_mount_file() did not work in
case the memfd_create() syscall was not available.
Furthermore, mkstemp() modifies its template argument, hence it
should not be a constant, or undefined behavior can happen. Fixed
both occurrences.
//cc @thmo I tried to push directly to your branch but I think you opted out of this feature. So I'm doing a new pr here. It's really just coding OCD stuff. :)

Fix temp file creation

---

configure.ac
src/lxc/Makefile.am

Commit c06ed219c47098f34485d408410b6ecc94a40877 has broken
compilation with a static libcap and a shared gnutls.
This results in a build failure on init_lxc_static if gnutls is
a shared library as init_lxc_static is built with -all-static option
(see src/lxc/Makefile.am) and AC_CHECK_LIB adds gnutls to LIBS.
This commit fix the issue by removing default behavior of AC_CHECK_LIB
and handling manually GNUTLS_LIBS and HAVE_LIBGNUTLS
Fixes:
- http://autobuild.buildroot.net/results/b655d6853c25a195df28d91512b3ffb6c654fc90

Fix compilation with static libcap and shared gnutls

---

src/lxc/attach.c
src/lxc/utils.h

attach: always drop supplementary groups

---

src/lxc/attach.c

attach: try to always drop supplementary groups

---

src/lxc/conf.c
src/lxc/execute.c
src/lxc/start.h

We should always default to mounting devpts with gid=5 but we should fallback
to mounting without gid=5. This let's us cover use-cases such as container
started with only a single mapping e.g.:
lxc.idmap = u 1000 1000 1
lxc.idmap = g 1000 1000 1
Closes #2257.

conf: ret-try devpts mount without gid=5 on error

---

src/lxc/conf.c

I noticed that with `lxc.hook.version = 1` set, environment variable `LXC_NET_PEER` wasn't set for veth interfaces in `lxc.net.[i].script.{up,down}` hooks. It seems to me that all net type check conditions in `run_script_argv()` should test for string equality, not inequality.

conf: fix net type checks in run_script_argv()

---

src/lxc/seccomp.c

This commit deals with different kernel and userspace layouts and nesting. Here
are three examples:
1. 64bit kernel and 64bit userspace running 32bit containers
2. 64bit kernel and 32bit userspace running 64bit containers
3. 64bit kernel and 64bit userspace running 32bit containers running 64bit containers
Two things to lookout for:
1. The compat arch that is detected might have already been present in the main
context. So check that it actually hasn't been and only then add it.
2. The contexts don't need merging if the architectures are the same and also can't be.
With these changes I can run all crazy/weird combinations with proper seccomp
isolation.
Closes #654.
Link: https://bugs.chromium.org/p/chromium/issues/detail?id=832366
Reported-by: Chirantan Ekbote <chirantan@chromium.org> …

seccomp: handle arch inversion

---

templates/lxc-oci.in

The directory might not exist on a fresh install.

lxc-oci: mkdir the download directory

---

src/lxc/tools/lxc_monitor.c

lxc_monitor.c uses offsetof(), so it should include
<stddef.h>. Otherwise the build fails with the musl C library:
tools/lxc_monitor.c: In function ‘lxc_abstract_unix_connect’:
tools/lxc_monitor.c:324:9: warning: implicit declaration of function ‘offsetof’ [-Wimplicit-function-declaration]
offsetof(struct sockaddr_un, sun_path) + len + 1);
^~~~~~~~
tools/lxc_monitor.c:324:18: error: expected expression before ‘struct’
offsetof(struct sockaddr_un, sun_path) + len + 1);
^~~~~~
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

lxc/tools/lxc_monitor: include missing <stddef.h>

---

src/lxc/tools/lxc_checkpoint.c

I noticed that support for passing action scripts to CRIU via lxc-checkpoint was added in #2236 , but the action script is only passed to CRIU in restore mode. This change adds passing of the action script in checkpoint mode as well.

Also pass action scripts to CRIU on checkpointing

---

src/lxc/tools/tool_utils.h

Add inline setns() function to tool_utils.h. Without it
tool_utils.c can't be build when HAVE_SETNS is unset.

Fix tool_utils.c build when HAVE_SETNS is unset

---

src/lxc/execute.c
src/lxc/utils.h

The problem here is that lxc-init runs *inside* the container. So if a
person has the log file set to /home/$USER/foo, lxc-init ends up making a
directory /home/$USER/foo inside the container to put the log file in. What
we really want are the logs to be propagated from inside the container to
the outside. We accomplish this by passing an fd without O_CLOEXEC, and
telling lxc-init to log to that file.

fix logic for execute log file 

---

src/lxc/execute.c

This is already done in do_lxcapi_start{l}() so a) no need to do it again here
and b) this would close the state socket pair sockets and corrupt memory.

execute: do not check inherited fds again

---

src/lxc/confile_utils.c

Apparently -Werror=stringop-overflow will trigger an error here even though
this is completely valid since we now that we're definitely copying a \0-byte.
Work around this gcc-8 quirk by using memcpy(). This shouldn't trigger the
warning.

confile: satisfy gcc-8

---

config/templates/userns.conf.in

Unprivileged containers can safely mount /sys as read-write. This also allows
systemd-udevd to be started in unprivileged containers.

config: allow read-write /sys in user namespace

---

src/lxc/caps.c
src/lxc/caps.h
src/lxc/start.c

Suggested-by: Jonathan Calmels <jcalmels@nvidia.com>

capabilities: raise ambient capabilities

---

src/lxc/conf.c

In function userns_exec_full() @ conf.c, there is the following
pointer that is used in a double-linked list, struct lxc_list *idmap = NULL;
This pointer is malloc()-ed, and then additional objects are added to
the list using lxc_list_add_tail().
At the end of the function, the dynamically allocated memory is freed with lxc_free_idmap(idmap);
lxc_free_idmap(idmap) does not free memory of the initial memory
allocation for "idmap", therefore there is a memory leak.
The function lxc_free_idmap() is used in another place as well, and at
that place it does not free() the initial pointer (correct behaviour).
Therefore, there is a need for a free() in the function
userns_exec_full() @ conf.c.

Fixed resource leak in userns_exec_full()

---

src/lxc/network.c

In function is_wlan() @ network.c, there is a file handle FILE* f.
There is one exit point in the function where the file handle is not fclose()-ed.

Fixed resource leak in is_wlan() at network.c

---

src/lxc/conf.h
src/lxc/log.c
src/lxc/lxccontainer.c

When using the LXC API multi-thread and users initialize a log:
struct lxc_log log;
log.name = "my-log";
lxc_log_init(&log);
all threads will have the same "my-log" prefix even though thy might call
lxc_container_new() in separate threads. There is currently no easy way to
handle per-thread container name prefixes.
To handle this carry a reference to the name of the container in struct
lxc_conf and if no log.name was set, use it by default. This way each thread
will get the container it is currently working on as a log-prefix.
Reported-by: duguhaotian <duguhaotian@gmail.com>

log: enable per-thread container name prefix

---

src/lxc/cmd/lxc_init.c

lxc-init: skip signals that can't be caught

---

src/lxc/tools/lxc_attach.c
src/lxc/tools/lxc_autostart.c
src/lxc/tools/lxc_cgroup.c
src/lxc/tools/lxc_checkpoint.c
src/lxc/tools/lxc_console.c
src/lxc/tools/lxc_copy.c
src/lxc/tools/lxc_create.c
src/lxc/tools/lxc_destroy.c
src/lxc/tools/lxc_device.c
src/lxc/tools/lxc_execute.c
src/lxc/tools/lxc_freeze.c
src/lxc/tools/lxc_info.c
src/lxc/tools/lxc_ls.c
src/lxc/tools/lxc_monitor.c
src/lxc/tools/lxc_snapshot.c
src/lxc/tools/lxc_start.c
src/lxc/tools/lxc_stop.c
src/lxc/tools/lxc_unfreeze.c
src/lxc/tools/lxc_wait.c

We used to initialize a log unconditionally before. This has led to scenarios
where users where left with container directories and an empty log file even
though they didn't request a log be created at all.
Switch all tools to only create a log file when the user explicitly requests
this.
Closes #1779.
Closes #2032.

tools: only create log file when requested

---

src/lxc/seccomp.c
src/lxc/utils.c
src/lxc/utils.h

The most important commit is eacebcc3cb8cf5d29556c85fe826096723475242, which fixes an integer overflow while parsing the argument filters.

Seccomp fixes

---

src/lxc/cmd/lxc_init.c
src/lxc/cmd/lxc_monitord.c
src/lxc/lxccontainer.c
src/lxc/start.c
src/lxc/terminal.c
src/lxc/utils.c

The behavior of sigprocmask() is unspecified in multi-threaded programs. Let's
use pthread_sigmask() instead.

tree-wide: s/sigprocmask/pthread_sigmask()/g

---

src/lxc/seccomp.c

Fix an error case not free()ing the line forgotten during
the move from fgets() on a static buffer to using getline.
Fixes: ccf8d128e430 ("seccomp: parse_config_v1()")

seccomp: leak fixup

---

src/lxc/seccomp.c

See individual commits.
Let me know if you prefer commit 2 to keep separate `line` pointers in the v1/v2 functions as I'm not sure this fits your style (as the parent's buffer is `realloc()`ed, and `free()`d inside the callees.

Seccomp fixup part 2

---

src/lxc/network.c

Hello,
The handle 'sockfd' was created at network.c:2025 by calling function 'socket' and lost at network.c:2031

network: fix socket handle leak

---

src/lxc/conf.c
src/lxc/start.c

ns_clone_flags is used as a bitmask so initializing it to -1 is a bad idea.

start: do not init ns_clone_flags to -1

---

src/lxc/start.c
src/lxc/utils.c
src/lxc/utils.h

Closes #2356.
See https://discuss.linuxcontainers.org/t/failed-to-start-lxc-on-linux-kernel-2-6-32-220 .

start: enable pre-setns() kernels

---

src/lxc/conf.c

Hello,
Function 'va_end' was not called before conf.534 inside function 'run_script'.
Function 'va_start' was called at conf.c:528.

conf: va_end was not called.

---

templates/lxc-download.in

The way 'mktemp' is currently used you will get a temp directory in
$TMPDIR or '/tmp' and DOWNLOAD_TEMP will not be pointing to an actual
directory. This will result in the wget operations failing and the
container will fail to create:
ERROR: Failed to download http://....
Instead we want to use the '-p' option for mktemp to set the base path
and this will ensure that the temp directory is created in the correct
location and DOWNLOAD_TEMP will be consistent with this location.
Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>

templates: actually create DOWNLOAD_TEMP directory
