lxc/lxc

src/lxc/lxclock.c
lxclock_name will fallback to /tmp/$(id -u)/lxc$lxcpath/.$lxcname when failed to create directories into rundir. But, in currently, lxclock_name returns untill preparing directories under the /tmp, so invoker will fail to get the container lock.  This patch fixes fixes this.
=> fix failed to fallback at lxclock_name

doc/lxc.container.conf.sgml.in, src/lxc/conf.h, src/lxc/confile.c
Update #533 by adding signed-off-by line for the doc commit.
=> Passthru v1.2

templates/lxc-oracle.in
fix a bug，& shoud be \\& in sed
Signed-off-by: feng xiahou xiahoufeng@yahoo.com
=> Update lxc-oracle.in fix a bug

templates/lxc-debian.in
Signed-off-by: feng xiahou <xiahoufeng@yahoo.com>
=> debian template: reconfigure locales

src/lxc/bdev.c
Loop devices can be added on the fly when needed, they're
not always created beforehand. The loop-control device can
be used to find and allocate the next available number
instead of going through the /dev directory contents (which
is now only a fallback mechanism).
=> Use /dev/loop-control if it exists

doc/common_options.sgml.in, doc/ja/common_options.sgml.in, doc/ja/lxc-ls.sgml.in, doc/ja/lxc-user-nic.sgml.in, doc/ko/lxc-user-nic.sgml.in, doc/lxc-ls.sgml.in, doc/lxc-user-nic.sgml.in
* Add the description for -P and --version option to lxc-ls(1) (English, Japanese only)
* Add the description for --version option to common options (English, Japanese only)
* Remove unnecessary common options from lxc-user-nic(1) (All languages)
=> Update man pages

doc/ko/common_options.sgml.in, doc/ko/lxc-ls.sgml.in, doc/ko/lxc-usernet.sgml.in
I update Korean manuals for commits : 7cab33b, 2cf7c05,1940bff, .
=> Update Korean manuals

src/lxc/lxc_clone.c
This commit adds an -R, --rename option to lxc-clone to rename a container. As
c->rename calls do_lxcapi_rename() which in turn calls do_lxcapi_clone() it
seemed best to implement it in lxc-clone rather than lxc-snapshot which also
calls do_lxcapi_clone(). Some additional unification regarding the usage of
return vs exit() in main() was done.
closes #606
=> Add option to rename container to lxc-clone

CONTRIBUTING
=> Fresh CONTRIBUTING

src/lxc/lxccontainer.c
Signed-off-by: Robert LeBlanc <robert@leblancnet.us>
=> Small trivial typo.

src/lxc/confile.c
Signed-off-by: Nicolas Cornu <nicolac76@yahoo.fr>
I correct a typo too. Tell me if I need to remove it.
=> Split handle of lxc.mount* with 3 functions

doc/lxc.container.conf.sgml.in, src/lxc/conf.c
This functionnality was duplicate 3 times. Let's merge it together ;)
And there was no documentation about it ;)
=> A little bit of refactor and doc

doc/lxc-snapshot.sgml.in
=> Adapt manpage for lxc-snapshot

config/templates/Makefile.am, config/templates/slackware.common.conf.in, config/templates/slackware.userns.conf.in, configure.ac, templates/Makefile.am, templates/lxc-slackware.in
Requires pkgtools and slackpkg (from the slackware-current tree).
Signed-off-by: Matteo Bernardini <ponce@slackbuilds.org>
=> Add a slackware template.

src/lxc/seccomp.c
lxc uses uname to check the kernel version.  Seccomp respects userspace.  In the case
of 32-bit userspace on 64-bit kernel, this was a bad combination.
When we run into that case, make sure that the compat seccomp context is 32-bit, and
the lxc->seccomp_ctx is the 64-bit.
Closes #654
=> seccomp: handle inverted arch

src/lxc/lxccontainer.h
=> lxc_container struct: add comment about moving member fns

src/lxc/lxccontainer.c
Always try a btrfs snapshot first. If that fails and the user
did not request -s, then try a copy-clone.
See lp #1532125
=> copy_storage: try to use snapshot for btrfs

templates/lxc-archlinux.in
=> Fix typo in lxc-archlinux.in

templates/lxc-ubuntu.in
This is a replacement for #733
Parameter is optional. Added help text and parameter parsing. A couple packages that make network work out of the box added.
Signed-off-by: Vaidas Kascėnas <vaidas@kascenas.lt>
=> Template parameter --variant tells debootstrap which variant to use.

doc/ja/lxc.container.conf.sgml.in, doc/ko/lxc.container.conf.sgml.in, doc/lxc.container.conf.sgml.in, src/lxc/conf.c
a fix for #781 
please review.
thanks
=> increase /dev size to 500k ( issue #781)

src/lxc/cgfs.c
This allows cgfs to be used to create containers in a user namespace,
and have the container owner be able to use cgroups.
=> implement chown for cgfs

src/lxc/lxc_copy.c
various fixes/improvements to lxc-copy.
=> lxc-copy: cleanup

src/lxc/conf.c
All lxc.mount.entry entries will be relative to the host's / when a container
does not have a rootfs.
=> no rootfs => mounts always relative to host's /

src/lxc/lsm/apparmor.c
Ideally a container configuration will specify 'unchanged' if
it wants the container to use the current (parent) profile.  But
lxd passes its current label.  Support that too.
Note that if/when stackable profiles exist, this behavior may
or may not be what we want.  But the code to deal with aa
stacking will need some changes anyway so this is ok.
With this patch, I can create nested containers inside a
lxd xenial container both using
lxc launch x2
and unprivileged
lxc-start -n x2
=> apparmor: don't fail if current aa label is given

src/lxc/lxc_destroy.c
As per https://bugs.launchpad.net/bugs/1543016.
=> lxc_destroy: be quiet if asked

src/lxc/log.c
Tiniest of changes to the log code to try to make it more robust.
=> 2016 02 15/lognull

doc/ja/lxc-checkpoint.sgml.in, doc/ko/lxc-checkpoint.sgml.in, doc/ko/lxc-ls.sgml.in, doc/lxc-checkpoint.sgml.in
=> Fix doc build warnings

src/lxc/cgfs.c
This makes lxc with cgfs backend work when the cgroup mounts come from lxcfs.
=> 2016 02 19/cgfs

config/apparmor/Makefile.am, config/apparmor/profiles/lxc-default-cgns, config/apparmor/profiles/lxc-default-with-nesting, doc/lxc.container.conf.sgml.in, src/lxc/lsm/apparmor.c, src/tests/attach.c, src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-ubuntu
Apparmor policy support for user namespaces.
=> 2016 02 21/cgns.aa

doc/ja/lxc.container.conf.sgml.in
=> doc: Add Japanese description of cgns apparmor profile in lxc.container.conf(5)

src/lxc/lxc_attach.c
- The code required to prepare an fd to act as a login tty is shared among
pty_on_host_callback() and fork_pty(). This implements login_pty(), a
minimalistic login_tty() clone, to avoid code redundancy.
- Give pty_in_container() a slightly extended comment.
=> lxc-attach: add comment, & implement login_tty()

doc/ja/lxc-attach.sgml.in, doc/ja/lxc-clone.sgml.in, doc/ja/lxc-start-ephemeral.sgml.in
Update
* lxc-attach(1)
* lxc-clone(1)
* lxc-start-ephemeral(1)
=> Update Japanese man

src/lxc/cgfs.c
If lxcfs starts before cgroup-lite, then the first cgroup mountpoints in
/proc/self/mountinfo are /run/lxcfs/*.  Unprivileged users cannot access
these.  So privileged containers are ok, and unprivileged containers are ok
since they won't cache those to begin with.  But unprivileged root-owned
containers cache /run/lxcfs/* and then try to use them.
So when doing cgroup automounting check whether the mountpoints we have
stored are accessible, and if not look for a new one to use.
=> cgfs: make sure we use valid cgroup mountpoints

doc/ja/lxc-attach.sgml.in
Update the description of pty allocation. Update for commit 478dda7.
=> doc: Update Japanese lxc-attach(1)

src/lxc/lxc_attach.c
closes #858 
lxc-attach uses lxc_console_create() to allocate a pty on the host.
lxc_console_create() in turn calls lxc_console_peer_default() which either
makes the current controlling pty our controlling pty for the container, or
uses whatever the user gave us (e.g. /dev/tty2 etc.). For lxc-attach we always
want the current controlling pty to be used. This commit ensures that we're in
fact always using the current controlling pty. The commit also fixes a segfault
when the user specified lxc.console.path = none.
=> lxc-attach: always allocate current controlling pty

src/lxc/start.c
closes #861 (ping @stgraber)
lxc should not reboot the container when lxc.hook.post-stop fails. It should
simply shutdown. This makes the behavior of lxc.hook.post-stop and
lxc.hook.pre-start consistent. When lxc.hook.pre-start fails, the container
does not start.
=> start.c: do not reboot on lxc.hook.post-stop fail

templates/lxc-plamo.in
=> plamo: Update release version and repository for getting packages

src/lxc/console.c, src/lxc/console.h
Something which I sorely missed when working on the new lxc-attach.
=> console.{c.h}: add/improve documentation

configure.ac, templates/lxc-altlinux.in
- Added ALTLinux distribution.
- Updated template for ALTLinux Sisyphus
Signed-off-by: Denis Pynkin <denis_pynkin@epam.com>
=> Added ALTLinux distribution.

src/lxc/cgfsng.c
=> Remove trailing newlines in log

src/lxc/cgfsng.c
=> cgfsng: set cpuset clone_children if needed

src/tests/lxc-test-lxc-attach
=> lxc-attach: update and improve tests

src/lxc/cgfsng.c
Add a temporary workaround for talking to containers started with the
buggy monitor.  We can remove it sometime after 2.0 release.
=> cgfsng: get_cgroup_path: return the cgroup path not full mounted path

src/lxc/cgfsng.c
=> cgfsng: chmod the tasks and procns files

src/lxc/cgfsng.c, src/lxc/cgroup.c, src/lxc/liblxc.so.1, src/tests/Makefile.am, src/tests/lxc-test-automount
Not sure about the second patch.  Do we want cgmanager to be used if available and compiled in, or not?
=> 2016 03 16/cgroupauto

src/lxc/cgfsng.c
to hopefully define RELATIME for android
=> cgfsng: include sys/mount.h

src/lxc/conf.c
In particular, only create /dev/console when it is set to "none".
Otherwise, we will bind mount a pts device later, so let's just leave it.
Also, when bind mounting the pts device, let's create /dev/console if it
doesn't exist, since it may not already exist due to the above :)
=> autodev: don't always create /dev/console

src/lxc/criu.c
probably should have done both of these long ago :)
=> Better criu logging

templates/lxc-busybox.in
Signed-off-by: Bogdan Purcareata <bogdan.purcareata@nxp.com>
=> lxc-busybox: Touch /etc/fstab in the container rootfs

src/lxc/start.c
See comments for details, but basically, only use the host's /dev/null when
absolutely necessary (i.e. there is no reasonable /dev/null in the
container).
=> start: only use host's /dev/null when absolutely necessary

templates/lxc-ubuntu.in
=> lxc-ubuntu: Fix building on secondary architectures

.gitignore, src/lxc/liblxc.so.1
=> also ingore *.so.*

doc/lxc.container.conf.sgml.in, src/lxc/confile.c
=> switch user facing name to lxc.rootfs.backend

doc/ja/lxc.container.conf.sgml.in
=> doc: Add lxc.rootfs.backend in Japanese lxc.container.conf(5)

src/lxc/lxccontainer.c
=> add more error handling + cleanup copy_storage()

src/lxc/nl.c
All uses of netlink_open() assume that on error the
nl_handler doesn't need to be closed, but some error cases
happen after the socket was opened successfully and used to
simply return -errno.
=> netlink_open: close socket on error

src/lxc/lxc_create.c
- call lxc_container_put() before we exit()
- reorder includes
- use EXIT_FAILURE and EXIT_SUCCESS macros
=> lxc-create: bugfixes and small improvements

src/lxc/conf.c
=> lxc_mount_auto_mounts(): free memory on failure

src/lxc/cgfsng.c
This requires us to check that at cgfsng_ops_init, rather than
cgfs_init.  Cache the hierarchy and cgroup.use info globally
rather than putting it into the per-container info, as cgmanager
does.  This is ok as both cgroup.use and the list of usable
hierarchies are in fact global to a lxc run.
Closes #952
=> cgfsng: defer to cgfs if needed subsystems are not available

src/lxc/lxc_create.c
=> lxc-create: fix -B best option

.gitignore
Signed-off-by: Matt Ullman <staticfox@staticfox.net>
=> Ignore temporary files generated by doxygen

doc/lxc-attach.sgml.in
=> lxc-attach: add logging option to manpage

config/init/sysvinit/lxc-containers.in, config/init/sysvinit/lxc-net.in
original patch by Daniel Baumann
closes #308
=> add missing lsb headers to sysvinit scripts

src/lxc/console.c
Let's be on the safe side and mimic ssh.
=> use raw settings of ssh for pty

doc/ja/lxc-attach.sgml.in
=> doc: Add logging option to Japanese lxc-attach(1)

src/lxc/lxc_ls.c
Speed things up a little on hosts with a lot of containers.
=> 2016 04 28/less syscall for lxc ls

src/lxc/sync.c
=> sync.c: use correct types

templates/lxc-centos.in
Signed-off-by: Hartnell Foster <hartnell.foster@bbc.co.uk>
=> Added OR statement for cases of ID = rhel in RHEL 7+

config/apparmor/abstractions/container-base, config/apparmor/abstractions/container-base.in
=> Also allow fstype=fuse for fuse filesystems

templates/lxc-alpine.in
Signed-off-by: Andrey Kostin <andrey@kostin.email>
=> Fix hostname in interface config for apline template

templates/lxc-plamo.in
* configure to start only the minimum of service
* add ntp, kmod to ignore packages
=> plamo: Improve Plamo template

doc/ja/lxc-attach.sgml.in, doc/ko/lxc-attach.sgml.in, doc/lxc-attach.sgml.in
=> Fix typo found by lintian

src/lxc/criu.c, src/lxc/lxccontainer.h
=> c/r: add support for CRIU's --action-script

doc/lxc-copy.sgml.in
=> lxc-copy: update manpage to include tmpfs option

src/lxc/criu.c, src/lxc/lxccontainer.h
This is an old option that we probably should have exposed long ago :)
=> c/r: add support for ghost-limit in CRIU

doc/ja/lxc-copy.sgml.in
=> doc: Update Japanese lxc-copy(1) to include tmpfs option

doc/ko/lxc-copy.sgml.in
Update for commit a361e56
Signed-off-by: Sungbae Yoo <sungbae.yoo@samsung.com>
=> doc: Update Korean lxc-copy(1) to include tmpfs option

templates/lxc-debian.in
Nothing special in these commits (imho). Just a few changes explained by the commit-messages.
=> simple enhancements of lxc-debian-template-script

src/lxc/lxc_copy.c
Fixes android builds:
DSBINDIR=\"/data/lxc/lxc/sbin\"      -I/build/libcap/libcap/include/ -Wall -Werror -MT lxc_copy.o -MD -MP -MF $depbase.Tpo -c -o lxc_copy.o lxc_copy.c &&\
mv -f $depbase.Tpo $depbase.Po
lxc_copy.c: In function 'mount_tmpfs':
lxc_copy.c:834:2: error: implicit declaration of function 'mkostemp' [-Werror=implicit-function-declaration]
fd = mkostemp(premount, O_CLOEXEC);
^
lxc_copy.c:841:2: error: implicit declaration of function 'dprintf' [-Werror=implicit-function-declaration]
ret = dprintf(fd, "#! /bin/sh\n"
^
=> lxc-copy: do not use mkostemp and dprintf

src/lxc/criu.c
=> criu: replace tmpnam() with mkstemp()

doc/lxc.container.conf.sgml.in, src/lxc/confile.c, src/lxc/log.c, src/lxc/log.h, src/lxc/start.c
Add a syslog logger activable via the configuration file.
While here add the VM name in the log lines to help debugging
=> Add syslog support

doc/ja/lxc.container.conf.sgml.in, doc/lxc.container.conf.sgml.in
and add local6 to valid facility
=> doc: Add documentation of lxc.syslog to Japanese lxc.container.conf(5)

doc/ko/lxc.container.conf.sgml.in
=> doc: Add documentation of lxc.syslog to Korean lxc.container.conf(5)

src/lxc/tools/lxc_ls.c
So far we've simply been using RUNTIME_PATH for the privileged and unprivileged
case. We should actually use XDG_RUNTIME_DIR for the unprivileged case.
=> tools: use correct runtime path for lxc-ls

src/lxc/tools/lxc_create.c
=> tools: add missing newline in lxc-create output

src/tests/Makefile.am
=> autotools: fix tests

src/lxc/seccomp.c
- log more errnos
- adapt coding style
=> seccomp: non functional changes

configure.ac, templates/Makefile.am, templates/lxc-pld.in
from pld-linux repo:
https://github.com/pld-linux/lxc/commits/auto/th/lxc-2.0.4-1/lxc-pld.in.sh
https://github.com/pld-linux/lxc/commits/auto/th/lxc-2.0.4-1/lxc-pld.patch
they are mature enough to upstreamed (not much changes recently to those files) and it's always better if these are present in upstream as well so upstream could make common changes to all distro scripts.
=> add PLD Linux support to upstream repo

src/lxc/tools/lxc_autostart.c, src/lxc/tools/lxc_cgroup.c, src/lxc/tools/lxc_checkpoint.c, src/lxc/tools/lxc_clone.c, src/lxc/tools/lxc_config.c, src/lxc/tools/lxc_console.c, src/lxc/tools/lxc_device.c, src/lxc/tools/lxc_execute.c, src/lxc/tools/lxc_freeze.c, src/lxc/tools/lxc_info.c, src/lxc/tools/lxc_monitor.c, src/lxc/tools/lxc_start.c, src/lxc/tools/lxc_stop.c, src/lxc/tools/lxc_top.c, src/lxc/tools/lxc_unfreeze.c, src/lxc/tools/lxc_unshare.c, src/lxc/tools/lxc_usernsexec.c, src/lxc/tools/lxc_wait.c
=> tools: use exit(EXIT_*) everywhere

src/lxc/tools/lxc_device.c
=> tools: use boolean for ret in lxc_device.c

src/lxc/criu.c
=> c/r: Fix pid_t on some arches

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/log.c, src/lxc/log.h, src/tests/get_item.c, src/tests/lxctest.h
- simplify and model after lxc log functions
- add necessary callbacks to confile.c
Closes #1165.
=> syslog tweaks

templates/lxc-alpine.in
Signed-off-by: Alex Athanasopoulos <alex@melato.org>
=> templates: use correct cron version in alpine template

src/lxc/lxccontainer.c
=> c/r: zero a smaller than known migrate_opts struct

doc/ja/lxc.container.conf.sgml.in
=> doc: Add lxc.no_new_privs to Japanese lxc.container.conf(5)

src/lxc/cgroups/cgfs.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgmanager.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/criu.c, src/lxc/utils.c, src/lxc/utils.h
This is a fix for one of the issues mentioned in #1156; see the 4th patch in the series for the bulk of the fix.  The CRIU commit in question went into criu-dev today, and should be in 2.7.
=> Cgroup root on dump

src/lxc/attach.c, src/lxc/seccomp.c
=> tools: fix lxc-attach regression with -s USER

src/lxc/tools/lxc_ls.c
=> tools: do not add trailing spaces on lxc-ls -1

src/lxc/criu.c
=> c/r: detatch from controlling tty on restore

src/lxc/utils.c
Make sure we don't return uninitialized memory.
=> utils: fix lxc_string_split()

src/lxc/criu.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/lxc-test-utils.c
Unit tests used to segfault on `///` and `""`.
=> 2016 09 25/lxc deslashify

config/init/systemd/lxc.service.in, config/init/systemd/lxc@.service.in
=> add Documentation entries to lxc and lxc@ units

templates/lxc-archlinux.in
=> archlinux: Do DHCP on eth0

templates/lxc-archlinux.in
=> archlinux: Fix resolving

config/templates/Makefile.am, config/templates/voidlinux.common.conf.in, config/templates/voidlinux.userns.conf.in, configure.ac, templates/Makefile.am, templates/lxc-voidlinux.in
Requires `xbps-query` and `xbps-install` 
Signed-off-by: Gregor Reitzenstein <dean4devil@paranoidlabs.org>
=> Add voidlinux distribution

templates/lxc-alpine.in
Signed-off-by: Sander Klein <github@roedie.nl>
=> alpine: Fix installing extra packages

templates/lxc-ubuntu.in
=> ubuntu: Fix package upgrades requiring proc

src/lxc/Makefile.am
=> Tweak libtool handling to work with Android

src/python-lxc/setup.py
=> Fix environment before importing setuptools

src/lxc/cgroups/cgfs.c
And let's be on the safe side by NULLing free()ed variables.
Closes #1258.
=> cgfs: fix invalid free()

templates/lxc-opensuse.in
this is how it is shipped in Debian and Ubuntu
=> find OpenSUSE's build also as obs-build

src/lxc/start.c
rather than waiting and later unsharing.
This "makes the creation of a new cgroup early enough that the existing
cgroup mounts are visible.  Which means any fancy permission checks
I dream will work on a future version of liblxc."
This also includes what should be a tiny improvement regarding netns,
though it's conceivable it'll break something.  Remember that with new
kernels we need to unshare netns after we've become the root user in the
new userns, so that netns files are owned by that root.  But we were
passing the unfiltered handler->clone_flags to the original clone().
This just resulted in a temporary extra netns generation, but still
worked since our target netns, which we passed our devices into, was
created late enough.
Signed-off-by: Serge Hallyn serge@hallyn.com …
=> container start: clone newcgroup immediately

src/lxc/start.c
If we do it earlier we end up with a wrong view of /proc/self/cgroup. For
example, assume we unshare(CLONE_NEWCGROUP) first, and then create the cgroup
for the container, say /sys/fs/cgroup/cpuset/lxc/c, then /proc/self/cgroup
would show us:
8:cpuset:/lxc/c
whereas it should actually show
8:cpuset:/
=> start: CLONE_NEWCGROUP after we have setup cgroups

src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-autostart, src/tests/lxc-test-unpriv, src/tests/lxc-test-usernic.in, templates/lxc-ubuntu-cloud.in
=> Update Ubuntu release name: add zesty

templates/lxc-ubuntu-cloud.in
Add squashfs format file support for lxc-ubuntu-cloud.in
Closes #1287
=> templates: add squashfs support to lxc-ubuntu-cloud.in

config/bash/Makefile.am, configure.ac
=> install bash completion where pkg-config tells us to

src/lxc/attach.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/error.c, src/lxc/lxc_user_nic.c, src/lxc/namespace.c, src/lxc/namespace.h, src/lxc/start.c, src/lxc/start.h, src/lxc/utils.c, src/lxc/utils.h
Closes #1253.
Closes https://github.com/lxc/lxd/issues/2439.
=> remove veth device from host

src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_unshare.c
The identifiers for namespaces used with lxc-unshare and lxc-attach as given on
the manpage do not align with the standard identifiers. This affects network,
mount, and uts namespaces. The standard identifiers are: "mnt", "uts", and
"net" whereas lxc-unshare and lxc-attach use "MOUNT", "UTSNAME", and "NETWORK".
I'm weary to hack this into namespace.{c.h} by e.g. adding additional members
to the ns_info struct or to special case this in lxc_fill_namespace_flags().
Internally, we should only accept standard identifiers to ensure that we are
always correctly aligned with the kernel. So let's use some cheap memmove()s to
replace them by their standard identifiers in lxc-unshare and lxc-attach.
=> tools: replace non-standard namespace identifiers

src/lxc/monitor.c
This will allow us to better debug possible errors.
=> cleanup monitor + improve log

src/lxc/bdev/lxclvm.c
=> lvm: supress warnings about leaked files

src/lxc/commands.c
=> commands: improve logging

src/lxc/lxc_monitord.c
Setting loglevel to DEBUG will allow us to retrieve more useful information in
case something goes wrong. The total size of the log will not increase
significantly.
=> lxc_monitord: improve log + set log level to DEBUG

src/lxc/lxc_monitord.c
Before lxc_monitord called lxc_monitord_cleanup() from a signal handler.  This
function calls a bunch of async signal unsafe functions and basically begs for
deadlocks. This commit switches lxc-monitord to using sigsetjmp() and
siglongjmp() in the signal handler to jump to a cleanup label that call
lxc_monitord_cleanup(). In this way, we avoid using async signal unsafe
functions.
=> lxc_monitord: make lxc-monitord async signal safe

src/lxc/lxc_monitord.c, src/lxc/mainloop.c, src/lxc/monitor.c
=> monitord: close mainloop on exit if we opened it

src/lxc/state.c
gettimeofday() is not async signal safe. So let's switch to clock_gettime() to
be on the safe side.
=> state: use async signal safe fun in lxc_wait()

src/tests/lxc-test-usernic.in
=> tests; Don't cause test failures on cleanup errors

src/lxc/tools/lxc_top.c
Signed-off-by: martin serrano <martin@attivio.com>
=> attach batch mode with -b flag which prints csv output with a timestamp

src/lxc/tools/lxc_top.c
=> tools: account for different architectures

src/lxc/attach.c
=> attach: close lsm label file descriptor

templates/lxc-busybox.in, templates/lxc-opensuse.in, templates/lxc-oracle.in, templates/lxc-plamo.in, templates/lxc-slackware.in, templates/lxc-sparclinux.in
=> do not set insecure passwords

src/lxc/console.c, src/lxc/criu.c, src/lxc/log.c, src/lxc/lxccontainer.c, src/lxc/tools/lxc_attach.c, src/lxc/utils.c
=> tree-wide: Sic semper assertis!

src/lxc/start.c
Sorry about the oversight! I saw the "(with -s !)" note on the contributing page right after I submitted the earlier PR.
=> Allow build without sys/capability.h

src/lxc/utils.c
=> util: always malloc for setproctitle

config/templates/Makefile.am, config/templates/sabayon.common.conf.in, config/templates/sabayon.userns.conf.in, configure.ac, templates/Makefile.am, templates/lxc-sabayon.in
Hi,
please add lxc-sabayon script for add support to Sabayon containers.
Thanks.
geaaru
=> Add LXC template script of Sabayon OS

src/lxc/utils.c
=> util: update setproctitle comments

src/lxc/conf.c, src/lxc/confile.c, src/lxc/utils.c
conf.c: In function 'lxc_assign_network':
conf.c:3096:25: error: '%lu' directive output may be truncated writing between 1 and 20 bytes into a region of size 19 [-Werror=format-truncation=]
snprintf(pidstr, 19, "%lu", (unsigned long) pid);
^~~
conf.c:3096:24: note: using the range [1, 18446744073709551615] for directive argument
snprintf(pidstr, 19, "%lu", (unsigned long) pid);
^~~~~
In file included from /usr/include/stdio.h:938:0,
from conf.c:35:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: format output between 2 and 21 bytes into a destination of size 19
return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
__bos (__s), __fmt, __va_arg_pack ());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
confile.c: In …
=> conf/ile: make sure buffer is large enough

src/lxc/console.c
Prevent an endless loop while executing lxc-attach in the background:
The kernel might fire SIGTTOU while an ioctl() in tcsetattr()
is executed. When the ioctl() is resumed and retries,
the signal handler interrupts it again.
We can't configure the TTY to stop sending
the signals in the first place since that
is a modification/write to the TTY already.
Still we clear the TOSTOP flag to prevent further signals.
Command to reproduce the hang:
----------------------------
cat > lxc_hang.sh << EOF
/usr/bin/timeout 5s /usr/bin/lxc-attach -n SOMECONTAINER -- /bin/true
EOF
sh lxc_hang.sh    # hangs
----------------------------
Signed-off-by: Thomas Jarosch <thomas.jarosch@intra2net.com>
=> lxc_setup_tios(): Ignore SIGTTOU and SIGTTIN signals

src/lxc/start.c
=> start: dumb down SIGCHLD from WARN() to NOTICE()

templates/lxc-archlinux.in
- already found /etc/localtime
- duplicate creation /etc/resolv.conf
=> [templates] archlinux: resolve conflicting files

src/python-lxc/lxc.c
=> python3: Deal with potential NULL char*

src/lxc/bdev/lxclvm.c, src/lxc/conf.c
=> tree-wide: include <sys/sysmacros.h> directly

src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-checkpoint-restore, src/tests/lxc-test-ubuntu, src/tests/lxc-test-unpriv
=> tests: Support running on IPv6 networks

templates/lxc-fedora.in
=> fedora: Fix i386 handling

configure.ac, src/include/prlimit.c, src/include/prlimit.h, src/lxc/Makefile.am, src/lxc/conf.c
=> android: add prlimit implementation for 32bit

src/lxc/conf.c
=> fix typo introduced in #1509

src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_unshare.c
=> attach|unshare: fix the wrong comment

src/lxc/caps.c, src/lxc/conf.c
=> caps: skip file capability checks on android

src/lxc/conf.c
=> conf: use bind-mount for /dev/ptmx

src/lxc/confile.c
=> confile: fix musl build

doc/ja/lxc.container.conf.sgml.in
=> doc: add lxc.limit to lxc.container.conf(5)

src/lxc/conf.c
=> conf: close fd in lxc_setup_devpts()

src/lxc/monitor.c
=> monitor: report errno on exec() error

src/lxc/af_unix.c, src/lxc/af_unix.h, src/lxc/commands.c, src/lxc/lxccontainer.c, src/lxc/monitor.c
=> bugfixes: {segfaults, hashes, abstract unix sockets}

config/templates/userns.conf.in, doc/lxc.container.conf.sgml.in, src/lxc/conf.c, src/lxc/console.c, src/lxc/utils.c, src/lxc/utils.h
=> harden console handling

src/lxc/utils.c
I mean.. really? But better safe than sorry.
=> utils: handle > 2^31 in lxc_unstack_mountpoint()

configure.ac
Fix: https://github.com/lxc/lxc/issues/1546
=> Install systemd units for CentOS

src/lxc/start.c
=> start: add crucial details about lxc_spawn()

src/lxc/utils.c, src/tests/lxc-test-utils.c
Suggested-by: Benedikt Rosenkranz beluro@web.de
=> utils: fix num parsing functions

src/lxc/tools/lxc_top.c
This patch add Read and Write information for blkio bytes.
=> add more detail for blkio

src/lxc/seccomp.c
=> Seccomp: update comment, print action name etc

src/lxc/start.c
=> start: pin rootfs when privileged

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c
=> conf{,ile}: allow to clear all config items

src/lxc/tools/lxc_top.c
This is patch add memory + swap monitoring from lxc-top tool
=> [lxc-top] Add memory+swap monitoring

templates/lxc-centos.in
Add cronie to have crond running in the containers.
=> Add cronie to the pkg list

src/lxc/utils.c
- check for buffer overflow
- only call INFO() after we ensured that readlink() was successful
- simplify logic
Reported-by: Benedikt Rosenkranz beluro@web.de
=> utils: fix lxc_mount_proc_if_needed()

src/lxc/conf.c
Improve setting up /dev/tty<N> devices.
=> conf: non-functional changes

doc/ja/lxc.container.conf.sgml.in
Update for commit 6e3bb2890c26ff0ca8a400eb3c0777f07ff76d83
=> doc: Add console behavior to Japanese lxc.container.conf(5)

README.md
Suggested-by: Serge Hallyn <serge@hallyn.com>
=> README: reword id mapping restrictions when unpriv

src/lxc/conf.c, src/lxc/utils.c, src/lxc/utils.h
=> idmap improvements

src/lxc/tools/lxc-checkconfig.in
For issue https://github.com/lxc/lxc/issues/1604
Signed-off-by: Shane Chen <ss1ha3tw@gmail.com>
=> add probe status checking

src/lxc/Makefile.am, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/lxccontainer.c, src/tests/parse_config_file.c
=> unit test idmap parser + userns_exec_1() rework

src/lxc/bdev/bdev.c, src/lxc/bdev/lxcaufs.c, src/lxc/bdev/lxcbtrfs.c, src/lxc/bdev/lxcoverlay.c, src/lxc/cgroups/cgfs.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgmanager.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/lxccontainer.c, src/lxc/start.c
=> idmapping bugfixes

templates/lxc-opensuse.in
=> lxc-opensuse: add Tumbleweed as supported release

src/lxc/log.c, src/lxc/log.h, src/lxc/lxc_monitord.c, src/lxc/lxccontainer.h, src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_autostart.c, src/lxc/tools/lxc_cgroup.c, src/lxc/tools/lxc_checkpoint.c, src/lxc/tools/lxc_console.c, src/lxc/tools/lxc_copy.c, src/lxc/tools/lxc_create.c, src/lxc/tools/lxc_destroy.c, src/lxc/tools/lxc_device.c, src/lxc/tools/lxc_execute.c, src/lxc/tools/lxc_freeze.c, src/lxc/tools/lxc_info.c, src/lxc/tools/lxc_init.c, src/lxc/tools/lxc_ls.c, src/lxc/tools/lxc_monitor.c, src/lxc/tools/lxc_snapshot.c, src/lxc/tools/lxc_start.c, src/lxc/tools/lxc_stop.c, src/lxc/tools/lxc_unfreeze.c, src/lxc/tools/lxc_wait.c
Fix: https://github.com/lxc/lxc/issues/1589
More discuss: https://github.com/lxc/lxc/pull/1586
=> API: expose function lxc_log_init

src/lxc/utils.c
=> utils: use 1LU otherwise we overflow

src/lxc/console.c
This patch fix the memory leak of 'lxc_tty_state' while `lxc_console_sigwinch_init` returned` lxc_tty_state*` with the sigfd is -1. We did not call the `lxc_console_sigwinch_fini` to release the ` lxc_tty_state*` memory, so the memory had been lost.
=> Fix memory leak of 'lxc_tty_state'

src/lxc/attach.c, src/lxc/bdev/bdev.c
=> fix memory and resource leak

src/lxc/arguments.c, src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/conf.c, src/lxc/start.c, src/lxc/sync.c, src/lxc/tools/lxc_init.c, src/tests/reboot.c
=> Use strerror(errno) instead of %m 

templates/lxc-centos.in
=> default to CentOS 7

src/lxc/lxccontainer.h
Fix issue: https://github.com/lxc/lxc/issues/505
=> API doc: update note for get_config_item

src/lxc/confile.c, src/lxc/confile_legacy.h
=> refactor confile code

src/lxc/confile_legacy.c
=> confile: free netdev->downscript

src/lxc/lxclock.c
=> remove the unused macro

README.md
=> README: add CII Best Practices badge to README

src/lxc/tools/lxc_execute.c
=> lxc-execute: print error message when failed

src/lxc/utils.c
=> utils: close parent end in child process after fork

src/lxc/state.h
=> state: remove lxc_rmstate declaration

src/lxc/utils.c
we shoud test whether the file exists and grants
execute permissions.
=> utils: use access instead of stat

src/lxc/cgroups/cgfsng.c
=> cgfsng: remove the old workdaround code

src/lxc/confile.c
=> stable-2.0: bugfixes

src/lxc/Makefile.am, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup_utils.c, src/lxc/cgroups/cgroup_utils.h, src/lxc/utils.c, src/lxc/utils.h
Closes #1669.
Closes #1678.
Relates to systemd/systemd#6408.
=> cgroups: handle hybrid cgroup layouts

src/lxc/cgroups/cgfsng.c
=> cgroups: workaround gcc-7 bug

src/lxc/bdev/lxclvm.c
Signed-off-by: Thomas Hipp <thipp@suse.de>
=> lvm: fix check

src/lxc/cgroups/cgfsng.c
In particular, any text (like a #comment) following the mode
would end up in our mode line.
=> Fix some bugs in #1719

templates/lxc-opensuse.in
Allows building a tumbleweed and Leap 42.3 template
=> Opensuse template improvements

config/templates/userns.conf.in, src/lxc/conf.c, src/lxc/criu.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/lxc-test-utils.c
=> conf: NOTICE() on mounts on container's /dev

.travis.yml
=> travis: fix builds

src/lxc/start.c
When a container is marked as being in STOPPED state it is possible
for another thread to start it again even though not all cleanup operations for
that container have finished. This is not a problem for most things like
sockets and friends which are unique to the container. It is however a problem
for cgroups which are named after that container in that we cause our cgroup
driver to waste cpu cycles finding a new cgroup name.
Closes  #1726.
=> start: ensure cgroups are cleaned up

templates/lxc-debian.in
Signed-off-by: feng xiahou xiahoufeng@yahoo.com
=> debian: jessie and stretch keyring support

src/lxc/storage/aufs.h, src/lxc/storage/overlay.h
=> android: fix includes

src/lxc/tools/lxc_start.c
Signed-off-by: Shukui Yang <yangshukui@huawei.com>
=> Fix mem leak with realpath

src/lxc/tools/lxc-checkconfig.in
Closes https://github.com/lxc/lxd/issues/3685
=> Add CONFIG_NETFILTER_XT_MATCH_COMMENT to lxc-checkconfig

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_legacy.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/criu.c, src/lxc/lxc_user_nic.c, src/lxc/network.c, src/lxc/network.h, src/lxc/start.c, src/lxc/start.h, src/lxc/utils.c, src/lxc/utils.h
=> network: improvements + bugfixes

src/lxc/conf.c, src/lxc/network.c, src/lxc/start.c
=> conf: don't send ttys when none are configured

src/lxc/start.c, src/lxc/start.h, src/lxc/sync.c
=> start: document all handler fields

src/lxc/conf.c
This will serve us well in the future!
=> conf: record idmap that gets written

src/lxc/conf.c
=> conf: bugfixes

doc/ja/lxc.container.conf.sgml.in, doc/ko/lxc.container.conf.sgml.in, doc/lxc.container.conf.sgml.in, doc/lxc.sgml.in, src/lxc/cgroups/cgmanager.c, src/lxc/conf.c, src/lxc/conf.h, src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-unpriv, src/tests/lxc-test-usernic.in, src/tests/parse_config_file.c, templates/lxc-sabayon.in
=> doc: adapt + update

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/criu.c, src/lxc/lxc_user_nic.c, src/lxc/network.c, src/lxc/network.h, src/lxc/start.c, src/lxc/start.h, src/lxc/sync.c, src/lxc/utils.c, src/lxc/utils.h, templates/lxc-ubuntu.in
=> stable 2.0: cherry-picks + delta reduction between master and stable 2.0

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/console.c, src/lxc/criu.c, src/lxc/lxc_user_nic.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/network.c, src/lxc/start.c, src/lxc/storage/aufs.c, src/lxc/storage/btrfs.c, src/lxc/storage/overlay.c, src/lxc/storage/storage.c, src/lxc/storage/storage.h, src/lxc/tools/lxc_unshare.c, src/lxc/tools/lxc_usernsexec.c, src/lxc/utils.c, src/tests/concurrent.c, src/tests/containertests.c, src/tests/destroytest.c, src/tests/saveconfig.c, src/tests/shortlived.c, src/tests/startone.c
=> conf: add userns_exec_full()

src/lxc/start.c, src/lxc/storage/storage.c
=> start: switch ids at last possible instance

src/lxc/start.c
=> start: set environment variables correctly

doc/lxc.container.conf.sgml.in, src/lxc/start.c, src/lxc/utils.c, src/lxc/utils.h
=> start: pass LXC_LOG_LEVEL to hooks

src/tests/lxc-test-apparmor-mount, src/tests/lxc-test-unpriv, src/tests/lxc-test-usernic.in
=> tests: Support systemd hybrid cgroups

src/lxc/cgroups/cgfsng.c
So far, we silently skipped over limits that failed to be applied which is very
odd. Let's error on when cgroup limits fail to apply.
Closes #1815.
=> cgfsng: fail when limits fail to apply

configure.ac, doc/Makefile.am, doc/lxc-update-config.sgml.in
=> doc: add lxc-update-config manpage

src/lxc/storage/lvm.c
=> lvm: fix thinpool logical volumes

doc/lxc.container.conf.sgml.in, src/lxc/cgroups/cgfsng.c, src/lxc/conf.c, src/lxc/confile.c, src/lxc/console.c, src/lxc/network.c, src/lxc/storage/aufs.c, src/lxc/storage/btrfs.c, src/lxc/storage/overlay.c, src/lxc/storage/storage.c, src/lxc/storage/storage.h
=> stable 2.0: backports

configure.ac, doc/ja/Makefile.am, doc/ja/lxc-update-config.sgml.in
=> doc: Translate lxc-update-config(1) into Japanese

src/lxc/lxccontainer.h
=> lxccontainer: preserve ABI compatibility

src/lxc/conf.c, src/lxc/log.c
=> log: bugfixes

src/lxc/confile.c, src/lxc/confile_utils.c
=> confile: use correct check on char array

src/lxc/tools/lxc_attach.c
For example the following sequence is expected to work:
lxc-start -n containerName -f /path/to/conf \
-s 'lxc.id_map = u 0 100000 65536' \
-s 'lxc.id_map = g 0 100000 65536' \
-s 'lxc.rootfs = /path/to/rootfs' \
-s 'lxc.init_cmd = /path/to/initcmd'
lxc-attach -n containerName
Closes #984.
=> stable-2.0: tools: allow lxc-attach to undefined containers

src/lxc/attach.c
When attaching to a container's namespaces we did not handle the case where we
inherited namespaces correctly. In essence, liblxc on start records the
namespaces the container was created with in the handler. But it only records
the clone flags that were passed to clone() and doesn't record the namespaces
we e.g. inherited from other containers. This means that attach only ever
attached to the clone flags. But this is only correct if all other namespaces
not recorded in the handler refer to the namespaces of the caller. However,
this need not be the case if the container has inherited namespaces from
another container. To handle this case we need to check whether caller and
container are in the same namespace. If they are, we know that things are all
good. If they aren't then we need to …
=> attach: correctly handle namespace inheritance

src/lxc/commands.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/monitor.c, src/lxc/namespace.c, src/lxc/namespace.h, src/lxc/network.c, src/lxc/network.h, src/lxc/start.c, src/lxc/start.h, src/lxc/tools/lxc_start.c
=> confile: add lxc.namespace.<namespace-key> + add user namespace sharing + rework start logic

src/lxc/start.c
=> start: only preserve CLONE_NEWCGROUP when supported

src/lxc/storage/storage.h, src/lxc/tools/lxc_create.c
=> storage: switch to ext4 as default fs

templates/lxc-oci.in
=> lxc-oci: correctly handle --url

src/lxc/attach.c
=> attach: allow attach with empty conf

src/lxc/storage/lvm.c, src/lxc/storage/lvm.h
=> lvm: generate new UUID for xfs + btrfs filesystems

doc/lxc.container.conf.sgml.in, src/lxc/commands.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/console.c, src/lxc/console.h, src/tests/console_log.c
=> console: add lxc.console.buffer.size, lxc.console.buffer.logfile, lxc.console.rotate

templates/lxc-oci.in
Remaining improvements (will be separate PRs):
- Handle uid/gid (`USER` in a Dockerfile), this value can be non-numeric so it might require some discussions.
- Handle layer caching.
=> Improve lxc-oci.in

doc/lxc.container.conf.sgml.in, src/lxc/confile.c
=> doc: documents lxc.namespace.[namespace identifier] + confile: improve legacy update message

lxc.spec.in
Signed-off-by: David Negreira David@otherreality.net
=> Fixed typo on lxc.spec.in

config/ax_pthread.m4, configure.ac
=> Use AX_PTHREAD config script to detect pthread api

src/lxc/tools/lxc_cgroup.c
=> tools/lxc_cgroup: remove internal logging

src/lxc/tools/lxc_autostart.c
=> tools/lxc_autostart: remove internal logging

src/lxc/tools/lxc_console.c
=> tools/lxc_console: remove internal logging

src/lxc/tools/lxc_copy.c
=> tools/lxc_copy: remove internal logging

src/lxc/tools/lxc_create.c
=> tools/lxc_create: remove internal logging

src/lxc/tools/lxc_device.c
=> tools/lxc_device: remove internal logging

src/lxc/tools/lxc_unshare.c
=> tools/lxc_unshare: removed internal logging

src/lxc/tools/lxc_execute.c
=> tools/lxc_execute: removed internal logging

src/lxc/tools/lxc_freeze.c
=> tools/lxc_freeze: remove internal logging

src/lxc/tools/lxc_info.c
=> tools/lxc_info: removed internal logging

src/lxc/tools/lxc_monitor.c
=> tools/lxc_monitor: removed internal logging

src/lxc/tools/lxc_ls.c
=> tools/lxc_ls: remove internal logging

src/lxc/tools/lxc_snapshot.c
=> tools/lxc_snapshot: removed internal logging

src/lxc/tools/lxc_start.c
=> tools/lxc_start: removed internal logging

src/lxc/tools/lxc_stop.c
=> tools/lxc_stop: removed internal logging

src/lxc/tools/lxc_top.c
=> tools/lxc_top: removed internal logging

src/lxc/tools/lxc_unfreeze.c
=> tools/lxc_unfreeze: removed internal logging

src/lxc/tools/lxc_usernsexec.c
=> tools/lxc_usernsexec: removed internal logging

src/lxc/tools/lxc_wait.c
=> tools/lxc_wait: removed internal logging

src/lxc/utils.h
=> utils: declare sethostname() static inline

doc/ja/lxc.container.conf.sgml.in, doc/lxc.container.conf.sgml.in
* add the description of lxc.console.buffer.* in Japanese man
* add the description of lxc.namespace.[namespace identifier] in Japanese man
* update the description of namespace inheritance in English man
* add the description of lxc.init.cwd in Japanese man
=> Add lxc.console.*, lxc.namespace.*, and lxc.init.cwd to Japanese lxc.container.conf(5)

.travis.yml
=> test: Coverity scan integration

src/lxc/attach.c, src/lxc/conf.c, src/lxc/confile.c, src/lxc/confile_legacy.c, src/lxc/criu.c, src/lxc/utils.c
=> attach: do not fail on non-existing namespaces

src/lxc/cgroups/cgfsng.c, src/lxc/confile.c, src/lxc/confile_legacy.c, src/lxc/lxccontainer.c, src/lxc/storage/overlay.c, src/lxc/storage/rsync.c, src/tests/snapshot.c
=> coverity: bugfixes

src/lxc/storage/overlay.c
=> overlay: fix out-of-bounds copy

doc/lxc.container.conf.sgml.in, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/start.c, src/tests/get_item.c, src/tests/parse_config_file.c
Signed-off-by: Yifeng Tan <tanyifeng1@huawei.com>
=> confile: enable tune host's OOM preferences

src/lxc/Makefile.am, src/lxc/lxc_init.c, src/lxc/tools/lxc_execute.c
coverity: #1426132
coverity: #1426133
=> lxc_init: fix cgroup parsing 

doc/lxc.container.conf.sgml.in, src/lxc/conf.c
Signed-off-by: Yifeng Tan <tanyifeng1@huawei.com>
=> conf.c: add relative option for lxc.mount.entry

templates/lxc-gentoo.in
=> gentoo: Add support for .xz tarballs

doc/lxc-attach.sgml.in, src/lxc/attach.c, src/lxc/attach_options.h, src/lxc/conf.c, src/lxc/conf.h, src/lxc/console.c, src/lxc/console.h, src/lxc/start.c, src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_start.c, src/lxc/utils.c, src/tests/attach.c, src/tests/lxc-test-lxc-attach, src/tests/lxc-test-utils.c
=> attach: add LXC_ATTACH_ALLOCATE_PTY

src/lxc/lxccontainer.c, src/lxc/network.c, src/lxc/start.c, src/lxc/storage/aufs.c, src/lxc/storage/btrfs.c, src/lxc/storage/overlay.c, src/lxc/storage/storage.c, src/lxc/utils.c, src/lxc/utils.h
Hey guys,
I'm doing something slightly weird, running lxc inside of lxc-usernsexec. I uncovered some bugs. Take a look.
=> Unpriv fixups

configure.ac, src/lxc/Makefile.am, src/lxc/attach.c, src/lxc/lsm/apparmor.c, src/lxc/lsm/lsm.c, src/lxc/lsm/lsm.h, src/lxc/lsm/nop.c, src/lxc/lsm/selinux.c, src/lxc/utils.h
=> lsm: simplifcations

src/lxc/confile_legacy.c
=> confile_legacy: fix legacy network parser

src/lxc/lxc_init.c, src/lxc/start.c
Here's my proposed fix for #2127
=> Sigterm handling

src/lxc/tools/lxc_ls.c
=> tools: add UNPRIVILEGED field in fancy output mode

doc/lxc.container.conf.sgml.in, src/lxc/cgroups/cgfs.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgmanager.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/cgroups/cgroup_utils.c, src/lxc/cgroups/cgroup_utils.h, src/lxc/commands.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/utils.c, src/lxc/utils.h
=> cgroups: add unified hierarchy support

src/lxc/cgroups/cgfsng.c, src/lxc/conf.c
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9566d6742852c527bf5af38af5cbb878dad75705
=> cgfsng: add required remount flags

src/lxc/tools/lxc_ls.c
=> tools/lxc-ls: fix logic for unpriv containers

doc/lxc.container.conf.sgml.in, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/start.c, src/lxc/tools/arguments.c, src/tests/share_ns.c
=> confile: add lxc.namespace.share.[namespace], lxc.namespace.keep, lxc.namespace.clone

src/lxc/start.c
=> start: check for cgroup namespace support

src/lxc/cgroups/cgfs.c, src/lxc/cgroups/cgfsng.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/start.c, src/tests/share_ns.c
=> coverity: bug smash

src/lxc/console.c
=> console: they are really not necessary

src/lxc/cgroups/cgfsng.c, src/lxc/conf.c
=> conf: fix clearing cgroup settings

CODING_STYLE.md, CONTRIBUTING
=> CODING_STYLE: add coding style file

src/lxc/conf.c, src/lxc/console.c, src/lxc/start.c
This fixes a SIGBUS/SIGSEGV Stéphane reported on aarch64 and armf.
Reported-by: Stéphane Graber <stgraber@ubuntu.com>
=> conf: fix run_script_argv()

README.md
=> README: add coverity

doc/lxc.container.conf.sgml.in, src/lxc/utils.h
=> doc: document cgroup-full:{mixed,ro,rw}:force

src/lxc/cgroups/cgfsng.c
=> cgfsng: fix off-by-one error

doc/ja/lxc.container.conf.sgml.in
=> doc: Add cgroup-full:*:force to Japanese lxc.container.conf(5)

src/lxc/Makefile.am, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/lxc_user_nic.c, src/lxc/confile.c, src/lxc/confile.h, src/lxc/criu.c, src/lxc/error.h, src/lxc/lxccontainer.c, src/lxc/lxclock.c, src/lxc/network.c, src/lxc/parse.c, src/lxc/parse.h, src/lxc/utils.c, src/lxc/utils.h
=> tree-wide: thread-safety improvements

CODING_STYLE.md, src/lxc/parse.c
=> CODING_STYLE: add section about _exit()

configure.ac, src/lxc/Makefile.am, src/lxc/pam/pam_cgfs.c
=> configure: add --enable-pam

doc/lxc.container.conf.sgml.in, src/lxc/commands.c, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/console.c, src/lxc/console.h, src/lxc/lxccontainer.h, src/tests/console_log.c
@duguhaotian, this is my proposal.
=> console: simplify console logging

config/templates/userns.conf.in, src/lxc/attach.c, src/lxc/attach_options.h, src/lxc/start.c, src/lxc/tools/lxc_attach.c
=> start: handle kernels without setns support 

CODING_STYLE.md
=> CODING_STYLE: update

src/lxc/caps.h
=> Add a workaround for a build issue with old versions of libcap

doc/ja/lxc-copy.sgml.in, doc/ja/lxc-snapshot.sgml.in, doc/ja/lxc.container.conf.sgml.in, doc/lxc-copy.sgml.in
* and tweak English lxc-copy(1)
=> doc: Remove aufs in Japanese man pages

src/lxc/tools/lxc_execute.c
Fields `daemonize` and `error_num` were being called after the
`lxc_container_put`.
=> tools: fix container use-after-free

src/lxc/Makefile.am, src/lxc/pam/utils.c, src/lxc/pam/utils.h
=> pam: Fix missing symbols in module

hooks/dhclient.in
=> hooks: fix dhclient hook when an AppArmor profile is active

configure.ac
=> configure.ac: Support redhatenterpriseserver

src/lxc/tools/lxc_checkpoint.c
Closes #2236.
Signed-off-by: Eytan Heidingsfeld <eytanh@gmail.com>
=> Allow passing action scripts to CRIU

doc/ja/lxc.container.conf.sgml.in
=> doc: Tweak Japanese translation in lxc.container.conf(5)

src/lxc/conf.c
On NFS, avoid random names of the root pin file due to "NFS silly renaming" but use a fixed hidden name instead.
IMHO this is a better solution because one is able to relate the anyway vislble file to a purpose.
Signed-off-by: <G.Jaekel@DNB.DE>
=> rootfs pinning: On NFS, make file hidden but don't delete it

doc/lxc-execute.sgml.in, src/lxc/seccomp.c, src/lxc/tools/lxc_execute.c, src/tests/api_reboot.c
=> seccomp: handle arch inversion - The Architecture Strikes Back

src/lxc/pam/pam_cgfs.c
=> pam-cgfs: ignore the system umask when creating the cgroup hierarchy

src/lxc/cgroups/cgfsng.c
=> Fix the memory leak in cgfsng_attach

src/lxc/lxccontainer.c
=> Fix memory leak in list_active_containers

src/lxc/execute.c
The problem here is that lxc-init runs *inside* the container. So if a
person has the log file set to /home/$USER/foo, lxc-init ends up making a
directory /home/$USER/foo inside the container to put the log file in. What
we really want are the logs to be propagated from inside the container to
the outside. We accomplish this by passing an fd without O_CLOEXEC, and
telling lxc-init to log to that file.
=> fix logic for execute log file

src/lxc/conf.c, src/lxc/execute.c, src/lxc/start.c
=> fix execute when init in the container already exists

src/lxc/network.c
=> gcc-8: silence

src/lxc/Makefile.am, src/lxc/tools/lxc_monitor.c
=> tools: s/strncpy()/strlcpy()/g

src/lxc/Makefile.am, src/lxc/tools/lxc_monitor.c
=> tools: s/strncpy()/memcpy()/g

src/lxc/conf.c
Resource leak
Signed-off-by: Simos Xenitellis <simos.lists@googlemail.com>
=> coverity: #1425844

src/lxc/conf.c
Resource leak
Signed-off-by: Simos Xenitellis <simos.lists@googlemail.com>
=> coverity: #1425802

src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/commands.c, src/lxc/conf.c, src/lxc/criu.c, src/lxc/freezer.c, src/lxc/lxc.h, src/lxc/lxccontainer.c, src/lxc/seccomp.c, src/lxc/start.c, src/lxc/start.h, src/lxc/state.c, src/tests/cgpath.c
=> cgroups: refactor cgroup handling

src/lxc/lxccontainer.c, src/lxc/lxcseccomp.h, src/lxc/seccomp.c, src/lxc/utils.c, src/lxc/utils.h
=> seccomp: cleanup

src/lxc/seccomp.c, src/lxc/tools/lxc_create.c
=> seccomp: more fixes

src/lxc/cgroups/cgfsng.c, src/lxc/lxccontainer.c, src/lxc/start.c, src/lxc/tools/lxc_create.c
=> tools: fix lxc-create with global config value II

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/execute.c, src/lxc/lxccontainer.c, src/lxc/parse.c, src/lxc/parse.h, src/lxc/seccomp.c, src/lxc/start.c, src/lxc/terminal.c, src/lxc/tools/arguments.h, src/lxc/tools/lxc_start.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/Makefile.am, src/tests/lxc-test-utils.c
=> conf: cleanups, and bugfixes

src/lxc/cmd/lxc_monitord.c, src/lxc/commands.c, src/lxc/start.c, src/lxc/tools/lxc_top.c
Hello,
change defines for return value of handlers
=> change defines for return value of handlers

src/lxc/confile_utils.c
Hello,
confile_utils: apply strprint()
=> confile_utils: apply strprint()

src/lxc/conf.c, src/lxc/start.c
=> tree-wide: handle EINTR in some read()/write()

src/lxc/conf.c
While a container reads mountinfo from proc fs, the mountinfo can be changed by
the kernel anytime. This has caused critical issues on some devices.
Signed-off-by: Donghwa Jeong dh48.jeong@samsung.com
Reported-by: Donghwa Jeong dh48.jeong@samsung.com
=> conf: copy mountinfo for remount_all_slave()

src/lxc/conf.c
Hello,
I changed some logs to print errno.
=> conf: change some logs to print errno

src/lxc/pam/pam_cgfs.c
Hello,
fix "Logically dead code."
Thanks.
=> pam_cgfs: fix Logically dead code.

src/lxc/conf.c
=> coverity: #1425836

src/lxc/confile.c
=> coverity: #1425811

src/lxc/conf.c
This is useful for users that are not in `/etc/sub{u,g}id` and only want to remap themselves like so:
```
lxc.idmap = u 1000 1000 1                                                                                                                                                                                           
lxc.idmap = g 1000 1000 1
lxc.init.uid = 1000
lxc.init.gid = 1000
```
Without this the container fails to launch and the cgroups aren't torn down properly for some reason. When retrying you will get:
```
lxc-execute cuda 20180609002300.889 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-121.scope/lxc/cuda" already existed …
```
=> conf: only use newuidmap and newgidmap when necessary

src/lxc/criu.c, src/lxc/lxccontainer.c, src/lxc/monitor.c, src/lxc/tools/lxc_monitor.c
=> coverity: #1425747

src/lxc/pam/pam_cgfs.c, src/lxc/tools/lxc_unshare.c
=> fix getpwnam() thread safe issue

src/lxc/tools/lxc_unshare.c
=> coverity: #1436916

src/lxc/attach.c, src/lxc/cmd/lxc_user_nic.c, src/lxc/cmd/lxc_usernsexec.c, src/lxc/conf.c
Hello,
fix getpwuid() thread safe issue.
Thanks.
=> fix getpwuid() thread safe issue

src/lxc/storage/storage_utils.c
=> storage: Resource leak

src/lxc/criu.c, src/lxc/lxccontainer.c, src/lxc/network.c, src/lxc/start.c, src/lxc/storage/btrfs.c
Hello,
clang error is fixed.
Thanks.
=> secure coding: strcpy => strlcpy

src/lxc/cmd/lxc_user_nic.c, src/lxc/confile.c, src/lxc/initutils.c, src/lxc/pam/pam_cgfs.c, src/lxc/storage/nbd.c, src/lxc/storage/rbd.c, src/lxc/storage/storage.c, src/lxc/tools/tool_utils.c, src/lxc/utils.c
Hello,
secure coding: #2 strcpy => strclpy
Thanks.
=> secure coding: #2 strcpy => strlcpy

src/lxc/conf.c
Hello,
conf: remove unused argument
Thanks.
=> conf: remove unused argument

src/lxc/confile.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/tests/attach.c, src/tests/cgpath.c, src/tests/shortlived.c
Hello,
secure coding: #3 strcpy => strlcpy
Thanks.
=> secure coding: #3 strcpy => strlcpy

src/lxc/cmd/lxc_usernsexec.c, src/tests/get_item.c
Hello,
fix fd handle leak.
Thanks.
=> fix fd handle leak

src/lxc/Makefile.am, src/lxc/storage/btrfs.c
=> btrfs: s/strncat()/strlcat()/g

src/lxc/commands.c
=> commands: simplify lxc_cmd()

src/lxc/conf.c
Starting with commit
`55956b59df33 ("vfs: Allow userns root to call mknod on owned filesystems.")`
Linux will allow mknod() in user namespaces for userns root if CAP_MKNOD is
available.
However, these device nodes are useless since
```
static struct super_block *alloc_super(struct file_system_type *type, int flags,
struct user_namespace *user_ns)
{
/* <snip> */
if (s->s_user_ns != &init_user_ns)
s->s_iflags |= SB_I_NODEV;
/* <snip> */
}
```
will set the SB_I_NODEV flag on the filesystem. When a device node created in
non-init userns is open()ed the call chain will hit:
```
bool may_open_dev(const struct path *path)
{
return !(path->mnt->mnt_flags & MNT_NODEV) &&
!(path->mnt->mnt_sb->s_iflags & SB_I_NODEV);
}
```
which will cause an EPERM because the device node is located on an fs
owned …
=> autodev: adapt to changes in Linux 4.18

CODING_STYLE.md, src/lxc/attach.c, src/lxc/conf.c, src/lxc/start.c, src/lxc/terminal.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/attach.c
=> terminal: security fixes

src/tests/api_reboot.c, src/tests/clonetest.c, src/tests/concurrent.c, src/tests/config_jump_table.c, src/tests/console.c, src/tests/containertests.c, src/tests/createtest.c, src/tests/criu_check_feature.c, src/tests/destroytest.c, src/tests/device_add_remove.c, src/tests/get_item.c, src/tests/getkeys.c, src/tests/list.c, src/tests/locktests.c, src/tests/lxc-test-utils.c, src/tests/lxc_raw_clone.c, src/tests/lxcpath.c, src/tests/may_control.c, src/tests/reboot.c, src/tests/saveconfig.c, src/tests/shortlived.c, src/tests/shutdowntest.c, src/tests/snapshot.c, src/tests/startone.c, src/tests/state_server.c
Hello,
This is non-functional changes for cleanup source codes of tests.
Thanks.
=> tests: cleanup source codes.

src/lxc/namespace.c, src/lxc/namespace.h, src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_unshare.c
Hello,
The new api is added to convert namespaces to standard identifiers.
And lxc-attach and lxc-unshare are change to use this api.
Thanks.
=> add namespace api

src/lxc/Makefile.am, src/lxc/conf.c, src/lxc/start.c
Cc: Serge Hallyn <serge@hallyn.com>
Cc: Tycho Andersen <tycho@tycho.ws>
=> static liblxc, always create /dev directory when autodev = 1, open("/dev/null") opportunistically

src/lxc/conf.c
This improves handling kernels which allow userspace to create partially
functional devices nodes.
=> conf: handle partially functional device nodes

src/lxc/Makefile.am, src/lxc/attach.c
=> autotool fixes, attach cleanups

src/lxc/lxclock.c
Hello,
Some logs using strerror() are changed to SYSERROR.
Thanks.
=> lxclock: change error log using strerror to SYSERROR

src/lxc/af_unix.c, src/lxc/af_unix.h, src/lxc/attach.c, src/lxc/cmd/lxc_monitord.c, src/lxc/commands.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/lxccontainer.c, src/lxc/start.c
Hello,
fix error handling of af_unix and confile_utils.
I'll check it for all apis additionally.
Thanks.
=> error handling cleanups #2471

doc/ja/lxc-unshare.sgml.in, doc/ko/lxc-unshare.sgml.in, doc/lxc-unshare.sgml.in
Hello,
long options of lxc-unshare are added to docs.
Thanks.
=> docs: add long options of lxc-unshare

src/lxc/attach.c, src/lxc/start.c, src/lxc/utils.c
Hello,
attach: fix return value & cleanups
Thanks.
=> attach: fix return value & cleanups

src/lxc/attach.c, src/lxc/confile_utils.c, src/lxc/network.c
Hello,
fix thread safe issue : rand() => rand_r()
Thanks.
=> thread safe: rand() => rand_r()

doc/ko/lxc-execute.sgml.in
=> docs: tools: -d/--daemonize for lxc-execute

src/lxc/lxccontainer.h
=> lxccontainer: fix indendation

configure.ac, src/include/ifaddrs.c, src/include/lxcmntent.c, src/lxc/cgroups/cgfsng.c, src/lxc/conf.c, src/lxc/confile.c, src/lxc/lxccontainer.c, src/lxc/namespace.c, src/lxc/parse.c, src/lxc/state.c, src/lxc/storage/storage.c, src/lxc/tools/lxc_autostart.c, src/lxc/tools/lxc_destroy.c, src/lxc/utils.c, src/lxc/utils.h, src/tests/Makefile.am, src/tests/mount_injection.c
=> utils: add lxc_iterate_parts(), compile with -Wvla and -std=gnu11

hooks/nvidia
=> Fix license of the nvidia hook

src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/criu.c, src/lxc/start.c, src/lxc/storage/dir.c, src/lxc/utils.c
=> conf: improve rootfs setup

doc/ja/lxc.container.conf.sgml.in
=> doc: Add incompatibility with network type=none into Japanese man

src/lxc/Makefile.am, src/lxc/caps.c, src/lxc/log.c, src/lxc/macro.h, src/lxc/utils.h
=> macro: add new macro header, caps: bugfixes, log: bugfixes

src/lxc/pam/pam_cgfs.c
Hello,
coverity issues are fixed.
Thanks.
=> fix coverity issues

templates/lxc-busybox.in
=> templates: avoid endless loop

src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/pam/pam_cgfs.c, src/tests/containertests.c
Hello,
fix dereference pointer c in containertests
=> tests: containertests: fix dereference pointer c

src/lxc/conf.c, src/lxc/criu.c, src/lxc/storage/btrfs.c, src/lxc/storage/btrfs.h
Hello,
Fix assignment of a signed value which has type 'int' to a variable of a bigger integer type 'unsigned long' issue.
Thanks.
=> fix assignment of signed to bigger unsigned issue

src/lxc/macro.h, src/lxc/network.c, src/lxc/nl.c, src/lxc/start.c
=> netns: improve netnsid allocation

src/lxc/log.c, src/lxc/lxccontainer.c, src/lxc/macro.h
Hello,
thread-safe issue is fixed.
Thanks.
=> fix thread-safe issue (localtime => localtime_r)

src/lxc/lxccontainer.c
When we check whether an open file description lock has been taken on a file we
need to set the l_pid field to 0 otherwise the kernel will send back EINVAL.
Additionally, the kernel will not do pid translation and simply set the l_pid
value to -1.
Fixes https://discuss.linuxcontainers.org/t/container-deleted-or-stopped-when-lxc-ls-executed-concurrently/2439
=> lxccontainer: fix F_OFD_GETLK checks

src/lxc/lxccontainer.c
=> lxccontainer: minor fixes

src/lxc/cmd/lxc_init.c, src/lxc/cmd/lxc_monitord.c, src/lxc/cmd/lxc_usernsexec.c
@brauner commented on another PR that `src/lxc/cmd/lxc_usernsexec.c` could do with some cleaning up.  I parsed `src/lxc/cmd/*.c` with the kernel 'linter' `scripts/checkpatch.pl`.  Here are just fixes to the most obvious ERROR messages.  Just doing a few patches in this PR to see that I'm following protocol.
Code builds but is untested.  I see you guys have CI on your side, are there tests I should be running locally before raising pull requests?
thanks,
Tobin.
=> Checkpatch

src/lxc/Makefile.am, src/lxc/cmd/lxc_usernsexec.c, src/lxc/log.h
=> log: add logging tools for commands; lxc-usernsexec: cleanup and bugfixes

src/lxc/tools/lxc_attach.c, src/lxc/tools/lxc_cgroup.c, src/lxc/tools/lxc_checkpoint.c, src/lxc/tools/lxc_console.c, src/lxc/tools/lxc_create.c, src/lxc/tools/lxc_destroy.c, src/lxc/tools/lxc_device.c, src/lxc/tools/lxc_execute.c, src/lxc/tools/lxc_freeze.c, src/lxc/tools/lxc_start.c, src/lxc/tools/lxc_stop.c, src/lxc/tools/lxc_unfreeze.c
Hello,
default log priority is added to some tools with cleanups.
Thanks.
=> tools: add default log priority & cleanups

src/lxc/Makefile.am, src/lxc/cmd/lxc_user_nic.c
Hello,
log macros using strerror are changed to CMD_SYSERROR macro.
Thanks.
=> cmd: lxc-user-nic: change log macro & cleanups

src/lxc/tools/lxc_autostart.c
When running `lxc-autostart` we do not currently indicate failure to start containers, either partial failure (i.e. some of the containers failed to start) or total failure (i.e. all of the containers failed to start).
(We specifically use -1 instead of EXIT_FAILURE.  Even if EXIT_FAILURE is defined as 1 this is congruent with 'total failure'.)
Indicate container startup failure.  For total failure return -1, for partial failure return -2.
Fixes: #2523 
Tested using systemd service described in the issue (#2523).  Before applying this patch:
```
$ systemctl --user start lxc-autostart
$ systemctl --user status lxc-autostart
● lxc-autostart.service - Start LXC containers on boot
Loaded: loaded (/home/tobin/.config/systemd/user/lxc-autosta
Active: active (exited) since Fri 2018-08-17 …
```
=> tools: Indicate container startup failure

src/lxc/storage/nbd.c, src/lxc/tools/lxc_wait.c
Hello,
1. storage: exit() => _exit()
=> When exec syscall is failed, child process needs to use _exit().
2. tools: lxc-wait: add default log priority & cleanups
Thanks.
=> storage: exit() => _exit()

src/lxc/Makefile.am, src/lxc/cmd/lxc_usernsexec.c, src/lxc/confile_utils.c, src/lxc/confile_utils.h, src/lxc/macro.h
=> cmd: lxc-usernsexec fixes + macro: move declarations + config_utils: macvlan fixes

src/lxc/cmd/lxc_init.c, src/lxc/cmd/lxc_monitord.c, src/lxc/cmd/lxc_user_nic.c
`clang-format` finds a few format issues, lets fix these up.
Fix format issues found by clang-format.
OK this will be my last trivial PR, I think I get how you guys are doing things now :)
=> cmd: Fix format issues found by clang-format

src/lxc/conf.c
=> conf: fix devpts mounting when fully unprivileged

src/lxc/attach.c, src/lxc/macro.h
=> attach: bugfixes

src/lxc/Makefile.am, src/lxc/conf.h, src/lxc/file_utils.c, src/lxc/initutils.c, src/lxc/initutils.h, src/lxc/string_utils.c, src/lxc/string_utils.h
=> remove last pam_cgfs special-casing

src/lxc/execute.c
Unprivileged app containers will not be able to open the passed in
/proc/1/fd/<idx> log path and will thus currently fail completely as soon as
any log level or log file is passed.
Reported-by: Mrinal Dhillon <mdhillon@juniper.net>
=> execute: skip lxc-init logging when unprivileged

src/lxc/commands.c, src/tests/Makefile.am, src/tests/basic.c
=> commands: always return -1 on lxc_cmd_get_init_pid() err

configure.ac, src/lxc/Makefile.am, src/lxc/caps.c, src/lxc/cgroups/cgfsng.c, src/lxc/commands.c, src/lxc/commands.h, src/lxc/commands_utils.c, src/lxc/compiler.h, src/lxc/conf.c, src/lxc/conf.h, src/lxc/confile.c, src/lxc/initutils.c, src/lxc/log.c, src/lxc/lsm/lsm.h, src/lxc/lxccontainer.c, src/lxc/macro.h, src/lxc/monitor.c, src/lxc/network.c, src/lxc/parse.c, src/lxc/start.c, src/lxc/string_utils.c, src/lxc/tools/lxc_monitor.c, src/lxc/utils.c, src/tests/lxc-test-utils.c
=> build: fix musl + add compiler.h

src/lxc/commands.c, src/lxc/macro.h
=> commands: pass around intmax_t

src/lxc/commands.c, src/lxc/macro.h
=> macro: calculate buffer lengths correctly 

src/lxc/conf.c, src/lxc/macro.h
=> macro: move MS_* macros

src/lxc/caps.c, src/lxc/nl.c, src/lxc/seccomp.c, src/lxc/utils.c
Hello,
fix illegal access to array bound
Thanks.
=> caps: fix illegal access to array bound

src/lxc/lxccontainer.c
Hello,
dereferenced pointer issues are fixed.
Thanks.
=> lxccontainer: fix dereferenced pointer

doc/lxc-attach.sgml.in, doc/lxc-execute.sgml.in, src/lxc/attach.c, src/lxc/cgroups/cgfsng.c, src/lxc/cmd/lxc_usernsexec.c, src/lxc/macro.h, src/lxc/start.c, src/lxc/storage/rsync.c, src/lxc/tools/lxc_attach.c, src/lxc/utils.c, src/lxc/utils.h
=> utils: allow lxc-attach to set uid / gid

src/lxc/confile.c, src/lxc/file_utils.c, src/lxc/storage/rsync.c
Hello,
removed unused variables & function.
Thanks.
=> remove unused variables & function

src/lxc/af_unix.c
Hello,
A function for abstract unix socket is added to remove duplicated codes for setting sockaddr.
Thanks.
=> af_unix: add function to remove duplicated codes for set sockaddr

src/lxc/execute.c, src/lxc/lxc.h, src/lxc/start.c, src/lxc/start.h
=> start: s/backgrounded/daemonize/g

src/lxc/macro.h, src/lxc/network.c, src/lxc/network.h
=> network: add lxc_netns_get_nsid()

src/lxc/cgroups/cgfsng.c, src/lxc/conf.h, src/lxc/confile.c
=> confile: s/lxc.cgroup.keep/lxc.cgroup.relative/g

doc/api-extensions.md, src/lxc/Makefile.am, src/lxc/api_extensions.h, src/lxc/lxccontainer.c, src/lxc/lxccontainer.h
=> api_extensions: introduce lxc_has_api_extension()

CODING_STYLE.md, config/ax_check_compile_flag.m4, configure.ac, src/lxc/attach.c, src/lxc/cmd/lxc_init.c, src/lxc/compiler.h, src/lxc/tools/arguments.c
=> autotools: add -Wimplicit-fallthrough

configure.ac, src/lxc/cgroups/cgfsng.c, src/lxc/cgroups/cgroup.c, src/lxc/cgroups/cgroup.h, src/lxc/criu.c, src/lxc/initutils.c, src/lxc/start.c, src/tests/cgpath.c
This adds a new scoping mechanism to even better integrate with cgroup v2 but will also be used with cgroup v1.
//fyi @poettering
=> cgroups: scoping for cgroup v2
